import{describe,expect,it}from"vitest";import{readFileSync}from"node:fs";const ui=readFileSync("app/community-directory.tsx","utf8"),page=readFileSync("app/page.tsx","utf8"),sql=readFileSync("supabase/migrations/202609170020_community_player_stable_directory.sql","utf8"),css=readFileSync("app/community-directory.css","utf8"),layoutFix=readFileSync("app/community-layout-fix.css","utf8");
describe("Community Players & Stables directory",()=>{
 it("is the default Community section with history-aware Chat navigation",()=>{expect(ui).toContain('location.pathname==="/community/chat"?"chat":"directory"');expect(ui.indexOf("Players &amp; Stables")).toBeLessThan(ui.indexOf("Chat Rooms"));expect(ui).toContain('addEventListener("popstate",restore)');expect(page).toContain("<CommunityHub")});
 it("searches every requested public identity",()=>{expect(sql).toContain("v.username");expect(sql).toContain("v.name ilike");expect(sql).toContain("v.brand_code");expect(sql).toContain("v.account_number::text")});
 it("filters, sorts, and paginates server-side",()=>{for(const value of["p_level","p_profession","account_asc","account_desc","stable","player","level","p_offset","p_limit"])expect(sql).toContain(value);expect(ui).toContain("Load 100 more")});
 it("links visitor-safe player and Stable routes",()=>{expect(ui).toContain("VIEW PROFILE");expect(ui).toContain("VISIT STABLE");expect(ui).toContain("/players/${row.stable_id}");expect(ui).toContain("/stables/${row.stable_id}")});
 it("returns only active accounts and public fields",()=>{expect(sql).toContain("s.account_status='active'");for(const privateField of["email","phone","balance","is_admin","community_role"])expect(sql.split("create or replace function public.get_community_directory")[1].split("$$;")[0]).not.toContain(privateField)});
 it("has compact responsive contained results",()=>{expect(layoutFix).toContain("height: auto");expect(layoutFix).toContain("flex: 0 0 auto");expect(css).toContain(".directoryresults{max-height:");expect(css).toContain(".directorytools{grid-template-columns:1fr}");expect(css).toContain(".directorycard{grid-template-columns:58px")});
});
