import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const sql=readFileSync("supabase/migrations/202609180015_commerce_payment_readiness.sql","utf8"),admin=readFileSync("app/admin-commerce.tsx","utf8"),page=readFileSync("app/page.tsx","utf8"),checkout=readFileSync("app/api/stalls/checkout/route.ts","utf8"),webhook=readFileSync("app/api/stalls/webhook/route.ts","utf8");
describe("commerce and entitlement readiness",()=>{
 it("keeps live commerce disabled and exposes no checkout collection",()=>{expect(sql).toContain("live_payments_enabled boolean not null default false");expect(sql).toContain("update set live_payments_enabled=false");expect(checkout).toContain("No payment information was collected");expect(checkout).not.toContain("STRIPE_SECRET_KEY");expect(webhook).not.toContain("STRIPE_WEBHOOK_SECRET");expect(page).not.toContain('fetch("/api/stalls/checkout"')});
 it("provides a versioned provider-neutral catalog and authoritative orders",()=>{for(const value of ["commerce_products","purchase_type","price_minor","currency","entitlement_effect","effective_at","version","commerce_orders","external_transaction_ref","external_subscription_ref","idempotency_ref"])expect(sql).toContain(value);expect(sql).toContain("unique(provider,mode,idempotency_ref)")});
 it("supports subscription lifecycle and authoritative capabilities",()=>{for(const state of ["active","past_due","canceled","expired"])expect(sql).toContain(`'${state}'`);expect(sql).toContain("commerce_capabilities");expect(sql).toContain("'profession_career_slots',profession_slots");expect(sql).toContain("'feed_storage_bonus',feed_bonus");expect(sql).toContain("owner_unlimited:=s.account_number=1")});
 it("makes feed capacity non-destructive and entitlement-driven",()=>{expect(sql).toContain("caps:=commerce_capabilities(s.id)");expect(sql).toContain("'over_capacity',not unlim and used>cap");expect(sql).not.toMatch(/delete from (player_store_items|horses|artwork_album_items)/i)});
 it("makes provider events idempotent and test mode effect-free",()=>{expect(sql).toContain("unique(provider,mode,provider_event_ref)");expect(sql).toContain("test_confirmation_no_gameplay_effect");expect(sql).toContain("'effects_applied',false");expect(sql).toContain("grant execute on function public.confirm_commerce_order");expect(sql).toContain("to service_role")});
 it("prepares non-destructive reversal review and LED credits",()=>{expect(sql).toContain("commerce_reversal_reviews");expect(sql).toContain("review_required");expect(sql).toContain("'non_destructive',true");expect(sql).toContain("Confirmed commerce LED purchase");expect(sql).toContain('"cash_redeemable":false')});
 it("provides the Owner commerce audit workspace through real Admin navigation",()=>{expect(admin).toContain("admin_commerce_workspace");expect(admin).toContain("No checkout or live payment collection is enabled");expect(page).toContain('{id:"commerce",label:"Commerce"');expect(page).toContain('topic==="commerce"&&ownerAccount&&<AdminCommerce')});
});
