import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const sql=readFileSync(new URL("../supabase/migrations/202609180010_feed_system_v2.sql",import.meta.url),"utf8"),store=readFileSync(new URL("../app/page.tsx",import.meta.url),"utf8"),room=readFileSync(new URL("../app/stable-inventory.tsx",import.meta.url),"utf8"),admin=readFileSync(new URL("../app/store-wellness-admin.tsx",import.meta.url),"utf8"),bulk=readFileSync(new URL("../app/store-bulk-purchase.tsx",import.meta.url),"utf8");
describe("Feed System V2",()=>{
 it("preserves IDs while publishing all five Hay and four Grain products",()=>{for(const value of ["Grass Hay","Orchard Grass Hay","Alfalfa Hay","Teff Hay","Timothy Hay","LE Basic Feed","LE Advanced Feed","LE Performance Feed","LE Elite Performance Feed"])expect(sql).toContain(value);expect(sql).toContain("where id='basic_hay'");expect(sql).toContain("where id='quality_hay'");expect(sql).toContain("where id='performance_feed'");expect(sql).toContain("where id='premium_performance_feed'")});
 it("enforces one Hay and one Grain per horse per LE day",()=>{expect(sql).toContain("unique index if not exists horse_feed_log_horse_day_type");expect(sql).toContain("f.feed_type=product.feed_type");expect(sql).toContain("hay_eligible_horse_ids");expect(sql).toContain("grain_eligible_horse_ids")});
 it("applies configured random development rolls only on success",()=>{expect(sql).toContain("random()<product.feed_success_probability");expect(sql).toContain("product.development_min+floor(random()*(product.development_max-product.development_min+1))");expect(sql.indexOf("if success then stat")).toBeLessThan(sql.indexOf("update horses set stats=after_stats"))});
 it("implements combined level/subscriber storage and exact Owner #1 unlimited access",()=>{expect(sql).toContain("cfg.base_storage+floor(lvl/5.0)::integer*cfg.storage_per_five_levels");expect(sql).toContain("subscriber_storage_bonus");expect(sql).toContain("unlim:=s.account_number=1");expect(room).toContain("Feed Storage");expect(room).toContain("Unlimited Storage")});
 it("preserves over-capacity inventory while blocking additions",()=>{expect(sql).toContain("'over_capacity',not unlim and used>cap");expect(sql).toContain("Feed Storage limit: maximum purchasable");expect(room).toContain("Over capacity — use existing feed before purchasing more.")});
 it("uses per-product daily global stock with safe restock and audit",()=>{expect(sql).toContain("create table if not exists public.store_daily_stock");expect(sql).toContain("remaining_stock=remaining_stock-p_quantity");expect(sql).toContain("feed.manual_restock");expect(sql).toContain("admin_audit_log");expect(store).toContain("remaining today")});
 it("allows custom quantities beyond 50 while enforcing live constraints",()=>{expect(bulk).toContain("maxPurchase??1_000_000");expect(bulk).toContain("[1,5,10,25,50]");expect(store).toContain("Math.min(stock,storage,affordable)")});
 it("keeps purchases atomic and idempotent",()=>{expect(sql).toContain("store_purchase_requests");expect(sql).toContain("'duplicate',true");expect(sql.indexOf("if p_quantity>maximum")).toBeLessThan(sql.indexOf("update stables set balance=balance-total"));expect(sql.indexOf("update stables set balance=balance-total")).toBeLessThan(sql.indexOf("insert into player_store_items"))});
 it("gives Admin configuration and audited manual restock controls",()=>{expect(admin).toContain("admin_update_feed_v2_product");expect(admin).toContain("admin_update_feed_storage_config");expect(admin).toContain("admin_restock_feed_product");expect(admin).toContain("Daily stock")});
 it("renders category-aware Store and Feed Room UX",()=>{expect(store).toContain('<option value="grain">Grain</option>');expect(store).toContain("one {p.feed_type} per horse per LE day");expect(room).toContain('feedType==="hay"?"Hay":"Grain"');expect(room).toContain("Eligible today:")});
});
