import{describe,expect,it}from"vitest";import{readFileSync}from"node:fs";
const sql=readFileSync("supabase/migrations/202609210002_help_support_center.sql","utf8"),player=readFileSync("app/support-center.tsx","utf8"),admin=readFileSync("app/admin-support.tsx","utf8"),nav=readFileSync("app/universal-game-navigation.tsx","utf8"),shell=readFileSync("app/page.tsx","utf8"),css=readFileSync("app/support-center.css","utf8");
describe("private Help and Support",()=>{
 it("creates authoritative private tickets and human-readable numbers",()=>{expect(sql).toContain("create table if not exists public.support_tickets");expect(sql).toContain("generated always as identity(start with 1000)");expect(sql).toContain("'LE-'||p_number::text")});
 it("enforces player isolation and hides internal notes",()=>{expect(sql).toContain("stable_id=auth.uid()");expect(sql).toContain("message_type<>'internal_note'");expect(sql).toContain("support-attachments");expect(sql).toContain("public,file_size_limit");expect(sql).toContain("false,5242880")});
 it("captures only allowlisted diagnostic and object context",()=>{for(const value of["route","viewport","device_class","user_agent","build","horse_id","show_id","profession","career_level","listing_id"])expect(sql).toContain(`'${value}'`);for(const secret of["password","cookie","token","payment"])expect(sql.toLowerCase()).not.toContain(`'${secret}'`)});
 it("provides player bug, general contact, reports, replies, and screenshots",()=>{for(const value of["Report a Bug","Contact Admin","My Reports","Submit Bug Report","Send to Admin","add_support_reply","support-attachments"])expect(player).toContain(value)});
 it("provides permissioned admin management, notes, priorities, assignment, and duplicates",()=>{expect(sql).toContain("support.manage");expect(sql).toContain("admin_update_support_ticket");for(const value of["Unresolved Bugs","Reply to Player","Internal Note","Priority","Assign","Duplicate of"])expect(admin).toContain(value)});
 it("links Support in navigation with update badges and responsive layouts",()=>{expect(nav).toContain("Help & Support");expect(shell).toContain('view === "support"');expect(shell).toContain("Report a Problem");expect(css).toContain("@media(max-width:700px)");expect(css).toContain("@media(max-width:800px)")});
});
