import{describe,expect,it}from"vitest";
import{readFileSync}from"node:fs";
const sql=readFileSync("supabase/migrations/202609180023_authenticated_home_news.sql","utf8"),refinement=readFileSync("supabase/migrations/202609210005_home_news_feed_and_article.sql","utf8"),home=readFileSync("app/home-news.tsx","utf8"),auth=readFileSync("app/public-auth.tsx","utf8"),page=readFileSync("app/page.tsx","utf8"),navigation=readFileSync("app/universal-game-navigation.tsx","utf8"),styles=readFileSync("app/home-news.css","utf8");

describe("authenticated Home News",()=>{
 it("supports five categories, drafts, scheduling, pinning and expiration",()=>{for(const value of["official","updates","shows","contests","community","draft","published","unpublished","publish_at","expires_at","pinned"])expect(sql).toContain(value)});
 it("uses a lightweight last-viewed cursor",()=>{expect(sql).toContain("news_reader_state");expect(sql).toContain("last_viewed_at");expect(sql).not.toContain("news_post_reads")});
 it("sanitizes content and internal routes",()=>{expect(sql).toContain("news_safe_text");expect(sql).toContain("news_safe_destination")});
 it("publishes configured milestones without routine-show spam",()=>{expect(sql).toContain("news_auto_rules");expect(sql).toContain("horse_cp_milestone");expect(sql).toContain("new.source<>'auto_host'");expect(sql).toContain("new.feature_on_news")});
 it("provides cohesive feed, filters and compact quick links",()=>{for(const value of["Featured / Important","Latest News","Quick Links","LOAD MORE"])expect(home).toContain(value);for(const value of["My Stable","Enter Shows","LE Store","Marketplace","Professions","Community"])expect(home).toContain(value);expect(styles).toContain("grid-template-columns:repeat(2,minmax(0,1fr))");expect(styles).toContain("overflow-x:auto");expect(styles).toContain("scrollbar-width:none");expect(home).toContain("filtersRef.current?.scrollTo({left:0})");expect(home).toContain('className="newsfilterviewport"');expect(styles).toContain(".newsfilters{display:flex;flex-wrap:nowrap");expect(styles).toContain(".homeheadline h1{")});
 it("keeps pinned articles in Latest News and opens eligible article records",()=>{expect(home).toContain("posts.map(post=><NewsCard");expect(home).not.toContain("latest=posts.filter(p=>!p.pinned)");expect(home).toContain('rpc("get_news_article"');expect(refinement).toContain("create or replace function public.get_news_article");expect(refinement).toContain("n.status='published'");expect(refinement).toContain("n.expires_at is null or n.expires_at>now()");expect(refinement).toContain("coalesce(n.publish_at,n.published_at,n.created_at)<=now()")});
 it("labels News consistently in desktop and mobile game navigation",()=>{expect(navigation.match(/`News · \$\{newsNew\} New`:"News"/)).toBeTruthy();expect(navigation).toContain('icon:"news"')});
 it("redirects authentication to Home and exposes Home and article routes",()=>{expect(auth).not.toContain('"/stable/horses"');expect(auth).toContain('"/home"');expect(page).toContain('"home"');expect(home).toContain("articleIdFromPath")});
});
