import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const ui=readFileSync("app/professions.tsx","utf8"),page=readFileSync("app/page.tsx","utf8"),sql=readFileSync("supabase/migrations/202609180018_owner_profession_live_transition_and_qa_override.sql","utf8");
describe("Owner Profession QA to Live enrollment and progression override",()=>{
	 it("requires an explicit paid enrollment before enabling Live Gameplay",()=>{const transition=ui.slice(ui.indexOf("const enrollFromQa"),ui.indexOf("const markRequirementComplete"));expect(ui).toContain("if (!p.enrolled)");expect(ui).toContain("This career is not enrolled.");expect(ui).toContain("ENROLL & CONTINUE");expect(transition).toContain("rpc(\"enroll_profession\"");expect(transition.indexOf("setRunNormal(true)")).toBeGreaterThan(transition.indexOf("rpc(\"enroll_profession\""))});
 it("locks and de-duplicates enrollment before charging",()=>{expect(sql).toContain("from stables where id=auth.uid()for update");expect(sql.indexOf("already permanently enrolled")).toBeLessThan(sql.indexOf("update stables set balance=balance-p.enrollment_fee"));expect(sql).toContain("not public.is_owner_account(s.id)and exists");expect(sql).toContain("Complete your current career through Professional")});
 it("keeps preview simulation non-persistent and inside QA Controls",()=>{expect(ui).toContain("SIMULATE SERVICE REQUIREMENT COMPLETE");expect(ui).toContain("setQaServiceCredit(requiredServices)");const preview=ui.slice(ui.indexOf("SIMULATE SERVICE REQUIREMENT COMPLETE")-500,ui.indexOf("SIMULATE SERVICE REQUIREMENT COMPLETE")+100);expect(preview).not.toMatch(/rpc\(|currency_ledger|horse_service_records/)});
 it("records persistent overrides separately without altering honest services",()=>{expect(sql).toContain("profession_advancement_overrides");expect(sql).toContain("actual_service_count");expect(sql).toContain("profession.qa_progression_override");expect(sql).toContain("'actual_service_count',actual");expect(sql).not.toMatch(/update horse_service_records|insert into horse_service_records|update currency_ledger|insert into currency_ledger[^\n]*override/)});
 it("enforces the granular permission server-side and exposes it for later grants",()=>{expect(sql).toContain("has_admin_permission('professions.qa_progression_override')");expect(page).toContain('"professions.qa_progression_override"');expect(sql).toContain("Profession QA progression override permission required")});
 it("uses overrides only at the shared advancement gate and supports every data-driven profession and level",()=>{expect(sql).toContain("completed<required and not overridden");expect(sql).toContain("certification_level integer not null references public.certification_levels(level)");expect(sql).not.toMatch(/profession_id\s+in\s*\(/i)});
 it("keeps actual counts truthful in dashboard and UI",()=>{expect(sql).toContain("'qualifying_credit',coalesce(legit.completed,0)");expect(sql).toContain("'requirement_overridden',ov.id is not null");expect(ui).toContain("Actual Services: {p.qualifying_credit}");expect(ui).toContain("Actual Services: {serviceCredit}")});
});
