import{describe,expect,it}from"vitest";import{readFileSync}from"node:fs";
const page=readFileSync("app/page.tsx","utf8"),profile=readFileSync("app/public-stable-profile.tsx","utf8"),css=readFileSync("app/public-stable-profile.css","utf8"),baseSql=readFileSync("supabase/migrations/202609170019_public_stable_profiles.sql","utf8"),customSql=readFileSync("supabase/migrations/202609170027_dedicated_stable_customizer.sql","utf8");
describe("public Stable profiles",()=>{
 it("preserves ranch imagery on the public Stable",()=>{expect(profile).toContain("profile.ranch_image_url");expect(page).toContain("View Stable Profile")});
 it("uses a dedicated routed editor instead of an overlay",()=>{expect(page).toContain('window.location.assign(`/stables/${stable.id}/customize`)');expect(profile).toContain('location.pathname.endsWith("/customize")');expect(profile).toContain("← Back to My Stable");expect(profile).not.toContain("examoverlay");expect(profile).not.toContain("stableeditor")});
 it("keeps Preview and Save reachable in persistent editor actions",()=>{expect(profile).toContain('className="customizersticky"');expect(profile).toContain("Save Changes");expect(css).toContain("position:fixed");expect(css).toContain("bottom:8px")});
 it("supports Standard and safe image-backed Custom modes",()=>{expect(profile).toContain("Standard LE Layout");expect(profile).toContain("Custom Layout");expect(profile).toContain("uploadLayoutImage");expect(customSql).toContain("layout_mode text");expect(customSql).toContain("layout_image_url text")});
 it("preserves content blocks, featured horses, and shared professional services",()=>{for(const name of["Stable News","About the Stable","Featured Horses","Professional Services","Horse Roster","Move Up","Move Down","Reset to Standard Layout"])expect(profile).toContain(name);expect(customSql).toContain("get_public_professional_services");expect(profile).toContain("save_public_stable_content")});
 it("connects Owner and Level 20 capability without changing horse data",()=>{expect(baseSql).toContain("is_owner_account(p_stable)");expect(baseSql).toContain("c.custom_stable_layout");expect(baseSql).toContain("stable_layout_capability_grants");expect(customSql).not.toContain("update horses")});
 it("rejects executable content and untrusted layout URLs server-side",()=>{expect(baseSql).toContain("stable_safe_rich_text");expect(baseSql).toContain("'<[^>]*>'");expect(customSql).toContain("stable_safe_rich_text");expect(customSql).toContain("/storage/v1/object/public/legacy-equine-media/");expect(profile).not.toContain("dangerouslySetInnerHTML");expect(profile).not.toContain("iframe")});
 it("uses bounded percentage hotspots and mobile-safe stacked navigation",()=>{for(const field of["'x'","'y'","'width'","'height'"])expect(customSql).toContain(field);expect(css).toContain("position:static!important");expect(css).toContain("width:100%!important");expect(css).toContain(".customizersticky{left:8px;right:8px")});
});
