import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const sql=readFileSync("supabase/migrations/202609180011_show_allocatable_points.sql","utf8"),horse=readFileSync("app/horse-allocatable-points.tsx","utf8"),profile=readFileSync("app/horse-profile.tsx","utf8"),shows=readFileSync("app/shows-v2.tsx","utf8"),admin=readFileSync("app/admin-shows.tsx","utf8");
describe("Show-earned horse-specific Allocatable Points",()=>{
 it("awards configurable 3/2/1 defaults only to top-three committed result rows",()=>{expect(sql).toContain("first_place integer not null default 3");expect(sql).toContain("second_place integer not null default 2");expect(sql).toContain("third_place integer not null default 1");expect(sql).toContain("if new.placement>3 then return new");expect(sql).toContain("after insert on public.player_show_results")});
 it("keeps preview and cancelled Shows side-effect free",()=>{expect(sql).not.toContain("admin_preview_show_results");expect(sql).not.toContain("status='cancelled'");expect(sql).toContain("show_result_id uuid not null unique")});
 it("never modifies or derives AP from Career Points",()=>{expect(sql).not.toMatch(/career_points\s*[=+]/);expect(sql).toContain("allocatable_points=allocatable_points+award");expect(shows).toContain("Career Points");expect(shows).toContain("ap_earned")});
 it("is idempotent for single, scheduled, manual, and bulk Show execution",()=>{expect(sql).toContain("on conflict(show_result_id)do nothing");expect(sql).toContain("if found then update horses");expect(sql).toContain("show_result_id uuid not null unique")});
 it("stores every balance, award, and allocation on one authoritative horse",()=>{expect(sql).toContain("alter table public.horses add column if not exists allocatable_points");expect(sql).toContain("horse_id uuid not null references public.horses(id)");expect(sql).toContain("where id=new.horse_id");expect(sql).not.toMatch(/stable.*ap_(balance|wallet|pool)/i)});
 it("rejects cross-horse and overspend attempts server-side",()=>{expect(sql).toContain("select * into h from horses where id=p_horse for update");expect(sql).toContain("if h.owner_id<>auth.uid()");expect(sql).toContain("requested>h.allocatable_points");expect(sql).not.toContain("sum(allocatable_points)")});
 it("allocates atomically to unrestricted permanent stats",()=>{expect(sql).toContain("update horses set stats=after_stats,allocatable_points=allocatable_points-requested");expect(sql).not.toMatch(/stat.{0,20}(cap|maximum|limit)/i);expect(sql).not.toMatch(/lifetime.{0,20}(cap|maximum|limit)/i);expect(sql).toContain("insert into horse_ap_allocations")});
 it("flows into existing Show and breeding permanent-stat architecture",()=>{expect(sql).toContain("stats=after_stats");const breeding=readFileSync("supabase/migrations/202609160007_authoritative_age_gameplay.sql","utf8");expect(breeding).toContain("sire.stats");expect(breeding).toContain("dam.stats")});
 it("survives sale and transfer because AP belongs to the horse row",()=>{expect(sql).not.toMatch(/update stables set.*allocatable/i);expect(sql).not.toMatch(/owner_id.*horse_ap_awards/i);expect(sql).toContain("where id=h.id")});
 it("provides permanent confirmation, unsaved reset, history, and mobile-safe controls",()=>{expect(horse).toContain("RESET UNSAVED");expect(horse).toContain("This cannot normally be undone");expect(horse).toContain("Show Development History");expect(profile).toContain("HorseAllocatablePoints");expect(readFileSync("app/horse-allocatable-points.module.css","utf8")).toContain("@media(max-width:520px)")});
 it("shows AP on results and provides audited Owner/config corrections",()=>{expect(shows).toContain("+{r.ap_earned} AP");expect(admin).toContain("admin_update_show_ap_config");expect(sql).toContain("horse.ap_correction");expect(sql).toContain("actor.account_number<>1")});
});
