import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const sql=readFileSync("supabase/migrations/202609180016_owner_auto_show_host.sql","utf8"),ui=readFileSync("app/show-auto-host.tsx","utf8"),admin=readFileSync("app/admin-shows.tsx","utf8"),runner=readFileSync("supabase/migrations/202609150045_expanded_show_system.sql","utf8"),ap=readFileSync("supabase/migrations/202609180011_show_allocatable_points.sql","utf8");
describe("Owner Auto Show Host",()=>{
 it("is Owner/delegable and defaults production OFF",()=>{expect(sql).toContain("enabled boolean not null default false");expect(sql).toContain("account_number=1");expect(sql).toContain("admin.shows.auto_host");expect(admin).toContain('["auto","Auto Host"]')});
 it("supports full and custom selection with both quantity modes",()=>{expect(sql).toContain("selection_mode in('full','custom')");expect(sql).toContain("quantity_mode in('maintain','create_new')");expect(ui).toContain("Full Show Base");expect(ui).toContain("Custom Selection");expect(ui).toContain("Maintain X Available");expect(ui).toContain("Create X New Each Cycle")});
 it("previews without creating and calculates shortages",()=>{expect(sql).toContain("admin_preview_show_auto_host");expect(sql).toContain("greatest(wanted-current_count,0)");expect(sql).toContain("'side_effects',false");expect(ui).toContain("PREVIEW — ZERO SHOWS CREATED")});
 it("uses ET scheduling with distinct creation and future run times",()=>{const schedulerFix=readFileSync("supabase/migrations/202609180017_fix_auto_host_scheduler_context.sql","utf8");expect(sql).toContain("timezone text not null default 'America/New_York'");expect(sql).toContain("creation_time time not null default '00:05'");expect(sql).toContain("run_delay_days integer not null default 1");expect(sql).toContain("run_at_time:=(run_day::timestamp at time zone c.timezone)");expect(schedulerFix).toContain("auth.uid()is not null and not has_show_capability")});
 it("is cycle-idempotent and retry safe",()=>{expect(sql).toContain("cycle_key text not null unique");expect(sql).toContain("on conflict(cycle_key)do nothing");expect(sql).toContain("'-daily'");expect(sql).toContain("'manual-'||p_request::text")});
 it("creates normal sourced shows without fake entries or a second runner",()=>{expect(sql).toContain("insert into player_shows");expect(sql).toContain("'auto_host'");expect(sql).not.toContain("insert into player_show_entries");expect(runner).toContain("process_due_player_shows");expect(ap).toContain("create trigger award_ap_from_show_result")});
 it("keeps normal AP awards and execution idempotency",()=>{expect(ap).toContain("first_place integer not null default 3");expect(ap).toContain("second_place integer not null default 2");expect(ap).toContain("third_place integer not null default 1");expect(ap).toContain("show_result_id uuid not null unique")});
 it("provides responsive contained controls and run history",()=>{expect(ui).toContain("Auto Host History");expect(ui).toContain("RUN AUTO HOST NOW");expect(ui).toContain("SELECT ALL DISCIPLINES + LEVELS");expect(readFileSync("app/show-auto-host.css","utf8")).toContain("max-height:580px;overflow:auto");expect(readFileSync("app/show-auto-host.css","utf8")).toContain("@media(max-width:700px)")});
});
