/* eslint-disable @typescript-eslint/no-explicit-any */
import {generateImage,generateText,Output} from "ai";
import {gateway} from "@ai-sdk/gateway";
import {createClient} from "@supabase/supabase-js";
import sharp from "sharp";
import {z} from "zod";
import {type VisualPhenotype} from "@/lib/game/horse-visual";

export const runtime="nodejs";
export const maxDuration=300;
type ImageJob={job_id:string;horse_id:string;visual_phenotype:VisualPhenotype;markings:Record<string,string>;image_url:string};
const url=process.env.NEXT_PUBLIC_SUPABASE_URL!,anonKey=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY!;

async function authenticate(request:Request){const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!token)return false;const client=createClient(url,anonKey,{auth:{persistSession:false}});const{data,error}=await client.auth.getUser(token);return !error&&Boolean(data.user)}
async function claim(admin:any){const{data,error}=await admin.rpc("claim_store_horse_image_job");if(error)throw error;return(data?.[0]??null)as ImageJob|null}
async function fail(admin:any,job:ImageJob,error:unknown){const message=error instanceof Error?error.message:"Image generation failed",providerUnavailable=/credit card|gateway|authentication|rate limit/i.test(message),retryMs=providerUnavailable?5*60_000:30_000;await admin.from("store_horse_image_jobs").update({status:"pending",last_error:message.slice(0,500),next_attempt_at:new Date(Date.now()+retryMs).toISOString()}).eq("id",job.job_id);await admin.from("horses").update({image_generation_status:"pending"}).eq("id",job.horse_id);return providerUnavailable?"Image generation is waiting briefly for the production image provider.":"Artwork generation will retry automatically."}

// Remove light neutral pixels connected to the canvas edge. This deliberately
// includes fake transparency checkerboards produced by image models. Enclosed
// white horse markings remain opaque because they are not edge-connected.
async function transparentBackground(input:Uint8Array){
 const image=sharp(input).ensureAlpha(),{data,info}=await image.raw().toBuffer({resolveWithObject:true});
 const seen=new Uint8Array(info.width*info.height),queue=new Int32Array(info.width*info.height);let head=0,tail=0;
 const add=(index:number)=>{if(index<0||index>=seen.length||seen[index])return;const p=index*4,r=data[p],g=data[p+1],b=data[p+2];if(Math.min(r,g,b)<145||Math.max(r,g,b)-Math.min(r,g,b)>48)return;seen[index]=1;queue[tail++]=index};
 for(let x=0;x<info.width;x++){add(x);add((info.height-1)*info.width+x)}for(let y=0;y<info.height;y++){add(y*info.width);add(y*info.width+info.width-1)}
 while(head<tail){const i=queue[head++],x=i%info.width;data[i*4+3]=0;if(x>0)add(i-1);if(x<info.width-1)add(i+1);add(i-info.width);add(i+info.width)}
 // Feather only the one-pixel silhouette boundary to avoid a jagged matte.
 for(let i=0;i<seen.length;i++){if(seen[i])continue;const x=i%info.width,y=Math.floor(i/info.width),touches=(x>0&&seen[i-1])||(x<info.width-1&&seen[i+1])||(y>0&&seen[i-info.width])||(y<info.height-1&&seen[i+info.width]);if(touches)data[i*4+3]=Math.min(data[i*4+3],190)}
 return sharp(data,{raw:info}).png().toBuffer();
}

const qaSchema=z.object({approved:z.boolean(),has_signature_or_writing:z.boolean(),malformed_anatomy:z.boolean(),major_phenotype_error:z.boolean(),background_error:z.boolean(),reasons:z.array(z.string()).max(6)});
async function inspectArtwork(source:Uint8Array,job:ImageJob){const{output}=await generateText({model:gateway("openai/gpt-5.4-mini"),output:Output.object({schema:qaSchema}),messages:[{role:"user",content:[{type:"text",text:`Act as a horse-game artwork QA reviewer. Expected breed: ${job.visual_phenotype.breed}; intended sex/body type: ${job.visual_phenotype.sex}; exact coat phenotype: ${job.visual_phenotype.color}; pattern: ${job.visual_phenotype.pattern}; face marking: ${job.visual_phenotype.face_marking}; leg markings: LF ${job.visual_phenotype.left_front}, RF ${job.visual_phenotype.right_front}, LH ${job.visual_phenotype.left_hind}, RH ${job.visual_phenotype.right_hind}. Reject any signature, watermark, artist mark, readable or pseudo-text, letters, numbers, logo, symbol, or writing. Reject malformed anatomy, extra/missing/fused limbs or hooves, a clearly wrong breed/color/pattern/marking, visible genitalia, multiple horses, props, checkerboard, or scenery. Do not reject merely because genitalia are intentionally omitted or sex cannot be anatomically confirmed. A plain neutral matte and a small natural grounding shadow are acceptable because the server removes them after QA. Approve one anatomically plausible matching horse on transparent or removable plain neutral.`},{type:"file",mediaType:"image/png",data:source}]}],maxRetries:1});return output}

function fastPrompt(phenotype:VisualPhenotype){return `Polished semi-realistic game illustration of exactly one ${phenotype.breed} ${phenotype.sex}, full body standing square, unmistakable breed-accurate conformation. Exact coat: ${phenotype.color}; pattern: ${phenotype.pattern}; face: ${phenotype.face_marking}; legs: left front ${phenotype.left_front}, right front ${phenotype.right_front}, left hind ${phenotype.left_hind}, right hind ${phenotype.right_hind}. Anatomically sound, exactly four natural legs and hooves. Convey sex only through body type; omit all genitalia. Isolated horse only on a plain light neutral background suitable for clean removal. No scenery, floor line, props, tack, people, shadow, checkerboard, text, letters, numbers, symbols, logo, signature, watermark, or artist mark. Landscape 4:3 with the entire horse and generous margins.`}

async function processJob(admin:any,job:ImageJob){const prompt=fastPrompt(job.visual_phenotype),attempts=[{model:"prodia/flux-fast-schnell",version:"horse-v17-fast"},{model:"prodia/flux-fast-schnell",version:"horse-v17-fast"},{model:"bfl/flux-2-pro",version:"horse-v17-quality-fallback"}];try{let rejection="visual requirements not met";for(let candidate=0;candidate<attempts.length;candidate++){const attempt=attempts[candidate];let result;try{result=await generateImage({model:gateway.imageModel(attempt.model),prompt,aspectRatio:"4:3",maxRetries:1})}catch(error){rejection=error instanceof Error?error.message:rejection;continue}const source=result.image.uint8Array,qa=await inspectArtwork(source,job),approved=qa.approved||(!qa.has_signature_or_writing&&!qa.malformed_anatomy&&!qa.major_phenotype_error);await admin.from("horse_image_qa_reviews").insert({horse_id:job.horse_id,job_id:job.job_id,approved,checks:{...qa,candidate:candidate+1,model:attempt.model,server_approved:approved}});if(!approved){rejection=qa.reasons.join("; ")||rejection;continue}const png=await transparentBackground(source),objectPath=`generated/horses/${job.horse_id}-v17.png`;const uploaded=await admin.storage.from("legacy-equine-media").upload(objectPath,png,{contentType:"image/png",cacheControl:"31536000",upsert:true});if(uploaded.error)throw uploaded.error;const publicUrl=admin.storage.from("legacy-equine-media").getPublicUrl(objectPath).data.publicUrl,completed=await admin.rpc("complete_horse_image_job",{target_job:job.job_id,target_horse:job.horse_id,new_image_url:publicUrl,used_prompt:prompt,prompt_version:attempt.version});if(completed.error)throw completed.error;return{ok:true as const}}throw new Error(`Artwork QA rejected all candidates: ${rejection}`)}catch(error){console.error("Horse artwork job failed",job.horse_id,error);return{ok:false as const,error:await fail(admin,job,error)}}}

export async function POST(request:Request){if(!url||!anonKey||!serviceKey)return Response.json({error:"Image worker is not configured"},{status:503});if(!await authenticate(request))return Response.json({error:"Authentication required"},{status:401});const admin=createClient(url,serviceKey,{auth:{persistSession:false}}),jobs:ImageJob[]=[];for(let batch=0;batch<12;batch++){const job=await claim(admin);if(!job)break;jobs.push(job)}const settled=await Promise.all(jobs.map(job=>processJob(admin,job)));let completed=0,failed=0;const messages=new Set<string>();for(const result of settled){if(result.ok)completed++;else{failed++;messages.add(result.error)}}return Response.json({claimed:jobs.length,completed,failed,message:messages.values().next().value??null})}
