"use client";
import{useCallback,useEffect,useState,type ReactNode}from"react";
import Link from"next/link";
import{createClient}from"@/lib/supabase/client";
import"./account-safety.css";
const supabase=createClient();
type Eligibility={identity_complete:boolean;adult:boolean;social_allowed:boolean;status:string};

function AccountInformation({socialGate=false,onEligible}:{socialGate?:boolean;onEligible?:()=>void}){const[state,setState]=useState<Eligibility|null>(null),[first,setFirst]=useState(""),[last,setLast]=useState(""),[dob,setDob]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const load=useCallback(async()=>{const{data,error}=await supabase.rpc("get_my_account_eligibility");if(error)setMessage(error.message);else setState(data as Eligibility)},[]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);const save=async()=>{setBusy(true);setMessage("");const{data,error}=await supabase.rpc("complete_account_information",{p_first_name:first,p_last_name:last,p_date_of_birth:dob||null});setBusy(false);if(error){setMessage(error.message);return}const next=data as Eligibility;setState(next);if(next.social_allowed)onEligible?.();else setMessage("Legacy Equine is currently available to players age 18 and older. Contact Admin through Help & Support for account questions.")};if(!state)return <section className="accountinfo panel">Loading account eligibility…</section>;if(state.identity_complete)return <section className={`accountinfo panel ${socialGate?"gate":""}`}><p className="eyebrow">PRIVATE ACCOUNT INFORMATION</p><h2>{state.social_allowed?"Account Information Complete":"Account Review Required"}</h2><p>{state.social_allowed?"Your private account information is complete. It is not shown to other players.":"Legacy Equine is currently available to players age 18 and older."}</p>{!state.social_allowed&&<Link href="/support">Contact Admin through Help &amp; Support →</Link>}</section>;return <section className={`accountinfo panel ${socialGate?"gate":""}`}><p className="eyebrow">ACCOUNT INFORMATION REQUIRED</p><h2>Complete Your Private Account Information</h2><p>Legacy Equine is currently available to players age 18 and older.</p><p className="accountprivacy">Private account information — not shown to other players.</p><div className="accountinfogrid"><label>First Name<input autoComplete="given-name" maxLength={80} value={first} onChange={e=>setFirst(e.target.value)} required/></label><label>Last Name<input autoComplete="family-name" maxLength={80} value={last} onChange={e=>setLast(e.target.value)} required/></label><label>Date of Birth<input type="date" autoComplete="bday" value={dob} onChange={e=>setDob(e.target.value)} required/></label></div><p>By continuing, you confirm that the information provided is accurate and that you meet Legacy Equine&apos;s current age requirement.</p><button className="primary" disabled={busy||!first.trim()||!last.trim()||!dob} onClick={()=>void save()}>{busy?"Saving…":"Complete Account Information"}</button>{message&&<p role="alert" className="authmessage">{message}</p>}<Link href="/support">Questions? Contact Admin through Help &amp; Support →</Link></section>}
export function AccountInformationPanel(){return <><AccountInformation/><nav className="accountpolicylinks" aria-label="Privacy and safety information"><Link href="/privacy-safety">Privacy &amp; Safety</Link><Link href="/community-standards">Community Standards</Link></nav></>}
export function SocialEligibilityGate({children}:{children:ReactNode}){const[eligible,setEligible]=useState(false),[checked,setChecked]=useState(false);useEffect(()=>{const timer=setTimeout(()=>void supabase.rpc("get_my_account_eligibility").then(({data})=>{setEligible(Boolean((data as Eligibility|null)?.social_allowed));setChecked(true)}),0);return()=>clearTimeout(timer)},[]);if(!checked)return <section className="accountinfo panel">Checking account eligibility…</section>;return eligible?<>{children}</>:<AccountInformation socialGate onEligible={()=>setEligible(true)}/>}
