"use client";
import{useCallback,useEffect,useMemo,useState}from"react";
import{createClient}from"@/lib/supabase/client";

const supabase=createClient(),money=(n:number)=>new Intl.NumberFormat("en-US").format(n);
type Area="open"|"scheduled"|"qa"|"controls"|"history"|"audit";
type Show={id:string;name:string;discipline:string;tier:string;run_at:string;entry_fee:number;max_entries:number|null;description:string;status:string;entry_count:number;purse:number;locked:boolean;is_private:boolean;is_admin_qa:boolean;processed_at?:string|null;cancelled_at?:string|null};
type Audit={id:string;show_name?:string;actor:string;actor_account:number;action:string;details:Record<string,unknown>;created_at:string};
type Account={stable_id:string;name:string;account_number:number};
type Workspace={shows:Show[];audit:Audit[];allowlist:(Account&{active:boolean;note:string})[];accounts:Account[];capabilities:Record<string,boolean>};

export function AdminShows({notify}:{notify:(message:string)=>void}){
 const[area,setArea]=useState<Area>("open"),[data,setData]=useState<Workspace|null>(null),[selected,setSelected]=useState(""),[qaTarget,setQaTarget]=useState(""),[busy,setBusy]=useState(false),[preview,setPreview]=useState<{show_name:string;entries:{horse_name:string;owner_name:string;score:number}[]}|null>(null),[edit,setEdit]=useState(false);
 const load=useCallback(async()=>{const{data,error}=await supabase.rpc("admin_show_workspace");if(error)notify(error.message);else{const next=data as Workspace;setData(next);setSelected(current=>current||next.shows.find(x=>x.status==="open")?.id||next.shows[0]?.id||"")}},[notify]);
 useEffect(()=>{void load()},[load]);
 const shows=data?.shows??[],chosen=shows.find(x=>x.id===selected),now=Date.now();
 const visible=useMemo(()=>shows.filter(s=>area==="open"?s.status==="open"&&!s.is_admin_qa:area==="scheduled"?s.status==="open"&&new Date(s.run_at).getTime()>now&&!s.is_admin_qa:area==="qa"?s.is_admin_qa||s.is_private:area==="history"?["processing","complete","cancelled"].includes(s.status):area==="controls"?s.status==="open":false),[shows,area,now]);
 const act=async(action:string,changes:Record<string,unknown>={})=>{if(!chosen)return;setBusy(true);const{error}=await supabase.rpc("admin_show_action",{p_show:chosen.id,p_action:action,p_changes:changes});setBusy(false);notify(error?.message??`${chosen.name}: ${action.replaceAll("_"," ")} complete.`);if(!error){setPreview(null);setEdit(false);await load()}};
 const previewResults=async()=>{if(!chosen)return;setBusy(true);const{data,error}=await supabase.rpc("admin_preview_show_results",{p_show:chosen.id});setBusy(false);if(error)notify(error.message);else setPreview(data)};
 const setQaAccess=async(stableId:string,active:boolean)=>{setBusy(true);const{error}=await supabase.rpc("admin_set_show_qa_access",{p_stable:stableId,p_active:active,p_note:active?"Owner-enabled Show QA access":"Owner-disabled Show QA access"});setBusy(false);notify(error?.message??`Test-account access ${active?"enabled":"disabled"}.`);if(!error){setQaTarget("");await load()}};
 const tabs:[Area,string][]=[["open","Open Shows"],["scheduled","Scheduled"],["qa","Test / QA"],["controls","Run Controls"],["history","Processing / History"],["audit","Audit"]];
 return <section className="panel adminshows"><p className="eyebrow">SHOW OPERATIONS</p><h2>Shows</h2><label className="adminshowselect">Show Admin Area<select value={area} onChange={e=>setArea(e.target.value as Area)}>{tabs.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><nav className="adminsubnav adminshowtabs">{tabs.map(([id,label])=><button key={id} className={area===id?"active":""} onClick={()=>setArea(id)}>{label}</button>)}</nav>
 {area!=="audit"&&<div className="adminshowlayout"><aside>{visible.map(s=><button className={selected===s.id?"active":""} key={s.id} onClick={()=>setSelected(s.id)}><b>{s.name}</b><small>{s.discipline} · {s.tier}</small><span>{s.status}{s.locked?" · locked":""}{s.is_admin_qa?" · QA":""}</span></button>)}{!visible.length&&<p>No Shows in this area.</p>}</aside>{chosen&&<article><p className="eyebrow">{chosen.is_admin_qa?"PRIVATE / TEST SHOW":chosen.status.toUpperCase()}</p><h3>{chosen.name}</h3><dl><div><dt>Discipline</dt><dd>{chosen.discipline}</dd></div><div><dt>Tier</dt><dd>{chosen.tier}</dd></div><div><dt>Scheduled</dt><dd>{new Date(chosen.run_at).toLocaleString()}</dd></div><div><dt>Entries</dt><dd>{chosen.entry_count}{chosen.max_entries?` / ${chosen.max_entries}`:""}</dd></div><div><dt>Purse</dt><dd>{money(chosen.purse)} LED</dd></div><div><dt>Entry Fee</dt><dd>{money(chosen.entry_fee)} LED</dd></div></dl>
 {area==="controls"&&<><div className="adminshowactions"><button disabled={busy} onClick={()=>void act(chosen.locked?"unlock":"lock")}>{chosen.locked?"Unlock":"Lock"}</button><button disabled={busy} onClick={()=>setEdit(true)}>Edit Show</button><button disabled={busy} onClick={()=>void previewResults()}>Preview Results</button><button disabled={busy} onClick={()=>void act("duplicate")}>Duplicate Show</button><button disabled={busy} onClick={()=>{if(confirm("Run this Show now using the production scoring engine?"))void act("run_now")}}>Run Show Now</button><button className="danger" disabled={busy} onClick={()=>{const reason=prompt("Cancellation reason");if(reason)void act("cancel",{reason})}}>Cancel Show</button></div><p className="featurehint">Run Now locks entries and uses the same idempotent processor as scheduled execution. Preview has zero gameplay or economic side effects.</p></>}
 {area==="qa"&&<section className="qacontrols"><b>QA / Sandbox execution</b><p>Private/Test Shows use the real preview scoring engine without CP, XP, LED, result, or Wellness effects.</p><div><button disabled={busy} onClick={()=>void act("duplicate_test")}>Create Private/Test Copy</button><button disabled={busy} onClick={()=>void previewResults()}>Run QA Preview</button></div><h4>Test-account allowlist</h4><div><select aria-label="Test account" value={qaTarget} onChange={e=>setQaTarget(e.target.value)}><option value="">Choose an account</option>{data?.accounts.map(x=><option key={x.stable_id} value={x.stable_id}>#{x.account_number} · {x.name}</option>)}</select><button disabled={busy||!qaTarget} onClick={()=>void setQaAccess(qaTarget,true)}>Allow Test Access</button></div>{data?.allowlist.map(x=><span key={x.stable_id}>#{x.account_number} · {x.name} · {x.active?"Allowed":"Disabled"} <button disabled={busy} onClick={()=>void setQaAccess(x.stable_id,!x.active)}>{x.active?"Disable":"Enable"}</button></span>)}{!data?.allowlist.length&&<small>No test accounts are allowlisted.</small>}</section>}
 {preview&&<section className="showpreview"><h4>Preview Results — No Side Effects</h4>{preview.entries.map((x,i)=><p key={`${x.horse_name}-${i}`}><b>{i+1}. {x.horse_name}</b><span>{x.owner_name}</span><em>{Number(x.score).toFixed(2)}</em></p>)}{!preview.entries.length&&<p>No entries to score.</p>}</section>}
 {edit&&<EditShow show={chosen} cancel={()=>setEdit(false)} save={changes=>void act("edit",changes)}/>}</article>}</div>}
 {area==="audit"&&<div className="adminshowaudit">{data?.audit.map(x=><article key={x.id}><b>{x.action.replaceAll("_"," ")}</b><span>{x.show_name||"Show system"}</span><small>{x.actor} #{x.actor_account} · {new Date(x.created_at).toLocaleString()}</small><details><summary>Details</summary><pre>{JSON.stringify(x.details,null,2)}</pre></details></article>)}{!data?.audit.length&&<p>No Show administration actions recorded yet.</p>}</div>}</section>
}

function EditShow({show,cancel,save}:{show:Show;cancel:()=>void;save:(changes:Record<string,unknown>)=>void}){const[name,setName]=useState(show.name),[description,setDescription]=useState(show.description),[runAt,setRunAt]=useState(show.run_at.slice(0,16)),[max,setMax]=useState(show.max_entries?.toString()??"");return <div className="showadminmodal"><section><h3>Edit Show</h3><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Run time<input type="datetime-local" value={runAt} onChange={e=>setRunAt(e.target.value)}/></label><label>Maximum entries<input type="number" min={2} value={max} onChange={e=>setMax(e.target.value)}/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><div><button onClick={cancel}>Cancel</button><button className="primary" onClick={()=>save({name,description,run_at:new Date(runAt).toISOString(),max_entries:max?Number(max):null})}>Save Show</button></div></section></div>}
