"use client";
import{useCallback,useEffect,useState}from"react";
import{createClient}from"@/lib/supabase/client";
const supabase=createClient(),categories=["All","Income","Purchases","Horses","Shows","Professional Services","Profession Education","LE Shop","Awards","Other"];
type Activity={id:string;amount:number;description:string;category:string;created_at:string;horse_id:string|null;resulting_balance:number};
type Summary={current_balance:number;earned:number;spent:number};
const money=(n:number)=>Number(n).toLocaleString();
export function Bank({balance,notify}:{balance:number;notify:(s:string)=>void}){const[activity,setActivity]=useState<Activity[]>([]),[summary,setSummary]=useState<Summary>({current_balance:balance,earned:0,spent:0}),[category,setCategory]=useState("All"),[older,setOlder]=useState(true),[loading,setLoading]=useState(false);
 const load=useCallback(async(before?:string)=>{setLoading(true);const[{data,error},{data:totals}]=await Promise.all([supabase.rpc("get_bank_activity",{before_time:before??null,page_size:25,category_filter:category}),supabase.rpc("get_bank_summary")]);if(error)notify(error.message);else{const page=(data??[])as Activity[];setActivity(current=>before?[...current,...page]:page);setOlder(page.length===25)}if(totals)setSummary(totals as Summary);setLoading(false)},[category,notify]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 return <><header className="title banktitle"><div><p className="eyebrow">LEGACY EQUINE BANK</p><h1>Your Bank</h1><p>Your LE Dollars, recent activity, and complete financial history.</p></div><button className="primary" disabled title="LED purchases are coming in a separately secured update">Buy LE Dollars · Soon</button></header><section className="banksummary"><article><span>Current Balance</span><b>{money(summary.current_balance)} LED</b></article><article><span>LED Earned</span><b className="credit">+{money(summary.earned)} LED</b></article><article><span>LED Spent</span><b className="debit">−{money(summary.spent)} LED</b></article></section><section className="panel bankactivity"><div className="bankheading"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Transaction History</h2></div><label>Filter<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><div className="banklist">{activity.map(a=><article key={a.id}><span className={a.amount>0?"bankamount income":"bankamount expense"}>{a.amount>0?"+":"−"}{money(Math.abs(a.amount))} LED</span><span><b>{a.description}</b><small>{a.category}{a.horse_id?" · Related horse":""}</small></span><span><time>{new Date(a.created_at).toLocaleString([],{dateStyle:"medium",timeStyle:"short"})}</time><small>Balance: {money(a.resulting_balance)} LED</small></span></article>)}{!activity.length&&!loading&&<p className="featurehint">No transactions in this category yet.</p>}</div>{older&&activity.length>0&&<button className="older" disabled={loading} onClick={()=>load(activity[activity.length-1].created_at)}>{loading?"Loading…":"Load Older Activity"}</button>}</section><section className="banknote"><b>LE Dollars stay in Legacy Equine.</b><span>USD → LED purchases may be added later. LED can never be withdrawn, redeemed, or exchanged for USD.</span></section></>}
