"use client";
import{useCallback,useEffect,useState}from"react";
import{GAME}from"@/lib/game/config";
import{createClient}from"@/lib/supabase/client";
const supabase=createClient();
type Row={breed:string;locus:string;allele:string;category:string;allele_frequency:number;rarity:string;foundation_generated:boolean;notes:string};
const rarities=["common","uncommon","rare","exceptional","not_generated"];
export function BreedGeneticsAdmin({notify}:{notify:(message:string)=>void}){
 const[breed,setBreed]=useState<string>(GAME.foundationBreeds[0]);const[rows,setRows]=useState<Row[]>([]);const[saving,setSaving]=useState<string|null>(null);
 const load=useCallback(async()=>{const{data,error}=await supabase.rpc("admin_list_foundation_genetics",{p_breed:breed});if(error)notify(error.message);else setRows((data??[])as Row[])},[breed,notify]);useEffect(()=>{void load()},[load]);
 const change=(locus:string,patch:Partial<Row>)=>setRows(current=>current.map(row=>row.locus===locus?{...row,...patch}:row));
 const save=async(row:Row)=>{setSaving(row.locus);const{error}=await supabase.rpc("admin_update_foundation_genetic_weight",{p_breed:row.breed,p_locus:row.locus,p_frequency:Number(row.allele_frequency),p_generated:row.foundation_generated,p_rarity:row.foundation_generated?row.rarity:"not_generated",p_notes:row.notes});notify(error?.message??`${row.breed} ${row.locus} Foundation frequency saved.`);setSaving(null);if(!error)await load()};
 return <section className="panel geneticsadmin"><p className="eyebrow">BREED GENETIC POPULATIONS</p><h2>Foundation genetics configuration</h2><p className="panelsub">These frequencies apply only when a new Foundation horse is generated. Existing genotypes and parent-to-foal inheritance are never rewritten or suppressed.</p><label>Breed<select value={breed} onChange={e=>setBreed(e.target.value)}>{GAME.foundationBreeds.map(value=><option key={value}>{value}</option>)}</select></label><div className="geneticstable"><div className="geneticshead"><b>Locus</b><b>Category</b><b>Allele frequency</b><b>Rarity</b><b>Foundation</b><b/></div>{rows.map(row=><div key={row.locus}><span><b>{row.locus}</b><small>{row.allele}</small></span><span>{row.category.replaceAll("_"," ")}</span><label><input aria-label={`${row.locus} allele frequency`} type="number" min="0" max="1" step="0.0001" disabled={!row.foundation_generated} value={row.allele_frequency} onChange={e=>change(row.locus,{allele_frequency:Number(e.target.value)})}/><small>{(Number(row.allele_frequency)*100).toFixed(3)}%</small></label><select aria-label={`${row.locus} rarity`} disabled={!row.foundation_generated} value={row.foundation_generated?row.rarity:"not_generated"} onChange={e=>change(row.locus,{rarity:e.target.value})}>{rarities.map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select><label className="geneticstoggle"><input type="checkbox" checked={row.foundation_generated} onChange={e=>change(row.locus,{foundation_generated:e.target.checked,rarity:e.target.checked?(row.rarity==="not_generated"?"rare":row.rarity):"not_generated",allele_frequency:e.target.checked?row.allele_frequency:0})}/><span>{row.foundation_generated?"Generated":"Excluded"}</span></label><button disabled={saving===row.locus} onClick={()=>void save(row)}>{saving===row.locus?"Saving…":"Save"}</button></div>)}</div></section>;
}
