/* eslint-disable @next/next/no-img-element */
"use client";
import{useCallback,useEffect,useState}from"react";
import{createClient}from"@/lib/supabase/client";
import styles from"./equipped-tack-strip.module.css";
const supabase=createClient();
type Slot="bridle"|"saddle"|"saddle_pad"|"leg_protection"|"shoes";
type EquippedItem={item_id:string;slot:Slot;item_name:string;quality:string|null;bonuses:Record<string,number>;icon_url:string|null;maker_brand_code:string|null;maker_stable_name:string|null;maker_account_number:number|null};
const slots:{id:Slot;label:string;short:string}[]=[{id:"bridle",label:"Bridle",short:"Bridle"},{id:"saddle",label:"Saddle",short:"Saddle"},{id:"saddle_pad",label:"Saddle Pad",short:"Pad"},{id:"leg_protection",label:"Boots / Leg Protection",short:"Boots"},{id:"shoes",label:"Shoes",short:"Shoes"}];
const statLabels:Record<string,string>={Agility:"AGI",Speed:"SPD",Endurance:"END",Temperament:"TMP",Strength:"STR",Intelligence:"INT",Conformation:"CON"};
function TackIcon({slot}:{slot:Slot}){if(slot==="bridle")return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 5c2-2 8-2 10 0l-1 5c-.5 5-2 8-4 9-2-1-3.5-4-4-9L7 5Z"/><path d="M8 8h8M9 12h6M7 5 5 3m12 2 2-2"/></svg>;if(slot==="saddle")return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 15c1-6 3-9 7-10 1 3 3 5 7 6l-1 5H7l-2-1Z"/><path d="M8 16v4m8-4v4M9 10h7"/></svg>;if(slot==="saddle_pad")return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 5 13 3-3 11-13-3L6 5Z"/><path d="m8 8 8 2-2 6-8-2 2-6Z"/></svg>;if(slot==="leg_protection")return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3h8l-1 18H9L8 3Z"/><path d="M9 7h7M9 12h6M9 17h6"/></svg>;return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 5c-2 5-1 11 3 14 3 2 8 0 9-4 1-3-1-8-4-10"/><path d="M7 8c3 2 6 2 9 0M8 17c2-2 5-2 8 0"/></svg>}
const bonuses=(item:EquippedItem)=>Object.entries(item.bonuses??{}).filter(([,value])=>Number(value)!==0);
export function EquippedTackStrip({horseId,canManage,onChanged,openTackRoom}:{horseId:string;canManage:boolean;onChanged:()=>void;openTackRoom:()=>void}){const[items,setItems]=useState<EquippedItem[]>([]),[open,setOpen]=useState<Slot|null>(null),[busy,setBusy]=useState(false);const load=useCallback(async()=>{const{data}=await supabase.rpc("get_horse_equipped_tack",{p_horse:horseId});setItems((data??[])as EquippedItem[])},[horseId]);useEffect(()=>{void load()},[load]);const unequip=async(item:EquippedItem)=>{setBusy(true);const{error}=await supabase.rpc("unequip_tack",{p_horse:horseId,p_slot:item.slot});if(!error){setItems(current=>current.filter(x=>x.item_id!==item.item_id));setOpen(null);onChanged()}setBusy(false)};return <section className={styles.section} aria-label="Equipped Tack"><p className={styles.heading}>EQUIPPED TACK</p><div className={styles.strip}>{slots.map(slot=>{const item=items.find(x=>x.slot===slot.id),expanded=open===slot.id;return <article className={`${styles.slot} ${item?"":styles.empty}`} key={slot.id}><button type="button" className={styles.summaryButton} disabled={!item} aria-expanded={item?expanded:undefined} onClick={()=>item&&setOpen(expanded?null:slot.id)}><span className={styles.summary}><span className={styles.icon}>{item?.icon_url?<img src={item.icon_url} alt=""/>:<TackIcon slot={slot.id}/>}</span><span><b>{item?.item_name??`${slot.short} — Empty`}</b>{item&&<small>{bonuses(item).map(([stat,value])=>`+${value} ${statLabels[stat]??stat.slice(0,3).toUpperCase()}`).join(" · ")||"No bonus"}</small>}</span></span></button>{item&&expanded&&<div className={styles.detail}><b>{item.item_name}</b><small>{item.quality}</small><span className={styles.bonuses}>{bonuses(item).map(([stat,value])=><em key={stat}>+{value} {stat}</em>)}</span><small>Effective Stats only</small>{item.maker_stable_name&&<small>Crafted by {item.maker_brand_code?`${item.maker_brand_code} • `:""}{item.maker_stable_name} #{item.maker_account_number}</small>}{canManage&&<span className={styles.actions}><button type="button" onClick={openTackRoom}>CHANGE</button><button type="button" disabled={busy} onClick={()=>void unequip(item)}>UNEQUIP</button></span>}</div>}</article>})}</div></section>}
