"use client";
import Link from"next/link";
import{useCallback,useEffect,useMemo,useState}from"react";
import{createClient}from"@/lib/supabase/client";
import"@/app/handbook.css";
const supabase=createClient();
type Category={id:string;name:string;description:string;sort_order:number};
type Article={id:string;slug:string;category_id:string;category?:string;title:string;summary:string;body?:string;featured:boolean;sort_order:number;config?:Record<string,unknown>};
type Data={categories:Category[];articles:Article[]};
export function Handbook({slug=""}:{slug?:string}){const[data,setData]=useState<Data>({categories:[],articles:[]}),[article,setArticle]=useState<Article|null>(null),[query,setQuery]=useState(""),[category,setCategory]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");if(slug){const{data:row,error:e}=await supabase.rpc("get_handbook_article",{p_slug:slug});if(e)setError(e.message);else setArticle(row as Article|null)}else{const{data:rows,error:e}=await supabase.rpc("get_handbook",{p_search:query,p_category:category||null});if(e)setError(e.message);else setData(rows as Data)}setLoading(false)},[slug,query,category]);
 useEffect(()=>{const t=setTimeout(()=>void load(),query?180:0);return()=>clearTimeout(t)},[load,query]);
 if(slug)return <article className="handbook article"><Link className="back" href="/how-to-play">← Back to How to Play</Link>{loading?<p>Loading article…</p>:error?<p className="featurehint">{error}</p>:article?<><header><p className="eyebrow">{article.category}</p><h1>{article.title}</h1><p>{article.summary}</p></header><SafeArticle body={article.body??""}/><ConfigPanel config={article.config??{}}/></>:<p>Article not found.</p>}</article>;
 const grouped=useMemo(()=>data.categories.map(c=>({...c,articles:data.articles.filter(a=>a.category_id===c.id)})).filter(c=>!category||c.id===category),[data,category]);
 return <div className="handbook"><header className="handbookhero"><p className="eyebrow">PLAYER HANDBOOK</p><h1>HOW TO PLAY LEGACY EQUINE</h1><p>Learn the basics, understand game systems, and find answers as you build your Legacy.</p><label>Search How to Play<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search AP, Feed, Shows, Professions…"/></label></header><nav className="handbookcategories" aria-label="Handbook categories"><button className={!category?"active":""} onClick={()=>setCategory("")}>All</button>{data.categories.map(c=><button className={category===c.id?"active":""} key={c.id} onClick={()=>setCategory(c.id)}>{c.name}</button>)}</nav>{loading?<p>Searching Handbook…</p>:error?<p className="featurehint">{error}</p>:<div className="handbooksections">{grouped.map(c=><section key={c.id}><div><h2>{c.name}</h2><p>{c.description}</p></div><div className="handbookgrid">{c.articles.map(a=><Link className={a.featured?"featured":""} href={`/how-to-play/${a.slug}`} key={a.id}><small>{a.featured?"FEATURED GUIDE":"GUIDE"}</small><h3>{a.title}</h3><p>{a.summary}</p><b>Read guide →</b></Link>)}</div></section>)}{!data.articles.length&&<p className="panel">No published guides match your search.</p>}</div>}</div>}
function SafeArticle({body}:{body:string}){const lines=body.split("\n");return <div className="handbookbody">{lines.map((line,i)=>{if(line.startsWith("# "))return <h2 key={i}>{line.slice(2)}</h2>;if(line.startsWith("## "))return <h3 key={i}>{line.slice(3)}</h3>;if(/^\d+\. /.test(line))return <p className="handbookstep" key={i}>{line}</p>;if(line.startsWith("- "))return <p className="handbookbullet" key={i}>• {line.slice(2)}</p>;return line?<p key={i}>{renderInline(line)}</p>:<br key={i}/>})}</div>}
function renderInline(text:string){const parts=text.split(/(\[[^\]]+\]\(\/[A-Za-z0-9_?&=#./-]+\)|\*\*[^*]+\*\*|\*[^*]+\*)/g);return parts.map((part,i)=>{const link=part.match(/^\[([^\]]+)\]\((\/[A-Za-z0-9_?&=#./-]+)\)$/);if(link)return <Link key={i} href={link[2]}>{link[1]}</Link>;if(part.startsWith("**")&&part.endsWith("**"))return <strong key={i}>{part.slice(2,-2)}</strong>;if(part.startsWith("*")&&part.endsWith("*"))return <em key={i}>{part.slice(1,-1)}</em>;return part})}
function ConfigPanel({config}:{config:Record<string,unknown>}){if(!Object.keys(config).length)return null;if(Array.isArray(config.tiers))return <section className="handbookconfig"><h2>Current authoritative Show configuration</h2><p><b>Eligibility basis:</b> {config.basis==="career_points"?"Career Points":"Average Permanent Stats"}</p><div className="configtable">{(config.tiers as{name:string;minimum:number;maximum:number|null}[]).map(t=><div key={t.name}><b>{t.name}</b><span>{t.minimum.toLocaleString()}–{t.maximum==null?"and above":t.maximum.toLocaleString()}</span></div>)}</div></section>;if("first"in config)return <section className="handbookconfig"><h2>Current AP awards</h2><div className="configtable"><div><b>1st</b><span>+{String(config.first)} AP</span></div><div><b>2nd</b><span>+{String(config.second)} AP</span></div><div><b>3rd</b><span>+{String(config.third)} AP</span></div></div></section>;if("base_storage"in config)return <section className="handbookconfig"><h2>Current Feed rules</h2><div className="configtable"><div><b>Daily Hay</b><span>{String(config.hay_per_horse_per_day)} per horse</span></div><div><b>Daily Grain</b><span>{String(config.grain_per_horse_per_day)} per horse</span></div><div><b>Base storage</b><span>{String(config.base_storage)} units</span></div><div><b>Level capacity</b><span>+{String(config.storage_per_five_levels)} per 5 levels</span></div><div><b>Subscriber bonus</b><span>+{String(config.subscriber_bonus)}</span></div></div></section>;return null}
export function HandbookHelpLink({slug,children="How does this work?"}:{slug:string;children?:string}){return <Link className="handbookhelp" href={`/how-to-play/${slug}`}>? {children}</Link>}
