/* eslint-disable @next/next/no-img-element, react-hooks/static-components */
"use client";
import{useCallback,useEffect,useMemo,useState}from"react";
import{createClient}from"@/lib/supabase/client";
import{GAME}from"@/lib/game/config";
import{ContainedHorseArtwork}from"@/app/contained-horse-artwork";
import{horseArtworkCandidates}from"@/lib/game/horse-artwork";
import{HorseCare}from"@/app/professions";
import{competitionTier,type CompetitionTier}from"@/lib/game/show-engine";
const supabase=createClient();
export type ProfileHorse={id:string;owner_id:string|null;name:string;breed:string;sex:"Mare"|"Stallion";color:string;origin:string;birth_date:string;sire_id:string|null;dam_id:string|null;generation:number;career_points:number;birth_stats:Record<string,number>;stats:Record<string,number>;tack_bonuses:Record<string,number>;biography:string;image_url:string;image_generation_status?:string;stud_fee:number;last_bred_at:string|null;last_trained_at:string|null;retired:boolean;genetics:Record<string,string[]>;breed_composition:Record<string,number>};
type Tab="overview"|"stats"|"training"|"shows"|"farrier"|"health"|"pedigree"|"progeny"|"breeding";
function HorseArtwork({horse,onPrimaryFailure}:{horse:ProfileHorse;onPrimaryFailure?:(url:string)=>void}){return <ContainedHorseArtwork className="horseartwork" url={horse.image_url} alt={`${horse.name}, ${horse.color} ${horse.breed}`} onPrimaryFailure={onPrimaryFailure} showFallbackLabel/>}
type Training={id:string;stat_key:string;gain:number;created_at:string};type Service={profession_id:string;effect:Record<string,number>;effect_expires_at:string|null;completed_at:string};type Entry={id:string;entered_at:string;player_shows:{name:string;run_at:string;status:string;discipline_id:string;tier_id:string}|null};
type ShowRecord={starts:number;wins:number;places:number;shows:number;other_placings:number;career_points:number;earnings:number;disciplines:{discipline:string;starts:number;wins:number;places:number;shows:number}[];history:{id:string;show_id:string;name:string;discipline:string;tier:string;run_at:string;placement:number;score:number;career_points:number;earnings:number;owner_name_snapshot:string;owner_account_snapshot:number}[]};
const labels:Record<string,string>={Agility:"AGI",Speed:"SPD",Endurance:"END",Temperament:"TMP",Strength:"STR",Intelligence:"INT",Conformation:"CON"},tabs:Tab[]=["overview","stats","training","shows","farrier","health","pedigree","progeny","breeding"];
const age=(h:ProfileHorse)=>(Date.now()-new Date(h.birth_date).getTime())/86400000*GAME.age.gameDaysPerRealDay/365.25;
const breedingAgeStatus=(h:ProfileHorse)=>age(h)<GAME.age.breedingMinimumYears?{eligible:false,label:"🔒 Too Young",detail:`Eligible at age ${GAME.age.breedingMinimumYears}`}:(age(h)>=GAME.age.breedingMaximumYears+1||h.retired)?{eligible:false,label:"Retired from Breeding",detail:`Breeding eligibility ends after age ${GAME.age.breedingMaximumYears}`}:{eligible:true,label:"✓ Eligible",detail:`Age ${Math.floor(age(h))} · eligible through age ${GAME.age.breedingMaximumYears}`};
const canBreed=(h:ProfileHorse)=>breedingAgeStatus(h).eligible&&(!h.last_bred_at||h.sex!=="Mare"||Date.now()-new Date(h.last_bred_at).getTime()>=GAME.mareCooldownDays*86400000),canTrain=(h:ProfileHorse)=>!h.last_trained_at||Date.now()-new Date(h.last_trained_at).getTime()>=20*3600000;
export function HorseProfile({h,horses,tiers,stableName,canEdit,isAdmin,save,train,breed,openHorse,openProfessions,regenerateImage,reportImageFailure}:{h:ProfileHorse;horses:ProfileHorse[];tiers:CompetitionTier[];stableName:string;canEdit:boolean;isAdmin:boolean;save:(n:string,b:string,i:string)=>void;train:(s:string)=>void;breed:(m:string)=>void;openHorse:(h:ProfileHorse)=>void;openProfessions:()=>void;regenerateImage:()=>void;reportImageFailure:(url:string)=>void}){const initial=typeof window!=="undefined"&&tabs.includes(location.hash.slice(1)as Tab)?location.hash.slice(1)as Tab:"overview",[tab,setTab]=useState<Tab>(initial),[name,setName]=useState(h.name),[bio,setBio]=useState(h.biography),[image,setImage]=useState(h.image_url),[mare,setMare]=useState(""),[training,setTraining]=useState<Training[]>([]),[services,setServices]=useState<Service[]>([]),[entries,setEntries]=useState<Entry[]>([]),[showRecord,setShowRecord]=useState<ShowRecord|null>(null),[relatives,setRelatives]=useState<ProfileHorse[]>([]),[offspring,setOffspring]=useState<ProfileHorse[]>([]),[openStat,setOpenStat]=useState<string|null>(null),tierName=competitionTier(h.career_points??0,tiers)?.name??"Unassigned";
 const tier=(_points:number)=>tierName;
 const load=useCallback(async()=>{const[{data:t},{data:s},{data:e},{data:o},{data:record}]=await Promise.all([supabase.from("training_log").select("id,stat_key,gain,created_at").eq("horse_id",h.id).order("created_at",{ascending:false}),supabase.from("horse_service_records").select("profession_id,effect,effect_expires_at,completed_at").eq("horse_id",h.id).eq("status","completed"),supabase.from("player_show_entries").select("id,entered_at,player_shows(name,run_at,status,discipline_id,tier_id)").eq("horse_id",h.id).order("entered_at",{ascending:false}),supabase.from("horses").select("*").or(`sire_id.eq.${h.id},dam_id.eq.${h.id}`).order("birth_date",{ascending:false}),supabase.rpc("get_horse_show_record",{target_horse:h.id})]);setTraining((t??[])as Training[]);setServices((s??[])as Service[]);setEntries((e??[])as unknown as Entry[]);setShowRecord(record as ShowRecord|null);setOffspring((o??[])as ProfileHorse[]);
 const ids=[h.sire_id,h.dam_id].filter(Boolean)as string[];if(ids.length){const{data:p}=await supabase.from("horses").select("*").in("id",ids);const parents=(p??[])as ProfileHorse[],grandIds=parents.flatMap(x=>[x.sire_id,x.dam_id]).filter(Boolean)as string[];let grands:ProfileHorse[]=[];if(grandIds.length){const{data:g}=await supabase.from("horses").select("*").in("id",grandIds);grands=(g??[])as ProfileHorse[];const greatIds=grands.flatMap(x=>[x.sire_id,x.dam_id]).filter(Boolean)as string[];if(greatIds.length){const{data:gg}=await supabase.from("horses").select("*").in("id",greatIds);setRelatives([...parents,...grands,...((gg??[])as ProfileHorse[])])}else setRelatives([...parents,...grands])}else setRelatives(parents)}else setRelatives([])},[h.id,h.sire_id,h.dam_id]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 const trainingByStat=useMemo(()=>Object.fromEntries(GAME.stats.map(stat=>[stat,training.filter(x=>x.stat_key===stat).reduce((n,x)=>n+x.gain,0)])),[training]);const active=services.filter(s=>!s.effect_expires_at||new Date(s.effect_expires_at)>new Date()),serviceValue=(stat:string,profession:string)=>active.filter(s=>s.profession_id===profession).reduce((n,s)=>n+Number(s.effect?.[stat]??0),0),breakdown=(stat:string)=>{const developed=Number(h.stats[stat]??0),birth=Number(h.birth_stats?.[stat]??Math.max(0,developed-Number(trainingByStat[stat]??0))),development=developed-birth,tack=Number(h.tack_bonuses?.[stat]??0),farrier=serviceValue(stat,"farrier"),massage=serviceValue(stat,"massage"),other=serviceValue(stat,"veterinarian")+serviceValue(stat,"trainer");return{birth,development,developed,tack,farrier,massage,other,effective:developed+tack+farrier+massage+other}};
 const choose=(next:Tab)=>{setTab(next);history.replaceState(null,"",`${location.pathname}${location.search}#${next}`)},find=(id:string|null)=>relatives.find(x=>x.id===id),mares=horses.filter(x=>x.sex==="Mare"&&x.id!==h.id&&canBreed(x)),upcoming=entries.filter(e=>e.player_shows?.status==="open");
 const StatStrip=()=> <div className="compactstats" aria-label="All horse stats">{GAME.stats.map(stat=>{const d=breakdown(stat),shown=openStat===stat;return <button key={stat} onClick={()=>setOpenStat(shown?null:stat)} onBlur={()=>setOpenStat(null)} aria-expanded={shown}><span>{labels[stat]}</span><b>{d.effective}</b><aside className={shown?"open":""}><strong>{stat}</strong><small>Birth: {d.birth}</small><small>Development: +{d.development}</small><small>Developed: {d.developed}</small><small>Tack: +{d.tack}</small><small>Farrier: +{d.farrier}</small><small>Massage: +{d.massage}</small><small>Other: +{d.other}</small><b>Effective: {d.effective}</b></aside></button>})}</div>;
 const P=({horse,label}:{horse:ProfileHorse|undefined;label:string})=><div className="ped"><small>{label}</small>{horse?<button onClick={()=>openHorse(horse)}><b>{horse.name}</b><span>{horse.breed}</span></button>:<i>Unknown foundation line</i>}</div>;
 return <><section className="horseprofilehero"><HorseArtwork horse={h} onPrimaryFailure={reportImageFailure}/><div className="horseprofileinfo"><p className="eyebrow">{h.origin.toUpperCase()} · GENERATION {h.generation}</p><h1>{h.name}</h1><p className="meta">{h.breed} <b>•</b> {h.sex} <b>•</b> {age(h).toFixed(1)} years <b>•</b> {h.color}</p><p className="ownerline">{stableName}</p><div className="careerquick"><b>{h.career_points??0}</b><span>Career Points · {tier(h.career_points??0)} Tier</span></div>{tab==="overview"&&<><button className="showrecordquick" onClick={()=>choose("shows")} title="Open this horse's public Show Record">{showRecord?.wins??0}W · {showRecord?.places??0}P · {showRecord?.shows??0}S · {showRecord?.career_points??h.career_points??0} PTS</button><StatStrip/><p className="horsebio">{h.biography||"No biography has been added yet."}</p>{canEdit&&<details className="profileeditor"><summary>Edit horse profile</summary><label>Horse name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Biography<textarea value={bio} placeholder="Write this horse's story…" onChange={e=>setBio(e.target.value)}/></label><label>Custom artwork URL<input value={image} onChange={e=>setImage(e.target.value)}/></label><button className="primary" onClick={()=>save(name,bio,image)}>Save Profile</button></details>}{isAdmin&&<button className="adminregenerate" onClick={regenerateImage}>Regenerate Image</button>}</>}</div></section><nav className="profiletabs" aria-label="Horse profile sections">{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>choose(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav>
 {tab==="overview"&&<section className="panel overviewstatus"><h2>Current Status</h2><span>{canTrain(h)?"Ready to train":"Training cooldown active"}</span><span>{canBreed(h)?"Breeding eligible":"Not currently breeding eligible"}</span><span>{active.length} active professional service effect{active.length===1?"":"s"}</span></section>}
 {tab==="stats"&&<section className="panel"><p className="eyebrow">FULL BREAKDOWN · SEVEN CONFIRMED STATS</p><h2>Stats</h2><p className="panelsub">Birth values are permanent history. Developed values drive breeding; Effective values add tack and active services for shows. Stats have no fixed ceiling.</p><div className="statdetails">{GAME.stats.map(stat=>{const d=breakdown(stat);return <article key={stat}><header><b>{stat}</b><strong>{d.effective} Effective</strong></header><div><span>Birth {d.birth}</span><span>Development +{d.development}</span><span>Developed {d.developed}</span><span>Tack +{d.tack}</span><span>Farrier +{d.farrier}</span><span>Massage +{d.massage}</span><span>Other +{d.other}</span></div></article>})}</div></section>}
 {tab==="training"&&<section className="panel"><p className="eyebrow">PERMANENT DEVELOPMENT</p><h2>Training</h2><p>{canTrain(h)?"Ready for a training session.":`Cooldown active. Ready ${new Date(new Date(h.last_trained_at!).getTime()+20*3600000).toLocaleString()}.`}</p><div className="trainingactions">{GAME.stats.map(stat=><article key={stat}><span><b>{stat}</b><small>Birth {breakdown(stat).birth} · Development +{breakdown(stat).development} · Developed {breakdown(stat).developed}</small></span><button disabled={!canTrain(h)} onClick={()=>train(stat)}>Train +1</button></article>)}</div><h3>Training History</h3>{training.map(x=><div className="historyrow" key={x.id}><span>{x.stat_key} +{x.gain}</span><time>{new Date(x.created_at).toLocaleString()}</time></div>)}{!training.length&&<p className="featurehint">No training sessions recorded yet.</p>}<button onClick={openProfessions}>Find a Trainer</button></section>}
 {tab==="shows"&&<section className="panel horseshows"><p className="eyebrow">PUBLIC · {tier(h.career_points??0)} TIER</p><h2>Show Record</h2><div className="showfacts"><span><b>{showRecord?.starts??0}</b> Starts</span><span><b>{showRecord?.wins??0}</b> Wins</span><span><b>{showRecord?.places??0}</b> Places</span><span><b>{showRecord?.shows??0}</b> Shows</span><span><b>{showRecord?.other_placings??0}</b> Other Placings</span><span><b>{showRecord?.career_points??h.career_points??0}</b> Career Points</span><span><b>{Number(showRecord?.earnings??0).toLocaleString()}</b> LED Earnings</span><span><b>{showRecord?.starts?((showRecord.wins/showRecord.starts)*100).toFixed(1):'0.0'}%</b> Win Rate</span><span><b>{showRecord?.starts?(((showRecord.wins+showRecord.places+showRecord.shows)/showRecord.starts)*100).toFixed(1):'0.0'}%</b> Top 3</span></div><h3>Discipline Records</h3><div className="disciplinerecords">{showRecord?.disciplines.map(d=><article key={d.discipline}><b>{d.discipline}</b><span>{d.starts} starts · {d.wins} wins · {d.places} places · {d.shows} shows</span></article>)}</div>{!showRecord?.disciplines.length&&<p className="featurehint">No discipline record yet.</p>}<h3>Upcoming Entries</h3>{upcoming.map(e=><div className="historyrow" key={e.id}><span>{e.player_shows?.name} · {e.player_shows?.discipline_id.replaceAll('_',' ')}</span><time>{new Date(e.player_shows!.run_at).toLocaleString()}</time></div>)}{!upcoming.length&&<p className="featurehint">No upcoming entries.</p>}<h3>Historical Results</h3>{showRecord?.history.map(r=><article className="showhistory" key={r.id}><div><p className="eyebrow">{r.discipline} · {r.tier}</p><h4>{r.name}</h4><time>{new Date(r.run_at).toLocaleDateString()}</time><small>Owned at time by {r.owner_name_snapshot} #{r.owner_account_snapshot}</small></div><strong>{r.placement===1?'WIN':r.placement===2?'PLACE':r.placement===3?'SHOW':`#${r.placement}`}</strong><span>Score <b>{Number(r.score).toFixed(2)}</b><br/>Career Points <b>+{r.career_points}</b><br/>Earnings <b>{Number(r.earnings).toLocaleString()} LED</b></span></article>)}{!showRecord?.history.length&&<p className="featurehint">This horse has not completed a show yet.</p>}</section>}
 {tab==="farrier"&&<><HorseCare horseId={h.id} section="farrier"/><button className="primary careaction" onClick={openProfessions}>Request Farrier Service</button></>}{tab==="health"&&<><HorseCare horseId={h.id} section="health"/><button className="primary careaction" onClick={openProfessions}>Request Health or Massage Service</button></>}
 {tab==="pedigree"&&<section className="panel"><p className="eyebrow">THREE-GENERATION ANCESTRY</p><h2>Pedigree</h2><div className="pedigree"><div><P horse={h} label="HORSE"/></div><div><P horse={find(h.sire_id)} label="SIRE"/><P horse={find(h.dam_id)} label="DAM"/></div><div><P horse={find(find(h.sire_id)?.sire_id??null)} label="PATERNAL GRANDSIRE"/><P horse={find(find(h.sire_id)?.dam_id??null)} label="PATERNAL GRANDDAM"/><P horse={find(find(h.dam_id)?.sire_id??null)} label="MATERNAL GRANDSIRE"/><P horse={find(find(h.dam_id)?.dam_id??null)} label="MATERNAL GRANDDAM"/></div><div className="greats">{relatives.filter(x=>[...relatives.slice(0,6)].some(p=>p.sire_id===x.id||p.dam_id===x.id)).map(x=><P horse={x} label="GREAT-GRANDPARENT" key={x.id}/>)}</div></div></section>}
 {tab==="progeny"&&<section className="panel"><p className="eyebrow">PERMANENT OFFSPRING RECORD</p><h2>Progeny</h2><div className="progenygrid">{offspring.map(x=><button key={x.id} onClick={()=>openHorse(x)}>{horseArtworkCandidates(x.image_url)[0]?<img src={horseArtworkCandidates(x.image_url)[0]} alt={x.name}/>:<span className="horseartpending"><b>♞</b><small>Unique artwork generating…</small></span>}<span><b>{x.name}</b><small>{x.breed} · {x.sex} · {age(x).toFixed(1)} years</small></span><div>{GAME.stats.map(s=><i key={s}>{labels[s]} {x.stats[s]}</i>)}</div></button>)}</div>{!offspring.length&&<p className="featurehint">No offspring recorded.</p>}</section>}
 {tab==="breeding"&&<section className="panel breed"><p className="eyebrow">BREEDING RECORD</p><h2>Breeding</h2><div className={`breedingstatus ${breedingAgeStatus(h).eligible?"eligible":"ineligible"}`}><small>BREEDING STATUS</small><b>{breedingAgeStatus(h).label}</b><span>{breedingAgeStatus(h).detail}</span></div>{breedingAgeStatus(h).eligible&&!canBreed(h)&&<p>Breeding cooldown is currently active.</p>}{h.sex==="Stallion"&&<><p>Stud fee: {h.stud_fee} LED · {offspring.length} recorded offspring</p>{canBreed(h)&&<><select value={mare} onChange={e=>setMare(e.target.value)}><option value="">Select an eligible mare…</option>{mares.map(m=><option key={m.id} value={m.id}>{m.name} · Age {Math.floor(age(m))} · {m.breed}</option>)}</select><button className="primary" disabled={!mare} onClick={()=>breed(mare)}>Confirm Breeding · {h.stud_fee} LED</button></>}</>}{h.sex==="Mare"&&<p>{h.last_bred_at?`Last bred ${new Date(h.last_bred_at).toLocaleDateString()}. ${canBreed(h)?"Cooldown complete.":breedingAgeStatus(h).eligible?"Resting during breeding cooldown.":"Historical breeding record retained."}`:"No breeding history yet."}</p>}<h3>Offspring</h3>{offspring.map(x=><button className="historyrow" key={x.id} onClick={()=>openHorse(x)}>{x.name} · {x.breed}</button>)}</section>}</>}
