/* eslint-disable @next/next/no-img-element */
"use client";
import{useCallback,useEffect,useState}from"react";
import{createClient}from"@/lib/supabase/client";
import{GAME}from"@/lib/game/config";
const supabase=createClient();
type Template={id:string;breed:string;body_archetype:string;sex:"Mare"|"Stallion"|null;pose_label:string;image_url:string;status:"pending"|"approved"|"rejected";active:boolean;review_notes:string;created_at:string};
const blank={breed:GAME.foundationBreeds[0] as string,body_archetype:"Breed-standard balanced adult",sex:"",pose_label:"Balanced standing",image_url:""};
export function HorseImageTemplates({notify,changed}:{notify:(s:string)=>void;changed:()=>void}){const[templates,setTemplates]=useState<Template[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[previewColor,setPreviewColor]=useState("Bay");
 const load=useCallback(async()=>{const{data,error}=await supabase.rpc("admin_list_horse_image_templates");if(error)notify(error.message);else setTemplates((data??[])as Template[])},[notify]);useEffect(()=>{void load()},[load]);
 const upload=async(file:File)=>{if(!file.type.startsWith("image/")||file.size>5*1024*1024){notify("Template must be a JPG, PNG, WebP, or GIF under 5 MB.");return}setBusy(true);const{data:user}=await supabase.auth.getUser(),path=`${user.user!.id}/templates/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`,result=await supabase.storage.from("legacy-equine-media").upload(path,file,{upsert:false});if(result.error)notify(result.error.message);else{const publicUrl=supabase.storage.from("legacy-equine-media").getPublicUrl(path).data.publicUrl;setForm(x=>({...x,image_url:publicUrl}));notify("Template uploaded. Save it for review.")}setBusy(false)};
 const save=async()=>{setBusy(true);const{error}=await supabase.rpc("admin_save_horse_image_template",{target_template:editing,template_breed:form.breed,template_archetype:form.body_archetype,template_sex:form.sex,template_pose:form.pose_label,template_url:form.image_url});notify(error?.message??"Template saved as pending human review.");if(!error){setEditing(null);setForm(blank);await load()}setBusy(false)};
 const review=async(id:string,status:"approved"|"rejected",active:boolean)=>{const notes=prompt(`${status==="approved"?"Approval":"Rejection"} notes`)??"";const{error}=await supabase.rpc("admin_review_horse_image_template",{target_template:id,new_status:status,make_active:active,notes});notify(error?.message??`Template ${status}.`);if(!error)await load()};
 const batch=async()=>{if(!confirm("Replace all Foundation system artwork with approved templates or the official safe fallback? Horse data will not change."))return;setBusy(true);const{data,error}=await supabase.rpc("admin_batch_regenerate_foundation_images");notify(error?.message??`${data} Foundation horses queued. Unapproved output cannot be published.`);if(!error){const{data:session}=await supabase.auth.getSession();await fetch("/api/store-horse-images/generate",{method:"POST",headers:{Authorization:`Bearer ${session.session?.access_token??""}`}});changed()}setBusy(false)};
 return <section className="panel settingsform"><p className="eyebrow">QUALITY-GATED ARTWORK</p><h2>Horse Image Templates</h2><p className="panelsub">Only active, human-approved templates may guide production artwork. Correct anatomy outranks uniqueness; missing or rejected variations use the official Foundation fallback.</p><div className="adminformgrid"><label>Breed / body archetype<select value={form.breed} onChange={e=>setForm({...form,breed:e.target.value})}>{GAME.foundationBreeds.map(x=><option key={x}>{x}</option>)}<option value="*">Generic fallback</option></select></label><label>Body archetype<input value={form.body_archetype} onChange={e=>setForm({...form,body_archetype:e.target.value})}/></label><label>Sex template<select value={form.sex} onChange={e=>setForm({...form,sex:e.target.value})}><option value="">Any</option><option>Mare</option><option>Stallion</option></select></label><label>Pose / head carriage<input value={form.pose_label} onChange={e=>setForm({...form,pose_label:e.target.value})}/></label><label>Template image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" disabled={busy} onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0])}/></label><label>Phenotype preview target<select value={previewColor} onChange={e=>setPreviewColor(e.target.value)}>{["Bay","Chestnut","Black","Gray","Palomino","Buckskin","Bay Splashed White","Bay Tobiano"].map(x=><option key={x}>{x}</option>)}</select></label></div>{form.image_url&&<div className="templatepreview"><img src={form.image_url} alt="Template preview"/><span>{form.breed} · {form.sex||"Any sex"} · controlled variation target: {previewColor}</span></div>}<button className="primary" disabled={busy||!form.image_url||!form.body_archetype.trim()} onClick={save}>{editing?"Upload Replacement for Review":"Save Pending Template"}</button>{editing&&<button onClick={()=>{setEditing(null);setForm(blank)}}>Cancel Replacement</button>}<div className="templategrid">{templates.map(t=><article key={t.id}><img src={t.image_url} alt={`${t.breed} ${t.body_archetype}`}/><p className="eyebrow">{t.status}{t.active?" · ACTIVE":""}</p><h3>{t.breed==="*"?"Generic Foundation":t.breed}</h3><p>{t.body_archetype} · {t.sex??"Any sex"}<br/>{t.pose_label}</p>{t.review_notes&&<small>{t.review_notes}</small>}<div className="buttonrow"><button onClick={()=>{setEditing(t.id);setForm({breed:t.breed,body_archetype:t.body_archetype,sex:t.sex??"",pose_label:t.pose_label,image_url:t.image_url})}}>Replace</button>{t.status!=="approved"&&<button onClick={()=>void review(t.id,"approved",true)}>Approve & Activate</button>}{t.status==="approved"&&<button onClick={()=>void review(t.id,"approved",!t.active)}>{t.active?"Deactivate":"Activate"}</button>}<button onClick={()=>void review(t.id,"rejected",false)}>Reject</button></div></article>)}</div><button className="primary" disabled={busy} onClick={batch}>Regenerate Foundation Horse Images</button></section>}
