/* eslint-disable @next/next/no-img-element */
"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {GAME} from "@/lib/game/config";
const supabase=createClient();
const sections=["Identity","Age & Sex","Stats","Genetics","Appearance","Breeding","Pedigree","Ownership","Career","Traits","Advanced"] as const;
type Section=typeof sections[number];
type EditorData={horse:Record<string,any>;calculated_age:number;owner:{id:string;name:string;account_number:number}|null;stables:{id:string;name:string;account_number:number}[];templates:{asset_key:string;breed:string|null;sex:string|null;image_url:string}[];traits:{id:string;key:string;name:string;description:string;color:string;active:boolean;assigned:boolean}[];audit:{id:string;action:string;changed_fields:string[];reason:string;actor_account:number;created_at:string}[]};
const loci=["Extension","Agouti","Cream","Dun","Gray","Roan","Silver","Champagne","Pearl","Tobiano","Splash","Frame","Sabino"];
const highImpact=new Set(["sex","breed","genetics","sire_id","dam_id","owner_id","restore_from_sanctuary","career_points"]);
const shown=(v:unknown)=>typeof v==="object"?JSON.stringify(v):String(v??"");
export function HorseEditor({horseId,onSaved}:{horseId:string;onSaved:()=>void}){
 const[data,setData]=useState<EditorData|null>(null),[open,setOpen]=useState(false),[section,setSection]=useState<Section>("Identity"),[changes,setChanges]=useState<Record<string,any>>({}),[reason,setReason]=useState(""),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{const{data,error}=await supabase.rpc("get_horse_editor_data",{p_horse_id:horseId});if(error)setNotice(error.message);else setData(data as EditorData)},[horseId]);
 useEffect(()=>{if(open)void load()},[open,load]);
 const h=data?.horse,put=(key:string,value:any)=>setChanges(x=>({...x,[key]:value})),material=Object.keys(changes),needsConfirm=material.some(x=>highImpact.has(x));
 const statValues=useMemo(()=>Object.fromEntries(GAME.stats.map(stat=>{const birth=Number(h?.birth_stats?.[stat]??0),developed=Number(h?.stats?.[stat]??birth);return[stat,{birth,development:developed-birth}]})),[h]);
 const currentStats={...statValues,...(changes.stat_values??{})};
 const genetics={...(h?.genetics??{}),...(changes.genetics??{})};
 const save=async()=>{setBusy(true);const{age_years,...editorChanges}=changes;if(age_years!==undefined){const{error}=await supabase.rpc("owner_set_horse_age",{p_horse:horseId,p_age_years:Number(age_years),p_reason:reason||"Owner horse editor age correction"});if(error){setBusy(false);setNotice(error.message);return}}if(Object.keys(editorChanges).length){const{error}=await supabase.rpc("owner_edit_horse",{p_horse_id:horseId,p_changes:editorChanges,p_reason:reason,p_confirm_high_impact:needsConfirm});if(error){setBusy(false);setNotice(error.message);return}}setBusy(false);setNotice("Horse changes saved and added to the immutable audit log.");setChanges({});setReason("");setReview(false);await load();onSaved()};
 if(!open)return <button className="ownerhorseedit" onClick={()=>setOpen(true)}>Edit Horse</button>;
 if(!data||!h)return <section className="horseeditormodal"><button onClick={()=>setOpen(false)}>Close</button><p>{notice||"Loading Owner Horse Editor…"}</p></section>;
 const field=(label:string,key:string,type="text")=><label>{label}<input type={type} value={changes[key]??h[key]??""} onChange={e=>put(key,type==="number"?Number(e.target.value):e.target.value)}/></label>;
 return <div className="horseeditorbackdrop" role="dialog" aria-modal="true" aria-label="Owner Horse Editor"><section className="horseeditormodal"><header><div><p className="eyebrow">OWNER / AUTHORIZED HORSE EDITOR</p><h2>Edit {h.name}</h2><small>Horse ID {h.id}</small></div><button aria-label="Close Horse Editor" onClick={()=>setOpen(false)}>×</button></header>
  <nav>{sections.map(x=><button key={x} className={section===x?"active":""} onClick={()=>setSection(x)}>{x}</button>)}</nav>
  {section==="Identity"&&<div className="horseeditorgrid">{field("Horse Name","name")}{field("Breed","breed")}<label>Origin<select value={changes.origin??h.origin} onChange={e=>put("origin",e.target.value)}><option>Foundation</option><option>Bred</option><option>Admin Custom</option></select></label>{field("Generation","generation","number")}<label className="wide">Biography<textarea value={changes.biography??h.biography??""} onChange={e=>put("biography",e.target.value)}/></label></div>}
  {section==="Age & Sex"&&<div className="horseeditorgrid"><label>Sex<select value={changes.sex??h.sex} onChange={e=>put("sex",e.target.value)}><option>Mare</option><option>Stallion</option><option>Gelding</option></select></label>{field("Date of Birth","birth_date","datetime-local")}<label>Set Horse Age (game years)<input type="number" min="0" step="0.1" value={changes.age_years??Number(data.calculated_age).toFixed(1)} onChange={e=>put("age_years",Number(e.target.value))}/></label><div className="editorreadout"><b>Calculated age</b><span>{Number(changes.age_years??data.calculated_age).toFixed(2)} years</span><small>Future breeding and age eligibility recalculate from the saved timestamp.</small></div></div>}
  {section==="Stats"&&<div className="editorstats">{GAME.stats.map(stat=>{const s=currentStats[stat],tack=Number(h.tack_bonuses?.[stat]??0);return <article key={stat}><h3>{stat}</h3><label>Birth<input type="number" value={s.birth} onChange={e=>put("stat_values",{...currentStats,[stat]:{...s,birth:Number(e.target.value)}})}/></label><label>Permanent Development<input type="number" value={s.development} onChange={e=>put("stat_values",{...currentStats,[stat]:{...s,development:Number(e.target.value)}})}/></label><b>Developed {Number(s.birth)+Number(s.development)}</b><small>Tack {tack>=0?"+":""}{tack} · temporary services remain separate</small></article>})}</div>}
  {section==="Genetics"&&<><p className="editorwarning">Genotype is authoritative. Saving genetics recalculates phenotype automatically.</p><div className="horseeditorgrid">{loci.map(locus=><label key={locus}>{locus}<input value={(genetics[locus]??genetics[locus.toLowerCase()]??[]).join(" / ")} placeholder="allele 1 / allele 2" onChange={e=>put("genetics",{...genetics,[locus]:e.target.value.split("/").map(x=>x.trim()).filter(Boolean).slice(0,2)})}/></label>)}</div><details><summary>Calculated phenotype</summary><pre>{JSON.stringify(h.visual_phenotype??{},null,2)}</pre></details></>}
  {section==="Appearance"&&<div className="horseeditorgrid">{field("Displayed color (override only)","color")}<label>Body Template<select value={changes.visual_template_id??h.visual_template_id??""} onChange={e=>put("visual_template_id",e.target.value)}><option value="">Foundation fallback</option>{data.templates.map(t=><option key={t.asset_key} value={t.asset_key}>{t.asset_key} · {t.breed} · {t.sex??"Any sex"}</option>)}</select></label>{field("Custom artwork URL","custom_artwork_url")}<label>Face marking<input value={(changes.markings??h.markings)?.face??"none"} onChange={e=>put("markings",{...(changes.markings??h.markings),face:e.target.value})}/></label>{["left_front","right_front","left_hind","right_hind"].map(k=><label key={k}>{k.replaceAll("_"," ")} marking<input value={(changes.markings??h.markings)?.[k]??"none"} onChange={e=>put("markings",{...(changes.markings??h.markings),[k]:e.target.value})}/></label>)}<label>Mane/tail treatment<input value={(changes.markings??h.markings)?.mane_tail??h.visual_phenotype?.mane_tail??""} onChange={e=>put("markings",{...(changes.markings??h.markings),mane_tail:e.target.value})}/></label><label className="wide">Explicit Visual/Phenotype Override<textarea placeholder='{"coat":"exceptional appearance"}' value={changes.phenotype_override===undefined?JSON.stringify(h.phenotype_override??{},null,2):JSON.stringify(changes.phenotype_override,null,2)} onChange={e=>{try{put("phenotype_override",JSON.parse(e.target.value))}catch{setNotice("Override must be valid JSON")}}}/></label></div>}
  {section==="Breeding"&&<div className="horseeditorgrid"><label><input type="checkbox" checked={changes.breeding_available??h.breeding_available??true} onChange={e=>put("breeding_available",e.target.checked)}/> Administratively available for breeding</label>{field("Stud fee (LED)","stud_fee","number")}{field("Mare cooldown timestamp","last_bred_at","datetime-local")}<label><input type="checkbox" checked={changes.retired??h.retired??false} onChange={e=>put("retired",e.target.checked)}/> Retired from future breeding/gameplay</label><div className="editorreadout wide">Ordinary players remain subject to sex, authoritative age 3–25, cooldown, retirement, and ownership rules. Historical progeny are preserved.</div></div>}
  {section==="Pedigree"&&<div className="horseeditorgrid"><label>Sire ID<input value={changes.sire_id??h.sire_id??""} onChange={e=>put("sire_id",e.target.value)}/></label><label>Dam ID<input value={changes.dam_id??h.dam_id??""} onChange={e=>put("dam_id",e.target.value)}/></label><p className="editorwarning wide">Parentage changes require confirmation and are rejected if they create self-parentage or a pedigree cycle. Existing progeny records are not deleted.</p></div>}
  {section==="Ownership"&&<div className="horseeditorgrid"><label>Stable / Owner<select value={changes.owner_id??h.owner_id??""} onChange={e=>put("owner_id",e.target.value)}><option value="">No active owner</option>{data.stables.map(s=><option key={s.id} value={s.id}>#{s.account_number} · {s.name}</option>)}</select></label>{h.sanctuary_retired_at&&<label><input type="checkbox" checked={Boolean(changes.restore_from_sanctuary)} onChange={e=>put("restore_from_sanctuary",e.target.checked)}/> Restore from Sanctuary (Owner #1 emergency correction)</label>}<p className="editorwarning wide">Administrative transfers create ownership history and never fabricate a sale or LED transaction.</p></div>}
  {section==="Career"&&<div className="horseeditorgrid">{field("Career Points correction","career_points","number")}<p className="editorwarning wide">Completed show results remain authoritative. Result-level corrections and duplicate removal require the separate Owner correction action and immutable audit reason.</p></div>}
  {section==="Traits"&&<div className="traiteditor">{data.traits.map(t=><label key={t.id}><input type="checkbox" checked={(changes.trait_ids??data.traits.filter(x=>x.assigned).map(x=>x.id)).includes(t.id)} onChange={e=>{const current:string[]=changes.trait_ids??data.traits.filter(x=>x.assigned).map(x=>x.id);put("trait_ids",e.target.checked?[...current,t.id]:current.filter(x=>x!==t.id))}}/><span style={{borderColor:t.color}}>{t.name}<small>{t.description||"Data-driven special trait"}</small></span></label>)}</div>}
  {section==="Advanced"&&<><div className="horseeditorgrid">{field("Height (hands notation)","mature_height_hands","number")}<label className="wide">Current genotype<pre>{JSON.stringify(h.genetics??{},null,2)}</pre></label><label className="wide">Current phenotype<pre>{JSON.stringify(h.visual_phenotype??{},null,2)}</pre></label></div><h3>Recent immutable edit history</h3>{data.audit.map(a=><div className="historyrow" key={a.id}><span><b>{a.action}</b> · {a.changed_fields.join(", ")}<small>{a.reason}</small></span><time>Owner/Admin #{a.actor_account} · {new Date(a.created_at).toLocaleString()}</time></div>)}</>}
  {notice&&<p className="adminerror">{notice}</p>}
  <footer><button onClick={()=>{setChanges({});setReview(false);setOpen(false)}}>Cancel</button><button className="primary" disabled={!material.length||busy} onClick={()=>setReview(true)}>Review Changes</button></footer>
  {review&&<div className="editreview"><h3>Review material changes</h3>{material.map(key=><p key={key}><b>{key.replaceAll("_"," ")}</b><span>{shown(h[key])} → {shown(changes[key])}</span></p>)}{needsConfirm&&<p className="editorwarning">This changes future eligibility, identity, ownership, genetics, pedigree, Sanctuary state, or career data. Historical records remain unchanged unless using the separate career correction tool.</p>}<label>Audit reason {needsConfirm&&"(required)"}<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><div><button onClick={()=>setReview(false)}>Back</button><button className="primary" disabled={busy||(needsConfirm&&reason.trim().length<3)} onClick={()=>void save()}>Confirm & Save Changes</button></div></div>}
 </section></div>
}
