/* eslint-disable @next/next/no-img-element, react-hooks/static-components */
"use client";
import { useCallback,useEffect,useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createClient } from "@/lib/supabase/client";
import { GAME } from "@/lib/game/config";

type Horse={id:string;name:string;breed:string;sex:"Mare"|"Stallion";color:string;origin:"Foundation"|"Bred"|"Admin Custom";birth_date:string;sire_id:string|null;dam_id:string|null;generation:number;stats:Record<string,number>;tack_bonuses:Record<string,number>;biography:string;image_url:string;stud_fee:number;last_bred_at:string|null;last_trained_at:string|null;retired:boolean};
type Stable={account_number:number;name:string;balance:number;foundation_purchases:number;created_at:string};
type Ledger={id:string;amount:number;reason:string;created_at:string};
type StoreHorse={inventory_id:string;horse_id:string;name:string;breed:string;sex:"Mare"|"Stallion";color:string;birth_date:string;stats:Record<string,number>;image_url:string;price:number;generated_at:string;rotation_key:string};
const supabase=createClient(); const money=(n:number)=>new Intl.NumberFormat("en-US").format(n); const overall=(h:Horse)=>GAME.stats.reduce((n,k)=>n+(h.stats[k]??0)+(h.tack_bonuses[k]??0),0); const age=(h:Horse)=>Math.max(0,(Date.now()-new Date(h.birth_date).getTime())/86400000*GAME.age.gameDaysPerRealDay/365.25); const canTrain=(h:Horse)=>!h.last_trained_at||Date.now()-new Date(h.last_trained_at).getTime()>=GAME.training.cooldownHours*3600000; const canBreed=(h:Horse)=>!h.retired&&age(h)>=3&&age(h)<30&&(h.sex==="Stallion"||!h.last_bred_at||Date.now()-new Date(h.last_bred_at).getTime()>=GAME.mareCooldownDays*86400000);

export default function Home(){const [user,setUser]=useState<User|null>(null),[stable,setStable]=useState<Stable|null>(null),[horses,setHorses]=useState<Horse[]>([]),[ledger,setLedger]=useState<Ledger[]>([]),[inventory,setInventory]=useState<StoreHorse[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState("Welcome to Legacy Equine."),[view,setView]=useState<"stable"|"store"|"storehorse"|"horse"|"pedigree"|"progeny"|"ledger">("stable"),[selected,setSelected]=useState<string|null>(null),[storeSelected,setStoreSelected]=useState<string|null>(null);
const load=useCallback(async(u:User|null)=>{setUser(u);if(!u){setStable(null);setHorses([]);setLoading(false);return}const [{data:s,error:stableError},{data:h},{data:l}]=await Promise.all([supabase.from("stables").select("account_number,name,balance,foundation_purchases,created_at").eq("id",u.id).maybeSingle(),supabase.from("horses").select("*").eq("owner_id",u.id).order("created_at"),supabase.from("currency_ledger").select("id,amount,reason,created_at").order("created_at",{ascending:false})]);if(stableError)setNotice(stableError.message);setStable(s);setHorses((h??[]) as Horse[]);setLedger((l??[]) as Ledger[]);setLoading(false)},[]);
useEffect(()=>{void supabase.auth.getUser().then(({data})=>load(data.user));const{data}=supabase.auth.onAuthStateChange((_e,s)=>{setTimeout(()=>{void load(s?.user??null)},0)});return()=>data.subscription.unsubscribe()},[load]);
const action=async(fn:()=>Promise<{error:Error|null}>,success:string)=>{setLoading(true);const{error}=await fn();setNotice(error?.message??success);await load(user);setLoading(false)};const horse=horses.find(h=>h.id===selected)||null;const open=(h:Horse)=>{setSelected(h.id);setView("horse")};
const loadStore=useCallback(async()=>{const{data,error}=await supabase.rpc("get_store_inventory");if(error)setNotice(error.message);else setInventory((data??[]) as StoreHorse[])},[]);const openStore=async()=>{setView("store");await loadStore()};useEffect(()=>{if(!user||view!=="store")return;const timer=setTimeout(()=>{void loadStore()},0);return()=>clearTimeout(timer)},[user,view,loadStore]);const storeHorse=inventory.find(h=>h.inventory_id===storeSelected)||null;const purchase=async(id:string)=>{await action(async()=>{const{error}=await supabase.rpc("purchase_store_horse",{target_inventory:id});return{error}},"Wonderful choice! Your new Foundation horse is waiting at your stable.");await loadStore();setView("store")};
if(loading&&!user)return <div className="loading">LEGACY EQUINE</div>;if(!user)return <Auth/>;if(!stable)return <CreateStable loading={loading} message={notice} onCreate={async name=>action(async()=>{const{error}=await supabase.rpc("initialize_stable",{stable_name:name});return{error}},"Your stable is ready.")}/>;
return <div className="shell"><aside className="game-sidebar"><button className="brand" onClick={()=>setView("stable")}><span className="mark">LE</span><span>Legacy Equine<small>Breed Your Legacy.</small></span></button><nav className="game-nav" aria-label="Game areas"><button className={view==="stable"?"active":""} onClick={()=>setView("stable")}><span>♞</span>Stable Home</button><button className={view==="store"||view==="storehorse"?"active":""} onClick={openStore}><span>✦</span>LE Store</button><button disabled><span>↗</span>Training <i>Soon</i></button><button disabled><span>◇</span>Shows <i>Soon</i></button><button disabled><span>⌂</span>Marketplace <i>Soon</i></button><button disabled><span>◎</span>Community <i>Soon</i></button></nav><div className="sidebar-note">ALPHA 0.1</div></aside><div className="game-column"><header className="topbar"><button className="account-home" onClick={()=>setView("stable")}><small>LE ACCOUNT #{stable.account_number}</small><b>{stable.name}</b></button><nav className="account-nav" aria-label="Account links"><button className={view==="stable"?"active":""} onClick={()=>setView("stable")}>My Profile</button><button className={view==="ledger"?"active":""} onClick={()=>setView("ledger")}>Ledger</button><button disabled>Settings <i>Soon</i></button></nav><div className="balance"><span className="coin">LE</span><b>{money(stable.balance)}</b><span>LE Dollars</span></div><button className="signout" onClick={()=>supabase.auth.signOut()}>Sign out</button></header><main><div className="notice">✦ {notice}</div>
{view==="stable"&&<><section className="hero"><div><p className="eyebrow">LE ACCOUNT #{stable.account_number} · ESTABLISHED {new Date(stable.created_at).getFullYear()}</p><h1>{stable.name}</h1><p>Your bloodline begins here. Develop promising horses, make thoughtful pairings, and shape a legacy that lasts.</p><button className="primary" onClick={()=>setView("store")}>Visit the LE Store →</button></div><div className="crest"><span>LE</span><small>ACCOUNT #{stable.account_number}</small></div></section><section className="stats"><div><small>HORSES OWNED</small><b>{horses.length}</b></div><div><small>FOUNDATION PURCHASES</small><b>{stable.foundation_purchases} <em>/ {GAME.foundationLimit}</em></b></div><div><small>AVERAGE POINTS</small><b>{horses.length?Math.round(horses.reduce((n,h)=>n+overall(h),0)/horses.length):0}</b></div><div><small>GENERATIONS BRED</small><b>{Math.max(0,...horses.map(h=>h.generation))}</b></div></section><Title title="Your Horses" sub="Your persistent Legacy Equine bloodline"/>{horses.length?<div className="horsegrid">{horses.map(h=><Card key={h.id} h={h} open={open}/>)}</div>:<Empty go={()=>setView("store")}/>}</>}
{view==="store"&&<><Title title="The LE Store" sub="Browse the shared Foundation herd and find the horse that speaks to you"/><div className="storebar"><span>✦ {inventory.length} Foundation horses available</span><span>{inventory[0]?`Current herd arrived ${new Date(inventory[0].rotation_key).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}`:"Preparing the herd…"}</span><button onClick={loadStore}>Refresh store</button></div><div className="inventorygrid">{inventory.map(h=><StoreCard key={h.inventory_id} h={h} view={()=>{setStoreSelected(h.inventory_id);setView("storehorse")}} purchase={()=>purchase(h.inventory_id)} disabled={loading||stable.foundation_purchases>=3||stable.balance<h.price}/>)}</div><p className="storelimit">Your stable may purchase {3-stable.foundation_purchases} more introductory Foundation {3-stable.foundation_purchases===1?"horse":"horses"}. The shared store inventory rotates independently.</p></>}
{storeHorse&&view==="storehorse"&&<StorePreview h={storeHorse} back={()=>setView("store")} purchase={()=>purchase(storeHorse.inventory_id)} disabled={loading||stable.foundation_purchases>=3||stable.balance<storeHorse.price}/>}
{view==="ledger"&&<><Title title="Transaction Ledger" sub="A permanent record of every LE Dollar"/><section className="panel">{ledger.map(l=><div className="ledger" key={l.id}><span>{l.reason}<small>{new Date(l.created_at).toLocaleString()}</small></span><b className={l.amount<0?"debit":"credit"}>{l.amount>0?"+":""}${money(l.amount)}</b></div>)}</section></>}
{horse&&view==="horse"&&<HorsePage h={horse} horses={horses} openView={setView} save={(name,bio,img)=>action(async()=>{const{error}=await supabase.rpc("update_horse_profile",{target_horse:horse.id,new_name:name,new_biography:bio,new_image_url:img});return{error}},"Horse profile saved.")} train={stat=>action(async()=>{const{error}=await supabase.rpc("train_horse",{target_horse:horse.id,stat_name:stat});return{error}},`${horse.name} gained +1 ${stat}.`)} breed={mare=>action(async()=>{const{error}=await supabase.rpc("breed_horses",{stallion_id:horse.id,mare_id:mare});return{error}},"Your foal was born.")}/>} {horse&&view==="pedigree"&&<Pedigree h={horse} horses={horses} open={open}/>} {horse&&view==="progeny"&&<><Title title={`${horse.name} · Progeny`} sub="Permanent offspring record"/><div className="horsegrid">{horses.filter(x=>x.sire_id===horse.id||x.dam_id===horse.id).map(x=><Card key={x.id} h={x} open={open}/>)}</div></>}
</main><footer>LEGACY EQUINE · ALPHA 0.1 <span>Original browser horse simulation</span></footer></div></div>}

function Auth(){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[mode,setMode]=useState<"login"|"signup">("signup"),[message,setMessage]=useState("");const submit=async()=>{const{error}=mode==="signup"?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});setMessage(error?.message??(mode==="signup"?"Account created. Check your email if confirmation is required.":"Signed in."))};return <div className="auth"><div className="authbrand"><span className="mark">LE</span><h1>Legacy Equine</h1><p>Breed Your Legacy.</p></div><div className="authcard"><p className="eyebrow">{mode==="signup"?"BEGIN YOUR LEGACY":"WELCOME BACK"}</p><h2>{mode==="signup"?"Create your account":"Sign in"}</h2><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" onClick={submit}>{mode==="signup"?"Create Account":"Sign In"}</button><p>{message}</p><button className="textbtn" onClick={()=>setMode(mode==="signup"?"login":"signup")}>{mode==="signup"?"Already have an account? Sign in":"New here? Create an account"}</button></div></div>}
function CreateStable({onCreate,loading,message}:{onCreate:(n:string)=>Promise<void>;loading:boolean;message:string}){const[n,setN]=useState("");const submit=async(e:React.FormEvent)=>{e.preventDefault();if(n.trim().length>=2&&!loading)await onCreate(n)};return <div className="auth"><div className="authbrand"><span className="mark">LE</span><h1>Name Your Stable</h1><p>Choose the name players will know you by.</p></div><form className="authcard" onSubmit={submit}><p className="eyebrow">ESTABLISH YOUR LEGACY</p><h2>Create a stable</h2><label>Stable name<input value={n} maxLength={60} autoFocus disabled={loading} onChange={e=>setN(e.target.value)}/></label><button type="submit" className="primary" disabled={loading||n.trim().length<2}>{loading?"Opening your stable…":"Create Stable"}</button>{message!=="Welcome to Legacy Equine."&&<p className="formmessage" role="alert">{message}</p>}</form></div>}
function Title({title,sub}:{title:string;sub:string}){return <div className="title"><p className="eyebrow">LEGACY EQUINE</p><h2>{title}</h2><p>{sub}</p></div>}function Empty({go}:{go:()=>void}){return <div className="empty"><div>♞</div><h3>Your stalls are waiting</h3><p>Visit the LE Store to choose your first foundation horse.</p><button className="primary" onClick={go}>Find a Foundation Horse</button></div>}
function Card({h,open}:{h:Horse;open:(h:Horse)=>void}){return <button className="horsecard" onClick={()=>open(h)}><div className="horsepic">{h.image_url?<img src={h.image_url} alt={h.name}/>:"♞"}<span>{h.origin}</span></div><div><p className="eyebrow">{h.breed} · {h.sex}</p><h3>{h.name}</h3><p>{h.color} · {age(h).toFixed(1)} years</p><div className="cardstats"><span>⚡ {h.stats.Speed} Speed</span><span>✦ {h.stats.Agility} Agility</span></div><div className="cardfoot"><b>{overall(h)} <small>PTS</small></b><em>View horse →</em></div></div></button>}
function storeAge(h:StoreHorse){return Math.max(0,(Date.now()-new Date(h.birth_date).getTime())/86400000*GAME.age.gameDaysPerRealDay/365.25)}
function storeOverall(h:StoreHorse){return GAME.stats.reduce((sum,key)=>sum+(h.stats[key]??0),0)}
function StoreCard({h,view,purchase,disabled}:{h:StoreHorse;view:()=>void;purchase:()=>void;disabled:boolean}){return <article className="storecard"><button className="storeimage" onClick={view}><img src={h.image_url||"/foundation-horse.png"} alt={h.name}/><span>{h.sex}</span></button><div className="storecardbody"><p className="eyebrow">{h.breed}</p><h3>{h.name}</h3><p>{h.color} · {storeAge(h).toFixed(1)} years</p><div className="storestats">{GAME.stats.slice(0,4).map(s=><span key={s}><small>{s}</small><b>{h.stats[s]}</b></span>)}</div><div className="storeactions"><strong>{money(h.price)} <small>LE Dollars</small></strong><button onClick={view}>View Horse</button><button className="primary" disabled={disabled} onClick={purchase}>Purchase</button></div></div></article>}
function StorePreview({h,back,purchase,disabled}:{h:StoreHorse;back:()=>void;purchase:()=>void;disabled:boolean}){return <><button className="back" onClick={back}>← Back to all store horses</button><section className="storepreview"><div className="previewart"><img src={h.image_url||"/foundation-horse.png"} alt={h.name}/><span>FOUNDATION HORSE</span></div><div className="previewinfo"><p className="eyebrow">MEET YOUR NEXT LEGACY</p><h1>{h.name}</h1><p className="meta">{h.breed} <b>•</b> {h.sex} <b>•</b> {storeAge(h).toFixed(1)} years <b>•</b> {h.color}</p><div className="previewtotal"><span>Overall foundation points</span><b>{storeOverall(h)}</b></div><div className="previewstats">{GAME.stats.map(s=><div key={s}><span>{s}</span><i><em style={{width:`${Math.min(100,h.stats[s]/20*100)}%`}}/></i><b>{h.stats[s]}</b></div>)}</div><div className="previewbuy"><strong>{money(h.price)} <small>LE Dollars</small></strong><button className="primary" disabled={disabled} onClick={purchase}>Bring {h.name} Home</button></div></div></section></>}
function HorsePage({h,horses,openView,save,train,breed}:{h:Horse;horses:Horse[];openView:(v:"pedigree"|"progeny")=>void;save:(n:string,b:string,i:string)=>void;train:(s:string)=>void;breed:(m:string)=>void}){const[n,setN]=useState(h.name),[b,setB]=useState(h.biography),[i,setI]=useState(h.image_url),[mare,setMare]=useState("");const mares=horses.filter(x=>x.sex==="Mare"&&canBreed(x));return <><section className="profile"><div className="portrait">{i?<img src={i} alt={n}/>:<span>♞</span>}<label>Custom artwork URL<input value={i} onChange={e=>setI(e.target.value)}/></label></div><div><p className="eyebrow">{h.origin.toUpperCase()} · GENERATION {h.generation}</p><input className="nameedit" value={n} onChange={e=>setN(e.target.value)}/><p className="meta">{h.breed} <b>•</b> {h.sex} <b>•</b> {age(h).toFixed(1)} years <b>•</b> {h.color}</p><p className="ownerline">Owned by your stable</p><textarea value={b} placeholder="Write this horse's story…" onChange={e=>setB(e.target.value)}/><button className="primary" onClick={()=>save(n,b,i)}>Save Profile</button></div><div className="points"><b>{overall(h)}</b><span>Overall Points</span><small>{canBreed(h)?"● Breeding eligible":"○ Not eligible"}</small></div></section><div className="profiletabs"><button className="active">Overview</button><button>Stats</button><button>Training</button><button disabled>Shows · Soon</button><button onClick={()=>openView("pedigree")}>Pedigree</button><button onClick={()=>openView("progeny")}>Progeny</button><button>Breeding</button></div><section className="panel"><h2>Stats & Training</h2><p className="panelsub">Build your horse one thoughtful training session at a time.</p><div className="statlist">{GAME.stats.map(s=><div key={s}><span>{s}<i style={{width:`${Math.min(100,(h.stats[s]/30)*100)}%`}}/></span><strong>{h.stats[s]}</strong><em>+{h.tack_bonuses[s]??0} tack</em><b>{h.stats[s]+(h.tack_bonuses[s]??0)}</b><button disabled={!canTrain(h)} onClick={()=>train(s)}>Train +1</button></div>)}</div></section>{h.sex==="Stallion"&&<section className="panel breed"><p className="eyebrow">BREEDING BARN</p><h2>Breed {h.name}</h2><p>Choose an eligible mare and welcome a new foal to your legacy instantly.</p><select value={mare} onChange={e=>setMare(e.target.value)}><option value="">Select an eligible mare…</option>{mares.map(m=><option key={m.id} value={m.id}>{m.name} · {m.breed}</option>)}</select><button className="primary" disabled={!mare||!canBreed(h)} onClick={()=>breed(mare)}>Confirm Breeding · ${h.stud_fee} LE</button></section>}{h.sex==="Mare"&&h.last_bred_at&&<section className="panel cooldown"><h2>🌙 Resting after breeding</h2><p>Ready to breed again on {new Date(new Date(h.last_bred_at).getTime()+GAME.mareCooldownDays*86400000).toLocaleDateString()}.</p></section>}</>}
function Pedigree({h,horses,open}:{h:Horse;horses:Horse[];open:(h:Horse)=>void}){const find=(id:string|null)=>horses.find(x=>x.id===id);const sire=find(h.sire_id),dam=find(h.dam_id);const P=({x,label}:{x:Horse|undefined;label:string})=><div className="ped"><small>{label}</small>{x?<button onClick={()=>open(x)}><b>{x.name}</b><span>{x.breed}</span></button>:<i>Unknown foundation line</i>}</div>;return <><Title title={`${h.name} · Pedigree`} sub="Three generations of permanent ancestry"/><div className="pedigree"><div><P x={h} label="SUBJECT"/></div><div><P x={sire} label="SIRE"/><P x={dam} label="DAM"/></div><div><P x={find(sire?.sire_id??null)} label="PATERNAL GRANDSIRE"/><P x={find(sire?.dam_id??null)} label="PATERNAL GRANDDAM"/><P x={find(dam?.sire_id??null)} label="MATERNAL GRANDSIRE"/><P x={find(dam?.dam_id??null)} label="MATERNAL GRANDDAM"/></div></div></>}
