/* eslint-disable react-hooks/set-state-in-effect, react-hooks/static-components, @next/next/no-img-element */
"use client";
import { useEffect, useMemo, useState } from "react";
import { GAME } from "@/lib/game/config";
import { seededRandom } from "@/lib/game/random";
import { canBreed, canTrain, cooldownEnds, createFoal, createFoundationHorse, gameAge, overall } from "@/lib/game/simulation";
import type { Horse, StableState } from "@/lib/game/types";

const STORAGE = "legacy-equine-alpha";
const seedState = (): StableState => ({ stableNumber: 184, stableName: "Willowmere", established: 2026, balance: GAME.startingBalance, purchases: 0, horses: [], ledger: [{id:"welcome",amount:GAME.startingBalance,reason:"Starting funds",at:new Date().toISOString()}], trainingLog: [] });
const money = (n:number) => new Intl.NumberFormat("en-US").format(n);

export default function Home() {
  const [state,setState]=useState<StableState>(seedState); const [ready,setReady]=useState(false); const [view,setView]=useState<"stable"|"store"|"horse"|"pedigree"|"progeny">("stable"); const [selected,setSelected]=useState<string|null>(null); const [notice,setNotice]=useState("Welcome back, Stable #184.");
  useEffect(()=>{ const saved=localStorage.getItem(STORAGE); if(saved) setState(JSON.parse(saved)); setReady(true); },[]);
  useEffect(()=>{ if(ready) localStorage.setItem(STORAGE,JSON.stringify(state)); },[state,ready]);
  const horse=state.horses.find(h=>h.id===selected) ?? null;
  const mares=state.horses.filter(h=>h.sex==="Mare"&&canBreed(h));
  const open=(h:Horse)=>{setSelected(h.id);setView("horse")};
  const buy=()=>{ if(state.purchases>=GAME.foundationLimit)return setNotice("Your introductory purchase limit has been reached."); if(state.balance<GAME.foundationPrice)return setNotice("You need more LE Dollars."); const now=new Date(); const h=createFoundationHorse(seededRandom(Date.now()),now); setState(s=>({...s,balance:s.balance-GAME.foundationPrice,purchases:s.purchases+1,horses:[...s.horses,h],ledger:[...s.ledger,{id:h.id,amount:-GAME.foundationPrice,reason:`Foundation purchase: ${h.name}`,at:now.toISOString()}]})); setNotice(`${h.name} has joined your stable.`); open(h); };
  const updateHorse=(patch:Partial<Horse>)=>setState(s=>({...s,horses:s.horses.map(h=>h.id===selected?{...h,...patch}:h)}));
  const train=(stat:string)=>{ if(!horse||!canTrain(horse)) return setNotice("Training is on cooldown until tomorrow."); const now=new Date().toISOString(); setState(s=>({...s,horses:s.horses.map(h=>h.id===horse.id?{...h,stats:{...h.stats,[stat]:h.stats[stat]+GAME.training.gain},lastTrainedAt:now}:h),trainingLog:[...s.trainingLog,{horseId:horse.id,stat,gain:GAME.training.gain,at:now}]})); setNotice(`${horse.name} gained +${GAME.training.gain} ${stat}.`); };
  const breed=(mareId:string)=>{ if(!horse||horse.sex!=="Stallion")return; const dam=state.horses.find(h=>h.id===mareId); if(!dam||!canBreed(horse)||!canBreed(dam))return setNotice("That pairing is not currently eligible."); if(state.balance<horse.studFee)return setNotice("Insufficient funds for this stud fee."); const now=new Date(); const foal=createFoal(horse,dam,seededRandom(Date.now()+state.horses.length),now); setState(s=>({...s,balance:s.balance-horse.studFee,horses:[...s.horses.map(h=>h.id===dam.id?{...h,lastBredAt:now.toISOString()}:h),foal],ledger:[...s.ledger,{id:foal.id,amount:-horse.studFee,reason:`Stud fee: ${horse.name} × ${dam.name}`,at:now.toISOString()}]})); setSelected(foal.id);setView("horse");setNotice(`${foal.name} was born!`); };
  const avg=useMemo(()=>state.horses.length?Math.round(state.horses.reduce((n,h)=>n+overall(h),0)/state.horses.length):0,[state.horses]);
  if(!ready)return null;
  return <div className="shell"><header><button className="brand" onClick={()=>setView("stable")}><span className="mark">LE</span><span>LEGACY EQUINE<small>Breed Your Legacy.</small></span></button><nav><button onClick={()=>setView("stable")}>My Stable</button><button onClick={()=>setView("store")}>LE Store</button><button disabled>Shows <i>Soon</i></button></nav><div className="balance"><small>AVAILABLE BALANCE</small><b>${money(state.balance)}</b><span>LE DOLLARS</span></div></header><main><div className="notice">✦ {notice}</div>
  {view==="stable"&&<><section className="hero"><div><p className="eyebrow">STABLE #{state.stableNumber} · EST. {state.established}</p><h1>{state.stableName}</h1><p>Your bloodline begins here. Develop promising horses, make thoughtful pairings, and shape a legacy that lasts.</p><button className="primary" onClick={()=>setView("store")}>Visit the LE Store →</button></div><div className="crest"><span>LE</span><small>#{state.stableNumber}</small></div></section><section className="stats"><div><small>HORSES OWNED</small><b>{state.horses.length}</b></div><div><small>FOUNDATION PURCHASES</small><b>{state.purchases} <em>/ {GAME.foundationLimit}</em></b></div><div><small>AVERAGE POINTS</small><b>{avg}</b></div><div><small>GENERATIONS BRED</small><b>{Math.max(0,...state.horses.map(h=>h.generation))}</b></div></section><Title title="Your Horses" sub="The beginning of your Legacy Equine bloodline" />{state.horses.length?<div className="horsegrid">{state.horses.map(h=><HorseCard key={h.id} horse={h} onClick={()=>open(h)}/>)}</div>:<Empty onClick={()=>setView("store")}/>}</>}
  {view==="store"&&<><Title title="The LE Store" sub="Begin your bloodline with an original foundation horse"/><section className="store"><div className="store-art"><img src="/foundation-horse.png" alt="Legacy Equine foundation horse"/><span>FOUNDATION STOCK</span></div><div><p className="eyebrow">INTRODUCTORY OFFER</p><h2>Foundation Horse</h2><p>Each purchase reveals a unique horse with randomized breed, color, sex, and seven foundational stats.</p><ul><li>Stats generally range from 10–15</li><li>Small chance of exceptional outliers</li><li>Permanent pedigree-ready identity</li></ul><div className="price"><b>${money(GAME.foundationPrice)}</b><span>{GAME.currencyName}</span></div><button className="primary" onClick={buy} disabled={state.purchases>=GAME.foundationLimit||state.balance<GAME.foundationPrice}>Purchase Foundation Horse</button><small>{GAME.foundationLimit-state.purchases} of {GAME.foundationLimit} introductory purchases remaining</small></div></section></>}
  {horse&&view==="horse"&&<HorsePage horse={horse} all={state.horses} mares={mares} update={updateHorse} train={train} breed={breed} setView={setView}/>} 
  {horse&&view==="pedigree"&&<Pedigree horse={horse} all={state.horses} open={open}/>} {horse&&view==="progeny"&&<><Title title={`${horse.name} · Progeny`} sub="Permanent offspring record"/><div className="horsegrid">{state.horses.filter(h=>h.sireId===horse.id||h.damId===horse.id).map(h=><HorseCard key={h.id} horse={h} onClick={()=>open(h)}/>)}</div></>}
  </main><footer>LEGACY EQUINE · ALPHA 0.1 <span>Original browser horse simulation</span></footer></div>;
}

function Title({title,sub}:{title:string;sub:string}){return <div className="title"><p className="eyebrow">LEGACY EQUINE</p><h2>{title}</h2><p>{sub}</p></div>}
function Empty({onClick}:{onClick:()=>void}){return <div className="empty"><div>♞</div><h3>Your stalls are waiting</h3><p>Visit the LE Store to choose your first foundation horse.</p><button className="primary" onClick={onClick}>Find a Foundation Horse</button></div>}
function HorseCard({horse,onClick}:{horse:Horse;onClick:()=>void}){const image=horse.imageUrl||(horse.origin==="Foundation"?"/foundation-horse.png":"");return <button className="horsecard" onClick={onClick}><div className="horsepic">{image?<img src={image} alt={horse.name}/>:"♞"}<span>{horse.origin}</span></div><div><p className="eyebrow">{horse.breed} · {horse.sex}</p><h3>{horse.name}</h3><p>{horse.color} · {gameAge(horse).toFixed(1)} years</p><b>{overall(horse)} <small>PTS</small></b></div></button>}
function HorsePage({horse,all,mares,update,train,breed,setView}:{horse:Horse;all:Horse[];mares:Horse[];update:(p:Partial<Horse>)=>void;train:(s:string)=>void;breed:(id:string)=>void;setView:(v:"pedigree"|"progeny")=>void}){const [mare,setMare]=useState("");return <><button className="back" onClick={()=>location.reload()}>← Back to stable</button><section className="profile"><div className="portrait">{horse.imageUrl?<img src={horse.imageUrl} alt=""/>:<span>♞</span>}<label>Image URL<input value={horse.imageUrl} onChange={e=>update({imageUrl:e.target.value})}/></label></div><div><p className="eyebrow">{horse.origin.toUpperCase()} · GENERATION {horse.generation}</p><input className="nameedit" value={horse.name} onChange={e=>update({name:e.target.value})}/><p className="meta">{horse.color} {horse.breed} · {horse.sex} · {gameAge(horse).toFixed(1)} years</p><textarea placeholder="Write this horse's story…" value={horse.biography} onChange={e=>update({biography:e.target.value})}/><div className="links"><button onClick={()=>setView("pedigree")}>View Pedigree</button><button onClick={()=>setView("progeny")}>View Progeny ({all.filter(h=>h.sireId===horse.id||h.damId===horse.id).length})</button></div></div><div className="points"><b>{overall(horse)}</b><span>OVERALL POINTS</span><small>{canBreed(horse)?"● BREEDING ELIGIBLE":"○ NOT ELIGIBLE"}</small></div></section><section className="panel"><h2>Base & Effective Stats</h2><div className="statlist">{GAME.stats.map(s=><div key={s}><span>{s}</span><strong>{horse.stats[s]}</strong><em>+{horse.tackBonuses[s]??0}</em><b>{horse.stats[s]+(horse.tackBonuses[s]??0)}</b><button onClick={()=>train(s)} disabled={!canTrain(horse)}>Train +1</button></div>)}</div></section>{horse.sex==="Stallion"&&<section className="panel breed"><h2>Breed {horse.name}</h2><p>Choose an eligible mare. Your foal arrives immediately; the mare then rests for {GAME.mareCooldownDays} days.</p><select value={mare} onChange={e=>setMare(e.target.value)}><option value="">Select an eligible mare…</option>{mares.filter(m=>m.id!==horse.id).map(m=><option value={m.id} key={m.id}>{m.name} · {m.breed}</option>)}</select><button className="primary" disabled={!mare||!canBreed(horse)} onClick={()=>breed(mare)}>Confirm Breeding · ${horse.studFee}</button></section>}{horse.sex==="Mare"&&horse.lastBredAt&&<section className="panel"><h2>Breeding cooldown</h2><p>Eligible again {cooldownEnds(horse)?.toLocaleDateString()}.</p></section>}</>}
function Pedigree({horse,all,open}:{horse:Horse;all:Horse[];open:(h:Horse)=>void}){const parent=(id:string|null)=>all.find(h=>h.id===id); const P=({h,label}:{h:Horse|undefined;label:string})=><div className="ped"><small>{label}</small>{h?<button onClick={()=>open(h)}><b>{h.name}</b><span>{h.breed}</span></button>:<i>Unknown foundation line</i>}</div>; const sire=parent(horse.sireId),dam=parent(horse.damId);return <><Title title={`${horse.name} · Pedigree`} sub="Three generations of permanent ancestry"/><div className="pedigree"><div><P h={horse} label="SUBJECT"/></div><div><P h={sire} label="SIRE"/><P h={dam} label="DAM"/></div><div><P h={parent(sire?.sireId??null)} label="PATERNAL GRANDSIRE"/><P h={parent(sire?.damId??null)} label="PATERNAL GRANDDAM"/><P h={parent(dam?.sireId??null)} label="MATERNAL GRANDSIRE"/><P h={parent(dam?.damId??null)} label="MATERNAL GRANDDAM"/></div></div></>}
