"use client";
import {useCallback,useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";

type Horse={id:string;name:string;breed:string};
type Profession={id:string;name:string;description:string;enrollment_fee:number;exam_fee:number;level:number;level_name:string;available:boolean;client_services:number;self_services:number;qualifying_credit:number;study_completed:boolean;required_services:number;next_level:number|null};
type Directory={provider_id:string;stable_name:string;account_number:number;profession_id:string;profession_name:string;certification:string;completed_services:number;service_id:string;service_name:string;price:number};
type Catalog={id:string;profession_id:string;name:string;minimum_level:number;min_price:number;max_price:number;wellness_component:"health"|"hooves"|"recovery"|null;restoration_by_level:Record<string,number>};
type Wellness={health:number;hooves:number;recovery:number;readiness:number;label:string};
type Question={id:string;prompt:string;choices:string[]};
type StudyModule={id:string;profession_id:string;level:number;title:string;summary:string;lessons:string[]};
const supabase=createClient();

export function ProfessionalCenter({horses,notify,refresh}:{horses:Horse[];notify:(message:string)=>void;refresh:()=>void}){
 const[professions,setProfessions]=useState<Profession[]>([]),[directory,setDirectory]=useState<Directory[]>([]),[catalog,setCatalog]=useState<Catalog[]>([]),[modules,setModules]=useState<StudyModule[]>([]),[rates,setRates]=useState<Record<string,number>>({}),[filter,setFilter]=useState<string|null>(null),[questions,setQuestions]=useState<Question[]>([]),[testing,setTesting]=useState<Profession|null>(null),[answers,setAnswers]=useState<Record<string,number>>({}),[horse,setHorse]=useState(""),[wellness,setWellness]=useState<Wellness|null>(null);
 const load=useCallback(async()=>{const[{data:d,error:e},{data:listing},{data:services},{data:study}]=await Promise.all([supabase.rpc("get_profession_dashboard"),supabase.rpc("get_service_directory",{target_profession:filter}),supabase.from("service_catalog").select("id,profession_id,name,minimum_level,min_price,max_price,wellness_component,restoration_by_level").eq("active",true),supabase.from("study_modules").select("id,profession_id,level,title,summary,lessons").eq("active",true).order("sort_order")]);if(e)notify(e.message);else setProfessions((d?.professions??[]) as Profession[]);setDirectory((listing??[]) as Directory[]);setCatalog((services??[]) as Catalog[]);setModules((study??[]) as StudyModule[])},[filter,notify]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 const run=async(job:()=>Promise<{error:Error|null}>,ok:string)=>{const{error}=await job();notify(error?.message??ok);if(!error){await load();refresh()}};
 const study=async(p:Profession)=>run(async()=>{const{error}=await supabase.rpc("complete_profession_study",{target_profession:p.id,target_level:p.next_level});return{error}},`${p.name} Study completed. You can revisit the lessons whenever you like.`);
 const openTest=async(p:Profession)=>{const{data,error}=await supabase.rpc("get_certification_questions",{target_profession:p.id,target_level:p.next_level});if(error)return notify(error.message);setTesting(p);setQuestions((data??[]) as Question[]);setAnswers({})};
 const submit=async()=>{if(!testing?.next_level)return;const{data,error}=await supabase.rpc("take_certification_test",{target_profession:testing.id,target_level:testing.next_level,submitted_answers:answers});if(error)return notify(error.message);notify(data.passed?`Passed with ${data.score}%. You are now certified!`:`Score: ${data.score}%. Study again and retry after the cooldown.`);setTesting(null);await load()};
 return <><header className="title"><div><p className="eyebrow">LEGACY EQUINE GAME CERTIFICATIONS</p><h1>Professional Services</h1><p>Study, certify, build a lifetime record, and serve the horse community. These are in-game credentials—not real-world professional qualifications.</p></div></header>
 <div className="professiongrid">{professions.map(p=>{const studyModule=modules.find(m=>m.profession_id===p.id&&m.level===p.next_level);return <article className="panel professioncard" key={p.id}><p className="eyebrow">{p.level_name}</p><h2>{p.name}</h2><p>{p.description}</p>{p.level===0?<button className="primary" onClick={()=>run(async()=>{const{error}=await supabase.rpc("enroll_profession",{target_profession:p.id});return{error}},`Enrolled in ${p.name}.`)}>Enroll · {p.enrollment_fee.toLocaleString()} LED</button>:<><div className="progressline"><span>Lifetime record</span><b>{p.client_services+p.self_services} services</b></div><div className="progressline"><span>Qualifying services</span><b>{p.qualifying_credit} / {p.next_level?p.required_services:"Complete"}</b></div>{p.next_level&&<><details className="study"><summary>{p.study_completed?"✓ Study completed — revisit lessons":studyModule?.title??"Study module"}</summary><p>{studyModule?.summary}</p>{studyModule?.lessons?.map((lesson,index)=><p key={index}>{index+1}. {lesson}</p>)}{!p.study_completed&&<button onClick={()=>study(p)} disabled={p.qualifying_credit<p.required_services}>Complete Study</button>}</details><button className="primary" disabled={!p.study_completed} onClick={()=>openTest(p)}>Take {p.next_level===1?"Basic":"Next"} Test · {p.exam_fee.toLocaleString()} LED</button></>}<label className="availability"><input type="checkbox" checked={p.available} onChange={e=>run(async()=>{const{error}=await supabase.rpc("set_professional_availability",{target_profession:p.id,is_available:e.target.checked});return{error}},e.target.checked?"You are available for services.":"You are unavailable for services.")}/> Available to other players</label></>}</article>})}</div>
 <section className="panel"><p className="eyebrow">YOUR SERVICES</p><h2>Set Your Rates</h2><p className="panelsub">Certification unlocks services and their permitted market range. You choose the actual rate.</p><div className="servicelist">{catalog.filter(s=>(professions.find(p=>p.id===s.profession_id)?.level??0)>=s.minimum_level).map(s=><article key={s.id}><span><b>{s.name}</b><small>{s.min_price}–{s.max_price} LED</small></span><input aria-label={`${s.name} price`} type="number" min={s.min_price} max={s.max_price} value={rates[s.id]??s.min_price} onChange={e=>setRates({...rates,[s.id]:Number(e.target.value)})}/><button onClick={()=>run(async()=>{const{error}=await supabase.rpc("set_service_offering",{target_service:s.id,new_price:rates[s.id]??s.min_price,is_enabled:true});return{error}},`${s.name} is listed at ${rates[s.id]??s.min_price} LED.`)}>Offer Service</button></article>)}</div></section>
 <section className="panel"><p className="eyebrow">PLAYER MARKET</p><h2>Find a Professional</h2><div className="directoryfilters"><button className={!filter?"active":""} onClick={()=>setFilter(null)}>All</button>{professions.map(p=><button className={filter===p.id?"active":""} key={p.id} onClick={()=>setFilter(p.id)}>{p.name}</button>)}</div>{horses.length>0&&<label>Horse<select value={horse} onChange={e=>setHorse(e.target.value)}><option value="">Choose your horse…</option>{horses.map(h=><option key={h.id} value={h.id}>{h.name} · {h.breed}</option>)}</select></label>}<div className="servicelist">{directory.map(d=><article key={`${d.provider_id}-${d.service_id}`}><span><b>{d.stable_name} #{d.account_number}</b><small>{d.certification} {d.profession_name} · {d.completed_services} completed</small></span><span><b>{d.service_name}</b><small>{d.price.toLocaleString()} LED</small></span><button disabled={!horse} onClick={()=>run(async()=>{const{error}=await supabase.rpc("purchase_professional_service",{target_horse:horse,target_provider:d.provider_id,target_service:d.service_id,request_key:crypto.randomUUID()});return{error}},`${d.service_name} completed.`)}>Request Service</button></article>)}</div>{!directory.length&&<p className="featurehint">No players are offering this service yet. Earn certification and become the first.</p>}</section>
 {testing&&<div className="examoverlay" role="dialog" aria-modal="true"><section className="panel exam"><button className="examclose" onClick={()=>setTesting(null)}>×</button><p className="eyebrow">{testing.name.toUpperCase()}</p><h2>Certification Test</h2>{questions.map((q,index)=><fieldset key={q.id}><legend>{index+1}. {q.prompt}</legend>{q.choices.map((choice,i)=><label key={choice}><input type="radio" name={q.id} checked={answers[q.id]===i} onChange={()=>setAnswers({...answers,[q.id]:i})}/>{choice}</label>)}</fieldset>)}<button className="primary" disabled={Object.keys(answers).length<questions.length} onClick={submit}>Submit Test</button></section></div>}</>;
}

type ServiceRecord={completed_at:string;profession_name:string;service_name:string;provider_name:string;provider_account:number;certification:string;quality:string;effect:Record<string,number>;effect_expires_at:string|null;self_service:boolean};
export function HorseCare({horseId,section}:{horseId:string;section:"farrier"|"health"}){
 const[history,setHistory]=useState<ServiceRecord[]>([]);useEffect(()=>{void supabase.rpc("get_horse_service_history",{target_horse:horseId}).then(({data})=>setHistory((data??[]) as ServiceRecord[]))},[horseId]);
 const shown=history.filter(r=>section==="farrier"?r.profession_name==="Farrier":r.profession_name!=="Farrier");
 return <section className="panel"><p className="eyebrow">PERMANENT HORSE RECORD</p><h2>{section==="farrier"?"Farrier":"Health, Training & Recovery"}</h2><p className="panelsub">Professional effects are temporary and remain separate from inherited base values and permanent development.</p>{shown.map(r=><div className="servicehistory" key={`${r.completed_at}-${r.service_name}`}><span><b>{r.service_name}</b><small>{new Date(r.completed_at).toLocaleDateString()} · {r.provider_name} #{r.provider_account}</small></span><span><b>{r.quality}</b><small>{r.certification} {r.profession_name}{r.self_service?" · Self-service":""}</small></span><span>{Object.entries(r.effect).map(([stat,value])=><small key={stat}>{stat} +{value}{r.effect_expires_at?` until ${new Date(r.effect_expires_at).toLocaleDateString()}`:" permanent development"}</small>)}</span></div>)}{!shown.length&&<p className="featurehint">No {section==="farrier"?"farrier":"health or recovery"} services recorded yet. Schedule one in Professional Services.</p>}</section>;
}
