/* eslint-disable @next/next/no-img-element */
"use client";
import{Fragment,useCallback,useEffect,useMemo,useState}from"react";
import Link from"next/link";
import{createClient}from"@/lib/supabase/client";
import"./public-stable-profile.css";

type Horse={id:string;name:string;breed:string;sex:"Mare"|"Stallion"|"Gelding";color:string;image_url:string;career_points:number};
type Hotspot={x:number;y:number;width:number;height:number};
type Block={id:string;type:"banner"|"news"|"about"|"featured"|"stallions"|"broodmares"|"winners"|"services"|"roster"|"custom";visible:boolean;content?:string;hotspot?:Hotspot};
type Profile={id:string;name:string;username:string|null;account_number:number;ranch_image_url:string;created_at:string;brand:{code:string;mark_url:string|null;active:boolean}|null;stable_news:string;about:string;blocks:Block[];featured_horses:string[];layout_mode:"standard"|"custom";layout_image_url:string;owner:boolean;can_customize:boolean;horses:Horse[];services:{provider_id:string;service_id:string;profession_id:string;name:string;price:number;profession:string;certification:string}[]};
const supabase=createClient();
const labels:Record<Block["type"],string>={banner:"Stable Banner",news:"Stable News",about:"About the Stable",featured:"Featured Horses",stallions:"Stallions",broodmares:"Broodmares",winners:"Recent Winners",services:"Professional Services",roster:"Horse Roster",custom:"Custom Text"};
const hotspotTypes=new Set<Block["type"]>(["news","featured","about","services","roster"]);
const defaultHotspots:Record<string,Hotspot>={news:{x:7,y:12,width:25,height:10},featured:{x:67,y:12,width:26,height:10},about:{x:7,y:76,width:22,height:10},services:{x:69,y:76,width:24,height:10},roster:{x:38,y:76,width:24,height:10}};

function SafeRichText({text}:{text:string}){const inline=(value:string)=>{const parts=value.split(/(\*\*[^*]+\*\*|\*[^*]+\*|\[[^\]]+\]\(https?:\/\/[^)]+\))/g);return parts.map((part,index)=>{if(/^\*\*.*\*\*$/.test(part))return <strong key={index}>{part.slice(2,-2)}</strong>;if(/^\*.*\*$/.test(part))return <em key={index}>{part.slice(1,-1)}</em>;const link=part.match(/^\[([^\]]+)\]\((https?:\/\/[^)]+)\)$/);return link?<a key={index} href={link[2]} target="_blank" rel="noreferrer">{link[1]}</a>:<Fragment key={index}>{part}</Fragment>})};return <div className="saferichtext">{text.split("\n").map((raw,index)=>{const line=raw.trim();if(line.startsWith("- "))return <ul key={index}><li>{inline(line.slice(2))}</li></ul>;if(line==="---")return <hr key={index}/>;if(line.startsWith("### "))return <h4 key={index}>{inline(line.slice(4))}</h4>;if(line.startsWith("## "))return <h3 key={index}>{inline(line.slice(3))}</h3>;if(line.startsWith("# "))return <h2 key={index}>{inline(line.slice(2))}</h2>;if(line.startsWith("[center] "))return <p className="textcenter" key={index}>{inline(line.slice(9))}</p>;return line?<p key={index}>{inline(line)}</p>:null})}</div>}

function HorseList({horses}:{horses:Horse[]}){return <div className="publichorsegrid">{horses.map(h=><Link href={`/horses/${h.id}`} key={h.id}><div>{h.image_url?<img src={h.image_url} alt=""/>:<span>LE</span>}</div><b>{h.name}</b><small>{h.breed} · {h.sex} · {h.color}</small></Link>)}{!horses.length&&<p className="featurehint">No horses to display.</p>}</div>}

const normalizeBlocks=(value:Block[])=>{const blocks=[...value];if(!blocks.some(block=>block.type==="roster"))blocks.push({id:"roster",type:"roster",visible:true,hotspot:defaultHotspots.roster});return blocks.map(block=>hotspotTypes.has(block.type)?{...block,hotspot:block.hotspot??defaultHotspots[block.type]}:block)};

async function uploadLayoutImage(file:File){
 if(!["image/jpeg","image/png","image/webp"].includes(file.type))throw new Error("Choose a JPG, PNG, or WebP layout image.");
 if(file.size<=0||file.size>5*1024*1024)throw new Error("Stable Layout images must be 5 MB or smaller.");
 const bitmap=await createImageBitmap(file);if(bitmap.width<800||bitmap.height<400){bitmap.close();throw new Error("Stable Layout images must be at least 800 × 400 pixels.")}
 const scale=Math.min(1,1200/bitmap.width,1200/bitmap.height),width=Math.round(bitmap.width*scale),height=Math.round(bitmap.height*scale),canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;canvas.getContext("2d")!.drawImage(bitmap,0,0,width,height);bitmap.close();
 const processed=scale<1?await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error("Image processing failed")),file.type,.92)):file;
 const ext=file.type==="image/jpeg"?"jpg":file.type.split("/")[1],{data:reservation,error:reserveError}=await supabase.rpc("reserve_artwork_album_upload",{p_mime:processed.type,p_byte_size:processed.size,p_extension:ext});if(reserveError)throw reserveError;
 const item=(reservation as{storage_path:string;id:string}).id,path=(reservation as{storage_path:string;id:string}).storage_path,{error}=await supabase.storage.from("legacy-equine-media").upload(path,processed,{cacheControl:"3600"});if(error){await supabase.rpc("remove_artwork_album_item",{p_item:item});throw error}
 const{error:finalizeError}=await supabase.rpc("finalize_artwork_album_upload",{p_item:item,p_width:width,p_height:height});if(finalizeError){await supabase.storage.from("legacy-equine-media").remove([path]);await supabase.rpc("remove_artwork_album_item",{p_item:item});throw finalizeError}
 return supabase.storage.from("legacy-equine-media").getPublicUrl(path).data.publicUrl;
}

function CustomCanvas({image}:{image:string}){return <section className="customlayoutcanvas"><img src={image} alt="Custom Stable Layout"/></section>}

function CustomStableNav({blocks}:{blocks:Block[]}){const enabled=new Set(blocks.filter(block=>block.visible).map(block=>block.type)),items:[Block["type"],string,string][]=[["news","Stable News","#stable-news"],["about","About","#stable-about"],["roster","Horses","#stable-roster"],["featured","Featured","#stable-featured"],["services","Services","#stable-services"]];return <nav className="customstablenav" aria-label="Stable profile sections">{items.filter(([type])=>enabled.has(type)).map(([type,label,href])=><a key={type} href={href}>{label}</a>)}</nav>}

function CustomStableIdentity({profile}:{profile:Profile}){return <section className="panel customstableidentity"><div><p className="eyebrow">PUBLIC STABLE</p><h1>{profile.name}</h1><p>Owned by {profile.username?`@${profile.username}`:`Account #${profile.account_number}`}</p><small>LE Account #{profile.account_number} · Established {new Date(profile.created_at).getFullYear()} · {profile.horses.length} Horse{profile.horses.length===1?"":"s"}</small></div>{profile.brand&&<div className="publicbrandmark">{profile.brand.mark_url?<img src={profile.brand.mark_url} alt={`${profile.brand.code} Brand`}/>:<span>{profile.brand.code}</span>}<b>{profile.brand.code} Brand</b></div>}</section>}

function StableCustomization({profile,notify,reload}:{profile:Profile;notify:(message:string)=>void;reload:()=>Promise<void>}){
 const[mode,setMode]=useState<"standard"|"custom">(profile.layout_mode),[image,setImage]=useState(profile.layout_image_url),[news,setNews]=useState(profile.stable_news),[about,setAbout]=useState(profile.about),[featured,setFeatured]=useState<string[]>(profile.featured_horses),[blocks,setBlocks]=useState<Block[]>(normalizeBlocks(profile.blocks)),[busy,setBusy]=useState(false),[preview,setPreview]=useState(false);
 const move=(index:number,direction:-1|1)=>{const next=[...blocks],target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setBlocks(next)};
 const upload=async(file:File)=>{setBusy(true);try{setImage(await uploadLayoutImage(file));notify("Stable Layout image ready. Save Changes to publish it.")}catch(error){notify(error instanceof Error?error.message:"Layout upload failed")}finally{setBusy(false)}};
 const save=async()=>{setBusy(true);const content=await supabase.rpc("save_public_stable_content",{p_news:news,p_about:about,p_featured:featured});if(content.error){setBusy(false);return notify(content.error.message)}const{error}=await supabase.rpc("save_public_stable_customization",{p_mode:mode,p_layout_image_url:image||null,p_blocks:blocks});setBusy(false);notify(error?.message??"Stable customization saved.");if(!error)await reload()};
 const reset=()=>{setMode("standard");setBlocks(normalizeBlocks(profile.blocks).map(block=>({...block,visible:true,hotspot:hotspotTypes.has(block.type)?defaultHotspots[block.type]:block.hotspot})));notify("Standard Layout selected. Save Changes to publish it.")};
 return <div className="stablecustomizer"><header className="customizerhead"><div><Link href="/stable">← Back to My Stable</Link><p className="eyebrow">PUBLIC STABLE PRESENTATION</p><h1>Customize Stable</h1><p>Edit existing Stable content, choose a safe layout, and preview before publishing.</p></div><div className="customizeractions"><button onClick={()=>setPreview(!preview)}>{preview?"Exit Preview":"Preview"}</button><button className="primary" disabled={busy} onClick={()=>void save()}>{busy?"Saving…":"Save Changes"}</button></div></header>
 {preview&&<section className="panel customizerpreview"><p className="eyebrow">PREVIEW</p>{mode==="custom"&&image?<><CustomCanvas image={image}/><CustomStableNav blocks={blocks}/></>:<div className="standardpreview"><b>Standard LE Layout</b><span>{profile.name}</span></div>}</section>}
 <section className="panel customizersection"><p className="eyebrow">LAYOUT MODE</p><h2>Stable presentation</h2><div className="layoutmodes"><label><input type="radio" name="layout-mode" checked={mode==="standard"} onChange={()=>setMode("standard")}/><span><b>Standard LE Layout</b><small>The responsive Legacy Equine Stable presentation.</small></span></label><label className={!profile.can_customize?"locked":""}><input type="radio" name="layout-mode" checked={mode==="custom"} disabled={!profile.can_customize} onChange={()=>setMode("custom")}/><span><b>Custom Layout</b><small>{profile.can_customize?"Use one uploaded artwork canvas with safe LE content hotspots.":"Unlocks at Account Level 20."}</small></span></label></div>{profile.can_customize&&<label className="layoutupload">Stable Layout image <small>JPG, PNG, or WebP · 5 MB maximum · at least 800 × 400</small><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={event=>event.target.files?.[0]&&void upload(event.target.files[0])}/></label>}{image&&<div className="layoutthumb"><img src={image} alt="Uploaded Stable Layout preview"/><span>This single image is used only as presentation. LE content remains safe and separate.</span></div>}</section>
 <section className="panel customizersection"><p className="eyebrow">STABLE CONTENT</p><h2>News &amp; About</h2><label>Stable News <small>{news.length.toLocaleString()} / 10,000</small><textarea maxLength={10000} value={news} onChange={event=>setNews(event.target.value)} placeholder="# Stable News&#10;Use **bold**, *italic*, - lists, [links](https://…), --- dividers, or [center] text."/></label><label>About the Stable <small>{about.length.toLocaleString()} / 10,000</small><textarea maxLength={10000} value={about} onChange={event=>setAbout(event.target.value)}/></label></section>
 <section className="panel customizersection"><p className="eyebrow">FEATURED HORSES</p><h2>Select up to 12</h2><fieldset>{profile.horses.map(horse=><label className="horsecheck" key={horse.id}><input type="checkbox" checked={featured.includes(horse.id)} disabled={!featured.includes(horse.id)&&featured.length>=12} onChange={event=>setFeatured(event.target.checked?[...featured,horse.id]:featured.filter(id=>id!==horse.id))}/>{horse.name}</label>)}{!profile.horses.length&&<p className="featurehint">No owned horses are available.</p>}</fieldset></section>
 <section className="panel customizersection"><p className="eyebrow">CONTENT SECTIONS</p><h2>Show &amp; reorder</h2><p>Enabled core sections automatically appear in the compact navigation below your layout image. Content stays safely separate from the artwork on every screen size.</p><div className="blockeditor">{blocks.map((block,index)=><article key={block.id}><label><input type="checkbox" checked={block.visible} onChange={event=>setBlocks(blocks.map(item=>item.id===block.id?{...item,visible:event.target.checked}:item))}/>{labels[block.type]}</label><span><button disabled={index===0} onClick={()=>move(index,-1)}>Move Up</button><button disabled={index===blocks.length-1} onClick={()=>move(index,1)}>Move Down</button></span>{block.type==="custom"&&<textarea maxLength={10000} value={block.content??""} onChange={event=>setBlocks(blocks.map(item=>item.id===block.id?{...item,content:event.target.value}:item))}/>}</article>)}</div><button onClick={reset}>Reset to Standard Layout</button></section>
 <div className="customizersticky"><Link href="/stable">← Back to My Stable</Link><button onClick={()=>setPreview(!preview)}>{preview?"Exit Preview":"Preview"}</button><button className="primary" disabled={busy} onClick={()=>void save()}>{busy?"Saving…":"Save Changes"}</button></div></div>;
}

export function PublicStableProfile({stableId,notify}:{stableId:string;notify:(message:string)=>void}){
 const[profile,setProfile]=useState<Profile|null>(null),[customizing,setCustomizing]=useState(false);
 const load=useCallback(async()=>{const{data,error}=await supabase.rpc("get_public_stable_profile",{p_stable:stableId});if(error)notify(error.message);else{const value=data as Profile;value.blocks=normalizeBlocks(value.blocks);setProfile(value);setCustomizing(value.owner&&location.pathname.endsWith("/customize"))}},[stableId,notify]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 const shown=useMemo(()=>profile?.blocks.filter(block=>block.visible)??[],[profile]);
 if(!profile)return <section className="panel"><p>Loading Stable Profile…</p></section>;
 if(customizing)return <StableCustomization profile={profile} notify={notify} reload={load}/>;
 const render=(block:Block)=>{const featuredHorses=profile.horses.filter(h=>profile.featured_horses.includes(h.id));const typeHorses=block.type==="stallions"?profile.horses.filter(h=>h.sex==="Stallion"):block.type==="broodmares"?profile.horses.filter(h=>h.sex==="Mare"):block.type==="winners"?profile.horses.filter(h=>h.career_points>0).sort((a,b)=>b.career_points-a.career_points).slice(0,6):[];if(block.type==="banner")return <section id="stable-banner" className={`publicstablebanner ${profile.ranch_image_url?"hasimage":""}`} style={profile.ranch_image_url?{backgroundImage:`linear-gradient(90deg,#28183bdb,#5a3987aa),url(${profile.ranch_image_url})`}:undefined}><div><p className="eyebrow">PUBLIC STABLE · LE ACCOUNT #{profile.account_number}</p><h1>{profile.name}</h1><p>Owned by {profile.username?`@${profile.username}`:`Account #${profile.account_number}`} · Established {new Date(profile.created_at).getFullYear()}</p></div>{profile.brand&&<div className="publicbrandmark">{profile.brand.mark_url?<img src={profile.brand.mark_url} alt={`${profile.brand.code} Brand`}/>:<span>{profile.brand.code}</span>}<b>{profile.brand.code}</b></div>}</section>;if(block.type==="news")return <section id="stable-news" className="panel publicblock"><p className="eyebrow">STABLE NEWS</p><SafeRichText text={profile.stable_news||"No Stable news has been posted."}/></section>;if(block.type==="about")return <section id="stable-about" className="panel publicblock"><p className="eyebrow">ABOUT THE STABLE</p><SafeRichText text={profile.about||"This Stable has not added an introduction yet."}/></section>;if(block.type==="featured")return <section id="stable-featured" className="panel publicblock"><h2>Featured Horses</h2><HorseList horses={featuredHorses}/></section>;if(block.type==="roster")return <section id="stable-roster" className="panel publicblock"><h2>Public Horse Roster</h2><HorseList horses={profile.horses}/></section>;if(["stallions","broodmares","winners"].includes(block.type))return <section id={`stable-${block.type}`} className="panel publicblock"><h2>{labels[block.type]}</h2><HorseList horses={typeHorses}/></section>;
if(block.type==="services"){const businesses=[...new Map(profile.services.map(service=>[service.profession_id,service])).values()];return <section id="stable-services" className="panel publicblock"><h2>Professional Businesses &amp; Services</h2>{businesses.map(service=><div className="publicservice" key={service.profession_id}><span><b>{profile.name} · {service.profession}</b><small>{service.certification}</small></span><span><Link href={`/professions/storefront/${service.provider_id}/${service.profession_id}`}>VIEW STOREFRONT →</Link><small><Link href={`/professions?profession=${service.profession_id}&provider=${service.provider_id}&service=${service.service_id}`}>VIEW SERVICES / HIRE PROFESSIONAL</Link></small></span></div>)}{!businesses.length&&<p className="featurehint">No professional businesses are currently active.</p>}</section>}return <section id="stable-custom" className="panel publicblock"><SafeRichText text={block.content??""}/></section>};
 const custom=profile.layout_mode==="custom"&&Boolean(profile.layout_image_url);
 return <><div className="publicstableactions"><Link href="/stable">← My Stable</Link>{profile.owner&&<Link className="button" href={`/stables/${profile.id}/customize`}>{profile.can_customize?"CUSTOMIZE STABLE":"EDIT STABLE PROFILE"}</Link>}</div>{!profile.can_customize&&profile.owner&&<p className="featurehint">Custom Stable Layouts unlock at Account Level 20. Standard Stable content remains editable.</p>}{custom?<><CustomCanvas image={profile.layout_image_url}/><CustomStableNav blocks={shown}/><CustomStableIdentity profile={profile}/>{shown.filter(block=>block.type!=="banner").map(block=><Fragment key={block.id}>{render(block)}</Fragment>)}</>:shown.map(block=><Fragment key={block.id}>{render(block)}</Fragment>)}</>;
}
