"use client";
import{useCallback,useEffect,useMemo,useState}from"react";
import{createClient}from"@/lib/supabase/client";
import"./show-auto-host.css";
const supabase=createClient();
type Ref={id:string;name:string;sort_order?:number};type Combo={discipline_id:string;tier_id:string;enabled:boolean;quantity:number;entry_fee:number;base_purse:number};
type Plan={enabled:boolean;selection_mode:"full"|"custom";quantity_mode:"maintain"|"create_new";daily_enabled:boolean;default_quantity:number;run_delay_days:number;use_show_defaults:boolean;next_run:string|null;combination_count:number;current_qualifying:number;target_total:number;would_create:number;items:{discipline:string;tier:string;current:number;would_create:number}[]};
type Run={id:string;cycle_key:string;trigger:string;shows_evaluated:number;shows_created:number;shows_skipped:number;error_count:number;created_at:string};
type Workspace={plan:Plan;disciplines:Ref[];tiers:Ref[];combinations:Combo[];history:Run[]};
type Preview={combination_count:number;current_qualifying:number;target_total:number;would_create:number;side_effects:boolean;items:{discipline:string;tier:string;current:number;target:number;would_create:number}[]};
export function ShowAutoHost({notify,reloadShows}:{notify:(message:string)=>void;reloadShows:()=>Promise<void>}){
 const[data,setData]=useState<Workspace|null>(null),[config,setConfig]=useState<Plan|null>(null),[combos,setCombos]=useState<Combo[]>([]),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const{data:next,error}=await supabase.rpc("get_show_auto_host_workspace");if(error)notify(error.message);else{const workspace=next as Workspace;setData(workspace);setConfig(workspace.plan);setCombos(workspace.combinations)}},[notify]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 const selectedCount=useMemo(()=>config?.selection_mode==="full"?(data?.disciplines.length??0)*(data?.tiers.length??0):combos.filter(x=>x.enabled).length,[config?.selection_mode,data,combos]);
 const patchCombo=(discipline_id:string,tier_id:string,patch:Partial<Combo>)=>setCombos(current=>current.map(x=>x.discipline_id===discipline_id&&x.tier_id===tier_id?{...x,...patch}:x));
 const configPayload=()=>config&&{enabled:config.enabled,selection_mode:config.selection_mode,quantity_mode:config.quantity_mode,daily_enabled:config.daily_enabled,default_quantity:config.default_quantity,run_delay_days:config.run_delay_days,use_show_defaults:config.use_show_defaults};
 const doPreview=async()=>{setBusy(true);const{data:result,error}=await supabase.rpc("admin_preview_show_auto_host",{p_config:configPayload(),p_combinations:combos});setBusy(false);if(error)notify(error.message);else setPreview(result as Preview)};
 const save=async()=>{setBusy(true);const{error}=await supabase.rpc("admin_save_show_auto_host",{p_config:configPayload(),p_combinations:combos});setBusy(false);notify(error?.message??`Auto Host saved ${config?.enabled?"ON":"OFF"}.`);if(!error){setPreview(null);await load()}};
 const runNow=async()=>{if(!confirm("Run Auto Host now using the displayed configuration? This creates real scheduled Shows."))return;setBusy(true);const{data:result,error}=await supabase.rpc("admin_run_show_auto_host",{p_request:crypto.randomUUID()});setBusy(false);notify(error?.message??`Auto Host created ${Number(result?.created??0)} Shows; ${Number(result?.errors??0)} errors.`);if(!error){await load();await reloadShows()}};
 if(!data||!config)return <section className="autohost"><p>Loading Auto Host…</p></section>;
 return <section className="autohost"><header><div><p className="eyebrow">OWNER SHOW SEEDING</p><h3>Auto Host</h3><p>Maintains real Legacy Equine Show opportunities through the existing Show engine. Production remains OFF until you explicitly enable and save it.</p></div><label className="autohosttoggle">AUTO HOST SHOWS<input type="checkbox" checked={config.enabled} onChange={e=>setConfig({...config,enabled:e.target.checked})}/><b>{config.enabled?"ON":"OFF"}</b></label></header>
 <div className="autohoststatus"><span><small>Status</small><b>{config.enabled?"ON":"OFF"}</b></span><span><small>Next Auto Host Run</small><b>{config.daily_enabled&&config.next_run?new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",year:"numeric",month:"numeric",day:"numeric",hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(new Date(config.next_run)):"Daily schedule off"}</b></span><span><small>Mode</small><b>{config.quantity_mode==="maintain"?"Maintain Target Availability":"Create X New"}</b></span><span><small>Configured</small><b>{selectedCount} combinations</b></span></div>
 <div className="autohostcontrols"><label>Selection Mode<select value={config.selection_mode} onChange={e=>setConfig({...config,selection_mode:e.target.value as Plan["selection_mode"]})}><option value="full">Full Show Base</option><option value="custom">Custom Selection</option></select></label><label>Creation Mode<select value={config.quantity_mode} onChange={e=>setConfig({...config,quantity_mode:e.target.value as Plan["quantity_mode"]})}><option value="maintain">Maintain X Available</option><option value="create_new">Create X New Each Cycle</option></select></label><label>Run Shows In<select value={config.run_delay_days} onChange={e=>setConfig({...config,run_delay_days:Number(e.target.value)})}><option value={1}>1 LE day</option><option value={2}>2 LE days</option><option value={3}>3 LE days</option><option value={7}>7 LE days</option></select></label><label className="check"><input type="checkbox" checked={config.daily_enabled} onChange={e=>setConfig({...config,daily_enabled:e.target.checked})}/> Create Shows Daily · 12:05 AM ET</label><label className="check"><input type="checkbox" checked={config.use_show_defaults} onChange={e=>setConfig({...config,use_show_defaults:e.target.checked})}/> Use existing Show defaults</label>{config.selection_mode==="full"&&<label>Shows per Discipline / Level<input type="number" min={0} max={100} value={config.default_quantity} onChange={e=>setConfig({...config,default_quantity:Number(e.target.value)})}/><small>{data.disciplines.length} disciplines × {data.tiers.length} levels × {config.default_quantity} = {data.disciplines.length*data.tiers.length*config.default_quantity} Shows</small></label>}</div>
 {config.selection_mode==="custom"&&<><div className="autohostbulk"><button onClick={()=>setCombos(combos.map(x=>({...x,enabled:true})))}>SELECT ALL DISCIPLINES + LEVELS</button><button onClick={()=>setCombos(combos.map(x=>({...x,enabled:false})))}>CLEAR</button></div><div className="autohostmatrix">{data.disciplines.map(d=><article key={d.id}><h4>{d.name}</h4>{data.tiers.map(t=>{const x=combos.find(c=>c.discipline_id===d.id&&c.tier_id===t.id);return x&&<div key={t.id}><label className="check"><input type="checkbox" checked={x.enabled} onChange={e=>patchCombo(d.id,t.id,{enabled:e.target.checked})}/>{t.name}</label><label>Target / New<input type="number" min={0} max={100} value={x.quantity} onChange={e=>patchCombo(d.id,t.id,{quantity:Number(e.target.value)})}/></label>{!config.use_show_defaults&&<><label>Entry Fee<input type="number" min={0} value={x.entry_fee} onChange={e=>patchCombo(d.id,t.id,{entry_fee:Number(e.target.value)})}/></label><label>Base Purse<input type="number" min={0} value={x.base_purse} onChange={e=>patchCombo(d.id,t.id,{base_purse:Number(e.target.value)})}/></label></>}</div>})}</article>)}</div></>}
 <div className="autohostactions"><button disabled={busy} onClick={()=>void doPreview()}>PREVIEW — ZERO SHOWS CREATED</button><button disabled={busy} onClick={()=>void save()}>SAVE CONFIGURATION</button><button className="primary" disabled={busy} onClick={()=>void runNow()}>RUN AUTO HOST NOW</button></div>
 {preview&&<section className="autohostpreview"><p className="eyebrow">AUTO HOST PREVIEW · ZERO SIDE EFFECTS</p><h4>{preview.would_create} Shows would be created now</h4><p>{preview.current_qualifying} current qualifying Shows · {preview.target_total} target/new total · {preview.combination_count} combinations</p><div>{preview.items.map(x=><span key={`${x.discipline}-${x.tier}`}><b>{x.discipline} · {x.tier}</b><small>{x.current} current · target {x.target} · create {x.would_create}</small></span>)}</div></section>}
 <details className="autohosthistory"><summary>Auto Host History</summary>{data.history.map(run=><p key={run.id}><b>{new Date(run.created_at).toLocaleString()} · {run.trigger}</b><span>{run.shows_created} created · {run.shows_skipped} skipped · {run.error_count} errors</span><small>{run.cycle_key}</small></p>)}{!data.history.length&&<p>No Auto Host cycles recorded.</p>}</details></section>;
}
