"use client";
import{useCallback,useEffect,useState}from"react";
import{createClient}from"@/lib/supabase/client";
const supabase=createClient();
type Horse={id:string;name:string;breed:string;career_points:number};
type Show={id:string;name:string;discipline:string;tier:string;run_at:string;entry_fee:number;max_entries:number|null;entry_count:number;description:string;creator_name:string;creator_account:number;status:string};
type Ref={id:string;name:string};
export function PlayerShows({horses,notify,refreshAccount}:{horses:Horse[];notify:(s:string)=>void;refreshAccount:()=>void}){const[shows,setShows]=useState<Show[]>([]),[disciplines,setDisciplines]=useState<Ref[]>([]),[tiers,setTiers]=useState<Ref[]>([]),[creating,setCreating]=useState(false),[name,setName]=useState(""),[discipline,setDiscipline]=useState("racing"),[tier,setTier]=useState("novice"),[date,setDate]=useState(""),[fee,setFee]=useState(0),[max,setMax]=useState(""),[description,setDescription]=useState(""),[choices,setChoices]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{const[{data:s,error},{data:d},{data:t}]=await Promise.all([supabase.rpc("get_player_shows"),supabase.from("show_disciplines").select("id,name").eq("active",true),supabase.from("show_tiers").select("id,name").eq("active",true).order("sort_order")]);if(error)notify(error.message);setShows((s??[])as Show[]);setDisciplines((d??[])as Ref[]);setTiers((t??[])as Ref[])},[notify]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 const create=async()=>{const{error}=await supabase.rpc("create_player_show",{show_name:name,target_discipline:discipline,target_tier:tier,target_run_date:date,new_entry_fee:fee,new_max_entries:max?Number(max):null,new_description:description});notify(error?.message??"Show created for midnight America/New_York.");if(!error){setCreating(false);await load();refreshAccount()}};
 const enter=async(showId:string)=>{const horse=choices[showId];if(!horse)return;const{error}=await supabase.rpc("enter_player_show",{target_show:showId,target_horse:horse});notify(error?.message??"Show entry confirmed and tier eligibility snapshotted.");if(!error){await load();refreshAccount()}};
 return <><header className="title"><p className="eyebrow">PLAYER-HOSTED COMPETITION</p><h2>Legacy Equine Shows</h2><p>Deterministic, stat-based competition. Tack and active approved service effects count; random rolls do not.</p><button className="primary" onClick={()=>setCreating(!creating)}>{creating?"Close Creator":"Create Show"}</button></header>{creating&&<section className="panel showcreator"><h2>Create a Show</h2><div className="adminformgrid"><label>Show name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Discipline<select value={discipline} onChange={e=>setDiscipline(e.target.value)}>{disciplines.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Career Point tier<select value={tier} onChange={e=>setTier(e.target.value)}>{tiers.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Run date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/><small>Runs at 12:00 AM America/New_York</small></label><label>Entry fee (LED)<input type="number" min={0} value={fee} onChange={e=>setFee(Number(e.target.value))}/></label><label>Maximum entries<input type="number" min={2} placeholder="No maximum" value={max} onChange={e=>setMax(e.target.value)}/></label></div><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="primary" disabled={name.trim().length<3||!date} onClick={create}>Create Show</button></section>}<div className="featuregrid">{shows.map(s=><article className="featurecard showcard" key={s.id}><div className="showmark">◇</div><div><p className="eyebrow">{s.discipline} · {s.tier}</p><h3>{s.name}</h3><p>{s.description||"A player-hosted Legacy Equine competition."}</p><p><b>Hosted by {s.creator_name} #{s.creator_account}</b></p><p>{new Date(s.run_at).toLocaleString([],{timeZone:"America/New_York"})} · {s.entry_count}{s.max_entries?` / ${s.max_entries}`:""} entries · {s.entry_fee} LED</p>{s.status==="open"&&<><select value={choices[s.id]??""} onChange={e=>setChoices({...choices,[s.id]:e.target.value})}><option value="">Choose an eligible horse…</option>{horses.map(h=><option value={h.id} key={h.id}>{h.name} · {h.career_points??0} Career Points</option>)}</select><button className="primary" disabled={!choices[s.id]} onClick={()=>enter(s.id)}>Enter Show</button></>}</div></article>)}</div>{!shows.length&&<p className="featurehint">No player-created shows yet. Host the first one.</p>}</>}
