"use client";
import{useCallback,useEffect,useMemo,useState}from"react";
import{createClient}from"@/lib/supabase/client";
const supabase=createClient();
type Horse={id:string;name:string;breed:string};
type Product={name:string;department:string;tack_slot:string|null;quality:string|null;tack_bonuses:Record<string,number>;description?:string;icon_url?:string|null};
type Item={id:string;product_id:string;purchased_at:string;store_products:Product|null};
type Equipped={item_id:string;horse_id:string;slot:string;horses:{name:string}|null};
export function StableInventory({horses,notify,refresh}:{horses:Horse[];notify:(message:string)=>void;refresh:()=>void}){
 const[items,setItems]=useState<Item[]>([]),[equipped,setEquipped]=useState<Equipped[]>([]),[room,setRoom]=useState<"feed"|"tack">("feed"),[chosen,setChosen]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{const[{data,error},{data:eq}]=await Promise.all([supabase.from("player_store_items").select("id,product_id,purchased_at,store_products(name,description,department,tack_slot,quality,tack_bonuses,icon_url)").is("consumed_at",null).order("purchased_at"),supabase.from("horse_equipment").select("item_id,horse_id,slot,horses(name)")]);if(error)notify(error.message);else setItems((data??[])as unknown as Item[]);setEquipped((eq??[])as unknown as Equipped[])},[notify]);
 useEffect(()=>{void load()},[load]);
 const visible=items.filter(i=>i.store_products?.department===room),groups=useMemo(()=>{const result=new Map<string,Item[]>();for(const item of visible){const list=result.get(item.product_id)??[];list.push(item);result.set(item.product_id,list)}return[...result.values()]},[visible]);
 const useItem=async(item:Item)=>{const horse=chosen[item.product_id];if(!horse){notify("Choose a horse first.");return}const feed=item.store_products?.department==="feed",{data,error}=await supabase.rpc(feed?"feed_horse":"equip_tack",{p_horse:horse,p_item:item.id});if(error)notify(error.message);else if(feed)notify(data.success?`Development feeding: ${data.stat} +${data.gain}.`:`Development feeding complete; no point was awarded this time.`);else notify(`${item.store_products?.name} equipped. Effective Stats updated.`);if(!error){await load();refresh()}};
 return <section className="panel inventoryrooms"><p className="eyebrow">MY STABLE · INVENTORY ROOMS</p><h2>{room==="feed"?"Feed Room":"Tack Room"}</h2><nav><button className={room==="feed"?"active":""} onClick={()=>setRoom("feed")}>Feed Room</button><button className={room==="tack"?"active":""} onClick={()=>setRoom("tack")}>Tack Room</button></nav><p>{room==="feed"?"Optional Development feeding; missing a day never creates a penalty.":"Owned equipment remains here while equipped. Tack changes Effective Stats only."}</p><div className="inventoryshelves">{groups.map(group=>{const item=group.find(x=>!equipped.some(e=>e.item_id===x.id))??group[0],product=item.store_products!,eq=equipped.filter(e=>group.some(x=>x.id===e.item_id));return <article key={item.product_id}><div className="inventoryicon" aria-hidden="true">{product.icon_url?<img src={product.icon_url} alt=""/>:room==="feed"?"◇":"♢"}</div><span><b>{product.name}</b><small>{product.quality??(room==="feed"?"Development Feed":"Tack")} · Quantity {group.length}</small>{product.description&&<small>{product.description}</small>}{room==="tack"&&Object.entries(product.tack_bonuses??{}).map(([stat,n])=><em key={stat}>{stat} +{n} Effective</em>)}{eq.map(e=><small key={e.item_id}>Equipped: {e.horses?.name??"Horse"}</small>)}</span><label>Select horse<select value={chosen[item.product_id]??""} onChange={e=>setChosen({...chosen,[item.product_id]:e.target.value})}><option value="">Choose…</option>{horses.map(h=><option value={h.id} key={h.id}>{h.name}</option>)}</select></label><button disabled={!chosen[item.product_id]||(!item&&!room)} onClick={()=>void useItem(item)}>{room==="feed"?"Use Feed":"Equip / Change"}</button></article>})}</div>{!groups.length&&<p className="featurehint">Purchased {room==="feed"?"Feed & Hay":"Tack"} products will appear here.</p>}</section>;
}
