"use client";
import {useCallback,useEffect,useMemo,useState}from"react";
import{createClient}from"@/lib/supabase/client";
const supabase=createClient();
type Horse={id:string;name:string;breed:string};
type Product={name:string;department:string;tack_slot:string|null;quality:string|null;tack_bonuses:Record<string,number>;description?:string;icon_url?:string|null};
type Item={id:string;product_id:string;purchased_at:string;custom_name:string|null;custom_tack_bonuses:Record<string,number>|null;maker_brand_code:string|null;maker_stable_name:string|null;maker_account_number:number|null;crafted_tier:string|null;crafted_at:string|null;store_products:Product|null};
type Equipped={item_id:string;horse_id:string;slot:string;horses:{name:string}|null};
export function StableInventory({horses,notify,refresh,room}:{horses:Horse[];notify:(message:string)=>void;refresh:()=>void;room:"feed"|"tack"|"supplies"}){
 const[items,setItems]=useState<Item[]>([]),[equipped,setEquipped]=useState<Equipped[]>([]),[chosen,setChosen]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{const[{data,error},{data:eq}]=await Promise.all([supabase.from("player_store_items").select("id,product_id,purchased_at,custom_name,custom_tack_bonuses,maker_brand_code,maker_stable_name,maker_account_number,crafted_tier,crafted_at,store_products(name,description,department,tack_slot,quality,tack_bonuses,icon_url)").is("consumed_at",null).order("purchased_at"),supabase.from("horse_equipment").select("item_id,horse_id,slot,horses(name)")]);if(error)notify(error.message);else setItems((data??[])as unknown as Item[]);setEquipped((eq??[])as unknown as Equipped[])},[notify]);
 useEffect(()=>{void load()},[load]);
 const visible=items.filter(i=>i.store_products?.department===(room==="supplies"?"stable_supplies":room)),groups=useMemo(()=>{const result=new Map<string,Item[]>();for(const item of visible){const key=item.custom_name?item.id:item.product_id,list=result.get(key)??[];list.push(item);result.set(key,list)}return[...result.values()]},[visible]);
 const useItem=async(item:Item)=>{const horse=chosen[item.id]??chosen[item.product_id];if(!horse){notify("Choose a horse first.");return}const feed=item.store_products?.department==="feed",{data,error}=await supabase.rpc(feed?"feed_horse":"equip_tack",{p_horse:horse,p_item:item.id});if(error)notify(error.message);else if(feed)notify(data.success?`Development feeding: ${data.stat} +${data.gain}.`:`Development feeding complete; no point was awarded this time.`);else notify(`${item.custom_name??item.store_products?.name} equipped. Effective Stats updated.`);if(!error){await load();refresh()}};
 const unequip=async(e:Equipped)=>{const{error}=await supabase.rpc("unequip_tack",{p_horse:e.horse_id,p_slot:e.slot});if(error)notify(error.message);else notify(`${e.horses?.name??"Horse"}'s ${e.slot.replaceAll("_"," ")} was returned to the Tack Room.`);await load();refresh()};
 const title=room==="feed"?"Feed Room":room==="tack"?"Tack Room":"Supply Room";
 return <section className="panel inventoryrooms"><p className="eyebrow">MY STABLE · INVENTORY</p><h2>{title}</h2><p>{room==="feed"?"Optional Development feeding; missing a day never creates a penalty.":room==="tack"?"Owned equipment remains here while equipped. Tack changes Effective Stats only.":"Owned stable supplies are stored here."}</p><div className="inventoryshelves">{groups.map(group=>{const item=group.find(x=>!equipped.some(e=>e.item_id===x.id))??group[0],product=item.store_products!,eq=equipped.filter(e=>group.some(x=>x.id===e.item_id)),bonuses=item.custom_tack_bonuses??product.tack_bonuses;return <article key={item.custom_name?item.id:item.product_id}><div className="inventoryicon" aria-hidden="true">{product.icon_url?<img src={product.icon_url} alt=""/>:room==="feed"?"◇":room==="tack"?"♢":"□"}</div><span><b>{item.custom_name??product.name} × {group.length}</b><small>{item.crafted_tier??product.quality??(room==="feed"?"Development Feed":room==="tack"?"Tack":"Stable Supply")}</small>{product.description&&<small>{product.description}</small>}{room==="tack"&&Object.entries(bonuses??{}).map(([stat,n])=><em key={stat}>+{n} {stat} Effective</em>)}{item.maker_stable_name&&<small>Crafted by {item.maker_brand_code?`${item.maker_brand_code} · `:""}{item.maker_stable_name} #{item.maker_account_number}</small>}{eq.map(e=><small key={e.item_id}>Equipped: {e.horses?.name??"Horse"} <button onClick={()=>void unequip(e)}>Unequip</button></small>)}</span>{room!=="supplies"&&<><label>Select horse<select value={chosen[item.id]??chosen[item.product_id]??""} onChange={e=>setChosen({...chosen,[item.id]:e.target.value})}><option value="">Choose…</option>{horses.map(h=><option value={h.id} key={h.id}>{h.name}</option>)}</select></label><button disabled={!(chosen[item.id]??chosen[item.product_id])} onClick={()=>void useItem(item)}>{room==="feed"?"Use Feed":"Equip / Change"}</button></>}</article>})}</div>{!groups.length&&<p className="featurehint">Purchased {room==="feed"?"Feed & Hay":room==="tack"?"Tack":"Stable Supply"} products will appear here.</p>}</section>;
}
