"use client";
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import {useCallback,useEffect,useState}from"react";
import{createClient}from"@/lib/supabase/client";
import"@/app/support-center.css";

const supabase=createClient();
type Mode="home"|"bug"|"contact"|"reports"|"ticket";
type Ticket={id:string;ticket_number:string;type:string;category:string;title:string;status:string;priority?:string;created_at:string;updated_at:string;has_update?:boolean;description?:string;reproduction?:string;attachment_path?:string|null;object_context?:Record<string,string>;duplicate_of?:string|null;messages?:Message[]};
type Message={id:string;type:string;body:string;author:string;created_at:string};
const bugCategories=["Horse / Stable","Shows","Store / Inventory","Feed / Tack","Marketplace","Professions","Community","Bank / LED","Account","Mobile / Display","Other"];
const contactCategories=["Account Help","Gameplay Question","Player/Community Concern","Purchase/LED Problem","Report Player/Content","Other"];
const statusLabels:Record<string,string>={open:"Open",in_review:"In Review",need_info:"Need More Information",resolved:"Resolved",closed:"Closed",duplicate:"Duplicate"};

function contextFromLocation(){const current=`${location.pathname}${location.search}${location.hash}`,source=new URLSearchParams(location.search).get("from"),url=new URL(source||current,location.origin),route=`${url.pathname}${url.search}${url.hash}`,parts=url.pathname.split("/").filter(Boolean),query=url.searchParams,object:Record<string,string>={};if(parts[0]==="horses"&&parts[1])object.horse_id=parts[1];if(parts[0]==="shows"&&query.get("show"))object.show_id=query.get("show")!;if(parts[0]==="professions"){if(parts[1])object.profession=parts[1];if(query.get("level"))object.career_level=query.get("level")!}if(parts[0]==="marketplace"&&query.get("listing"))object.listing_id=query.get("listing")!;return{technical:{route,reported_at:new Date().toISOString(),viewport:`${window.innerWidth}×${window.innerHeight}`,device_class:window.innerWidth<=520?"phone":window.innerWidth<=900?"tablet":"desktop",user_agent:navigator.userAgent,build:process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA??"local"},object};}

export function SupportCenter({notify,onUpdateCount}:{notify:(message:string)=>void;onUpdateCount?:(count:number)=>void}){
 const params=typeof location!=="undefined"?new URLSearchParams(location.search):new URLSearchParams(),initialTicket=params.get("ticket");
 const[mode,setMode]=useState<Mode>(initialTicket?"ticket":"home"),[tickets,setTickets]=useState<Ticket[]>([]),[ticket,setTicket]=useState<Ticket|null>(null),[loading,setLoading]=useState(false),[reply,setReply]=useState(""),[attachmentUrl,setAttachmentUrl]=useState("");
 const[form,setForm]=useState({type:"bug",category:bugCategories[0],title:"",description:"",reproduction:"",attachment:""});
 const loadReports=useCallback(async()=>{const{data,error}=await supabase.rpc("get_my_support_tickets");if(error)return notify(error.message);const rows=(data??[])as Ticket[];setTickets(rows);onUpdateCount?.(rows.filter(row=>row.has_update).length)},[notify,onUpdateCount]);
 const openTicket=useCallback(async(id:string)=>{setLoading(true);const{data,error}=await supabase.rpc("get_support_ticket",{p_ticket:id});setLoading(false);if(error)return notify(error.message);const row=data as Ticket;setTicket(row);setMode("ticket");history.pushState({leSupport:true},"",`/support?ticket=${id}`);if(row.attachment_path){const signed=await supabase.storage.from("support-attachments").createSignedUrl(row.attachment_path,600);setAttachmentUrl(signed.data?.signedUrl??"")}else setAttachmentUrl("");await loadReports()},[loadReports,notify]);
 useEffect(()=>{const timer=setTimeout(()=>{void loadReports();if(initialTicket)void openTicket(initialTicket)},0);return()=>clearTimeout(timer)},[]);// eslint-disable-line react-hooks/exhaustive-deps
 const go=(next:Mode)=>{setMode(next);setTicket(null);history.pushState({leSupport:true},"","/support");if(next==="reports")void loadReports()};
 const start=(type:"bug"|"general")=>{const {object}=contextFromLocation();setForm({type,category:type==="bug"?bugCategories[0]:contactCategories[0],title:"",description:"",reproduction:"",attachment:""});sessionStorage.setItem("le-support-object",JSON.stringify(object));setMode(type==="bug"?"bug":"contact")};
 const upload=async(file:File)=>{if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024)throw new Error("Choose a JPG, PNG, or WebP screenshot up to 5 MB.");const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sign in to attach a screenshot.");const ext=file.type==="image/jpeg"?"jpg":file.type.split("/")[1],path=`${user.id}/${crypto.randomUUID()}.${ext}`,result=await supabase.storage.from("support-attachments").upload(path,file,{upsert:false});if(result.error)throw result.error;setForm(current=>({...current,attachment:path}));};
 const submit=async()=>{setLoading(true);const captured=contextFromLocation(),stored=sessionStorage.getItem("le-support-object");const{data,error}=await supabase.rpc("submit_support_ticket",{p_type:form.type,p_category:form.category,p_title:form.title,p_description:form.description,p_reproduction:form.reproduction,p_attachment_path:form.attachment||null,p_technical_context:captured.technical,p_object_context:stored?JSON.parse(stored):captured.object});setLoading(false);if(error)return notify(error.message);sessionStorage.removeItem("le-support-object");notify(`${data.ticket_number} submitted to Legacy Equine Support.`);await loadReports();await openTicket(data.id)};
 const sendReply=async()=>{setLoading(true);const{error}=await supabase.rpc("add_support_reply",{p_ticket:ticket!.id,p_body:reply});setLoading(false);if(error)return notify(error.message);setReply("");notify("Your follow-up was added.");await openTicket(ticket!.id)};
 if(mode==="bug"||mode==="contact")return <SupportForm kind={mode} form={form} setForm={setForm} busy={loading} upload={upload} submit={submit} back={()=>go("home")}/>;
 if(mode==="ticket"&&ticket)return <TicketConversation ticket={ticket} attachmentUrl={attachmentUrl} reply={reply} setReply={setReply} sendReply={sendReply} busy={loading} back={()=>go("reports")}/>;
 return <div className="supportcenter"><header className="supporthero"><p className="eyebrow">PRIVATE PLAYER SUPPORT</p><h1>HELP &amp; SUPPORT</h1><p>Need help with Legacy Equine?</p></header>{mode==="home"?<><div className="supportactions"><button onClick={()=>start("bug")}><span>!</span><b>Report a Bug</b><small>Something isn&apos;t working correctly.</small></button><button onClick={()=>start("general")}><span>?</span><b>Contact Admin</b><small>Questions, account problems, disputes, or other help.</small></button><button onClick={()=>go("reports")}><span>{tickets.filter(x=>x.has_update).length||"✓"}</span><b>My Reports</b><small>View your existing reports and Admin responses.</small></button></div><Link className="supporthandbook" href="/how-to-play">Looking for gameplay instructions? <b>How to Play →</b></Link></>:<ReportList tickets={tickets} open={id=>void openTicket(id)} back={()=>go("home")}/>}</div>;
}

function SupportForm({kind,form,setForm,busy,upload,submit,back}:{kind:"bug"|"contact";form:{type:string;category:string;title:string;description:string;reproduction:string;attachment:string};setForm:React.Dispatch<React.SetStateAction<typeof form>>;busy:boolean;upload:(file:File)=>Promise<void>;submit:()=>Promise<void>;back:()=>void}){const bug=kind==="bug",categories=bug?bugCategories:contactCategories;return <div className="supportcenter"><button className="back" onClick={back}>← Back to Help &amp; Support</button><header className="supportformhead"><p className="eyebrow">{bug?"BUG REPORT":"PRIVATE ADMIN CONTACT"}</p><h1>{bug?"Report a Bug":"Contact Admin"}</h1><p>{bug?"Tell us what went wrong. Safe technical details are attached automatically.":"Send a private question or concern to authorized Legacy Equine Admins."}</p></header><section className="supportform panel"><label>{bug?"What’s wrong?":"Subject"}<input maxLength={120} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder={bug?"Short title":"What do you need help with?"}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>{bug?"What happened?":"Message"}<textarea rows={8} maxLength={5000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{bug&&<label>What were you trying to do? <small>Optional reproduction steps or context</small><textarea rows={5} maxLength={3000} value={form.reproduction} onChange={e=>setForm({...form,reproduction:e.target.value})}/></label>}<label>Screenshot <small>Optional · JPG, PNG or WebP · 5 MB maximum</small><input type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{await upload(file)}catch(error){alert(error instanceof Error?error.message:"Screenshot upload failed")}}}/>{form.attachment&&<b className="attachmentready">Screenshot attached ✓</b>}</label><div className="supportprivacy">Captured automatically: current page, time, viewport/device class, browser and production build. Passwords, payment data, cookies and tokens are never collected.</div><button className="primary" disabled={busy||form.title.trim().length<3||form.description.trim().length<10} onClick={()=>void submit()}>{busy?"Submitting…":bug?"Submit Bug Report":"Send to Admin"}</button></section></div>}
function ReportList({tickets,open,back}:{tickets:Ticket[];open:(id:string)=>void;back:()=>void}){return <section className="supportreports"><button className="back" onClick={back}>← Help &amp; Support</button><div><p className="eyebrow">PRIVATE HISTORY</p><h2>My Reports</h2></div><div>{tickets.map(ticket=><button key={ticket.id} onClick={()=>open(ticket.id)} className={ticket.has_update?"updated":""}><span><b>{ticket.ticket_number} · {ticket.title}</b><small>{ticket.category} · {ticket.type==="bug"?"Bug Report":"General Support"}</small></span><span><strong>{statusLabels[ticket.status]??ticket.status}</strong><small>Submitted {new Date(ticket.created_at).toLocaleDateString()} · Updated {new Date(ticket.updated_at).toLocaleDateString()}</small></span></button>)}{!tickets.length&&<p className="panel">You haven&apos;t submitted any Support reports.</p>}</div></section>}
function TicketConversation({ticket,attachmentUrl,reply,setReply,sendReply,busy,back}:{ticket:Ticket;attachmentUrl:string;reply:string;setReply:(x:string)=>void;sendReply:()=>Promise<void>;busy:boolean;back:()=>void}){const closed=["closed","duplicate"].includes(ticket.status);return <div className="supportticket"><button className="back" onClick={back}>← My Reports</button><header><div><p className="eyebrow">{ticket.ticket_number} · {ticket.type==="bug"?"BUG REPORT":"GENERAL SUPPORT"}</p><h1>{ticket.title}</h1><p>{ticket.category} · Submitted {new Date(ticket.created_at).toLocaleString()}</p></div><span data-status={ticket.status}>{statusLabels[ticket.status]??ticket.status}</span></header>{ticket.duplicate_of&&<p className="supportduplicate">Marked duplicate of {ticket.duplicate_of}. Your original report remains preserved.</p>}<section className="ticketoriginal panel"><h2>Your report</h2><p>{ticket.description}</p>{ticket.reproduction&&<><h3>What you were trying to do</h3><p>{ticket.reproduction}</p></>}{attachmentUrl&&<a href={attachmentUrl} target="_blank" rel="noreferrer"><img src={attachmentUrl} alt="Support ticket screenshot"/>View attached screenshot</a>}</section><section className="ticketconversation"><h2>Conversation</h2>{ticket.messages?.map(message=><article className={message.type} key={message.id}><b>{message.type==="admin_reply"?"Legacy Equine Support":message.author}</b><p>{message.body}</p><time>{new Date(message.created_at).toLocaleString()}</time></article>)}{!ticket.messages?.length&&<p className="featurehint">No follow-up messages yet.</p>}</section>{!closed&&<section className="ticketreply panel"><label>Add follow-up information<textarea rows={5} maxLength={3000} value={reply} onChange={e=>setReply(e.target.value)}/></label><button className="primary" disabled={busy||reply.trim().length<2} onClick={()=>void sendReply()}>{busy?"Sending…":"Send Follow-up"}</button></section>}</div>}
