"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";

const supabase=createClient();
type Fund={id:string;name:string;balance:number;lifetime_inflow:number;lifetime_outflow:number};
type Entry={id:string;fund_id:string;amount:number;transaction_type:string;source:string;destination:string;reason:string;internal_note:string|null;related_id:string|null;initiated_by:string|null;batch_id?:string|null;created_at:string};
type Stable={id:string;account_number:number;name:string};type Show={id:string;name:string;run_at:string};
type OwnerFundWorkspace={owner:{stable_id:string;account_number:number;name:string;balance:number};show_fund:Fund;auto_host:{enabled:boolean;daily_enabled:boolean;next_run:string|null;shows_needed:number;combination_count:number;required_show_fund:number;available_show_fund:number;shortfall:number}};

export function TreasuryDashboard(){
 const [funds,setFunds]=useState<Fund[]>([]),[entries,setEntries]=useState<Entry[]>([]),[stables,setStables]=useState<Stable[]>([]),[shows,setShows]=useState<Show[]>([]),[target,setTarget]=useState(""),[show,setShow]=useState(""),[amount,setAmount]=useState(1000),[reason,setReason]=useState("Community award"),[note,setNote]=useState(""),[message,setMessage]=useState("");
 const [type,setType]=useState(""),[ledgerShow,setLedgerShow]=useState(""),[account,setAccount]=useState(""),[direction,setDirection]=useState(""),[date,setDate]=useState("");
 const [ownerFund,setOwnerFund]=useState<OwnerFundWorkspace|null>(null),[fundAmount,setFundAmount]=useState(48000),[fundBusy,setFundBusy]=useState(false);
 const load=useCallback(async()=>{const[{data:f},{data:l},{data:s},{data:sh},{data:of}]=await Promise.all([supabase.from("system_funds").select("*"),supabase.from("system_fund_ledger").select("*").order("created_at",{ascending:false}).limit(500),supabase.rpc("admin_list_stables"),supabase.from("player_shows").select("id,name,run_at").order("run_at",{ascending:false}).limit(500),supabase.rpc("get_owner_show_fund_workspace")]);setFunds((f??[])as Fund[]);setEntries((l??[])as Entry[]);setStables((s??[])as Stable[]);setShows((sh??[])as Show[]);setOwnerFund((of??null)as OwnerFundWorkspace|null);if(!target&&s?.[0])setTarget(s[0].id);if(!show&&sh?.[0])setShow(sh[0].id)},[show,target]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 const run=async(fn:()=>Promise<{error:Error|null}>,ok:string)=>{const{error}=await fn();setMessage(error?.message??ok);if(!error)await load()};
 const visible=useMemo(()=>entries.filter(e=>(!type||e.transaction_type===type)&&(!ledgerShow||e.related_id===ledgerShow)&&(!account||e.initiated_by===account)&&(!direction||(direction==="contribution"?e.amount>0:e.amount<0))&&(!date||e.created_at.slice(0,10)===date)),[entries,type,ledgerShow,account,direction,date]);
 const showFund=funds.find(f=>f.id==="show_fund");
 const fundOwnerShowFund=async()=>{if(!ownerFund||fundAmount<=0)return;const ownerBefore=ownerFund.owner.balance,fundBefore=ownerFund.show_fund.balance,ownerAfter=ownerBefore-fundAmount,fundAfter=fundBefore+fundAmount;if(fundAmount>ownerBefore){setMessage("Owner account has insufficient LED.");return}if(!confirm(`Transfer ${fundAmount.toLocaleString()} LED from your account to the Legacy Equine Show Fund?\n\nOwner Balance Before: ${ownerBefore.toLocaleString()} LED\nOwner Balance After: ${ownerAfter.toLocaleString()} LED\n\nShow Fund Before: ${fundBefore.toLocaleString()} LED\nShow Fund After: ${fundAfter.toLocaleString()} LED`))return;setFundBusy(true);const requestId=crypto.randomUUID();const{data,error}=await supabase.rpc("owner_contribute_to_show_fund",{p_amount:fundAmount,p_request_id:requestId,p_reason:"SHOW_FUND_CONTRIBUTION",p_internal_note:null});setFundBusy(false);if(error)setMessage(error.message);else{setMessage(`${Number(data?.amount??fundAmount).toLocaleString()} LED transferred to the Show Fund.`);await load()}};
 return <>
  <section className="panel treasury"><p className="eyebrow">INSTITUTIONAL ECONOMY</p><h2>Treasury &amp; Show/Payout Fund</h2><p className="panelsub">System funds are permanently separate from personal stable balances. Every movement is ledgered.</p>{message&&<div className="notice">✦ {message}</div>}
   <div className="treasuryfunds">{funds.map(f=><article className="treasuryfund" key={f.id}><p>{f.id==="show_fund"?"Show/Payout Fund":f.name}</p><strong>{f.balance.toLocaleString()} <small>LED available</small></strong><span>Lifetime contributions {f.lifetime_inflow.toLocaleString()} · payouts/refunds {f.lifetime_outflow.toLocaleString()}</span></article>)}</div>
   {showFund&&<div className="fundsummary"><span><small>AVAILABLE BALANCE</small><b>{showFund.balance.toLocaleString()} LED</b></span><span><small>LIFETIME CONTRIBUTIONS</small><b>{showFund.lifetime_inflow.toLocaleString()} LED</b></span><span><small>LIFETIME PAYOUTS / ALLOCATIONS</small><b>{showFund.lifetime_outflow.toLocaleString()} LED</b></span></div>}
   {ownerFund&&<section className="ownershowfund"><div><p className="eyebrow">SHOW FUND</p><h3>Owner funding</h3><p>Transfer real LED from Owner Account #1 into the Legacy Equine Show Fund. This uses the authoritative ledger and does not mint currency.</p></div><div className="ownershowfundstats"><span><small>Current Show Fund Balance</small><b>{ownerFund.show_fund.balance.toLocaleString()} LED</b></span><span><small>Current Owner Account Balance</small><b>{ownerFund.owner.balance.toLocaleString()} LED</b></span><span><small>Auto Host Funding Requirement</small><b>{ownerFund.auto_host.required_show_fund.toLocaleString()} LED</b></span><span><small>Current Shortfall</small><b>{ownerFund.auto_host.shortfall.toLocaleString()} LED</b></span></div><div className="ownerfundtransfer"><label>Amount<input type="number" min={1} step={1} value={fundAmount} onChange={e=>setFundAmount(Number(e.target.value))}/></label><span><small>Source</small><b>Owner Account #{ownerFund.owner.account_number}</b></span><span><small>Destination</small><b>Legacy Equine Show Fund</b></span><button className="primary" disabled={fundBusy||fundAmount<=0||fundAmount>ownerFund.owner.balance} onClick={()=>void fundOwnerShowFund()}>{fundBusy?"Transferring…":`Transfer ${fundAmount.toLocaleString()} LED`}</button></div></section>}
   <div className="treasuryform"><label>Player award recipient<select value={target} onChange={e=>setTarget(e.target.value)}>{stables.map(s=><option value={s.id} key={s.id}>#{s.account_number} · {s.name}</option>)}</select></label><label>Amount<input type="number" min={1} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>Public reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Internal note<input value={note} onChange={e=>setNote(e.target.value)}/></label></div>
   <div className="treasuryactions"><button className="primary" disabled={!target||amount<=0} onClick={()=>run(async()=>{const{error}=await supabase.rpc("treasury_award",{target_stable:target,award_amount:amount,award_reason:reason,award_category:"community_award",internal_note:note||null});return{error}},"Treasury award completed.")}>Award LED</button><button className="secondary" disabled={amount<=0} onClick={()=>run(async()=>{const{error}=await supabase.rpc("treasury_to_show_fund",{transfer_amount:amount,transfer_reason:reason,internal_note:note||null});return{error}},"LED transferred to the Show Fund.")}>Transfer to Show Fund</button><button className="secondary" onClick={()=>run(async()=>{const{error}=await supabase.rpc("reconcile_show_fund_history");return{error}},"Verified historical Show transactions reconciled.")}>Reconcile Verified History</button></div>
   {shows.length>0&&<div className="showfunding"><label>Fund a show<select value={show} onChange={e=>setShow(e.target.value)}>{shows.map(s=><option value={s.id} key={s.id}>{s.name} · {new Date(s.run_at).toLocaleDateString()}</option>)}</select></label><button className="primary" disabled={!show||amount<=0} onClick={()=>run(async()=>{const{error}=await supabase.rpc("show_fund_fund_show",{target_show:show,funding_amount:amount,funding_reason:reason,internal_note:note||null});return{error}},"Show purse funded.")}>Fund Show from Show Fund</button></div>}
  </section>
  <section className="panel treasuryledger"><p className="eyebrow">AUDIT TRAIL</p><h2>Show/Payout Fund Ledger</h2><div className="ledgerfilters"><select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{[...new Set(entries.map(e=>e.transaction_type))].map(x=><option key={x}>{x}</option>)}</select><select value={ledgerShow} onChange={e=>setLedgerShow(e.target.value)}><option value="">All Shows</option>{shows.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={account} onChange={e=>setAccount(e.target.value)}><option value="">All accounts</option>{stables.map(s=><option key={s.id} value={s.id}>#{s.account_number} · {s.name}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><select value={direction} onChange={e=>setDirection(e.target.value)}><option value="">All directions</option><option value="contribution">Contributions</option><option value="outflow">Payouts / Refunds</option></select></div><div className="fundledgerlist">{visible.map(e=><article key={e.id}><span><b className={e.amount>0?"credit":"debit"}>{e.amount>0?"+":""}{e.amount.toLocaleString()} LED</b><small>{new Date(e.created_at).toLocaleString()} · {e.transaction_type.replaceAll("_"," ")}</small></span><span><b>{e.source} → {e.destination}</b><small>{e.reason}{e.batch_id?` · Batch ${e.batch_id.slice(0,8)}`:""}{e.internal_note?` · Internal: ${e.internal_note}`:""}</small></span></article>)}</div>{!visible.length&&<p className="panelsub">No transactions match these filters.</p>}</section>
 </>;
}
