"use client";
import{useCallback,useEffect,useState}from"react";
import{createClient}from"@/lib/supabase/client";
const supabase=createClient();
type Fund={id:string;name:string;balance:number;lifetime_inflow:number;lifetime_outflow:number};
type Entry={id:string;fund_id:string;amount:number;transaction_type:string;source:string;destination:string;reason:string;internal_note:string|null;created_at:string};
type Stable={id:string;account_number:number;name:string};
type Show={id:string;name:string;run_at:string};
export function TreasuryDashboard(){const[funds,setFunds]=useState<Fund[]>([]),[entries,setEntries]=useState<Entry[]>([]),[stables,setStables]=useState<Stable[]>([]),[shows,setShows]=useState<Show[]>([]),[target,setTarget]=useState(""),[show,setShow]=useState(""),[amount,setAmount]=useState(1000),[reason,setReason]=useState("Community award"),[note,setNote]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const[{data:f},{data:l},{data:s},{data:sh}]=await Promise.all([supabase.from("system_funds").select("*"),supabase.from("system_fund_ledger").select("*").order("created_at",{ascending:false}).limit(100),supabase.rpc("admin_list_stables"),supabase.from("player_shows").select("id,name,run_at").eq("status","open").order("run_at")]);setFunds((f??[])as Fund[]);setEntries((l??[])as Entry[]);setStables((s??[])as Stable[]);setShows((sh??[])as Show[]);if(!target&&s?.[0])setTarget(s[0].id);if(!show&&sh?.[0])setShow(sh[0].id)},[show,target]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 const run=async(fn:()=>Promise<{error:Error|null}>,ok:string)=>{const{error}=await fn();setMessage(error?.message??ok);if(!error)await load()};
 return <><section className="panel settingsform"><p className="eyebrow">INSTITUTIONAL ECONOMY</p><h2>Treasury & Show Fund</h2><p className="panelsub">System funds are permanently separate from personal stable balances. Every movement is ledgered.</p>{message&&<div className="notice">✦ {message}</div>}<div className="professiongrid">{funds.map(f=><article className="featurecard" key={f.id}><p className="eyebrow">{f.name}</p><h2>{f.balance.toLocaleString()} LED</h2><small>Lifetime in {f.lifetime_inflow.toLocaleString()} · out {f.lifetime_outflow.toLocaleString()}</small></article>)}</div><div className="adminformgrid"><label>Player award recipient<select value={target} onChange={e=>setTarget(e.target.value)}>{stables.map(s=><option value={s.id} key={s.id}>#{s.account_number} · {s.name}</option>)}</select></label><label>Amount<input type="number" min={1} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>Public reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Internal note<input value={note} onChange={e=>setNote(e.target.value)}/></label></div><button disabled={!target||amount<=0} onClick={()=>run(async()=>{const{error}=await supabase.rpc("treasury_award",{target_stable:target,award_amount:amount,award_reason:reason,award_category:"community_award",internal_note:note||null});return{error}},"Treasury award completed.")}>Award LED</button><button disabled={amount<=0} onClick={()=>run(async()=>{const{error}=await supabase.rpc("treasury_to_show_fund",{transfer_amount:amount,transfer_reason:reason,internal_note:note||null});return{error}},"LED transferred to the Show Fund.")}>Transfer to Show Fund</button>{shows.length>0&&<><label>Fund an open show<select value={show} onChange={e=>setShow(e.target.value)}>{shows.map(s=><option value={s.id} key={s.id}>{s.name} · {new Date(s.run_at).toLocaleDateString()}</option>)}</select></label><button disabled={!show||amount<=0} onClick={()=>run(async()=>{const{error}=await supabase.rpc("show_fund_fund_show",{target_show:show,funding_amount:amount,funding_reason:reason,internal_note:note||null});return{error}},"Show purse funded.")}>Fund Show from Show Fund</button></>}</section><section className="panel"><p className="eyebrow">AUDIT TRAIL</p><h2>System Fund Ledger</h2><div className="servicelist">{entries.map(e=><article key={e.id}><span><b>{e.amount>0?"+":""}{e.amount.toLocaleString()} LED · {e.fund_id.replace("_"," ")}</b><small>{new Date(e.created_at).toLocaleString()} · {e.transaction_type}</small></span><span><b>{e.source} → {e.destination}</b><small>{e.reason}{e.internal_note?` · Internal: ${e.internal_note}`:""}</small></span></article>)}</div></section></>}
