"use client";
import {useEffect,useMemo,useState} from "react";
import {NavIcon} from "@/app/nav-icons";
import "@/app/universal-game-navigation.css";
type Branch="world"|"compete"|"professions"|"community";
type Item={label:string;href:string;icon?:Parameters<typeof NavIcon>[0]["name"]};
const branches:Record<Branch,{label:string;icon:Parameters<typeof NavIcon>[0]["name"];items:Item[]}>= {
 world:{label:"World",icon:"store",items:[{label:"LE Store",href:"/store/foundation-horses",icon:"store"},{label:"Marketplace",href:"/marketplace",icon:"sale-tag"},{label:"Bank",href:"/bank",icon:"coin"},{label:"Sanctuary",href:"/sanctuary",icon:"heart"}]},
 compete:{label:"Compete",icon:"trophy",items:[{label:"Shows",href:"/shows",icon:"trophy"},{label:"Training",href:"/training",icon:"round-pen"}]},
 professions:{label:"Professions",icon:"toolbox",items:[{label:"Careers",href:"/professions",icon:"toolbox"},{label:"My Businesses",href:"/professions/businesses",icon:"store"},{label:"Find a Professional",href:"/professions?section=market#professional-market",icon:"sale-tag"}]},
 community:{label:"Community",icon:"bulletin",items:[{label:"Players & Stables",href:"/community",icon:"barn"},{label:"Chat Rooms",href:"/community/chat",icon:"bulletin"}]},
};
function activeBranch(path:string):Branch|null{if(/^\/(store|marketplace|bank|sanctuary)/.test(path))return"world";if(/^\/(shows|training)/.test(path))return"compete";if(path.startsWith("/professions"))return"professions";if(path.startsWith("/community"))return"community";return null}
function itemActive(item:Item,path:string){if(path===item.href)return true;const itemPath=item.href.split(/[?#]/)[0];if(item.href==="/professions"||item.href==="/community"||item.href==="/profile")return path===item.href;return path===itemPath||path.startsWith(`${itemPath}/`)}
function NavItem({item,path,onNavigate}:{item:Item;path:string;onNavigate:(href:string)=>void}){return <button className={itemActive(item,path)?"active":""} onClick={()=>onNavigate(item.href)}>{item.icon&&<NavIcon name={item.icon}/>}<span>{item.label}</span></button>}
export function MobileGameNavigation({path,newsNew,supportUpdates,isAdmin,onNavigate,onClose,onSignOut}:{path:string;newsNew:number;supportUpdates:number;isAdmin:boolean;onNavigate:(href:string)=>void;onClose:()=>void;onSignOut:()=>void}){const[current,setCurrent]=useState<Branch|null>(null),branch=current?branches[current]:null;return <><div className="mobile-menu-title"><span>LE</span><b>Legacy Equine™</b><button aria-label="Close navigation menu" onClick={onClose}>×</button></div>{branch?<><button className="nav-back" onClick={()=>setCurrent(null)}>‹ Back</button><p>{branch.label.toUpperCase()}</p><nav aria-label={`${branch.label} destinations`}>{branch.items.map(item=><NavItem key={item.href} item={item} path={path} onNavigate={onNavigate}/>)}</nav></>:<><p>GAME</p><nav aria-label="Game areas"><NavItem item={{label:newsNew?`News · ${newsNew} New`:"News",href:"/home",icon:"news"}} path={path} onNavigate={onNavigate}/><NavItem item={{label:"My Stable",href:"/stable/horses",icon:"barn"}} path={path} onNavigate={onNavigate}/>{(Object.keys(branches)as Branch[]).map(id=><button className={activeBranch(path)===id?"active":""} key={id} onClick={()=>setCurrent(id)}><NavIcon name={branches[id].icon}/><span>{branches[id].label}</span><i aria-hidden="true">›</i></button>)}</nav><p>ACCOUNT</p><nav aria-label="Account destinations"><NavItem item={{label:"My Profile",href:"/profile"}} path={path} onNavigate={onNavigate}/><NavItem item={{label:"Settings",href:"/profile/settings"}} path={path} onNavigate={onNavigate}/><NavItem item={{label:"How to Play",href:"/how-to-play",icon:"news"}} path={path} onNavigate={onNavigate}/><NavItem item={{label:supportUpdates?`Help & Support · ${supportUpdates} Update${supportUpdates===1?"":"s"}`:"Help & Support",href:"/support",icon:"bulletin"}} path={path} onNavigate={onNavigate}/></nav>{isAdmin&&<><p>OWNER</p><nav><NavItem item={{label:"Admin Control Center",href:"/admin"}} path={path} onNavigate={onNavigate}/></nav></>}<button className="mobile-signout" onClick={onSignOut}>Sign Out</button></>}</>}
export function DesktopGameNavigation({path,newsNew,onNavigate}:{path:string;newsNew:number;onNavigate:(href:string)=>void}){const routeBranch=useMemo(()=>activeBranch(path),[path]),[open,setOpen]=useState<Branch|null>(routeBranch);useEffect(()=>{if(routeBranch)setOpen(routeBranch)},[routeBranch]);return <nav className="game-nav universal-desktop-nav" aria-label="Game areas"><NavItem item={{label:newsNew?`News · ${newsNew} New`:"News",href:"/home",icon:"news"}} path={path} onNavigate={onNavigate}/><NavItem item={{label:"My Stable",href:"/stable/horses",icon:"barn"}} path={path} onNavigate={onNavigate}/>{(Object.keys(branches)as Branch[]).map(id=>{const branch=branches[id],expanded=open===id;return <div className="desktop-nav-branch" key={id}><button className={routeBranch===id?"active":""} aria-expanded={expanded} onClick={()=>setOpen(expanded?null:id)}><NavIcon name={branch.icon}/><span>{branch.label}</span><i aria-hidden="true">{expanded?"⌄":"›"}</i></button>{expanded&&<div className="desktop-nav-children">{branch.items.map(item=><NavItem key={item.href} item={item} path={path} onNavigate={onNavigate}/>)}</div>}</div>})}</nav>}
