"use client";
import{useCallback,useEffect,useMemo,useState}from"react";
import{createClient}from"@/lib/supabase/client";
const supabase=createClient();
type Row={body_template_key:string;breed:string;sex:string;category:string;trait_key:string;display_name:string;anatomical_position:string|null;variant:number;status:"missing"|"uploaded"|"review"|"approved"|"production";asset_key:string|null;notes:string};
const labels:Record<string,string>={clean_body:"Clean Body",base_coat:"Base Coat",gray_stage:"Gray Progression",dun:"Dun",cream:"Cream Dilution",roan:"Roan",silver:"Silver",champagne:"Champagne",pearl:"Pearl",dapple:"Dapple Effect",pinto_pattern:"Pinto / White Pattern",leopard_complex:"Leopard Complex",visual_detail:"Phenotype Detail",face_marking:"Face Marking",leg_marking:"Leg Marking",mane:"Mane",tail:"Tail"};
export function VisualAssetRequirements({notify}:{notify:(message:string)=>void}){const[rows,setRows]=useState<Row[]>([]),[master,setMaster]=useState("all"),[category,setCategory]=useState("all"),[status,setStatus]=useState("all"),[query,setQuery]=useState("");
 const load=useCallback(async()=>{const{data,error}=await supabase.rpc("admin_visual_asset_requirements");if(error)notify(error.message);else setRows((data??[])as Row[])},[notify]);useEffect(()=>{void load()},[load]);
 const masters=useMemo(()=>Array.from(new Set(rows.map(r=>r.body_template_key))),[rows]),categories=useMemo(()=>Array.from(new Set(rows.map(r=>r.category))),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>(master==="all"||r.body_template_key===master)&&(category==="all"||r.category===category)&&(status==="all"||r.status===status)&&(!query||`${r.display_name} ${r.trait_key} ${r.anatomical_position??""}`.toLowerCase().includes(query.toLowerCase()))),[rows,master,category,status,query]);
 const counts=useMemo(()=>Object.fromEntries(["missing","uploaded","review","approved","production"].map(s=>[s,rows.filter(r=>r.status===s).length])),[rows]);
 return <section className="panel assetmatrix"><p className="eyebrow">REFERENCE-LED · NO GENERATED ARTWORK</p><h2>Visual Asset Requirements Matrix</h2><p className="panelsub">Every row is an independent transparent asset registered to one exact approved body master. Missing assets remain fallback-only and cannot enter production.</p>
  <div className="matrixsummary">{Object.entries(counts).map(([key,value])=><span className={`status-${key}`} key={key}><b>{value}</b>{key}</span>)}</div>
  <div className="matrixfilters"><select aria-label="Body master" value={master} onChange={e=>setMaster(e.target.value)}><option value="all">All body masters</option>{masters.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Asset category" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{categories.map(x=><option key={x} value={x}>{labels[x]??x}</option>)}</select><select aria-label="Requirement status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{["missing","uploaded","review","approved","production"].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Search asset requirements" placeholder="Search marking, coat, modifier…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
  <p className="matrixorientation"><b>Anatomical orientation:</b> LF = horse’s left front · RF = horse’s right front · LH = horse’s left hind · RH = horse’s right hind. These labels never derive from screen position.</p>
  <div className="matrixtable" role="table" aria-label="Visual asset requirements"><div className="matrixhead" role="row"><b>Body Master</b><b>Category</b><b>Required Asset</b><b>Limb</b><b>Status</b></div>{filtered.map((r,i)=><div role="row" key={`${r.body_template_key}-${r.category}-${r.trait_key}-${r.anatomical_position}-${i}`}><span><b>{r.body_template_key}</b><small>{r.breed} · {r.sex}</small></span><span>{labels[r.category]??r.category}</span><span><b>{r.display_name}</b><small>{r.asset_key??"No asset uploaded"}</small></span><span>{r.anatomical_position??"—"}</span><span className={`matrixstatus status-${r.status}`}>{r.status}</span></div>)}</div>{!filtered.length&&<p className="featurehint">No requirements match these filters.</p>}
 </section>}
