export const GAME = {
  currencyName: "LE Dollars",
  startingBalance: 4000,
  foundationPrice: 1000,
  baseStableCapacity: 5,
  stallPackage: { quantity: 5, priceUsdCents: 499 },
  foundationBreeds: ["Thoroughbred", "Arabian", "Quarter Horse", "American Paint Horse", "Hanoverian", "Appaloosa", "Morgan", "Rocky Mountain Horse", "Tennessee Walking Horse"],
  store: { inventorySize: 6, minimumSize: 5, maximumSize: 8, rotationMinutes: 60 },
  colors: ["Bay", "Chestnut", "Black", "Gray", "Palomino"],
  stats: ["Agility", "Speed", "Endurance", "Temperament", "Strength", "Intelligence", "Conformation"],
  foundation: { minimum: 10, maximum: 15, outlierChance: 0.06, outlierMinimum: 7, outlierMaximum: 18 },
  breedingInheritanceVariation: { minimum: -6, maximum: 6 },
  mareCooldownDays: 10,
  training: { gain: 1, cooldownHours: 20 },
  age: { gameDaysPerRealDay: 30, breedingMinimumYears: 3, breedingMaximumYears: 25, retirementYears: 30 },
  defaultStudFee: 100,
} as const;
