import {describe,expect,it} from "vitest";
import {buildHorseImagePrompt,formatHandHeight,sexAnatomyConstraint,type VisualPhenotype} from "./horse-visual";
const visual:VisualPhenotype={breed:"Quarter Horse",sex:"Mare",age_years:2,color:"Palomino",body:"compact stock-horse build",height_range:"typically 14.2–16 hands",height_hands:15.3,movement:"quick balanced movement",temperament:"steady and willing",breed_constraints:"avoid exaggerated halter musculature",coat:"rich golden cream",mane_tail:"light cream",pattern:"solid",face_marking:"blaze",left_front:"sock",right_front:"none",left_hind:"stocking",right_hind:"sock",pose:"standing square",view:"side profile",background:"neutral studio"};
describe("horse visual prompt",()=>{
 it("uses calculated phenotype and persistent markings without raw genetics",()=>{const prompt=buildHorseImagePrompt(visual);expect(prompt).toContain("MUST MATCH EXACTLY: Palomino");expect(prompt).toContain("left front sock");expect(prompt).toContain("right front none");expect(prompt).toContain("compact stock-horse build");expect(prompt).toContain("15.3h at the withers");expect(prompt).toContain("four complete legs");expect(prompt).toContain("avoid exaggerated halter musculature");expect(prompt).toContain("transparent alpha background");expect(prompt).toContain("female mare");expect(prompt).toContain("OMIT ALL VISIBLE GENITALIA");expect(prompt).not.toContain("Extension")});
 it("uses base-four equine hand notation",()=>{expect(formatHandHeight(14)).toBe("14h");expect(formatHandHeight(14.3)).toBe("14.3h");expect(formatHandHeight(14.8)).toBe("16h")});
 it("uses body type while omitting genitalia",()=>{expect(sexAnatomyConstraint("Mare")).toContain("Omit all visible genitalia");expect(sexAnatomyConstraint("Stallion")).toContain("neck, and muscling");expect(sexAnatomyConstraint("Stallion")).toContain("Omit all visible genitalia")});
 it("forbids every kind of image mark or pseudo-writing",()=>{const prompt=buildHorseImagePrompt(visual);for(const phrase of ["NO SIGNATURE","NO WATERMARK","NO ARTIST MARK","NO TEXT","NO PSEUDO-TEXT","NO LETTERS","NO NUMBERS","NO LOGO","NO SYMBOLS","NO WRITING"])expect(prompt).toContain(phrase)});
});
