import { describe, expect, it } from "vitest";
import { GAME } from "./config";
import { seededRandom } from "./random";
import { canBreed, createFoal, createFoundationHorse, developHorse, effectiveStats, gameAge, permanentDevelopment } from "./simulation";
describe("simulation", () => {
  it("uses exactly seven data-driven stats",()=>expect(GAME.stats).toEqual(["Agility","Speed","Endurance","Temperament","Strength","Intelligence","Conformation"]));
  it("generates deterministic two-year-old foundation horses in configured bounds", () => { const now=new Date("2026-01-01");const a=createFoundationHorse(seededRandom(42),now); const b=createFoundationHorse(seededRandom(42),now); expect(a.stats).toEqual(b.stats);expect(gameAge(a,now)).toBeCloseTo(2,5);Object.values(a.stats).forEach(v=>expect(v).toBeGreaterThanOrEqual(GAME.foundation.outlierMinimum)); });
  it("inherits birth stats from parental developed stats with bounded variance", () => { const s=developHorse(createFoundationHorse(seededRandom(1)),{Speed:200}); const d=developHorse({...createFoundationHorse(seededRandom(2)),sex:"Mare" as const},{Speed:180}); const f=createFoal({...s,sex:"Stallion"},d,seededRandom(3)); GAME.stats.forEach(k=>expect(Math.abs(f.birthStats[k]-Math.round((s.stats[k]+d.stats[k])/2))).toBeLessThanOrEqual(GAME.breedingInheritanceVariation.maximum));expect(f.stats).toEqual(f.birthStats); });
  it("keeps birth stats immutable while permanent development grows",()=>{const born=createFoundationHorse(seededRandom(8)),birth={...born.birthStats},trained=developHorse(born,{Speed:500});expect(trained.birthStats).toEqual(birth);expect(permanentDevelopment(trained).Speed).toBe(500);expect(trained.stats.Speed).toBeGreaterThan(400)});
  it("uses tack and temporary services only in effective values",()=>{const h=createFoundationHorse(seededRandom(9));h.tackBonuses.Speed=5;const developed=h.stats.Speed;expect(effectiveStats(h,{Speed:3}).Speed).toBe(developed+8);expect(h.stats.Speed).toBe(developed);expect(h.birthStats.Speed).toBe(developed)});
  it("never inherits tack or temporary effective bonuses",()=>{const sire=developHorse({...createFoundationHorse(seededRandom(10)),sex:"Stallion" as const},{Speed:500}),dam=developHorse({...createFoundationHorse(seededRandom(11)),sex:"Mare" as const},{Speed:500});sire.tackBonuses.Speed=10000;const foal=createFoal(sire,dam,seededRandom(12));expect(foal.birthStats.Speed).toBeGreaterThan(400);expect(foal.birthStats.Speed).toBeLessThan(600)});
  it("calculates age from timestamps", () => { const h=createFoundationHorse(seededRandom(4),new Date("2026-01-01")); expect(gameAge(h,new Date("2026-01-02"))).toBeGreaterThan(gameAge(h,new Date("2026-01-01"))); });
  it("enforces mare cooldown", () => { const h={...createFoundationHorse(seededRandom(5)),sex:"Mare" as const,lastBredAt:new Date().toISOString()}; expect(canBreed(h)).toBe(false); });
});
