create table public.handbook_categories(
 id text primary key,name text not null unique,description text not null default'',sort_order integer not null default 0,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.handbook_articles(
 id uuid primary key default gen_random_uuid(),slug text not null unique,category_id text not null references public.handbook_categories(id),title text not null,summary text not null default'',body text not null default'',keywords text[]not null default'{}',sort_order integer not null default 0,featured boolean not null default false,status text not null default'draft'check(status in('draft','published','unpublished','archived')),config_key text,created_by uuid references public.stables(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),published_at timestamptz
);
create index handbook_article_feed_idx on public.handbook_articles(status,category_id,sort_order);
alter table public.handbook_categories enable row level security;alter table public.handbook_articles enable row level security;
create policy "handbook categories readable"on public.handbook_categories for select to authenticated using(active);
create policy "published handbook readable"on public.handbook_articles for select to authenticated using(status='published');

insert into public.handbook_categories(id,name,description,sort_order)values
('getting-started','Getting Started','Your first steps in Legacy Equine.',10),('your-stable','Your Stable','Manage your horses and Stable spaces.',20),('horses','Horses','Horse profiles, ownership, and records.',30),('horse-development-stats','Horse Development & Stats','Permanent stats, Effective Stats, and development.',40),('feeding','Feeding','Hay, Grain, Feed Storage, and daily care.',50),('tack-equipment','Tack & Equipment','Equipment slots and Effective Stat bonuses.',60),('training','Training','Develop horses through Training.',70),('showing','Showing','Show eligibility, entries, rewards, CP, and AP.',80),('breeding','Breeding','Breeding eligibility, genetics, and foals.',90),('marketplace','Marketplace','Buying and selling horses.',100),('professions','Professions','Careers, certifications, services, and businesses.',110),('world-economy','World & Economy','LED, transactions, and the LE world.',120),('community','Community','Players, Stables, Chat, and public spaces.',130),('account-levels-progression','Account Levels & Progression','Account XP, Levels, and capability unlocks.',140),('faq','FAQ','Quick answers to common questions.',150)
on conflict(id)do update set name=excluded.name,description=excluded.description,sort_order=excluded.sort_order;

insert into public.handbook_articles(slug,category_id,title,summary,body,keywords,sort_order,featured,status,config_key,published_at)values
('getting-started','getting-started','Getting Started','The normal first-player loop, from creating a Stable to building a Legacy.',E'# Welcome to Legacy Equine\n\nCreate your account, establish your Stable, and visit the LE Store for your first horse. Care for and develop your horses, train them, enter eligible Shows, earn rewards, then breed, trade, and grow your Stable.\n\n## Your first steps\n\n1. Create your Stable.\n2. Visit the LE Store and choose your first horse.\n3. Learn the horse’s permanent stats, development options, Feed, and Tack.\n4. Train and enter eligible Shows.\n5. Use rewards and experience to build your bloodlines and Stable.','{new player,first horse,stable,store}',10,true,'published',null,now()),
('your-stable','your-stable','Your Stable','Understand My Stable, the Tack Room, Feed Room, and your public Stable.',E'# Your Stable\n\nMy Stable is your operational home. My Horses manages owned horses, the Tack Room manages equipment, and the Feed Room manages Hay and Grain. Your Public Stable Profile is the presentation other players visit.','{stable,my horses,tack room,feed room}',10,false,'published',null,now()),
('horses','horses','Horses','Read a horse profile and understand ownership and permanent records.',E'# Horses\n\nEach horse has one authoritative profile containing ownership, pedigree, permanent stats, Effective Stats, Show records, and development history. Ownership transfers move the horse and its horse-specific records together.','{horse,profile,ownership,pedigree}',10,false,'published',null,now()),
('horse-development-stats','horse-development-stats','Horse Development & Stats','Permanent stats, temporary Effective Stats, and development.',E'# Horse Development & Stats\n\nThe seven permanent stats are Agility, Speed, Endurance, Temperament, Strength, Intelligence, and Conformation. Development and allocated AP permanently affect the horse. Tack contributes only to Effective Stats and never changes genetics, breeding values, or inherited stats.','{stats,effective stats,development,permanent}',10,false,'published',null,now()),
('feeding','feeding','Feeding','Current Hay and Grain rules, daily eligibility, and Feed Storage.',E'# Feeding\n\nHay and Grain use the authoritative LE-day feeding rules. The Feed Room shows only horses currently eligible for the selected feed type. A bulk feeding revalidates every horse and inventory unit atomically. Feed inventory is kept in Stable Feed Storage; over-capacity inventory is preserved, while new acquisition is restricted until capacity is available.','{feed,hay,grain,feed room,storage,daily}',10,false,'published','feeding',now()),
('tack-equipment','tack-equipment','Tack & Equipment','Equip Tack and understand Effective Stat bonuses.',E'# Tack & Equipment\n\nA horse may equip one Bridle, one Saddle, one Saddle Pad, and one Leg Protection item. Equipped Tack applies the item’s authoritative Effective Stat bonuses only. It does not change permanent or breeding stats.','{tack,bridle,saddle,pad,boots,effective stats}',10,false,'published',null,now()),
('training','training','Training','Use Training to develop eligible horses.',E'# Training\n\nTraining uses the current horse eligibility, cooldown, and development rules shown in the Training workspace. Professional Trainer services use the same authoritative Training restrictions.','{training,trainer,cooldown,development}',10,false,'published',null,now()),
('showing','showing','Showing','Show eligibility, Career Points, rewards, and horse-specific AP.',E'# Showing\n\nEnter horses in Shows for which they are eligible. Show results award configured prizes and career rewards.\n\n## Career Points\n\nCareer Points record a horse’s competitive accomplishments. The live Show Level basis and thresholds are displayed below from the authoritative Show configuration.\n\n## Effective Stats\n\nEquipment bonuses affect competition performance where configured, but do not alter a horse’s seven permanent stats.','{show,shows,tier,level,career points,cp,entries}',10,true,'published','showing',now()),
('allocatable-points','showing','Allocatable Points (AP)','Horse-specific permanent development earned through Show placements.',E'# Allocatable Points (AP)\n\nAP belongs exclusively to the individual horse that earned it. AP cannot be transferred, combined between horses, gifted, sold separately, or kept in a Stable-wide pool.\n\nThe current placement awards are shown below from Show configuration. Owners may allocate only that horse’s available AP into its seven permanent stats. Allocation is permanent, has no normal AP/stat ceiling, and remains with the horse through a sale or transfer. AP-developed permanent stats contribute to any gameplay system based on permanent stats.','{ap,allocatable points,win,place,show,permanent stats}',20,true,'published','ap',now()),
('breeding','breeding','Breeding','Breeding eligibility, genetic warnings, and permanent foal records.',E'# Breeding\n\nBreeding uses the authoritative age, sex, cooldown, fertility, and genetics rules shown in the horse profile. Genetic previews communicate configured risks. A foal receives its own permanent identity, pedigree, genetics, and birth records.','{breed,breeding,foal,genetics,pedigree}',10,false,'published',null,now()),
('marketplace','marketplace','Marketplace','List, buy, and transfer horses safely.',E'# Marketplace\n\nMarketplace listings use authoritative ownership and pricing records. A completed purchase transfers the horse and its horse-specific history to the buyer in one server transaction.','{market,marketplace,buy,sell,listing}',10,false,'published',null,now()),
('professions','professions','Professions','Enroll, study, certify, serve clients, advance, and run a business.',E'# Professions\n\nA normal career follows Study, Certification Test, certificate, required Rates, legitimate client Services, and Advancement. Levels progress Basic, Proficient, Advanced, then Professional. Certified providers save per-service rates that publish authorized services to Find a Professional and their public business storefront. Only legitimate completed services count toward normal advancement.','{profession,career,study,test,certificate,rates,services,business}',10,true,'published',null,now()),
('world-economy','world-economy','World & Economy','Understand LED and authoritative game transactions.',E'# World & Economy\n\nLED is Legacy Equine game currency. Purchases, fees, prizes, and player-to-player service payments use server-authoritative transactions and ledger records. LED is not cashable or redeemable for real money.','{led,economy,bank,ledger,currency}',10,false,'published',null,now()),
('community','community','Community','Discover players and Stables and use public community spaces.',E'# Community\n\nPlayers & Stables helps you discover active public accounts. Public player and Stable profiles show intentionally public information only. Community Chat and public links never expose private account settings or security information.','{community,players,stables,chat,public profile}',10,false,'published',null,now()),
('account-levels-progression','account-levels-progression','Account Levels & Progression','Account XP, Levels, and capability unlocks.',E'# Account Levels & Progression\n\nAccount XP advances your Account Level and unlocks configured capabilities. Permanent gameplay records and inventory are not deleted when a temporary capacity entitlement ends; over-capacity rules restrict new use safely.','{account level,xp,progression,unlock}',10,false,'published',null,now()),
('faq','faq','Frequently Asked Questions','Quick answers and links to deeper Handbook topics.',E'# FAQ\n\n## Does Tack change breeding stats?\n\nNo. Tack changes Effective Stats only.\n\n## Can AP move between horses?\n\nNo. AP belongs permanently to the horse that earned it.\n\n## Where do Store purchases go?\n\nFeed goes to the Feed Room and Tack goes to the Tack Room.','{faq,help,questions}',10,false,'published',null,now())
on conflict(slug)do nothing;

create or replace function public.handbook_safe_text(value text,max_length integer)returns text language sql immutable as $$select left(regexp_replace(coalesce(value,''),'<[^>]*>','','g'),max_length)$$;
create or replace function public.can_manage_handbook()returns boolean language sql stable security definer set search_path=public as $$select is_owner_account()or has_admin_permission('admin.handbook.manage')$$;
create or replace function public.handbook_game_config(p_key text)returns jsonb language plpgsql stable security definer set search_path=public as $$declare result jsonb:='{}';begin
 if p_key='showing'then select jsonb_build_object('basis','career_points','tiers',coalesce(jsonb_agg(jsonb_build_object('name',name,'minimum',minimum_points,'maximum',maximum_points)order by sort_order),'[]'::jsonb))into result from show_tiers where active;
 elsif p_key='ap'then select jsonb_build_object('first',first_place,'second',second_place,'third',third_place)into result from show_ap_config where id=true;
 elsif p_key='feeding'then select jsonb_build_object('hay_per_horse_per_day',1,'grain_per_horse_per_day',1,'base_storage',base_storage,'storage_per_five_levels',storage_per_five_levels,'subscriber_bonus',subscriber_storage_bonus)into result from feed_system_config where id=true;
 end if;return coalesce(result,'{}'::jsonb);end$$;
create or replace function public.get_handbook(p_search text default'',p_category text default null)returns jsonb language sql stable security definer set search_path=public as $$
 select jsonb_build_object('categories',coalesce((select jsonb_agg(to_jsonb(c)order by c.sort_order)from handbook_categories c where c.active),'[]'::jsonb),'articles',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'slug',a.slug,'category_id',a.category_id,'title',a.title,'summary',a.summary,'featured',a.featured,'sort_order',a.sort_order)order by a.featured desc,a.sort_order,a.title)from handbook_articles a where a.status='published'and(p_category is null or a.category_id=p_category)and(coalesce(trim(p_search),'')=''or a.title ilike'%'||p_search||'%'or a.summary ilike'%'||p_search||'%'or a.body ilike'%'||p_search||'%'or array_to_string(a.keywords,' ')ilike'%'||p_search||'%')),'[]'::jsonb))
$$;
create or replace function public.get_handbook_article(p_slug text)returns jsonb language sql stable security definer set search_path=public as $$select jsonb_build_object('id',a.id,'slug',a.slug,'category_id',a.category_id,'category',c.name,'title',a.title,'summary',a.summary,'body',a.body,'featured',a.featured,'config',handbook_game_config(a.config_key))from handbook_articles a join handbook_categories c on c.id=a.category_id where a.slug=p_slug and a.status='published'$$;
create or replace function public.admin_handbook_workspace()returns jsonb language plpgsql stable security definer set search_path=public as $$begin if not(can_manage_handbook()or has_admin_permission('admin.handbook.view'))then raise exception'Handbook administration permission required';end if;return jsonb_build_object('categories',coalesce((select jsonb_agg(to_jsonb(c)order by c.sort_order)from handbook_categories c),'[]'::jsonb),'articles',coalesce((select jsonb_agg(to_jsonb(a)order by a.updated_at desc)from handbook_articles a),'[]'::jsonb));end$$;
create or replace function public.admin_save_handbook_article(p_id uuid,p_slug text,p_category text,p_title text,p_summary text,p_body text,p_keywords text[],p_sort integer,p_featured boolean,p_status text,p_config_key text)returns uuid language plpgsql security definer set search_path=public as $$declare target uuid:=coalesce(p_id,gen_random_uuid());clean_slug text:=lower(regexp_replace(coalesce(p_slug,''),'[^a-zA-Z0-9-]+','-','g'));begin if not can_manage_handbook()then raise exception'Handbook management permission required';end if;if p_status not in('draft','published','unpublished','archived')then raise exception'Invalid article status';end if;if not exists(select 1 from handbook_categories where id=p_category)then raise exception'Choose a Handbook category';end if;if length(trim(p_title))<3 or length(clean_slug)<2 then raise exception'Title and slug are required';end if;
 insert into handbook_articles(id,slug,category_id,title,summary,body,keywords,sort_order,featured,status,config_key,created_by,published_at)values(target,clean_slug,p_category,handbook_safe_text(p_title,140),handbook_safe_text(p_summary,400),handbook_safe_text(p_body,20000),coalesce(p_keywords,'{}'),greatest(p_sort,0),p_featured,p_status,nullif(p_config_key,''),auth.uid(),case when p_status='published'then now()end)on conflict(id)do update set slug=excluded.slug,category_id=excluded.category_id,title=excluded.title,summary=excluded.summary,body=excluded.body,keywords=excluded.keywords,sort_order=excluded.sort_order,featured=excluded.featured,status=excluded.status,config_key=excluded.config_key,published_at=case when excluded.status='published'then coalesce(handbook_articles.published_at,now())else handbook_articles.published_at end,updated_at=now();return target;end$$;
create or replace function public.admin_save_handbook_category(p_id text,p_name text,p_description text,p_sort integer,p_active boolean)returns void language plpgsql security definer set search_path=public as $$begin if not can_manage_handbook()then raise exception'Handbook management permission required';end if;insert into handbook_categories(id,name,description,sort_order,active)values(lower(regexp_replace(p_id,'[^a-zA-Z0-9-]+','-','g')),handbook_safe_text(p_name,80),handbook_safe_text(p_description,300),greatest(p_sort,0),p_active)on conflict(id)do update set name=excluded.name,description=excluded.description,sort_order=excluded.sort_order,active=excluded.active,updated_at=now();end$$;
revoke all on function public.get_handbook(text,text),public.get_handbook_article(text),public.admin_handbook_workspace(),public.admin_save_handbook_article(uuid,text,text,text,text,text,text[],integer,boolean,text,text),public.admin_save_handbook_category(text,text,text,integer,boolean)from public;
grant execute on function public.get_handbook(text,text),public.get_handbook_article(text),public.admin_handbook_workspace(),public.admin_save_handbook_article(uuid,text,text,text,text,text,text[],integer,boolean,text,text),public.admin_save_handbook_category(text,text,text,integer,boolean)to authenticated;
