create table public.news_posts(
 id uuid primary key default gen_random_uuid(),title text not null,body text not null default'',summary text not null default'',
 category text not null check(category in('official','updates','shows','contests','community')),
 author_id uuid references public.stables(id),author_source text not null default'Legacy Equine',image_url text,
 destination_url text,pinned boolean not null default false,status text not null default'draft'check(status in('draft','published','unpublished')),
 publish_at timestamptz,expires_at timestamptz,source_type text not null default'editorial',source_key text,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),published_at timestamptz,
 unique(source_type,source_key)
);
create index news_feed_idx on public.news_posts(status,pinned desc,publish_at desc);
insert into public.news_posts(title,summary,body,category,author_source,pinned,status,publish_at,published_at,source_type,source_key)values('Welcome to Legacy Equine News','Official updates, special events, contests, and meaningful community milestones now have a home.','Visit Home after login for authoritative Legacy Equine news and game updates.','updates','Legacy Equine',true,'published',now(),now(),'system','home-news-launch')on conflict(source_type,source_key)do nothing;
create table public.news_reader_state(stable_id uuid primary key references public.stables(id)on delete cascade,last_viewed_at timestamptz not null default now());
alter table public.news_posts enable row level security;alter table public.news_reader_state enable row level security;
create policy "read own news cursor"on public.news_reader_state for select using(stable_id=auth.uid());

create or replace function public.news_safe_text(value text,max_length integer)returns text language sql immutable as $$
 select left(regexp_replace(coalesce(value,''),'<[^>]*>','','g'),max_length)
$$;
create or replace function public.news_safe_destination(value text)returns text language plpgsql immutable as $$begin
 if value is null or value=''then return null;end if;if value!~'^/[A-Za-z0-9_?&=#./-]+$'then raise exception'News destination must be a safe internal LE route';end if;return value;end$$;
create or replace function public.can_manage_news()returns boolean language sql stable security definer set search_path=public as $$select is_owner_account()or has_admin_permission('admin.news.manage')$$;

create or replace function public.get_home_news(p_category text default null,p_offset integer default 0,p_limit integer default 20)returns jsonb
language plpgsql security definer set search_path=public as $$declare viewed timestamptz;begin
 select last_viewed_at into viewed from news_reader_state where stable_id=auth.uid();
 return jsonb_build_object('last_viewed_at',viewed,'new_count',(select count(*)from news_posts n where n.status='published'and coalesce(n.publish_at,n.published_at,n.created_at)<=now()and(n.expires_at is null or n.expires_at>now())and coalesce(n.published_at,n.publish_at,n.created_at)>coalesce(viewed,'epoch')),
 'posts',coalesce((select jsonb_agg(to_jsonb(x))from(select id,title,summary,body,category,author_source,image_url,destination_url,pinned,coalesce(publish_at,published_at,created_at)published_at from news_posts n where n.status='published'and coalesce(n.publish_at,n.published_at,n.created_at)<=now()and(n.expires_at is null or n.expires_at>now())and(p_category is null or n.category=p_category)order by n.pinned desc,coalesce(n.publish_at,n.published_at,n.created_at)desc offset greatest(p_offset,0)limit least(greatest(p_limit,1),50))x),'[]'::jsonb));end$$;
create or replace function public.mark_news_viewed()returns void language sql security definer set search_path=public as $$insert into news_reader_state(stable_id,last_viewed_at)values(auth.uid(),now())on conflict(stable_id)do update set last_viewed_at=excluded.last_viewed_at$$;
create or replace function public.admin_news_list()returns jsonb language plpgsql stable security definer set search_path=public as $$begin if not(can_manage_news()or has_admin_permission('admin.news.view'))then raise exception'News administration permission required';end if;return coalesce((select jsonb_agg(to_jsonb(n)order by n.created_at desc)from news_posts n),'[]'::jsonb);end$$;
create or replace function public.admin_save_news(p_id uuid,p_title text,p_summary text,p_body text,p_category text,p_image_url text,p_destination text,p_pinned boolean,p_status text,p_publish_at timestamptz,p_expires_at timestamptz)returns uuid language plpgsql security definer set search_path=public as $$declare target uuid:=coalesce(p_id,gen_random_uuid());begin
 if not can_manage_news()then raise exception'News management permission required';end if;if p_category not in('official','updates','shows','contests','community')or p_status not in('draft','published','unpublished')then raise exception'Invalid News category or status';end if;
 insert into news_posts(id,title,summary,body,category,author_id,author_source,image_url,destination_url,pinned,status,publish_at,expires_at,published_at)values(target,news_safe_text(p_title,140),news_safe_text(p_summary,300),news_safe_text(p_body,10000),p_category,auth.uid(),'Legacy Equine',nullif(p_image_url,''),news_safe_destination(p_destination),p_pinned,p_status,coalesce(p_publish_at,case when p_status='published'then now()end),p_expires_at,case when p_status='published'then now()end)
 on conflict(id)do update set title=excluded.title,summary=excluded.summary,body=excluded.body,category=excluded.category,image_url=excluded.image_url,destination_url=excluded.destination_url,pinned=excluded.pinned,status=excluded.status,publish_at=excluded.publish_at,expires_at=excluded.expires_at,published_at=case when excluded.status='published'then coalesce(news_posts.published_at,now())else news_posts.published_at end,updated_at=now();return target;end$$;

create table public.news_auto_rules(rule_key text primary key,enabled boolean not null default true,threshold integer,category text not null default'community',minimum_interval interval not null default'1 day');
insert into news_auto_rules(rule_key,threshold)values('horse_cp_milestone',500)on conflict do nothing;
create or replace function public.publish_horse_cp_milestone()returns trigger language plpgsql security definer set search_path=public as $$declare threshold integer;s stables;begin select r.threshold into threshold from news_auto_rules r where rule_key='horse_cp_milestone'and enabled;if threshold is null or new.career_points<threshold or old.career_points>=threshold then return new;end if;select * into s from stables where id=new.owner_id and account_status='active';if found then insert into news_posts(title,summary,body,category,author_source,destination_url,status,publish_at,published_at,source_type,source_key)values('Career Milestone',new.name||' has reached '||threshold||' Career Points.',s.name||' celebrates '||new.name||' reaching '||threshold||' Career Points.','community','Around Legacy Equine','/horses/'||new.id,'published',now(),now(),'horse_cp_milestone',new.id||':'||threshold)on conflict(source_type,source_key)do nothing;end if;return new;end$$;
drop trigger if exists horse_cp_milestone_news on horses;create trigger horse_cp_milestone_news after update of career_points on horses for each row execute function publish_horse_cp_milestone();

alter table public.player_shows add column if not exists feature_on_news boolean not null default false;
create or replace function public.publish_featured_show_news()returns trigger language plpgsql security definer set search_path=public as $$begin if new.feature_on_news and not new.is_private and not new.is_admin_qa and new.source<>'auto_host'then insert into news_posts(title,summary,body,category,author_source,destination_url,status,publish_at,published_at,source_type,source_key)values(new.name,'Special Show · '||replace(new.discipline_id,'_',' ')||' · '||(new.entry_fee_purse+new.show_fund_allocation+new.treasury_allocation)||' LED purse',coalesce(new.description,'Entries are open for this featured Legacy Equine Show.'),'shows','Legacy Equine Shows','/shows?show='||new.id,'published',now(),now(),'featured_show',new.id::text)on conflict(source_type,source_key)do update set title=excluded.title,summary=excluded.summary,body=excluded.body,destination_url=excluded.destination_url,status='published',updated_at=now();end if;return new;end$$;
drop trigger if exists featured_show_news on player_shows;create trigger featured_show_news after insert or update of feature_on_news,name,description,run_at,entry_fee_purse,show_fund_allocation,treasury_allocation on player_shows for each row execute function publish_featured_show_news();

revoke all on function get_home_news(text,integer,integer),mark_news_viewed(),admin_news_list(),admin_save_news(uuid,text,text,text,text,text,text,boolean,text,timestamptz,timestamptz)from public;
grant execute on function get_home_news(text,integer,integer),mark_news_viewed(),admin_news_list(),admin_save_news(uuid,text,text,text,text,text,text,boolean,text,timestamptz,timestamptz)to authenticated;
