-- Authoritative breeding ages use the accelerated clock: 30 game days per real day.
-- A horse remains eligible throughout displayed age 25, until exact game age 26.
create or replace function public.breed_horses(stallion_id uuid,mare_id uuid)
returns public.horses language plpgsql security definer set search_path=public as $$
declare sire horses;dam horses;foal horses;s stables;child_stats jsonb='{}';child_genetics jsonb;child_markings jsonb;child_visual jsonb;d record;baseline int;variance int;fee int;child_breed text;child_sex horse_sex;sire_age numeric;dam_age numeric;begin
 if stallion_id=mare_id then raise exception 'Choose two different horses';end if;
 select * into sire from horses where id=stallion_id for update;select * into dam from horses where id=mare_id for update;
 if sire.id is null or dam.id is null or sire.owner_id<>auth.uid() or dam.owner_id<>auth.uid() then raise exception 'Both horses must be owned by you';end if;
 if sire.sex<>'Stallion' or dam.sex<>'Mare' then raise exception 'Breeding requires a stallion and mare';end if;
 sire_age:=greatest(0,extract(epoch from(now()-sire.birth_date))/86400*30/365.25);dam_age:=greatest(0,extract(epoch from(now()-dam.birth_date))/86400*30/365.25);
 if sire_age<3 then raise exception 'The stallion is too young to breed. Eligible at age 3.';end if;if dam_age<3 then raise exception 'The mare is too young to breed. Eligible at age 3.';end if;
 if sire_age>=26 or sire.retired then raise exception 'The stallion is retired from breeding.';end if;if dam_age>=26 or dam.retired then raise exception 'The mare is retired from breeding.';end if;
 if dam.last_bred_at is not null and dam.last_bred_at>now()-interval '10 days' then raise exception 'Mare cooldown active';end if;
 child_genetics:=inherit_genetics(sire.genetics,dam.genetics);if is_lethal_genotype(child_genetics) then raise exception 'This breeding produced a non-viable lethal genotype. No foal was created and no fee was charged.';end if;fee:=sire.stud_fee;select * into s from stables where id=auth.uid() for update;if s.balance<fee then raise exception 'Insufficient funds';end if;
 for d in select key from stat_definitions where active order by sort_order loop baseline:=round(((sire.stats->>d.key)::numeric+(dam.stats->>d.key)::numeric)/2)::int;variance:=floor(random()*13)::int-6;if random()<.25 then variance:=variance-1;end if;child_stats:=child_stats||jsonb_build_object(d.key,greatest(1,baseline+variance));end loop;
 child_breed:=resolve_crossbreed(sire.breed,dam.breed);child_sex:=(case when random()<.5 then 'Mare' else 'Stallion' end)::horse_sex;child_markings:=random_horse_markings(child_genetics,child_breed);child_visual:=jsonb_set(jsonb_set(build_visual_phenotype(child_breed,child_sex,0,child_genetics,child_markings),'{background}','"pure neutral white RGB 255 255 255 seamless background, edge-to-edge and shadow-free except for a faint natural hoof contact shadow"'::jsonb,true),'{lighting}','"bright neutral daylight, crisp coat detail, clean highlights, accurate coat color, strong natural contrast and no color cast"'::jsonb,true);
 insert into horses(owner_id,name,breed,sex,color,origin,birth_date,sire_id,dam_id,generation,stats,genetics,breed_composition,image_url,markings,visual_phenotype,image_generation_status,image_prompt_version) values(auth.uid(),'Unnamed Foal',child_breed,child_sex,genetic_color(child_genetics),'Bred',now(),sire.id,dam.id,greatest(sire.generation,dam.generation)+1,child_stats,child_genetics,combine_breed_composition(sire.breed_composition,dam.breed_composition),'/foundation-horse.png',child_markings,child_visual,'pending','horse-v4') returning * into foal;
 insert into store_horse_image_jobs(horse_id) values(foal.id);update horses set last_bred_at=now() where id=dam.id;update stables set balance=balance-fee where id=auth.uid();if fee>0 then insert into currency_ledger(stable_id,amount,reason,horse_id) values(auth.uid(),-fee,'Stud fee',foal.id);end if;insert into breeding_records(owner_id,sire_id,dam_id,foal_id,stud_fee) values(auth.uid(),sire.id,dam.id,foal.id,fee);return foal;
end $$;
revoke all on function public.breed_horses(uuid,uuid) from public;grant execute on function public.breed_horses(uuid,uuid) to authenticated;
