alter table public.breed_visual_archetypes
  add column height_range text,
  add column movement_description text,
  add column temperament_description text,
  add column breed_constraints text,
  add column source_organization text,
  add column source_url text;

update public.breed_visual_archetypes set body_description='compact, balanced stock-horse conformation with a short strong back, deep broad chest, substantial shoulder and forearm, low-set knees and powerful rounded hindquarters',height_range='typically 14.2–16 hands',movement_description='quick, balanced, agile movement with exceptional acceleration',temperament_description='steady, willing, versatile stock-horse character',breed_constraints='Avoid an overly fine racing build or exaggerated halter musculature.',source_organization='American Quarter Horse Association',source_url='https://www.aqha.com/' where breed='Quarter Horse';
update public.breed_visual_archetypes set body_description='refined, symmetrical light-horse frame with a small finely chiseled head, subtly concave profile, large expressive eyes, deep jowls, long arched neck, short straight back, deep chest, well-sprung ribs and comparatively horizontal croup',height_range='typically 14.1–15.1 hands',movement_description='balanced, energetic floating trot with proud natural high tail carriage',temperament_description='intelligent, courageous, alert and energetic',breed_constraints='Purebred coat must be bay, chestnut, gray or black; dark skin except beneath white markings; never portray an extreme caricatured dish.',source_organization='Arabian Horse Association',source_url='https://arabianhorses.org/discover/arabian-horses/' where breed='Arabian';
update public.breed_visual_archetypes set body_description='lean, long-lined athletic racing-horse frame with refined head, long neck, prominent withers, deep heartgirth, long sloping shoulder, long clean legs and muscular hindquarters without bulky stock-horse mass',height_range='commonly 15.2–17 hands',movement_description='efficient ground-covering athletic stride suggesting speed and stamina',temperament_description='sensitive, bold, energetic athletic character',breed_constraints='Keep the physique lean and conditioned, never draft-like or heavily muscled like a stock horse.',source_organization='The Jockey Club / USEF Thoroughbred Division',source_url='https://www.usef.org/forms-pubs/7qJ0t9vVd58/usef-rulebook' where breed='Thoroughbred';
update public.breed_visual_archetypes set body_description='noble, harmonious rectangular warmblood frame with expressive head, well-proportioned neck, pronounced long withers, open sloping shoulder, long broad forearm, short cannon, strong back, long sprung hind rib and broad slightly sloping croup',height_range='substantial sport-horse height in proportion to frame',movement_description='straight, elastic, ground-covering movement with impulsion from powerful hindquarters and an uphill canter',temperament_description='rideable, willing and balanced sport-horse character',breed_constraints='Rectangular rather than square frame; harmony and athletic function matter more than exaggerated size.',source_organization='American Hanoverian Society',source_url='https://hanoverian.org/mare-inspection-requirements/' where breed='Hanoverian';
update public.breed_visual_archetypes set body_description='symmetrical versatile stock-horse frame with a straight lean head, deep chest, muscular sloping shoulder, prominent withers, short straight back, wide loin, long muscular hip and strong well-rounded quarters',height_range='medium light-horse height',movement_description='straight, balanced, versatile athletic movement',temperament_description='intelligent, tractable and versatile',breed_constraints='When LP is expressed, include believable Appaloosa characteristics: mottled skin, visible white sclera and possibly vertically striped hooves; coat patterns are unique rather than mirrored.',source_organization='Appaloosa Horse Club',source_url='https://www.appaloosa.com/handbook' where breed='Appaloosa';
update public.breed_visual_archetypes set body_description='distinctive compact frame with expressive broad forehead and prominent eyes, short face, alert ears, slightly arched neck set atop a deeply angled shoulder, defined withers, short back, close coupling, broad loin, deep body and long rounded muscular croup with high tail attachment',height_range='typically 14.1–15.2 hands',movement_description='animated, strong, naturally springy movement with stamina and vigor',temperament_description='eager, alert, adaptable and tractable',breed_constraints='Substantial yet refined; the croup should not stand higher than the withers.',source_organization='American Morgan Horse Association',source_url='https://www.morganhorse.com/about-morgan/ideal-morgan/' where breed='Morgan';
update public.breed_visual_archetypes set body_description='medium-sized gaited frame with medium bone and feet, wide deep chest, ideally 45-degree sloping shoulders, proportional straight-profile head, bold eyes and a medium gracefully arched neck with natural carriage',height_range='14–16 hands',movement_description='natural smooth four-beat ambling gait with nearly even cadence, minimal knee and hock action and efficient ground-covering stride',temperament_description='notably gentle and willing',breed_constraints='Solid body color only; modest facial white only and no white above knee or hock; no bald face; face neither dished nor Roman-nosed.',source_organization='Rocky Mountain Horse Association',source_url='https://www.rmhorse.com/?page_id=734' where breed='Rocky Mountain Horse';
update public.breed_visual_archetypes set body_description='tall, smooth-lined gaited frame with a definitive head and small well-placed ears, long sloping shoulder, long sloping hip, fairly short back, short strong coupling and a noticeably longer underline than topline',height_range='14.3–17 hands',movement_description='natural running walk with a long, smooth, ground-covering stride',temperament_description='willing, manageable and calm pleasure-horse character',breed_constraints='Retain functional natural conformation; do not depict exaggerated padded-show posture or artificial action.',source_organization='Tennessee Walking Horse Breeders’ and Exhibitors’ Association',source_url='https://twhbea.com/the-breed/conformation/' where breed='Tennessee Walking Horse';

alter table public.breed_cross_rules add column recognition text not null default 'documented named cross';
alter table public.breed_cross_rules add column source_url text;
update public.breed_cross_rules set recognition='formal AHA registry',source_url='https://arabianhorses.org/export/content.export/aha-handbooks/2020-handbook/CHAPTER10.pdf' where result_breed='Anglo-Arabian';
update public.breed_cross_rules set recognition='AQHA registration pathway',source_url='https://helpcenter.aqha.com/knowledge/-how-do-i-register-a-foal-with-aqha' where result_breed='Appendix Quarter Horse';
update public.breed_cross_rules set recognition='specialist breed registry',source_url='https://www.quarab.it/english/' where result_breed='Quarab';
update public.breed_cross_rules set recognition='specialist registries acknowledged by AMHA',source_url='https://www.morganhorse.com/registry/faq/' where result_breed='Morab';
update public.breed_cross_rules set recognition='documented named cross; parent may qualify through ApHC/AHA rules',source_url='https://www.appaloosa.com/registration-quick-facts' where result_breed='AraAppaloosa';

create or replace function public.random_horse_markings(g jsonb,b text default null)
returns jsonb language plpgsql volatile as $$
declare white_bias numeric:=case when gene_count(g,'Sabino1','SB1')>0 or gene_count(g,'Splash1','SW1')>0 or gene_count(g,'Frame','O')>0 then .55 else .22 end;face_options text[]:=case when b='Rocky Mountain Horse' then array['star','snip','stripe'] else array['star','snip','stripe','blaze','bald face'] end;leg_options text[]:=array['coronet','pastern','sock','stocking'];
begin return jsonb_build_object('face',case when random()<white_bias then face_options[1+floor(random()*array_length(face_options,1))::int] else 'none' end,'left_front',case when b='Rocky Mountain Horse' then 'none' when random()<white_bias then leg_options[1+floor(random()*4)::int] else 'none' end,'right_front',case when b='Rocky Mountain Horse' then 'none' when random()<white_bias then leg_options[1+floor(random()*4)::int] else 'none' end,'left_hind',case when b='Rocky Mountain Horse' then 'none' when random()<white_bias then leg_options[1+floor(random()*4)::int] else 'none' end,'right_hind',case when b='Rocky Mountain Horse' then 'none' when random()<white_bias then leg_options[1+floor(random()*4)::int] else 'none' end);end $$;

create or replace function public.enforce_foundation_breed_genetics(b text,g jsonb)
returns jsonb language plpgsql immutable as $$
declare result jsonb:=g; locus text;begin
 if b='Arabian' then foreach locus in array array['Cream','Dun','Champagne','Silver','Pearl','Roan','Tobiano','Frame','Leopard','PATN1','Mushroom'] loop result:=jsonb_set(result,array[locus],'["N","N"]'::jsonb,true);end loop;end if;
 if b='Rocky Mountain Horse' then foreach locus in array array['Tobiano','Frame','Sabino1','Splash1','Splash2','Splash3','Splash5','Splash6','Splash7','Splash8','Leopard','PATN1','W5','W10','W13','W20','W22'] loop result:=jsonb_set(result,array[locus],'["N","N"]'::jsonb,true);end loop;end if;
 return result;end $$;

create or replace function public.build_visual_phenotype(b text,s horse_sex,age_years numeric,g jsonb,m jsonb)
returns jsonb language plpgsql stable as $$
declare color_name text:=genetic_color(g);a breed_visual_archetypes;pattern text:='solid';mane text:='coat-appropriate dark mane and tail';begin
 select * into a from breed_visual_archetypes where breed=b;
 if color_name ilike '%Palomino%' or color_name ilike '%Cremello%' or color_name ilike '%Perlino%' then mane:='light cream to flaxen mane and tail';elsif color_name ilike '%Silver%' then mane:='genetically silver-diluted mane and tail';elsif color_name ilike '%Chestnut%' or color_name ilike '%Red Dun%' or color_name ilike '%Red Roan%' then mane:='red or flaxen coat-appropriate mane and tail';end if;
 if gene_count(g,'Tobiano','TO')>0 then pattern:='tobiano white spotting';elsif gene_count(g,'Frame','O')=1 then pattern:='frame overo white spotting';elsif gene_count(g,'Sabino1','SB1')>0 then pattern:='sabino white pattern';elsif gene_count(g,'Splash1','SW1')>0 then pattern:='splashed white pattern';elsif gene_count(g,'Leopard','LP')>0 then pattern:='leopard complex Appaloosa pattern with mottled skin and breed-appropriate secondary characteristics';end if;
 return jsonb_build_object('breed',b,'sex',s,'age_years',age_years,'color',color_name,'body',coalesce(a.body_description,'realistic balanced conformation appropriate to the named breed'),'height_range',coalesce(a.height_range,'height proportionate to breed'),'movement',coalesce(a.movement_description,'balanced natural movement'),'temperament',coalesce(a.temperament_description,'alert, natural equine expression'),'breed_constraints',coalesce(a.breed_constraints,'avoid caricature'),'coat',color_name,'mane_tail',mane,'pattern',pattern,'face_marking',m->>'face','left_front',m->>'left_front','right_front',m->>'right_front','left_hind',m->>'left_hind','right_hind',m->>'right_hind','pose','standing square','view','side or subtle three-quarter profile','background','neutral light Legacy Equine studio');end $$;

create or replace function public.generate_store_horse(p_rotation timestamptz,p_preferred_breed text default null)
returns uuid language plpgsql security definer set search_path=public as $$
declare h_id uuid;breed_name text;g jsonb;m jsonb;visual jsonb;horse_sex_value horse_sex;begin
 select coalesce(p_preferred_breed,(select name from foundation_breeds where active order by random() limit 1)) into breed_name;
 g:=enforce_foundation_breed_genetics(breed_name,random_foundation_genetics(breed_name));m:=random_horse_markings(g,breed_name);horse_sex_value:=(case when random()<.5 then 'Mare' else 'Stallion' end)::horse_sex;visual:=build_visual_phenotype(breed_name,horse_sex_value,2,g,m);
 insert into horses(owner_id,name,breed,sex,color,origin,birth_date,stats,image_url,genetics,breed_composition,markings,visual_phenotype,image_generation_status,image_prompt_version) values(null,'Unnamed Foundation Horse',breed_name,horse_sex_value,genetic_color(g),'Foundation',now()-(interval '1 day'*(2*365.25/30)),random_foundation_stats(),'/foundation-horse.png',g,jsonb_build_object(breed_name,1),m,visual,'pending','store-horse-v2') returning id into h_id;
 insert into store_horse_image_jobs(horse_id) values(h_id);return h_id;end $$;

-- Refresh pending descriptions without rerolling genetics, identity, stats, or breed.
with revised as materialized (select h.id,case when h.breed='Rocky Mountain Horse' then random_horse_markings(h.genetics,h.breed) else h.markings end markings from public.horses h where h.image_generation_status in ('pending','failed') and h.image_url='/foundation-horse.png')
update public.horses h set markings=r.markings,visual_phenotype=build_visual_phenotype(h.breed,h.sex,extract(epoch from (now()-h.birth_date))/31557600,h.genetics,r.markings),image_prompt_version='store-horse-v2' from revised r where r.id=h.id;

revoke all on function public.random_horse_markings(jsonb,text),public.enforce_foundation_breed_genetics(text,jsonb) from public;
