create or replace function public.owner_register_prepared_visual_asset(p_requirement uuid,p_asset_key text,p_image_url text,p_width integer,p_height integer,p_file_size integer,p_validation jsonb default '{}'::jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare r horse_visual_asset_requirements;a uuid;m horse_visual_assets;prior uuid;next_version integer;
begin
 perform require_super_admin();
 if not exists(select 1 from stables where id=auth.uid() and account_number=1)then raise exception 'Owner Account #1 required';end if;
 select * into r from horse_visual_asset_requirements where id=p_requirement for update;if not found then raise exception 'Visual requirement not found';end if;
 if p_width<>r.canvas_width or p_height<>r.canvas_height then raise exception 'Prepared asset canvas must be exactly % x %',r.canvas_width,r.canvas_height;end if;
 if p_file_size<=0 or p_file_size>10485760 then raise exception 'Prepared asset must be under 10 MB';end if;
 select * into m from horse_visual_assets where asset_key=r.body_template_key and immutable_source=true;if not found then raise exception 'Immutable body master not found';end if;
 prior:=r.asset_id;select coalesce(max(version),0)+1 into next_version from horse_visual_assets where body_template_key=r.body_template_key and asset_type=r.category and coalesce(phenotype_key,marking_key,'')=r.trait_key;
 insert into horse_visual_assets(asset_key,asset_type,breed,sex,phenotype_key,marking_key,leg_position,image_url,z_index,status,active,review_notes,created_by,body_template_key,canvas_width,canvas_height,version,supersedes_asset_id,validation)
 values(left(p_asset_key||'_v'||next_version,120),r.category,m.breed,m.sex,case when r.category in('base_coat','modifier','dapple','mane','tail','clean_body')then r.trait_key end,case when r.category in('face_marking','leg_marking','pattern','pinto_pattern','leopard_complex')then r.trait_key end,case r.anatomical_position when'LF'then'left_front'when'RF'then'right_front'when'LH'then'left_hind'when'RH'then'right_hind'end,left(p_image_url,2048),50,'pending',false,'Prepared by Owner for visual review',auth.uid(),r.body_template_key,p_width,p_height,next_version,prior,coalesce(p_validation,'{}'::jsonb)||jsonb_build_object('technical_compatibility','pass','owner_approval_required',true)) returning id into a;
 update horse_visual_asset_requirements set asset_id=a,status='review',notes='Prepared for Owner visual review',updated_at=now()where id=r.id;
 return a;
end$$;
revoke all on function public.owner_register_prepared_visual_asset(uuid,text,text,integer,integer,integer,jsonb) from public;
grant execute on function public.owner_register_prepared_visual_asset(uuid,text,text,integer,integer,integer,jsonb) to authenticated;
comment on function public.owner_register_prepared_visual_asset is 'Owner-only handoff from non-destructive canvas normalization to visual Review. Diagnostics are warnings; Owner approval is authoritative.';

create or replace function public.admin_visual_workspace()returns jsonb language plpgsql stable security definer set search_path=public as $$declare result jsonb;begin perform require_admin();select coalesce(jsonb_agg(item order by item->>'master',item->>'category',item->>'display_name'),'[]')into result from(select jsonb_build_object('requirement_id',r.id,'master',r.body_template_key,'master_url',m.image_url,'breed',m.breed,'sex',m.sex,'category',r.category,'trait_key',r.trait_key,'display_name',t.display_name,'limb',r.anatomical_position,'variant',r.variant,'status',r.status,'notes',r.notes,'width',r.canvas_width,'height',r.canvas_height,'asset_id',a.id,'asset_key',a.asset_key,'asset_url',a.image_url,'version',a.version,'validation',coalesce(a.validation,'{}'::jsonb),'uploaded_at',a.created_at,'approved_at',a.approved_at,'history',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'key',v.asset_key,'url',v.image_url,'version',v.version,'status',v.status,'notes',v.review_notes,'uploaded_at',v.created_at,'approved_at',v.approved_at)order by v.version desc)from horse_visual_assets v where v.body_template_key=r.body_template_key and v.asset_type=r.category and coalesce(v.phenotype_key,v.marking_key,'')=coalesce(a.phenotype_key,a.marking_key,r.trait_key,'')and coalesce(v.leg_position,'')=coalesce(a.leg_position,case r.anatomical_position when'LF'then'left_front'when'RF'then'right_front'when'LH'then'left_hind'when'RH'then'right_hind'end,'')),'[]'::jsonb))item from horse_visual_asset_requirements r join horse_visual_assets m on m.asset_key=r.body_template_key join equine_visual_taxonomy t on t.category=r.category and t.trait_key=r.trait_key left join horse_visual_assets a on a.id=r.asset_id)s;return result;end$$;
