-- Reference-led deterministic phenotype taxonomy and per-master artwork requirements.
-- This migration creates no artwork and activates no derived visual asset.
alter table public.horses add column if not exists visual_modifiers jsonb not null default '{"dapple":"none"}'::jsonb;

create table public.equine_visual_taxonomy(category text not null,trait_key text not null,display_name text not null,family text not null default '',sort_order integer not null default 0,metadata jsonb not null default '{}'::jsonb,active boolean not null default true,primary key(category,trait_key),check(category in('face_marking','leg_marking','base_coat','gray_stage','dun','cream','roan','silver','champagne','pearl','dapple','pinto_pattern','leopard_complex','visual_detail','mane','tail','clean_body')));
alter table public.equine_visual_taxonomy enable row level security;
create policy "visual taxonomy is public" on public.equine_visual_taxonomy for select using(active);

insert into public.equine_visual_taxonomy(category,trait_key,display_name,family,sort_order,metadata) values
('face_marking','none','None','face',0,'{"description":"No facial white asset"}'),('face_marking','snip_01','Snip 01','face',10,'{"isolated_muzzle":true}'),('face_marking','faint_01','Faint Marking 01','face',20,'{}'),('face_marking','faint_star_01','Faint Star 01','face',30,'{}'),('face_marking','star_01','Star 01','face',40,'{}'),('face_marking','half_star_01','Half Star 01','face',50,'{}'),('face_marking','strip_01','Stripe / Strip 01','face',60,'{}'),('face_marking','broken_strip_01','Broken Stripe 01','face',70,'{}'),('face_marking','star_strip_01','Star + Stripe 01','face',80,'{}'),('face_marking','blaze_01','Blaze 01','face',90,'{}'),('face_marking','blaze_snip_01','Blaze + Snip 01','face',100,'{}'),('face_marking','irregular_blaze_01','Irregular Blaze 01','face',110,'{}'),('face_marking','bald_face_01','Bald Face 01','face',120,'{"broad_white_may_reach_eyes":true}'),
('leg_marking','none','None','leg',0,'{}'),('leg_marking','coronet_01','Coronet 01','leg',10,'{}'),('leg_marking','white_heel_01','White Heel 01','leg',20,'{}'),('leg_marking','half_pastern_01','Half Pastern 01','leg',30,'{}'),('leg_marking','pastern_01','Pastern 01','leg',40,'{}'),('leg_marking','ankle_01','Ankle 01','leg',50,'{}'),('leg_marking','half_sock_01','Half Sock 01','leg',60,'{}'),('leg_marking','full_sock_01','Full Sock 01','leg',70,'{}'),('leg_marking','high_sock_01','High Sock 01','leg',80,'{}'),
('base_coat','chestnut','Sorrel / Chestnut','base',10,'{}'),('base_coat','bay','Bay','base',20,'{}'),('base_coat','dark_bay_brown','Brown / Dark Bay','base',30,'{}'),('base_coat','black','Black','base',40,'{}'),
('gray_stage','early','Early Gray','gray',10,'{}'),('gray_stage','mid','Mid Gray','gray',20,'{}'),('gray_stage','dapple_gray','Dapple Gray','gray',30,'{}'),('gray_stage','late','Late Gray','gray',40,'{}'),('gray_stage','white_gray','White Gray','gray',50,'{}'),
('dun','red_dun','Red Dun','dun',10,'{"base":"chestnut","primitive_markings":true}'),('dun','bay_dun','Bay Dun','dun',20,'{"base":"bay","primitive_markings":true}'),('dun','grulla','Grulla / Grullo','dun',30,'{"base":"black","primitive_markings":true,"visual_direction":"mouse/slate body with dark points, mane, tail and dorsal stripe"}'),
('cream','palomino','Palomino','cream',10,'{}'),('cream','buckskin','Buckskin','cream',20,'{}'),('cream','smoky_black','Smoky Black','cream',30,'{}'),('cream','cremello','Cremello','cream',40,'{}'),('cream','perlino','Perlino','cream',50,'{}'),('cream','smoky_cream','Smoky Cream','cream',60,'{}'),
('roan','red_roan','Red Roan','roan',10,'{}'),('roan','bay_roan','Bay Roan','roan',20,'{}'),('roan','blue_roan','Blue Roan','roan',30,'{}'),('silver','silver_black','Silver Black','silver',10,'{}'),('silver','silver_bay','Silver Bay','silver',20,'{}'),
('champagne','gold_champagne','Gold Champagne','champagne',10,'{}'),('champagne','amber_champagne','Amber Champagne','champagne',20,'{}'),('champagne','classic_champagne','Classic Champagne','champagne',30,'{}'),('champagne','sable_champagne','Sable Champagne','champagne',40,'{}'),('pearl','pearl','Pearl','pearl',10,'{}'),
('dapple','none','None','dapple',0,'{"requires_asset":false}'),('dapple','subtle','Subtle','dapple',10,'{}'),('dapple','moderate','Moderate','dapple',20,'{}'),('dapple','strong','Strong','dapple',30,'{}'),
('pinto_pattern','tobiano_01','Tobiano 01','pinto',10,'{}'),('pinto_pattern','frame_overo_01','Frame Overo 01','pinto',20,'{}'),('pinto_pattern','splash_white_01','Splash White 01','pinto',30,'{}'),('pinto_pattern','sabino_01','Sabino-type 01','pinto',40,'{}'),('pinto_pattern','tovero_01','Tovero 01','pinto',50,'{"combined":["tobiano","overo"]}'),('pinto_pattern','medicine_hat_01','Medicine Hat 01','pinto',60,'{"ordinary_face_marking":false}'),
('leopard_complex','leopard_01','Leopard 01','appaloosa',10,'{}'),('leopard_complex','blanket_01','Blanket 01','appaloosa',20,'{}'),('leopard_complex','spotted_blanket_01','Spotted Blanket 01','appaloosa',30,'{}'),('leopard_complex','snowcap_01','Snowcap 01','appaloosa',40,'{}'),('leopard_complex','fewspot_01','Fewspot 01','appaloosa',50,'{}'),('leopard_complex','varnish_roan_01','Varnish Roan 01','appaloosa',60,'{}'),('leopard_complex','snowflake_01','Snowflake 01','appaloosa',70,'{}'),
('visual_detail','mottled_skin_01','Mottled Skin 01','appaloosa_detail',10,'{}'),('visual_detail','striped_hooves_01','Striped Hooves 01','appaloosa_detail',20,'{}'),('visual_detail','visible_sclera_01','Visible Sclera 01','appaloosa_detail',30,'{}'),('visual_detail','dorsal_stripe_01','Dorsal Stripe 01','primitive',40,'{}'),('visual_detail','leg_barring_01','Leg Barring 01','primitive',50,'{}'),
('mane','chestnut','Chestnut Mane','hair',10,'{}'),('mane','black','Black Mane','hair',20,'{}'),('mane','flaxen_cream','Flaxen / Cream Mane','hair',30,'{}'),('tail','chestnut','Chestnut Tail','hair',10,'{}'),('tail','black','Black Tail','hair',20,'{}'),('tail','flaxen_cream','Flaxen / Cream Tail','hair',30,'{}'),('clean_body','neutral','Neutral Clean Body','body',10,'{}')
on conflict(category,trait_key) do update set display_name=excluded.display_name,family=excluded.family,sort_order=excluded.sort_order,metadata=excluded.metadata,active=true;

alter table public.horse_visual_assets drop constraint if exists horse_visual_assets_asset_type_check;
alter table public.horse_visual_assets add constraint horse_visual_assets_asset_type_check check(asset_type in('body_template','clean_body','base_coat','gray_stage','dun','cream','roan','silver','champagne','pearl','dapple','modifier','leg_points','primitive_marking','pattern','pinto_pattern','leopard_complex','visual_detail','face_marking','leg_marking','mane','tail','mane_tail'));
alter table public.horse_visual_assets add column if not exists body_template_key text references public.horse_visual_assets(asset_key);
alter table public.horse_visual_assets add column if not exists canvas_width integer;
alter table public.horse_visual_assets add column if not exists canvas_height integer;
alter table public.horse_visual_assets add column if not exists registration_x integer not null default 0;
alter table public.horse_visual_assets add column if not exists registration_y integer not null default 0;
alter table public.horse_visual_assets add column if not exists registration_scale numeric(8,5) not null default 1;

create table public.horse_visual_asset_requirements(id uuid primary key default gen_random_uuid(),body_template_key text not null references public.horse_visual_assets(asset_key),category text not null,trait_key text not null,anatomical_position text,variant integer not null default 1 check(variant>0),status text not null default 'missing' check(status in('missing','uploaded','review','approved','production')),asset_id uuid references public.horse_visual_assets(id),canvas_width integer not null check(canvas_width>0),canvas_height integer not null check(canvas_height>0),registration_x integer not null default 0,registration_y integer not null default 0,registration_scale numeric(8,5) not null default 1 check(registration_scale=1),notes text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(body_template_key,category,trait_key,anatomical_position,variant),foreign key(category,trait_key) references public.equine_visual_taxonomy(category,trait_key),check(anatomical_position is null or anatomical_position in('LF','RF','LH','RH')),check((category='leg_marking' and anatomical_position is not null)or(category<>'leg_marking' and anatomical_position is null)),check(status='missing' or asset_id is not null));
alter table public.horse_visual_asset_requirements enable row level security;

insert into public.horse_visual_asset_requirements(body_template_key,category,trait_key,anatomical_position,canvas_width,canvas_height)
select m.asset_key,t.category,t.trait_key,null,1500,1024 from public.horse_visual_assets m cross join public.equine_visual_taxonomy t where m.asset_type='body_template' and m.status='approved' and m.asset_key<>'foundation_generic_01' and t.active and t.trait_key<>'none' and t.category<>'leg_marking' on conflict do nothing;
insert into public.horse_visual_asset_requirements(body_template_key,category,trait_key,anatomical_position,canvas_width,canvas_height)
select m.asset_key,t.category,t.trait_key,p.position,1500,1024 from public.horse_visual_assets m cross join public.equine_visual_taxonomy t cross join(values('LF'),('RF'),('LH'),('RH'))p(position) where m.asset_type='body_template' and m.status='approved' and m.asset_key<>'foundation_generic_01' and t.category='leg_marking' and t.trait_key<>'none' on conflict do nothing;

create or replace function public.admin_visual_asset_requirements() returns table(body_template_key text,breed text,sex horse_sex,category text,trait_key text,display_name text,anatomical_position text,variant integer,status text,asset_key text,notes text) language plpgsql stable security definer set search_path=public as $$begin perform require_admin();return query select r.body_template_key,m.breed,m.sex,r.category,r.trait_key,t.display_name,r.anatomical_position,r.variant,r.status,a.asset_key,r.notes from horse_visual_asset_requirements r join horse_visual_assets m on m.asset_key=r.body_template_key join equine_visual_taxonomy t on t.category=r.category and t.trait_key=r.trait_key left join horse_visual_assets a on a.id=r.asset_id order by m.asset_key,t.category,t.sort_order,r.anatomical_position,r.variant;end$$;
create or replace function public.admin_set_visual_requirement(p_requirement uuid,p_asset uuid,p_status text,p_notes text default '') returns void language plpgsql security definer set search_path=public as $$declare r horse_visual_asset_requirements;a horse_visual_assets;begin perform require_admin();if p_status not in('missing','uploaded','review','approved','production')then raise exception 'Invalid visual requirement status';end if;select * into r from horse_visual_asset_requirements where id=p_requirement for update;if not found then raise exception 'Visual requirement not found';end if;if p_status<>'missing'then select * into a from horse_visual_assets where id=p_asset and body_template_key=r.body_template_key;if not found then raise exception 'Asset must be registered to this exact body master';end if;end if;if p_status='production'and(a.status<>'approved'or not a.active)then raise exception 'Only an approved active asset may enter production';end if;update horse_visual_asset_requirements set asset_id=case when p_status='missing'then null else p_asset end,status=p_status,notes=left(coalesce(p_notes,''),500),updated_at=now()where id=p_requirement;end$$;

create or replace function public.anatomical_leg_marking(p_markings jsonb,p_limb text) returns text language plpgsql immutable as $$begin return case p_limb when'LF'then coalesce(p_markings->>'left_front','none')when'RF'then coalesce(p_markings->>'right_front','none')when'LH'then coalesce(p_markings->>'left_hind','none')when'RH'then coalesce(p_markings->>'right_hind','none')else null end;end$$;
create or replace function public.random_horse_markings(g jsonb,b text default null) returns jsonb language plpgsql volatile as $$declare white_bias numeric:=case when gene_count(g,'Sabino1','SB1')>0 or gene_count(g,'Splash1','SW1')>0 or gene_count(g,'Frame','O')>0 then .55 else .22 end;face_options text[]:=case when b='Rocky Mountain Horse'then array['snip_01','faint_01','faint_star_01','star_01','half_star_01','strip_01']else array['snip_01','faint_01','faint_star_01','star_01','half_star_01','strip_01','broken_strip_01','star_strip_01','blaze_01','blaze_snip_01','irregular_blaze_01','bald_face_01']end;leg_options text[]:=array['coronet_01','white_heel_01','half_pastern_01','pastern_01','ankle_01','half_sock_01','full_sock_01','high_sock_01'];begin return jsonb_build_object('face',case when random()<white_bias then face_options[1+floor(random()*array_length(face_options,1))::int]else'none'end,'left_front',case when b='Rocky Mountain Horse'then'none'when random()<white_bias then leg_options[1+floor(random()*array_length(leg_options,1))::int]else'none'end,'right_front',case when b='Rocky Mountain Horse'then'none'when random()<white_bias then leg_options[1+floor(random()*array_length(leg_options,1))::int]else'none'end,'left_hind',case when b='Rocky Mountain Horse'then'none'when random()<white_bias then leg_options[1+floor(random()*array_length(leg_options,1))::int]else'none'end,'right_hind',case when b='Rocky Mountain Horse'then'none'when random()<white_bias then leg_options[1+floor(random()*array_length(leg_options,1))::int]else'none'end);end$$;
create or replace function public.equine_visual_traits(g jsonb,age_years numeric,modifiers jsonb default '{}'::jsonb) returns jsonb language plpgsql immutable as $$declare base text;cream_count integer:=gene_count(g,'Cream','Cr');gray_stage text:='none';pinto text[]:='{}';leopard text:='none';begin base:=case when gene_count(g,'Extension','E')=0 then'chestnut'when gene_count(g,'Agouti','A')>0 then'bay'else'black'end;if gene_count(g,'Gray','G')>0 then gray_stage:=case when age_years<3 then'early'when age_years<7 then'mid'when age_years<12 then'dapple_gray'when age_years<18 then'late'else'white_gray'end;end if;if gene_count(g,'Tobiano','TO')>0 then pinto:=array_append(pinto,'tobiano_01');end if;if gene_count(g,'Frame','O')=1 then pinto:=array_append(pinto,'frame_overo_01');end if;if gene_count(g,'Splash1','SW1')>0 then pinto:=array_append(pinto,'splash_white_01');end if;if gene_count(g,'Sabino1','SB1')>0 then pinto:=array_append(pinto,'sabino_01');end if;if array_length(pinto,1)>1 then pinto:=array_append(pinto,'tovero_01');end if;if gene_count(g,'Leopard','LP')>0 then leopard:=case when gene_count(g,'PATN1','PATN1')>0 then'leopard_01'else'varnish_roan_01'end;end if;return jsonb_build_object('underlying_base',base,'gray_stage',gray_stage,'dun',case when gene_count(g,'Dun','D')=0 then'none'when base='chestnut'then'red_dun'when base='bay'then'bay_dun'else'grulla'end,'cream',case when cream_count=1 then case base when'chestnut'then'palomino'when'bay'then'buckskin'else'smoky_black'end when cream_count=2 then case base when'chestnut'then'cremello'when'bay'then'perlino'else'smoky_cream'end else'none'end,'roan',case when gene_count(g,'Roan','Rn')=0 then'none'when base='chestnut'then'red_roan'when base='bay'then'bay_roan'else'blue_roan'end,'pinto_patterns',to_jsonb(pinto),'leopard_complex',leopard,'dapple',coalesce(modifiers->>'dapple','none'),'primitive_markings',gene_count(g,'Dun','D')>0,'appaloosa_details',gene_count(g,'Leopard','LP')>0);end$$;

revoke all on function public.admin_visual_asset_requirements(),public.admin_set_visual_requirement(uuid,uuid,text,text) from public;
grant execute on function public.admin_visual_asset_requirements(),public.admin_set_visual_requirement(uuid,uuid,text,text) to authenticated;
grant execute on function public.anatomical_leg_marking(jsonb,text),public.equine_visual_traits(jsonb,numeric,jsonb) to authenticated;
comment on table public.horse_visual_asset_requirements is 'Owner-reviewed exact-master artwork matrix. Missing rows cannot render and no row creates artwork.';
comment on function public.anatomical_leg_marking(jsonb,text) is 'Maps LF/RF/LH/RH to horse anatomical limbs, never screen position.';
