-- Closed-loop LED institutional accounts, profession fees, and deterministic shows.
alter table public.stables add column is_super_admin boolean not null default false;
update public.stables set is_super_admin=true where account_number=1;
alter table public.professions add column enrollment_fee bigint not null default 500 check(enrollment_fee>=0);
update public.professions set enrollment_fee=750 where id='veterinarian';
alter table public.certification_levels add column exam_fee bigint not null default 0 check(exam_fee>=0);
update public.certification_levels set exam_fee=case level when 1 then 250 when 2 then 500 when 3 then 1000 when 4 then 2000 end;

create table public.economy_config(
 id boolean primary key default true check(id),profession_show_fund_percent numeric(5,2) not null default 50,profession_treasury_percent numeric(5,2) not null default 50,
 self_service_credit numeric(4,2) not null default .5,show_hosting_fee bigint not null default 0,show_entry_fee_max bigint not null default 10000,
 show_fund_daily_budget bigint not null default 25000,show_fund_weekly_budget bigint not null default 100000,show_fund_reserve bigint not null default 0,
 check(profession_show_fund_percent>=0 and profession_treasury_percent>=0 and profession_show_fund_percent+profession_treasury_percent=100)
);insert into public.economy_config(id) values(true);
create table public.system_funds(id text primary key check(id in('show_fund','treasury')),name text not null,balance bigint not null default 0 check(balance>=0),lifetime_inflow bigint not null default 0,lifetime_outflow bigint not null default 0);
insert into public.system_funds values('show_fund','Legacy Equine Show Fund',0,0,0),('treasury','Legacy Equine Treasury',0,0,0);
create table public.system_fund_ledger(id uuid primary key default gen_random_uuid(),fund_id text not null references public.system_funds(id),amount bigint not null check(amount<>0),transaction_type text not null,source text not null,destination text not null,initiated_by uuid references public.stables(id),reason text not null,internal_note text,related_id uuid,reversal_of uuid references public.system_fund_ledger(id),created_at timestamptz not null default now());
alter table public.economy_config enable row level security;alter table public.system_funds enable row level security;alter table public.system_fund_ledger enable row level security;
create policy "economy config readable" on public.economy_config for select using(true);create policy "fund balances readable" on public.system_funds for select using(true);create policy "fund ledger readable" on public.system_fund_ledger for select using(true);

create or replace function public.require_super_admin() returns void language plpgsql security definer set search_path=public as $$begin if not exists(select 1 from stables where id=auth.uid() and is_super_admin) then raise exception 'Super-admin access required';end if;end$$;
create or replace function public.allocate_profession_fee(payer uuid,fee bigint,reason_text text,related uuid default null) returns void language plpgsql security definer set search_path=public as $$declare cfg economy_config;show_amount bigint;treasury_amount bigint;begin
 select * into cfg from economy_config where id=true;show_amount:=floor(fee*cfg.profession_show_fund_percent/100);treasury_amount:=fee-show_amount;
 update system_funds set balance=balance+show_amount,lifetime_inflow=lifetime_inflow+show_amount where id='show_fund';update system_funds set balance=balance+treasury_amount,lifetime_inflow=lifetime_inflow+treasury_amount where id='treasury';
 if show_amount>0 then insert into system_fund_ledger(fund_id,amount,transaction_type,source,destination,initiated_by,reason,related_id) values('show_fund',show_amount,'profession_fee_allocation','Player','LE Show Fund',payer,reason_text,related);end if;
 if treasury_amount>0 then insert into system_fund_ledger(fund_id,amount,transaction_type,source,destination,initiated_by,reason,related_id) values('treasury',treasury_amount,'profession_fee_allocation','Player','LE Treasury',payer,reason_text,related);end if;end$$;

create or replace function public.enroll_profession(target_profession text) returns void language plpgsql security definer set search_path=public as $$declare p professions;s stables;begin
 if exists(select 1 from player_professions where stable_id=auth.uid() and profession_id=target_profession) then raise exception 'You are already permanently enrolled';end if;select * into p from professions where id=target_profession and active;select * into s from stables where id=auth.uid() for update;if p.id is null then raise exception 'Profession not found';end if;if s.balance<p.enrollment_fee then raise exception 'You need % LED to enroll',p.enrollment_fee;end if;
 update stables set balance=balance-p.enrollment_fee where id=s.id;insert into currency_ledger(stable_id,amount,reason) values(s.id,-p.enrollment_fee,p.name||' enrollment fee');perform allocate_profession_fee(s.id,p.enrollment_fee,p.name||' enrollment fee');
 insert into player_professions(stable_id,profession_id) values(s.id,p.id);insert into player_study_progress(stable_id,profession_id,level) values(s.id,p.id,1);end$$;

create or replace function public.get_profession_dashboard() returns jsonb language sql security definer set search_path=public stable as $$
 select jsonb_build_object('professions',coalesce(jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'description',p.description,'enrollment_fee',p.enrollment_fee,'level',coalesce(pp.certification_level,0),'level_name',coalesce(cl.name,'Not enrolled'),'available',coalesce(pp.available,false),'client_services',coalesce(pp.lifetime_client_services,0),'self_services',coalesce(pp.lifetime_self_services,0),'qualifying_credit',coalesce(pp.qualifying_credit,0),'study_completed',sp.completed_at is not null,'required_services',coalesce(nextcl.required_services,0),'exam_fee',coalesce(nextcl.exam_fee,0),'next_level',case when coalesce(pp.certification_level,0)<4 then coalesce(pp.certification_level,0)+1 end) order by p.sort_order),'[]')) from professions p left join player_professions pp on pp.profession_id=p.id and pp.stable_id=auth.uid() left join certification_levels cl on cl.level=pp.certification_level left join certification_levels nextcl on nextcl.level=coalesce(pp.certification_level,0)+1 left join player_study_progress sp on sp.stable_id=auth.uid() and sp.profession_id=p.id and sp.level=coalesce(pp.certification_level,0)+1 where p.active $$;

create or replace function public.take_certification_test(target_profession text,target_level integer,submitted_answers jsonb) returns jsonb language plpgsql security definer set search_path=public as $$declare pp player_professions;cfg certification_levels;latest timestamptz;correct int;total int;score numeric;passed boolean;s stables;pname text;attempt_id uuid;begin
 select * into pp from player_professions where stable_id=auth.uid() and profession_id=target_profession for update;if not found then raise exception 'Enroll first';end if;if target_level<>pp.certification_level+1 then raise exception 'Invalid certification level';end if;
 if not exists(select 1 from player_study_progress where stable_id=auth.uid() and profession_id=target_profession and level=target_level and completed_at is not null) then raise exception 'Complete Study first';end if;select * into cfg from certification_levels where level=target_level;select max(created_at) into latest from certification_attempts where stable_id=auth.uid() and profession_id=target_profession and level=target_level;if latest is not null and latest>now()-make_interval(mins=>cfg.retry_cooldown_minutes) then raise exception 'Certification retest cooldown is active';end if;
 select * into s from stables where id=auth.uid() for update;if s.balance<cfg.exam_fee then raise exception 'You need % more LED for this exam',cfg.exam_fee-s.balance;end if;select name into pname from professions where id=target_profession;
 select count(*),count(*) filter(where (submitted_answers->>q.id::text)::int=q.correct_index) into total,correct from certification_questions q where q.profession_id=target_profession and q.level=target_level and q.active;if total=0 then raise exception 'No active questions configured';end if;score:=round(correct::numeric/total*100,2);passed:=score>=cfg.passing_score;
 update stables set balance=balance-cfg.exam_fee where id=s.id;insert into currency_ledger(stable_id,amount,reason) values(s.id,-cfg.exam_fee,pname||' certification exam fee');
 insert into certification_attempts(stable_id,profession_id,level,score,passed,answers) values(s.id,target_profession,target_level,score,passed,submitted_answers) returning id into attempt_id;perform allocate_profession_fee(s.id,cfg.exam_fee,pname||' certification exam fee',attempt_id);
 if passed then update player_professions set certification_level=target_level,certified_at=now(),available=true where stable_id=s.id and profession_id=target_profession;end if;return jsonb_build_object('score',score,'passed',passed,'passing_score',cfg.passing_score,'fee_paid',cfg.exam_fee);end$$;

create or replace function public.treasury_award(target_stable uuid,award_amount bigint,award_reason text,award_category text,internal_note text default null) returns uuid language plpgsql security definer set search_path=public as $$declare entry_id uuid;begin perform require_super_admin();if award_amount<=0 then raise exception 'Award must be positive';end if;update system_funds set balance=balance-award_amount,lifetime_outflow=lifetime_outflow+award_amount where id='treasury' and balance>=award_amount;if not found then raise exception 'Treasury has insufficient LED';end if;update stables set balance=balance+award_amount where id=target_stable;if not found then raise exception 'Recipient not found';end if;insert into currency_ledger(stable_id,amount,reason) values(target_stable,award_amount,'Treasury award: '||award_reason);insert into system_fund_ledger(fund_id,amount,transaction_type,source,destination,initiated_by,reason,internal_note) values('treasury',-award_amount,award_category,'LE Treasury',(select name||' #'||account_number from stables where id=target_stable),auth.uid(),award_reason,internal_note) returning id into entry_id;return entry_id;end$$;
create or replace function public.treasury_to_show_fund(transfer_amount bigint,transfer_reason text,internal_note text default null) returns uuid language plpgsql security definer set search_path=public as $$declare entry_id uuid;begin perform require_super_admin();if transfer_amount<=0 then raise exception 'Transfer must be positive';end if;update system_funds set balance=balance-transfer_amount,lifetime_outflow=lifetime_outflow+transfer_amount where id='treasury' and balance>=transfer_amount;if not found then raise exception 'Treasury has insufficient LED';end if;update system_funds set balance=balance+transfer_amount,lifetime_inflow=lifetime_inflow+transfer_amount where id='show_fund';insert into system_fund_ledger(fund_id,amount,transaction_type,source,destination,initiated_by,reason,internal_note) values('treasury',-transfer_amount,'show_fund_transfer','LE Treasury','LE Show Fund',auth.uid(),transfer_reason,internal_note) returning id into entry_id;insert into system_fund_ledger(fund_id,amount,transaction_type,source,destination,initiated_by,reason,internal_note,related_id) values('show_fund',transfer_amount,'treasury_transfer','LE Treasury','LE Show Fund',auth.uid(),transfer_reason,internal_note,entry_id);return entry_id;end$$;

alter table public.horses add column career_points integer not null default 0 check(career_points>=0);
create table public.show_disciplines(id text primary key,name text not null unique,stat_weights jsonb not null,active boolean not null default true);
insert into public.show_disciplines values('racing','Racing','{"Speed":1,"Endurance":1}',true),('jumping','Jumping','{"Agility":1,"Strength":1,"Conformation":0.5}',true),('horsemanship','Horsemanship','{"Temperament":1,"Intelligence":1,"Agility":0.5}',true),('draghunting','Draghunting','{"Endurance":1,"Strength":0.5,"Agility":0.5}',true);
create table public.show_tiers(id text primary key,name text not null unique,minimum_points integer not null,maximum_points integer,sort_order integer not null,active boolean not null default true,check(maximum_points is null or maximum_points>=minimum_points));
insert into public.show_tiers values('novice','Novice',0,99,1,true),('intermediate','Intermediate',100,249,2,true),('advanced','Advanced',250,499,3,true),('elite','Elite',500,null,4,true);
create table public.show_placement_rules(placement integer primary key,career_points integer not null,prize_percent numeric(5,2) not null check(prize_percent>=0));insert into public.show_placement_rules values(1,25,50),(2,15,30),(3,10,20),(4,5,0),(5,3,0);
create table public.player_shows(id uuid primary key default gen_random_uuid(),creator_id uuid not null references public.stables(id),name text not null,discipline_id text not null references public.show_disciplines(id),tier_id text not null references public.show_tiers(id),run_date date not null,run_at timestamptz not null,entry_fee bigint not null default 0,max_entries integer,maximum_per_owner integer not null default 1,description text not null default '',status text not null default 'open' check(status in('open','processing','complete','cancelled')),entry_fee_purse bigint not null default 0,show_fund_allocation bigint not null default 0,treasury_allocation bigint not null default 0,processed_at timestamptz,created_at timestamptz not null default now());
create table public.player_show_entries(id uuid primary key default gen_random_uuid(),show_id uuid not null references public.player_shows(id),horse_id uuid not null references public.horses(id),owner_id uuid not null references public.stables(id),tier_id text not null references public.show_tiers(id),career_points_snapshot integer not null,entered_at timestamptz not null default now(),unique(show_id,horse_id));
create table public.player_show_results(id uuid primary key default gen_random_uuid(),show_id uuid not null references public.player_shows(id),entry_id uuid not null unique references public.player_show_entries(id),horse_id uuid not null references public.horses(id),owner_id uuid not null references public.stables(id),placement integer not null,competition_score numeric not null,base_contribution numeric not null,tack_contribution numeric not null,service_contribution numeric not null,career_points_awarded integer not null,led_winnings bigint not null,created_at timestamptz not null default now());
alter table public.show_disciplines enable row level security;alter table public.show_tiers enable row level security;alter table public.show_placement_rules enable row level security;alter table public.player_shows enable row level security;alter table public.player_show_entries enable row level security;alter table public.player_show_results enable row level security;
create policy "show disciplines readable" on public.show_disciplines for select using(true);create policy "show tiers readable" on public.show_tiers for select using(true);create policy "placement rules readable" on public.show_placement_rules for select using(true);create policy "player shows readable" on public.player_shows for select using(true);create policy "show entries readable" on public.player_show_entries for select using(true);create policy "show results readable" on public.player_show_results for select using(true);

create or replace function public.create_player_show(show_name text,target_discipline text,target_tier text,target_run_date date,new_entry_fee bigint default 0,new_max_entries integer default null,new_description text default '') returns public.player_shows language plpgsql security definer set search_path=public as $$declare result player_shows;s stables;cfg economy_config;scheduled timestamptz;begin
 select * into s from stables where id=auth.uid() for update;select * into cfg from economy_config where id=true;if length(trim(show_name)) not between 3 and 80 then raise exception 'Show name must be 3–80 characters';end if;if not exists(select 1 from show_disciplines where id=target_discipline and active) or not exists(select 1 from show_tiers where id=target_tier and active) then raise exception 'Choose an active discipline and tier';end if;if new_entry_fee<0 or new_entry_fee>cfg.show_entry_fee_max then raise exception 'Entry fee is outside the permitted range';end if;if new_max_entries is not null and new_max_entries not between 2 and 1000 then raise exception 'Maximum entries must be 2–1,000';end if;scheduled:=(target_run_date::timestamp at time zone 'America/New_York');if scheduled<=now() then raise exception 'Run date must be in the future';end if;if s.balance<cfg.show_hosting_fee then raise exception 'Insufficient LED for hosting fee';end if;
 if cfg.show_hosting_fee>0 then update stables set balance=balance-cfg.show_hosting_fee where id=s.id;insert into currency_ledger(stable_id,amount,reason) values(s.id,-cfg.show_hosting_fee,'Show hosting fee');end if;
 insert into player_shows(creator_id,name,discipline_id,tier_id,run_date,run_at,entry_fee,max_entries,description) values(s.id,trim(show_name),target_discipline,target_tier,target_run_date,scheduled,new_entry_fee,new_max_entries,left(coalesce(new_description,''),1000)) returning * into result;return result;end$$;

create or replace function public.enter_player_show(target_show uuid,target_horse uuid) returns public.player_show_entries language plpgsql security definer set search_path=public as $$declare sh player_shows;h horses;t show_tiers;s stables;result player_show_entries;begin select * into sh from player_shows where id=target_show for update;if sh.status<>'open' or sh.run_at<=now() then raise exception 'Show is no longer open';end if;if sh.max_entries is not null and(select count(*) from player_show_entries where show_id=sh.id)>=sh.max_entries then raise exception 'Show is full';end if;if(select count(*) from player_show_entries where show_id=sh.id and owner_id=auth.uid())>=sh.maximum_per_owner then raise exception 'Owner entry limit reached';end if;select * into h from horses where id=target_horse for update;if h.owner_id<>auth.uid() then raise exception 'Choose a horse you own';end if;select * into t from show_tiers where id=sh.tier_id;if h.career_points<t.minimum_points or(t.maximum_points is not null and h.career_points>t.maximum_points) then raise exception 'Horse is not eligible for this Career Point tier';end if;select * into s from stables where id=auth.uid() for update;if s.balance<sh.entry_fee then raise exception 'Insufficient LED for entry fee';end if;if sh.entry_fee>0 then update stables set balance=balance-sh.entry_fee where id=s.id;update player_shows set entry_fee_purse=entry_fee_purse+sh.entry_fee where id=sh.id;insert into currency_ledger(stable_id,amount,reason,horse_id) values(s.id,-sh.entry_fee,'Show entry: '||sh.name,h.id);end if;insert into player_show_entries(show_id,horse_id,owner_id,tier_id,career_points_snapshot) values(sh.id,h.id,s.id,sh.tier_id,h.career_points) returning * into result;return result;exception when unique_violation then raise exception 'Horse is already entered';end$$;

create or replace function public.get_player_shows() returns table(id uuid,name text,discipline text,tier text,run_at timestamptz,entry_fee bigint,max_entries integer,entry_count bigint,description text,creator_name text,creator_account bigint,status text) language sql security definer set search_path=public stable as $$select sh.id,sh.name,d.name,t.name,sh.run_at,sh.entry_fee,sh.max_entries,count(e.id),sh.description,s.name,s.account_number,sh.status from player_shows sh join show_disciplines d on d.id=sh.discipline_id join show_tiers t on t.id=sh.tier_id join stables s on s.id=sh.creator_id left join player_show_entries e on e.show_id=sh.id where sh.status in('open','complete') group by sh.id,d.name,t.name,s.name,s.account_number order by sh.run_at$$;

create or replace function public.show_fund_fund_show(target_show uuid,funding_amount bigint,funding_reason text,internal_note text default null) returns uuid language plpgsql security definer set search_path=public as $$declare entry_id uuid;cfg economy_config;spent_daily bigint;spent_weekly bigint;begin perform require_super_admin();if funding_amount<=0 then raise exception 'Funding must be positive';end if;select * into cfg from economy_config where id=true;select coalesce(-sum(amount),0) into spent_daily from system_fund_ledger where fund_id='show_fund' and transaction_type='show_funding' and amount<0 and created_at>=date_trunc('day',now());select coalesce(-sum(amount),0) into spent_weekly from system_fund_ledger where fund_id='show_fund' and transaction_type='show_funding' and amount<0 and created_at>=date_trunc('week',now());if spent_daily+funding_amount>cfg.show_fund_daily_budget or spent_weekly+funding_amount>cfg.show_fund_weekly_budget then raise exception 'Show Fund budget limit exceeded';end if;update player_shows set show_fund_allocation=show_fund_allocation+funding_amount where id=target_show and status='open';if not found then raise exception 'Open show not found';end if;update system_funds set balance=balance-funding_amount,lifetime_outflow=lifetime_outflow+funding_amount where id='show_fund' and balance-funding_amount>=cfg.show_fund_reserve;if not found then raise exception 'Show Fund balance or reserve is insufficient';end if;insert into system_fund_ledger(fund_id,amount,transaction_type,source,destination,initiated_by,reason,internal_note,related_id) values('show_fund',-funding_amount,'show_funding','LE Show Fund',(select name from player_shows where id=target_show),auth.uid(),funding_reason,internal_note,target_show) returning id into entry_id;return entry_id;end$$;

-- Service-role show processor. Deterministic ordering; no random performance roll.
create or replace function public.process_due_player_shows() returns integer language plpgsql security definer set search_path=public as $$declare sh player_shows;ent record;weights jsonb;purse bigint;rule show_placement_rules;rank_no int;processed int:=0;begin
 for sh in select * from player_shows where status='open' and run_at<=now() order by run_at for update skip locked loop update player_shows set status='processing' where id=sh.id;rank_no:=0;purse:=sh.entry_fee_purse+sh.show_fund_allocation+sh.treasury_allocation;select stat_weights into weights from show_disciplines where id=sh.discipline_id;
  for ent in select scored.* from(select e.*,sum(coalesce((h.stats->>w.key)::numeric,0)*(w.value::text)::numeric) base_score,sum(coalesce((h.tack_bonuses->>w.key)::numeric,0)*(w.value::text)::numeric) tack_score,coalesce((select sum((effect_item.value::text)::numeric*(weights->>effect_item.key)::numeric) from horse_service_records r cross join lateral jsonb_each(r.effect) effect_item where r.horse_id=h.id and r.status='completed' and(r.effect_expires_at is null or r.effect_expires_at>sh.run_at) and weights ? effect_item.key),0) service_score from player_show_entries e join horses h on h.id=e.horse_id cross join lateral jsonb_each(weights) w where e.show_id=sh.id group by e.id,h.id) scored order by(scored.base_score+scored.tack_score+scored.service_score) desc,scored.base_score desc,scored.career_points_snapshot desc,scored.entered_at,scored.horse_id loop
   rank_no:=rank_no+1;select * into rule from show_placement_rules where placement=rank_no;insert into player_show_results(show_id,entry_id,horse_id,owner_id,placement,competition_score,base_contribution,tack_contribution,service_contribution,career_points_awarded,led_winnings) values(sh.id,ent.id,ent.horse_id,ent.owner_id,rank_no,ent.base_score+ent.tack_score+ent.service_score,ent.base_score,ent.tack_score,ent.service_score,coalesce(rule.career_points,0),floor(purse*coalesce(rule.prize_percent,0)/100));update horses set career_points=career_points+coalesce(rule.career_points,0) where id=ent.horse_id;if coalesce(rule.prize_percent,0)>0 then update stables set balance=balance+floor(purse*rule.prize_percent/100) where id=ent.owner_id;insert into currency_ledger(stable_id,amount,reason,horse_id) values(ent.owner_id,floor(purse*rule.prize_percent/100),'Show winnings: '||sh.name,ent.horse_id);end if;end loop;update player_shows set status='complete',processed_at=now() where id=sh.id;processed:=processed+1;end loop;return processed;end$$;

revoke all on function public.require_super_admin(),public.allocate_profession_fee(uuid,bigint,text,uuid),public.treasury_award(uuid,bigint,text,text,text),public.treasury_to_show_fund(bigint,text,text),public.show_fund_fund_show(uuid,bigint,text,text),public.create_player_show(text,text,text,date,bigint,integer,text),public.enter_player_show(uuid,uuid),public.process_due_player_shows() from public;
grant execute on function public.enroll_profession(text),public.take_certification_test(text,integer,jsonb),public.get_profession_dashboard(),public.treasury_award(uuid,bigint,text,text,text),public.treasury_to_show_fund(bigint,text,text),public.show_fund_fund_show(uuid,bigint,text,text),public.create_player_show(text,text,text,date,bigint,integer,text),public.enter_player_show(uuid,uuid),public.get_player_shows() to authenticated;
grant execute on function public.process_due_player_shows() to service_role;

-- Supabase cron runs this server-side; due timestamps already encode midnight America/New_York.
create extension if not exists pg_cron with schema extensions;
select cron.schedule('le-process-player-shows','*/5 * * * *','select public.process_due_player_shows();');
