-- Database-driven realtime Community rooms with granular moderation authority.
create type public.community_role as enum('player','moderator','admin','owner');
alter table public.stables add column community_role public.community_role not null default 'player';
update public.stables set community_role=case when account_number=1 then 'owner'::community_role when is_admin then 'admin'::community_role else 'player'::community_role end;

create table public.chat_rooms(
 id uuid primary key default gen_random_uuid(),name text not null unique check(length(name) between 2 and 60),description text not null default '',display_order integer not null default 0,
 icon text not null default '💬',rules text not null default '',read_permission text not null default 'players' check(read_permission in('players','staff')),
 post_permission text not null default 'players' check(post_permission in('players','staff')),active boolean not null default true,archived_at timestamptz,locked boolean not null default false,read_only boolean not null default false,
 created_by uuid not null references public.stables(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.chat_messages(
 id uuid primary key default gen_random_uuid(),room_id uuid not null references public.chat_rooms(id),author_id uuid not null references public.stables(id),content text not null check(length(content) between 1 and 1000),
 entity_refs jsonb not null default '[]' check(jsonb_typeof(entity_refs)='array'),edited_at timestamptz,moderation_status text not null default 'visible' check(moderation_status in('visible','hidden')),
 moderated_by uuid references public.stables(id),moderated_at timestamptz,moderation_reason text,created_at timestamptz not null default now()
);
create index chat_messages_room_time_idx on public.chat_messages(room_id,created_at desc);
create table public.chat_mutes(id uuid primary key default gen_random_uuid(),stable_id uuid not null references public.stables(id),room_id uuid references public.chat_rooms(id),muted_by uuid not null references public.stables(id),reason text not null,expires_at timestamptz not null,created_at timestamptz not null default now());
create index chat_mutes_active_idx on public.chat_mutes(stable_id,room_id,expires_at);
create table public.community_audit_log(id uuid primary key default gen_random_uuid(),actor_id uuid not null references public.stables(id),action text not null,target_type text not null,target_id uuid,reason text,details jsonb not null default '{}',created_at timestamptz not null default now());

insert into public.chat_rooms(name,description,display_order,icon,rules,created_by)
select v.name,v.description,v.display_order,v.icon,'Be kind, stay constructive, and keep conversation appropriate for Legacy Equine.',s.id from(values
 ('General','General Legacy Equine conversation.',10,'💬'),('Horse Sales & Breeding','Horses for sale, stud advertisements, and breeding discussion.',20,'🐴'),('Shows','Competition discussion and upcoming shows.',30,'🏆'),
 ('Artwork','Horse artwork, profile images, and commissions.',40,'🎨'),('Professional Services','Farriers, Trainers, Veterinarians, and Massage Therapists.',50,'🩺'),('Help','Questions about Legacy Equine gameplay.',60,'✨')
)v(name,description,display_order,icon) cross join lateral(select id from public.stables where account_number=1 limit 1)s;

alter table public.chat_rooms enable row level security;alter table public.chat_messages enable row level security;alter table public.chat_mutes enable row level security;alter table public.community_audit_log enable row level security;
create policy "authenticated rooms readable" on public.chat_rooms for select to authenticated using(archived_at is null and(read_permission='players' or exists(select 1 from stables where id=auth.uid() and community_role in('moderator','admin','owner'))));
create policy "authenticated visible messages readable" on public.chat_messages for select to authenticated using(moderation_status='visible' or author_id=auth.uid() or exists(select 1 from stables where id=auth.uid() and community_role in('moderator','admin','owner')));

create or replace function public.community_staff(required_role text default 'moderator') returns boolean language sql security definer set search_path=public stable as $$select exists(select 1 from stables where id=auth.uid() and case required_role when 'admin' then community_role in('admin','owner') else community_role in('moderator','admin','owner') end)$$;
create or replace function public.get_chat_rooms() returns table(id uuid,name text,description text,display_order integer,icon text,rules text,read_permission text,post_permission text,active boolean,archived_at timestamptz,locked boolean,read_only boolean) language sql security definer set search_path=public stable as $$select r.id,r.name,r.description,r.display_order,r.icon,r.rules,r.read_permission,r.post_permission,r.active,r.archived_at,r.locked,r.read_only from chat_rooms r where r.archived_at is null and(r.read_permission='players' or community_staff()) order by r.display_order,r.name$$;
create or replace function public.get_chat_messages(target_room uuid,before_time timestamptz default null,page_size integer default 50) returns table(id uuid,room_id uuid,content text,created_at timestamptz,edited_at timestamptz,moderation_status text,moderation_reason text,author_id uuid,stable_name text,username text,account_number bigint,avatar_url text,community_role community_role) language plpgsql security definer set search_path=public stable as $$begin if not exists(select 1 from chat_rooms r where r.id=target_room and r.archived_at is null and(r.read_permission='players' or community_staff())) then raise exception 'Chat room is unavailable';end if;return query select m.id,m.room_id,case when m.moderation_status='hidden' then '[Message removed by Community staff]' else m.content end,m.created_at,m.edited_at,m.moderation_status,case when community_staff() then m.moderation_reason end,m.author_id,s.name,s.username,s.account_number,s.avatar_url,s.community_role from chat_messages m join stables s on s.id=m.author_id where m.room_id=target_room and(before_time is null or m.created_at<before_time) and(m.moderation_status='visible' or m.author_id=auth.uid() or community_staff()) order by m.created_at desc limit least(greatest(page_size,1),100);end$$;

create or replace function public.send_chat_message(target_room uuid,message_content text,refs jsonb default '[]') returns chat_messages language plpgsql security definer set search_path=public as $$declare r chat_rooms;s stables;result chat_messages;last_message chat_messages;begin select * into s from stables where id=auth.uid();if s.username is null then raise exception 'Create a username in Settings before chatting';end if;select * into r from chat_rooms where id=target_room for update;if not found or not r.active or r.archived_at is not null then raise exception 'Chat room is unavailable';end if;if r.locked or r.read_only then raise exception 'This room is currently read-only';end if;if r.post_permission='staff' and not community_staff() then raise exception 'Only Community staff may post here';end if;if exists(select 1 from chat_mutes m where m.stable_id=s.id and(m.room_id is null or m.room_id=r.id) and m.expires_at>now()) then raise exception 'You are temporarily muted from this chat';end if;if length(trim(message_content)) not between 1 and 1000 then raise exception 'Messages must be 1–1,000 characters';end if;select * into last_message from chat_messages where author_id=s.id order by created_at desc limit 1;if last_message.created_at>now()-interval '3 seconds' then raise exception 'Please wait a moment before sending another message';end if;if last_message.created_at>now()-interval '2 minutes' and lower(last_message.content)=lower(trim(message_content)) then raise exception 'Please do not repeat the same message';end if;insert into chat_messages(room_id,author_id,content,entity_refs) values(r.id,s.id,trim(message_content),coalesce(refs,'[]')) returning * into result;return result;end$$;

create or replace function public.manage_chat_room(target_room uuid,room_name text,short_description text,new_display_order integer,room_icon text,room_rules text,new_read_permission text,new_post_permission text,is_active boolean,is_locked boolean,is_read_only boolean,archive_room boolean default false) returns chat_rooms language plpgsql security definer set search_path=public as $$declare result chat_rooms;action_name text;begin if not community_staff('admin') then raise exception 'Community Admin access required';end if;if target_room is null then insert into chat_rooms(name,description,display_order,icon,rules,read_permission,post_permission,active,locked,read_only,created_by) values(trim(room_name),left(coalesce(short_description,''),240),new_display_order,left(coalesce(nullif(room_icon,''),'💬'),12),left(coalesce(room_rules,''),2000),new_read_permission,new_post_permission,is_active,is_locked,is_read_only,auth.uid()) returning * into result;action_name:='room_created';else update chat_rooms set name=trim(room_name),description=left(coalesce(short_description,''),240),display_order=new_display_order,icon=left(coalesce(nullif(room_icon,''),'💬'),12),rules=left(coalesce(room_rules,''),2000),read_permission=new_read_permission,post_permission=new_post_permission,active=is_active,locked=is_locked,read_only=is_read_only,archived_at=case when archive_room then now() else archived_at end,updated_at=now() where id=target_room returning * into result;if not found then raise exception 'Room not found';end if;action_name:=case when archive_room then 'room_archived' else 'room_updated' end;end if;insert into community_audit_log(actor_id,action,target_type,target_id,details) values(auth.uid(),action_name,'chat_room',result.id,jsonb_build_object('name',result.name,'locked',result.locked,'read_only',result.read_only));return result;end$$;
create or replace function public.moderate_chat_message(target_message uuid,hide_message boolean,reason text) returns void language plpgsql security definer set search_path=public as $$begin if not community_staff() then raise exception 'Community moderation access required';end if;update chat_messages set moderation_status=case when hide_message then 'hidden' else 'visible' end,moderated_by=auth.uid(),moderated_at=now(),moderation_reason=left(trim(reason),500) where id=target_message;if not found then raise exception 'Message not found';end if;insert into community_audit_log(actor_id,action,target_type,target_id,reason) values(auth.uid(),case when hide_message then 'message_hidden' else 'message_restored' end,'chat_message',target_message,left(trim(reason),500));end$$;
create or replace function public.mute_chat_user(target_stable uuid,target_room uuid,mute_minutes integer,reason text) returns uuid language plpgsql security definer set search_path=public as $$declare result uuid;begin if not community_staff() then raise exception 'Community moderation access required';end if;if mute_minutes not between 1 and 43200 then raise exception 'Mute duration must be 1 minute–30 days';end if;insert into chat_mutes(stable_id,room_id,muted_by,reason,expires_at) values(target_stable,target_room,auth.uid(),left(trim(reason),500),now()+make_interval(mins=>mute_minutes)) returning id into result;insert into community_audit_log(actor_id,action,target_type,target_id,reason,details) values(auth.uid(),'user_muted','stable',target_stable,left(trim(reason),500),jsonb_build_object('room_id',target_room,'minutes',mute_minutes));return result;end$$;
create or replace function public.get_community_audit() returns table(id uuid,actor_name text,actor_account bigint,action text,target_type text,target_id uuid,reason text,details jsonb,created_at timestamptz) language sql security definer set search_path=public stable as $$select a.id,s.name,s.account_number,a.action,a.target_type,a.target_id,a.reason,a.details,a.created_at from community_audit_log a join stables s on s.id=a.actor_id where community_staff() order by a.created_at desc limit 200$$;

revoke all on function public.community_staff(text),public.get_chat_rooms(),public.get_chat_messages(uuid,timestamptz,integer),public.send_chat_message(uuid,text,jsonb),public.manage_chat_room(uuid,text,text,integer,text,text,text,text,boolean,boolean,boolean,boolean),public.moderate_chat_message(uuid,boolean,text),public.mute_chat_user(uuid,uuid,integer,text),public.get_community_audit() from public;
grant execute on function public.get_chat_rooms(),public.get_chat_messages(uuid,timestamptz,integer),public.send_chat_message(uuid,text,jsonb),public.manage_chat_room(uuid,text,text,integer,text,text,text,text,boolean,boolean,boolean,boolean),public.moderate_chat_message(uuid,boolean,text),public.mute_chat_user(uuid,uuid,integer,text),public.get_community_audit() to authenticated;
alter publication supabase_realtime add table public.chat_messages,public.chat_rooms;
