-- Store departments, per-breed Foundation inventory, optional feed development,
-- equipment-only tack, activity-based Wellness, and continuous 28-day horse years.

-- Preserve every existing horse's displayed age while changing to the authoritative rate.
update public.horses set birth_date=now()-(interval '28 days'*(greatest(0,extract(epoch from(now()-birth_date))/86400*30/365.25)));
create table if not exists public.horse_game_config(
 id boolean primary key default true check(id),real_days_per_horse_year numeric not null default 28 check(real_days_per_horse_year>0),
 wellness_max integer not null default 100,readiness_health_weight numeric not null default .34,readiness_hooves_weight numeric not null default .33,readiness_recovery_weight numeric not null default .33,
 training_recovery_wear integer not null default 3,show_recovery_wear integer not null default 5,show_hoof_wear integer not null default 2,
 passive_recovery_per_real_day numeric not null default 8,very_poor_threshold integer not null default 25,poor_threshold integer not null default 45,fair_threshold integer not null default 65,good_threshold integer not null default 85
);
insert into public.horse_game_config(id) values(true) on conflict(id) do nothing;
create or replace function public.horse_game_age(p_birth timestamptz,p_at timestamptz default now()) returns numeric language sql stable as $$
 select greatest(0,extract(epoch from(p_at-p_birth))/86400/(select real_days_per_horse_year from public.horse_game_config where id=true))
$$;

alter table public.foundation_breeds add column if not exists store_inventory_size integer not null default 4 check(store_inventory_size between 1 and 12);
alter table public.foundation_breeds add column if not exists store_price integer check(store_price is null or store_price>=0);
alter table public.foundation_breeds add column if not exists store_rotation_minutes integer check(store_rotation_minutes between 15 and 1440);
alter table public.store_settings drop constraint if exists store_settings_inventory_size_check;
alter table public.store_settings alter column inventory_size set default 4;
update public.store_settings set inventory_size=4,foundation_price=1000,rotation_minutes=60 where singleton;
alter table public.store_settings add constraint store_settings_inventory_size_check check(inventory_size between 1 and 12);

create or replace function public.refresh_store_inventory() returns void language plpgsql security definer set search_path=public as $$
declare cfg store_settings;b foundation_breeds;active_count integer;oldest timestamptz;rotation timestamptz;horse uuid;i integer;target integer;minutes integer;price integer;begin
 perform pg_advisory_xact_lock(674381);select * into cfg from store_settings where singleton;
 for b in select * from foundation_breeds where active order by sort_order loop
  target:=coalesce(b.store_inventory_size,cfg.inventory_size);minutes:=coalesce(b.store_rotation_minutes,cfg.rotation_minutes);price:=coalesce(b.store_price,cfg.foundation_price);
  select count(*),min(si.generated_at) into active_count,oldest from store_inventory si join horses h on h.id=si.horse_id where si.status='active' and h.breed=b.name;
  if active_count=0 or oldest<=now()-make_interval(mins=>minutes) then update store_inventory si set status='expired' from horses h where h.id=si.horse_id and si.status='active' and h.breed=b.name;active_count:=0;rotation:=now();else select max(si.rotation_key) into rotation from store_inventory si join horses h on h.id=si.horse_id where si.status='active' and h.breed=b.name;end if;
  if active_count<target then for i in active_count+1..target loop horse:=generate_store_horse(coalesce(rotation,now()),b.name);insert into store_inventory(horse_id,price,rotation_key) values(horse,price,coalesce(rotation,now()));end loop;end if;
 end loop;
end$$;
create or replace function public.get_store_inventory(p_breed text default null)
returns table(inventory_id uuid,horse_id uuid,name text,breed text,sex horse_sex,color text,birth_date timestamptz,stats jsonb,image_url text,mature_height_hands numeric,price integer,generated_at timestamptz,rotation_key timestamptz)
language plpgsql security definer set search_path=public as $$begin perform refresh_store_inventory();return query select si.id,h.id,h.name,h.breed,h.sex,h.color,h.birth_date,h.stats,h.image_url,h.mature_height_hands,si.price,si.generated_at,si.rotation_key from store_inventory si join horses h on h.id=si.horse_id where si.status='active' and(p_breed is null or h.breed=p_breed) order by h.breed,si.generated_at,h.name;end$$;
drop function if exists public.get_store_inventory();
create function public.get_store_inventory() returns table(inventory_id uuid,horse_id uuid,name text,breed text,sex horse_sex,color text,birth_date timestamptz,stats jsonb,image_url text,mature_height_hands numeric,price integer,generated_at timestamptz,rotation_key timestamptz) language sql security definer set search_path=public as $$select * from get_store_inventory(null)$$;

create table public.store_products(
 id text primary key,department text not null check(department in('feed','tack','stable_supplies')),name text not null,description text not null default '',price integer not null check(price>=0),active boolean not null default true,
 feed_success_probability numeric check(feed_success_probability between 0 and 1),development_min integer,development_max integer,eligible_stats text[],
 tack_slot text check(tack_slot in('bridle','saddle','saddle_pad','leg_protection')),quality text,tack_bonuses jsonb not null default '{}',discipline_orientation text[] not null default '{}',sort_order integer not null default 0,
 check(development_min is null or development_max>=development_min)
);
insert into public.store_products(id,department,name,description,price,feed_success_probability,development_min,development_max,eligible_stats,sort_order) values
('basic_hay','feed','Basic Hay','A simple optional daily development opportunity.',25,.15,1,1,array['Endurance','Temperament'],1),
('quality_hay','feed','Quality Hay','Quality forage with a stronger development chance.',50,.28,1,1,array['Endurance','Temperament','Strength'],2),
('performance_feed','feed','Performance Feed','Balanced performance nutrition; never required.',100,.42,1,2,array['Agility','Speed','Endurance','Temperament','Strength','Intelligence','Conformation'],3),
('premium_performance_feed','feed','Premium Performance Feed','The strongest optional daily feed opportunity.',175,.58,1,3,array['Agility','Speed','Endurance','Temperament','Strength','Intelligence','Conformation'],4)
on conflict(id) do nothing;
insert into public.store_products(id,department,name,description,price,tack_slot,quality,tack_bonuses,discipline_orientation,sort_order) values
('basic_bridle','tack','Basic Bridle','A practical everyday bridle.',120,'bridle','Basic','{"Temperament":1}',array['horsemanship'],10),
('quality_saddle','tack','Quality All-Purpose Saddle','Balanced support for several disciplines.',300,'saddle','Quality','{"Agility":1,"Strength":1}',array['jumping','hunters'],11),
('racing_saddle','tack','Performance Racing Saddle','Lightweight racing-oriented equipment.',550,'saddle','Performance','{"Speed":2,"Endurance":1}',array['racing'],12),
('comfort_pad','tack','Quality Saddle Pad','A supportive all-purpose pad.',180,'saddle_pad','Quality','{"Temperament":1}',array[]::text[],13),
('performance_boots','tack','Performance Leg Boots','Sport protection with a modest effective bonus.',275,'leg_protection','Performance','{"Agility":1}',array['jumping','reining'],14)
on conflict(id) do nothing;
create table public.player_store_items(id uuid primary key default gen_random_uuid(),stable_id uuid not null references stables(id),product_id text not null references store_products(id),purchased_price integer not null,purchased_at timestamptz not null default now(),consumed_at timestamptz);
create table public.horse_equipment(id uuid primary key default gen_random_uuid(),horse_id uuid not null references horses(id),item_id uuid not null unique references player_store_items(id),slot text not null,equipped_at timestamptz not null default now(),unique(horse_id,slot));
create table public.horse_feed_log(id uuid primary key default gen_random_uuid(),horse_id uuid not null references horses(id),stable_id uuid not null references stables(id),item_id uuid not null unique references player_store_items(id),product_id text not null references store_products(id),fed_at timestamptz not null default now(),le_day date not null,result text not null,stat_affected text,development_amount integer not null default 0,stats_before jsonb not null,stats_after jsonb not null,unique(horse_id,le_day));

create table public.horse_wellness(horse_id uuid primary key references horses(id),health numeric not null default 100 check(health between 0 and 100),hooves numeric not null default 100 check(hooves between 0 and 100),recovery numeric not null default 100 check(recovery between 0 and 100),recovery_anchor timestamptz not null default now(),updated_at timestamptz not null default now());
insert into horse_wellness(horse_id) select id from horses on conflict do nothing;
create or replace function public.ensure_horse_wellness() returns trigger language plpgsql as $$begin insert into horse_wellness(horse_id) values(new.id) on conflict do nothing;return new;end$$;
drop trigger if exists initialize_horse_wellness on horses;create trigger initialize_horse_wellness after insert on horses for each row execute function ensure_horse_wellness();
create or replace function public.materialize_horse_recovery(p_horse uuid,p_at timestamptz default now()) returns horse_wellness language plpgsql security definer set search_path=public as $$declare w horse_wellness;cfg horse_game_config;gain numeric;begin select * into w from horse_wellness where horse_id=p_horse for update;select * into cfg from horse_game_config where id=true;gain:=extract(epoch from(p_at-w.recovery_anchor))/86400*cfg.passive_recovery_per_real_day;update horse_wellness set recovery=least(cfg.wellness_max,recovery+greatest(0,gain)),recovery_anchor=p_at,updated_at=p_at where horse_id=p_horse returning * into w;return w;end$$;
create or replace function public.get_horse_wellness(p_horse uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare w horse_wellness;cfg horse_game_config;ready numeric;label text;begin if not exists(select 1 from horses where id=p_horse)then raise exception 'Horse not found';end if;w:=materialize_horse_recovery(p_horse);select * into cfg from horse_game_config where id=true;ready:=round(w.health*cfg.readiness_health_weight+w.hooves*cfg.readiness_hooves_weight+w.recovery*cfg.readiness_recovery_weight,1);label:=case when ready>=cfg.good_threshold then 'Excellent' when ready>=cfg.fair_threshold then 'Good' when ready>=cfg.poor_threshold then 'Fair' when ready>=cfg.very_poor_threshold then 'Poor' else 'Very Poor' end;return jsonb_build_object('health',round(w.health,1),'hooves',round(w.hooves,1),'recovery',round(w.recovery,1),'readiness',ready,'label',label,'updated_at',w.updated_at);end$$;

create or replace function public.purchase_store_product(p_product text,p_quantity integer default 1) returns jsonb language plpgsql security definer set search_path=public as $$declare product store_products;s stables;i integer;ids uuid[]:='{}';new_id uuid;total integer;begin if p_quantity not between 1 and 25 then raise exception 'Quantity must be 1–25';end if;select * into product from store_products where id=p_product and active for update;if not found then raise exception 'Product unavailable';end if;total:=product.price*p_quantity;select * into s from stables where id=auth.uid() for update;if s.balance<total then raise exception 'Insufficient LED balance';end if;update stables set balance=balance-total where id=s.id;insert into currency_ledger(stable_id,amount,reason)values(s.id,-total,'LE Store — '||product.name||case when p_quantity>1 then ' ×'||p_quantity else '' end);for i in 1..p_quantity loop insert into player_store_items(stable_id,product_id,purchased_price)values(s.id,product.id,product.price)returning id into new_id;ids:=array_append(ids,new_id);end loop;return jsonb_build_object('items',ids,'quantity',p_quantity,'total',total,'balance',s.balance-total);end$$;
create or replace function public.feed_horse(p_horse uuid,p_item uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare h horses;item player_store_items;product store_products;today date;stat text;gain integer:=0;before jsonb;after jsonb;success boolean;begin select * into h from horses where id=p_horse for update;if not found or h.owner_id<>auth.uid() then raise exception 'Choose a horse you own';end if;select * into item from player_store_items where id=p_item and stable_id=auth.uid() and consumed_at is null for update;if not found then raise exception 'Feed item unavailable';end if;select * into product from store_products where id=item.product_id and department='feed' and active;if not found then raise exception 'This item is not Feed & Hay';end if;today:=(now() at time zone 'America/New_York')::date;if exists(select 1 from horse_feed_log where horse_id=h.id and le_day=today)then raise exception 'Today''s Development Feeding is already complete';end if;before:=h.stats;success:=random()<product.feed_success_probability;if success then stat:=product.eligible_stats[1+floor(random()*cardinality(product.eligible_stats))::integer];gain:=product.development_min+floor(random()*(product.development_max-product.development_min+1))::integer;after:=jsonb_set(h.stats,array[stat],to_jsonb(coalesce((h.stats->>stat)::integer,0)+gain));update horses set stats=after where id=h.id;else after:=h.stats;end if;update player_store_items set consumed_at=now() where id=item.id;insert into horse_feed_log(horse_id,stable_id,item_id,product_id,le_day,result,stat_affected,development_amount,stats_before,stats_after)values(h.id,auth.uid(),item.id,product.id,today,case when success then 'development' else 'no_change' end,stat,gain,before,after);return jsonb_build_object('success',success,'stat',stat,'gain',gain,'before',case when stat is null then null else before->stat end,'after',case when stat is null then null else after->stat end,'next_eligible',((today+1)::timestamp at time zone 'America/New_York'));end$$;
create or replace function public.recalculate_horse_tack(p_horse uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare bonuses jsonb;begin select coalesce(jsonb_object_agg(stat,total),'{}') into bonuses from(select stat,sum(value::numeric) total from horse_equipment e join player_store_items i on i.id=e.item_id join store_products p on p.id=i.product_id cross join lateral jsonb_each_text(p.tack_bonuses) j(stat,value) where e.horse_id=p_horse group by stat)x;update horses set tack_bonuses=bonuses where id=p_horse;return bonuses;end$$;
create or replace function public.equip_tack(p_horse uuid,p_item uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare h horses;i player_store_items;p store_products;old uuid;begin select * into h from horses where id=p_horse for update;if not found or h.owner_id<>auth.uid()then raise exception 'Choose a horse you own';end if;select * into i from player_store_items where id=p_item and stable_id=auth.uid() and consumed_at is null for update;if not found then raise exception 'Tack item unavailable';end if;select * into p from store_products where id=i.product_id and department='tack' and active;if not found then raise exception 'This item is not tack';end if;delete from horse_equipment where horse_id=h.id and slot=p.tack_slot returning item_id into old;insert into horse_equipment(horse_id,item_id,slot)values(h.id,i.id,p.tack_slot);return jsonb_build_object('bonuses',recalculate_horse_tack(h.id),'replaced_item',old);end$$;
create or replace function public.unequip_tack(p_horse uuid,p_slot text) returns jsonb language plpgsql security definer set search_path=public as $$begin if not exists(select 1 from horses where id=p_horse and owner_id=auth.uid())then raise exception 'Choose a horse you own';end if;delete from horse_equipment where horse_id=p_horse and slot=p_slot;return recalculate_horse_tack(p_horse);end$$;

create or replace function public.apply_activity_wellness() returns trigger language plpgsql security definer set search_path=public as $$declare cfg horse_game_config;begin select * into cfg from horse_game_config where id=true;perform materialize_horse_recovery(new.horse_id);if tg_table_name='training_log'then update horse_wellness set recovery=greatest(0,recovery-cfg.training_recovery_wear),updated_at=now()where horse_id=new.horse_id;else update horse_wellness set recovery=greatest(0,recovery-cfg.show_recovery_wear),hooves=greatest(0,hooves-cfg.show_hoof_wear),updated_at=now()where horse_id=new.horse_id;end if;return new;end$$;
drop trigger if exists wellness_wear_training on training_log;create trigger wellness_wear_training after insert on training_log for each row execute function apply_activity_wellness();
drop trigger if exists wellness_wear_show on player_show_results;create trigger wellness_wear_show after insert on player_show_results for each row execute function apply_activity_wellness();
create or replace function public.enforce_show_readiness() returns trigger language plpgsql security definer set search_path=public as $$declare w jsonb;threshold integer;begin if new.is_admin_qa then return new;end if;w:=get_horse_wellness(new.horse_id);select very_poor_threshold into threshold from horse_game_config where id=true;if(w->>'readiness')::numeric<threshold then raise exception 'This horse needs recovery before competing';end if;return new;end$$;
drop trigger if exists show_readiness_before_entry on player_show_entries;create trigger show_readiness_before_entry before insert on player_show_entries for each row execute function enforce_show_readiness();

alter table service_catalog add column if not exists wellness_component text check(wellness_component in('health','hooves','recovery'));
alter table service_catalog add column if not exists restoration_by_level jsonb not null default '{}';
update service_catalog set wellness_component=case profession_id when 'veterinarian'then'health'when'farrier'then'hooves'when'massage'then'recovery'end,restoration_by_level='{"1":12,"2":18,"3":24,"4":30}' where profession_id in('veterinarian','farrier','massage');
alter table horse_service_records add column if not exists wellness_before jsonb;
alter table horse_service_records add column if not exists wellness_after jsonb;
alter table horse_service_records add column if not exists horse_age_at_service numeric;
alter table horse_service_records add column if not exists care_window text;
alter table horse_service_records add column if not exists trim_status text;
alter table horse_service_records add column if not exists shoe_status text;
alter table horse_service_records add column if not exists shoe_type text;
create or replace function public.prepare_wellness_service() returns trigger language plpgsql security definer set search_path=public as $$declare sc service_catalog;age numeric;v_window text;wk date;w jsonb;restore integer;after_value numeric;begin select * into sc from service_catalog where id=new.service_id;if sc.wellness_component is null then return new;end if;age:=horse_game_age((select birth_date from horses where id=new.horse_id));wk:=le_week_start(new.completed_at);if new.profession_id='veterinarian'then v_window:=floor(age)::integer||case when age-floor(age)<.5 then ':first'else':second'end;if exists(select 1 from horse_service_records r where r.horse_id=new.horse_id and r.profession_id='veterinarian' and r.status='completed' and r.care_window=v_window)then raise exception 'Routine Vet care is already complete for this half of the horse-year';end if;elsif new.profession_id in('farrier','massage')then v_window:=wk::text;if exists(select 1 from horse_service_records r where r.horse_id=new.horse_id and r.profession_id=new.profession_id and r.status='completed' and r.care_window=v_window)then raise exception '% care is already complete for this LE week',case when new.profession_id='farrier'then'Farrier'else'Massage'end;end if;end if;w:=get_horse_wellness(new.horse_id);restore:=coalesce((sc.restoration_by_level->>new.provider_level::text)::integer,0);after_value:=least(100,(w->>sc.wellness_component)::numeric+restore);new.wellness_before:=w;new.wellness_after:=jsonb_set(w,array[sc.wellness_component],to_jsonb(after_value));new.horse_age_at_service:=age;new.care_window:=v_window;new.effect:='{}';new.effect_expires_at:=null;return new;end$$;
create or replace function public.apply_wellness_service() returns trigger language plpgsql security definer set search_path=public as $$declare sc service_catalog;value numeric;begin select * into sc from service_catalog where id=new.service_id;if sc.wellness_component is not null then value:=(new.wellness_after->>sc.wellness_component)::numeric;execute format('update horse_wellness set %I=$1,updated_at=now(),recovery_anchor=case when %L=''recovery'' then now() else recovery_anchor end where horse_id=$2',sc.wellness_component,sc.wellness_component)using value,new.horse_id;end if;return new;end$$;
drop trigger if exists prepare_wellness_service_record on horse_service_records;create trigger prepare_wellness_service_record before insert on horse_service_records for each row execute function prepare_wellness_service();
drop trigger if exists apply_wellness_service_record on horse_service_records;create trigger apply_wellness_service_record after insert on horse_service_records for each row execute function apply_wellness_service();

alter table store_products enable row level security;alter table player_store_items enable row level security;alter table horse_equipment enable row level security;alter table horse_feed_log enable row level security;alter table horse_wellness enable row level security;alter table horse_game_config enable row level security;
create policy "store products readable" on store_products for select using(active);create policy "own store items" on player_store_items for select using(stable_id=auth.uid());create policy "owned horse equipment readable" on horse_equipment for select using(exists(select 1 from horses h where h.id=horse_id and(h.owner_id=auth.uid()or h.owner_id is null)));create policy "owned feed history readable" on horse_feed_log for select using(stable_id=auth.uid());create policy "horse wellness readable" on horse_wellness for select using(true);create policy "game config readable" on horse_game_config for select using(true);
revoke all on function purchase_store_product(text,integer),feed_horse(uuid,uuid),equip_tack(uuid,uuid),unequip_tack(uuid,text),recalculate_horse_tack(uuid),materialize_horse_recovery(uuid,timestamptz) from public;
grant execute on function get_store_inventory(text),get_store_inventory(),purchase_store_product(text,integer),feed_horse(uuid,uuid),equip_tack(uuid,uuid),unequip_tack(uuid,text),get_horse_wellness(uuid) to authenticated;
select public.refresh_store_inventory();
