-- Permanent, auditable stable capacity and historical Sanctuary retirement.
create table public.stable_capacity_allocations(
 id uuid primary key default gen_random_uuid(), stable_id uuid not null references public.stables(id),
 source text not null check(source in ('base','purchased','admin','promotional','event','owner_unlimited')),
 quantity integer not null default 0 check(quantity>=0), unlimited boolean not null default false,
 status text not null default 'active' check(status in ('active','reversed')),
 payment_reference text, reason text not null default '', granted_by uuid references public.stables(id),
 reversed_by uuid references public.stables(id), reversed_at timestamptz, created_at timestamptz not null default now(),
 check((unlimited and quantity=0) or (not unlimited and quantity>0))
);
create unique index stable_capacity_one_base on public.stable_capacity_allocations(stable_id) where source='base' and status='active';
create unique index stable_capacity_one_unlimited on public.stable_capacity_allocations(stable_id) where unlimited and status='active';
create unique index stable_capacity_payment_once on public.stable_capacity_allocations(payment_reference) where payment_reference is not null;
create index stable_capacity_account_history on public.stable_capacity_allocations(stable_id,created_at desc);
alter table public.stable_capacity_allocations enable row level security;
create policy "players read own capacity" on public.stable_capacity_allocations for select using(stable_id=auth.uid());

insert into public.stable_capacity_allocations(stable_id,source,quantity,reason)
select id,'base',5,'Legacy Equine base stable capacity' from public.stables on conflict do nothing;
insert into public.stable_capacity_allocations(stable_id,source,quantity,unlimited,reason)
select id,'owner_unlimited',0,true,'Legacy Equine Owner privilege' from public.stables where account_number=1;

create or replace function public.ensure_base_stable_capacity() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into stable_capacity_allocations(stable_id,source,quantity,reason) values(new.id,'base',5,'Legacy Equine base stable capacity') on conflict do nothing;return new;end$$;
create trigger stable_capacity_after_account after insert on public.stables for each row execute function public.ensure_base_stable_capacity();

alter table public.horses add column sanctuary_retired_at timestamptz;
alter table public.horses add column sanctuary_former_owner_id uuid references public.stables(id);
alter table public.horses add column sanctuary_reason text not null default '';
create index horses_sanctuary_directory on public.horses(sanctuary_retired_at desc) where sanctuary_retired_at is not null;
alter table public.stables drop constraint if exists stables_foundation_purchases_check;

create or replace function public.stable_capacity(target uuid)
returns table(occupied bigint,base_capacity bigint,purchased_capacity bigint,complimentary_capacity bigint,total_capacity bigint,unlimited boolean,available bigint)
language sql stable security definer set search_path=public as $$
 with c as(select coalesce(sum(quantity) filter(where status='active' and source='base'),0) base_capacity,coalesce(sum(quantity) filter(where status='active' and source='purchased'),0) purchased_capacity,coalesce(sum(quantity) filter(where status='active' and source in('admin','promotional','event')),0) complimentary_capacity,coalesce(bool_or(unlimited) filter(where status='active'),false) unlimited from stable_capacity_allocations where stable_id=target),o as(select count(*) occupied from horses where owner_id=target and sanctuary_retired_at is null)
 select o.occupied,c.base_capacity,c.purchased_capacity,c.complimentary_capacity,c.base_capacity+c.purchased_capacity+c.complimentary_capacity,c.unlimited,case when c.unlimited then null else greatest(0,c.base_capacity+c.purchased_capacity+c.complimentary_capacity-o.occupied) end from c,o
$$;

create table public.horse_ownership_history(
 id uuid primary key default gen_random_uuid(),horse_id uuid not null references public.horses(id) on delete restrict,
 owner_id uuid references public.stables(id),acquired_at timestamptz,acquisition_method text not null,
 ended_at timestamptz,disposition text,related_id uuid,created_at timestamptz not null default now()
);
create index horse_ownership_history_horse on public.horse_ownership_history(horse_id,acquired_at);
alter table public.horse_ownership_history enable row level security;
create policy "public ownership history" on public.horse_ownership_history for select using(true);
insert into public.horse_ownership_history(horse_id,owner_id,acquired_at,acquisition_method)
select id,owner_id,created_at,case origin when 'Foundation' then 'Foundation Purchase' when 'Bred' then 'Bred by Player' else 'Admin Custom' end from public.horses where owner_id is not null;

create table public.stall_packages(id text primary key,display_name text not null,stall_quantity integer not null check(stall_quantity>0),price_usd_cents integer not null check(price_usd_cents>0),active boolean not null default true,allow_multiple boolean not null default true,updated_at timestamptz not null default now());
insert into public.stall_packages values('permanent_5','5 Permanent Stalls',5,499,true,true,now());
alter table public.stall_packages enable row level security;create policy "public active stall packages" on public.stall_packages for select using(active);
create table public.stall_payment_transactions(id uuid primary key default gen_random_uuid(),stable_id uuid not null references public.stables(id),package_id text not null references public.stall_packages(id),provider text not null default 'stripe',provider_transaction_id text unique,checkout_session_id text unique,usd_amount_cents integer not null,stall_quantity integer not null,status text not null default 'pending' check(status in('pending','paid','failed','refunded')),created_at timestamptz not null default now(),paid_at timestamptz);
alter table public.stall_payment_transactions enable row level security;create policy "players read own stall payments" on public.stall_payment_transactions for select using(stable_id=auth.uid());

create table public.stable_capacity_audit(id uuid primary key default gen_random_uuid(),actor_id uuid references public.stables(id),stable_id uuid not null references public.stables(id),action text not null,quantity integer,reason text not null default '',payment_reference text,horse_id uuid references public.horses(id),created_at timestamptz not null default now());
alter table public.stable_capacity_audit enable row level security;create policy "players read own capacity audit" on public.stable_capacity_audit for select using(stable_id=auth.uid());

create or replace function public.get_my_stable_capacity() returns jsonb language plpgsql stable security definer set search_path=public as $$declare c record;begin select * into c from stable_capacity(auth.uid());return to_jsonb(c);end$$;
create or replace function public.require_available_stall(target uuid) returns void language plpgsql security definer set search_path=public as $$declare c record;begin select * into c from stable_capacity(target);if not c.unlimited and c.occupied>=c.total_capacity then raise exception 'Your Stable Is Full. You currently have % / % stalls occupied. Add Stalls or visit the LE Equine Sanctuary.',c.occupied,c.total_capacity;end if;end$$;

create or replace function public.purchase_store_horse(target_inventory uuid) returns public.horses language plpgsql security definer set search_path=public as $$
declare item store_inventory;h horses;s stables;begin if auth.uid() is null then raise exception 'Authentication required';end if;perform pg_advisory_xact_lock(674381);select * into item from store_inventory where id=target_inventory for update;if not found or item.status<>'active' then raise exception 'That horse was just purchased by another stable. A new Foundation horse has arrived in the LE Store!';end if;select * into s from stables where id=auth.uid() for update;if not found then raise exception 'Create your stable first';end if;perform require_available_stall(s.id);if s.balance<item.price then raise exception 'Insufficient funds';end if;update horses set owner_id=s.id where id=item.horse_id and owner_id is null and sanctuary_retired_at is null returning * into h;if not found then raise exception 'That horse is no longer available';end if;update store_inventory set status='sold',sold_at=now(),sold_to=s.id where id=item.id;update stables set balance=balance-item.price,foundation_purchases=foundation_purchases+1 where id=s.id;insert into currency_ledger(stable_id,amount,reason,horse_id) values(s.id,-item.price,'LE Store purchase: '||h.name,h.id);insert into horse_ownership_history(horse_id,owner_id,acquired_at,acquisition_method,related_id) values(h.id,s.id,now(),'Foundation Purchase',item.id);perform refresh_store_inventory();return h;end$$;

create or replace function public.buy_marketplace_horse(target_listing uuid) returns public.horses language plpgsql security definer set search_path=public as $$
declare item marketplace_listings;buyer stables;seller stables;h horses;begin select * into item from marketplace_listings where id=target_listing for update;if not found or item.status<>'active' then raise exception 'That horse is no longer available';end if;if item.seller_id=auth.uid() then raise exception 'You already own this horse';end if;select * into buyer from stables where id=auth.uid() for update;select * into seller from stables where id=item.seller_id for update;perform require_available_stall(buyer.id);if buyer.balance<item.price then raise exception 'Insufficient funds';end if;update horses set owner_id=buyer.id where id=item.horse_id and owner_id=item.seller_id and sanctuary_retired_at is null returning * into h;if not found then raise exception 'That horse is no longer available';end if;update horse_ownership_history set ended_at=now(),disposition='Private Sale' where horse_id=h.id and owner_id=seller.id and ended_at is null;insert into horse_ownership_history(horse_id,owner_id,acquired_at,acquisition_method,related_id) values(h.id,buyer.id,now(),'Private Sale',item.id);update stables set balance=balance-item.price where id=buyer.id;update stables set balance=balance+item.price where id=seller.id;update marketplace_listings set status='sold',buyer_id=buyer.id,closed_at=now() where id=item.id;insert into currency_ledger(stable_id,amount,reason,horse_id) values(buyer.id,-item.price,'Marketplace purchase: '||h.name,h.id),(seller.id,item.price,'Marketplace sale: '||h.name,h.id);return h;end$$;

create or replace function public.breed_horses(stallion_id uuid,mare_id uuid) returns public.horses language plpgsql security definer set search_path=public as $$
declare sire horses;dam horses;foal horses;s stables;child_stats jsonb='{}';child_genetics jsonb;child_markings jsonb;child_visual jsonb;d record;baseline int;variance int;fee int;child_breed text;child_sex horse_sex;sire_age numeric;dam_age numeric;begin
 if stallion_id=mare_id then raise exception 'Choose two different horses';end if;select * into sire from horses where id=stallion_id for update;select * into dam from horses where id=mare_id for update;if sire.id is null or dam.id is null or sire.owner_id<>auth.uid() or dam.owner_id<>auth.uid() then raise exception 'Both horses must be owned by you';end if;if sire.sanctuary_retired_at is not null or dam.sanctuary_retired_at is not null then raise exception 'Sanctuary horses are permanently retired';end if;if sire.sex<>'Stallion' or dam.sex<>'Mare' then raise exception 'Breeding requires a stallion and mare';end if;sire_age:=greatest(0,extract(epoch from(now()-sire.birth_date))/86400*30/365.25);dam_age:=greatest(0,extract(epoch from(now()-dam.birth_date))/86400*30/365.25);if sire_age<3 then raise exception 'The stallion is too young to breed. Eligible at age 3.';end if;if dam_age<3 then raise exception 'The mare is too young to breed. Eligible at age 3.';end if;if sire_age>=26 or sire.retired then raise exception 'The stallion is retired from breeding.';end if;if dam_age>=26 or dam.retired then raise exception 'The mare is retired from breeding.';end if;if dam.last_bred_at is not null and dam.last_bred_at>now()-interval '10 days' then raise exception 'Mare cooldown active';end if;select * into s from stables where id=auth.uid() for update;perform require_available_stall(s.id);child_genetics:=inherit_genetics(sire.genetics,dam.genetics);if is_lethal_genotype(child_genetics) then raise exception 'This breeding produced a non-viable lethal genotype. No foal was created and no fee was charged.';end if;fee:=sire.stud_fee;if s.balance<fee then raise exception 'Insufficient funds';end if;
 for d in select key from stat_definitions where active order by sort_order loop baseline:=round(((sire.stats->>d.key)::numeric+(dam.stats->>d.key)::numeric)/2)::int;variance:=floor(random()*13)::int-6;if random()<.25 then variance:=variance-1;end if;child_stats:=child_stats||jsonb_build_object(d.key,greatest(1,baseline+variance));end loop;child_breed:=resolve_crossbreed(sire.breed,dam.breed);child_sex:=(case when random()<.5 then 'Mare' else 'Stallion' end)::horse_sex;child_markings:=random_horse_markings(child_genetics,child_breed);child_visual:=build_visual_phenotype(child_breed,child_sex,0,child_genetics,child_markings);
 insert into horses(owner_id,name,breed,sex,color,origin,birth_date,sire_id,dam_id,generation,stats,genetics,breed_composition,image_url,markings,visual_phenotype,image_generation_status,image_prompt_version) values(s.id,'Unnamed Foal',child_breed,child_sex,genetic_color(child_genetics),'Bred',now(),sire.id,dam.id,greatest(sire.generation,dam.generation)+1,child_stats,child_genetics,combine_breed_composition(sire.breed_composition,dam.breed_composition),'/foundation-horse.png',child_markings,child_visual,'pending','horse-v17') returning * into foal;insert into horse_ownership_history(horse_id,owner_id,acquired_at,acquisition_method) values(foal.id,s.id,now(),'Bred by Player');insert into store_horse_image_jobs(horse_id) values(foal.id);update horses set last_bred_at=now() where id=dam.id;update stables set balance=balance-fee where id=s.id;if fee>0 then insert into currency_ledger(stable_id,amount,reason,horse_id) values(s.id,-fee,'Stud fee',foal.id);end if;insert into breeding_records(owner_id,sire_id,dam_id,foal_id,stud_fee) values(s.id,sire.id,dam.id,foal.id,fee);return foal;end$$;

create or replace function public.send_horse_to_sanctuary(target_horse uuid,confirmation_name text) returns public.horses language plpgsql security definer set search_path=public as $$declare h horses;fee bigint:=0;s stables;begin select * into h from horses where id=target_horse for update;if not found or h.owner_id<>auth.uid() then raise exception 'Horse not found or not owned by you';end if;if h.sanctuary_retired_at is not null then raise exception 'This horse is already permanently retired';end if;if confirmation_name<>h.name then raise exception 'Type the horse name exactly to confirm permanent Sanctuary retirement';end if;select * into s from stables where id=auth.uid() for update;if s.balance<fee then raise exception 'Insufficient LED for Sanctuary fee';end if;update marketplace_listings set status='cancelled',closed_at=now() where horse_id=h.id and status='active';update horses set owner_id=null,retired=true,sanctuary_retired_at=now(),sanctuary_former_owner_id=s.id,sanctuary_reason='Player surrender' where id=h.id returning * into h;update horse_ownership_history set ended_at=now(),disposition='Sanctuary Retirement' where horse_id=h.id and owner_id=s.id and ended_at is null;insert into stable_capacity_audit(actor_id,stable_id,action,quantity,reason,horse_id) values(s.id,s.id,'sanctuary_retirement',-1,'Permanent LE Equine Sanctuary surrender',h.id);return h;end$$;

create or replace function public.get_sanctuary_horses(search_text text default '',breed_filter text default '',sex_filter text default '',retired_year integer default null) returns table(id uuid,name text,breed text,sex horse_sex,color text,birth_date timestamptz,image_url text,career_points integer,sanctuary_retired_at timestamptz,former_owner_name text,former_owner_account bigint,former_owner_id uuid) language sql stable security definer set search_path=public as $$select h.id,h.name,h.breed,h.sex,h.color,h.birth_date,h.image_url,h.career_points,h.sanctuary_retired_at,s.name,s.account_number,s.id from horses h left join stables s on s.id=h.sanctuary_former_owner_id where h.sanctuary_retired_at is not null and(search_text='' or h.name ilike '%'||search_text||'%' or h.breed ilike '%'||search_text||'%' or s.name ilike '%'||search_text||'%')and(breed_filter='' or h.breed=breed_filter)and(sex_filter='' or h.sex::text=sex_filter)and(retired_year is null or extract(year from h.sanctuary_retired_at)=retired_year)order by h.sanctuary_retired_at desc$$;

create or replace function public.owner_grant_stalls(target_stable uuid,stall_count integer,grant_reason text default 'Admin benefit') returns uuid language plpgsql security definer set search_path=public as $$declare result uuid;begin perform require_super_admin();if stall_count<=0 then raise exception 'Grant must be positive';end if;insert into stable_capacity_allocations(stable_id,source,quantity,reason,granted_by) values(target_stable,'admin',stall_count,left(grant_reason,200),auth.uid()) returning id into result;insert into stable_capacity_audit(actor_id,stable_id,action,quantity,reason) values(auth.uid(),target_stable,'complimentary_grant',stall_count,left(grant_reason,200));return result;end$$;
create or replace function public.owner_reverse_stall_allocation(target_allocation uuid,reverse_reason text) returns void language plpgsql security definer set search_path=public as $$declare a stable_capacity_allocations;begin perform require_super_admin();select * into a from stable_capacity_allocations where id=target_allocation for update;if not found or a.status<>'active' or a.source not in('admin','promotional','event') then raise exception 'Reversible complimentary allocation not found';end if;update stable_capacity_allocations set status='reversed',reversed_by=auth.uid(),reversed_at=now() where id=a.id;insert into stable_capacity_audit(actor_id,stable_id,action,quantity,reason) values(auth.uid(),a.stable_id,'allocation_reversed',-a.quantity,left(reverse_reason,200));end$$;
create or replace function public.owner_set_unlimited_capacity(target_stable uuid,make_unlimited boolean,change_reason text default 'Owner capacity decision') returns void language plpgsql security definer set search_path=public as $$begin perform require_super_admin();if make_unlimited then insert into stable_capacity_allocations(stable_id,source,quantity,unlimited,reason,granted_by) values(target_stable,'owner_unlimited',0,true,left(change_reason,200),auth.uid()) on conflict do nothing;else update stable_capacity_allocations set status='reversed',reversed_by=auth.uid(),reversed_at=now() where stable_id=target_stable and source='owner_unlimited' and status='active';end if;insert into stable_capacity_audit(actor_id,stable_id,action,reason) values(auth.uid(),target_stable,case when make_unlimited then 'unlimited_granted' else 'unlimited_revoked' end,left(change_reason,200));end$$;
create or replace function public.owner_capacity_history(target_stable uuid) returns setof public.stable_capacity_allocations language plpgsql stable security definer set search_path=public as $$begin perform require_super_admin();return query select * from stable_capacity_allocations where stable_id=target_stable order by created_at desc;end$$;
create or replace function public.owner_update_stall_package(package_key text,new_quantity integer,new_price_cents integer,is_active boolean) returns void language plpgsql security definer set search_path=public as $$begin perform require_super_admin();if new_quantity<=0 or new_price_cents<=0 then raise exception 'Quantity and price must be positive';end if;update stall_packages set stall_quantity=new_quantity,display_name=new_quantity||' Permanent Stalls',price_usd_cents=new_price_cents,active=is_active,updated_at=now() where id=package_key;if not found then raise exception 'Package not found';end if;end$$;
create or replace function public.complete_stall_payment(target_payment uuid,provider_payment text,provider_session text) returns void language plpgsql security definer set search_path=public as $$declare p stall_payment_transactions;begin select * into p from stall_payment_transactions where id=target_payment for update;if not found then raise exception 'Payment record not found';end if;if p.status='paid' then return;end if;if p.status<>'pending' then raise exception 'Payment cannot be completed';end if;update stall_payment_transactions set status='paid',provider_transaction_id=provider_payment,checkout_session_id=provider_session,paid_at=now() where id=p.id;insert into stable_capacity_allocations(stable_id,source,quantity,payment_reference,reason) values(p.stable_id,'purchased',p.stall_quantity,provider_payment,'Permanent stall purchase');insert into stable_capacity_audit(stable_id,action,quantity,reason,payment_reference) values(p.stable_id,'stall_purchase',p.stall_quantity,'Verified USD permanent stall purchase',provider_payment);end$$;

drop function public.admin_list_stables();
create function public.admin_list_stables() returns table(id uuid,account_number bigint,name text,username text,balance bigint,is_admin boolean,stable_occupied bigint,stable_capacity bigint,unlimited_capacity boolean) language plpgsql security definer set search_path=public as $$begin perform require_admin();return query select s.id,s.account_number,s.name,s.username,s.balance,s.is_admin,c.occupied,c.total_capacity,c.unlimited from stables s cross join lateral stable_capacity(s.id)c where s.account_number is not null order by s.account_number;end$$;

revoke all on function public.stable_capacity(uuid),public.require_available_stall(uuid),public.ensure_base_stable_capacity(),public.owner_grant_stalls(uuid,integer,text),public.owner_reverse_stall_allocation(uuid,text),public.owner_set_unlimited_capacity(uuid,boolean,text),public.owner_capacity_history(uuid) from public;
revoke all on function public.owner_update_stall_package(text,integer,integer,boolean) from public;
revoke all on function public.complete_stall_payment(uuid,text,text) from public;
grant execute on function public.complete_stall_payment(uuid,text,text) to service_role;
revoke all on function public.get_my_stable_capacity(),public.send_horse_to_sanctuary(uuid,text),public.get_sanctuary_horses(text,text,text,integer) from public;
grant execute on function public.get_my_stable_capacity(),public.send_horse_to_sanctuary(uuid,text),public.get_sanctuary_horses(text,text,text,integer) to authenticated;
grant execute on function public.owner_grant_stalls(uuid,integer,text),public.owner_reverse_stall_allocation(uuid,text),public.owner_set_unlimited_capacity(uuid,boolean,text),public.owner_capacity_history(uuid) to authenticated;
grant execute on function public.owner_update_stall_package(text,integer,integer,boolean) to authenticated;
grant execute on function public.admin_list_stables() to authenticated;
