create extension if not exists pgcrypto;
create type public.horse_sex as enum ('Mare','Stallion'); create type public.horse_origin as enum ('Foundation','Bred','Admin Custom');
create table public.stables(id uuid primary key references auth.users(id), stable_number bigint generated always as identity unique, name text not null check(length(name) between 2 and 60), bio text not null default '', balance integer not null default 3000 check(balance>=0), foundation_purchases integer not null default 0 check(foundation_purchases between 0 and 3), is_admin boolean not null default false, created_at timestamptz not null default now());
create table public.horses(id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.stables(id), name text not null default 'Unnamed Horse', breed text not null, sex public.horse_sex not null, color text not null, origin public.horse_origin not null, birth_date timestamptz not null, sire_id uuid references public.horses(id) on delete restrict, dam_id uuid references public.horses(id) on delete restrict, generation integer not null default 0 check(generation>=0), stats jsonb not null, tack_bonuses jsonb not null default '{}', biography text not null default '', image_url text not null default '', stud_fee integer not null default 100 check(stud_fee>=0), last_bred_at timestamptz, last_trained_at timestamptz, retired boolean not null default false, custom_traits jsonb not null default '[]', is_admin_custom boolean not null default false, created_at timestamptz not null default now(), check(sire_id is null or sire_id<>id), check(dam_id is null or dam_id<>id));
create table public.currency_ledger(id uuid primary key default gen_random_uuid(), stable_id uuid not null references public.stables(id), amount integer not null check(amount<>0), reason text not null, horse_id uuid references public.horses(id) on delete restrict, created_at timestamptz not null default now());
create table public.training_log(id uuid primary key default gen_random_uuid(), horse_id uuid not null references public.horses(id), stable_id uuid not null references public.stables(id), stat_key text not null, gain integer not null check(gain>0), created_at timestamptz not null default now());
create table public.items(id uuid primary key default gen_random_uuid(), name text not null, stat_bonuses jsonb not null default '{}'); create table public.inventory(id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.stables(id), item_id uuid not null references public.items(id), equipped_horse_id uuid references public.horses(id));
create table public.competitions(id uuid primary key default gen_random_uuid(), discipline text not null, class_name text not null, eligibility jsonb not null default '{}', starts_at timestamptz not null); create table public.competition_entries(id uuid primary key default gen_random_uuid(), competition_id uuid references public.competitions(id), horse_id uuid references public.horses(id), result jsonb, points_awarded integer not null default 0);
alter table public.stables enable row level security; alter table public.horses enable row level security; alter table public.currency_ledger enable row level security; alter table public.training_log enable row level security; alter table public.inventory enable row level security;
create policy "public stable profiles" on public.stables for select using(true); create policy "public horses" on public.horses for select using(true); create policy "owner ledger" on public.currency_ledger for select using(auth.uid()=stable_id); create policy "owner training history" on public.training_log for select using(auth.uid()=stable_id); create policy "owner inventory" on public.inventory for select using(auth.uid()=owner_id);
create or replace function public.create_stable(stable_name text) returns public.stables language plpgsql security definer set search_path=public as $$ declare result public.stables; begin insert into stables(id,name) values(auth.uid(),stable_name) returning * into result; insert into currency_ledger(stable_id,amount,reason) values(auth.uid(),3000,'Starting funds'); return result; end $$;
revoke all on function public.create_stable(text) from public; grant execute on function public.create_stable(text) to authenticated;
-- Purchases, training, and breeding are intentionally exposed only through future
-- security-definer RPC migrations. Direct inserts are denied by the absence of policies.
