-- Ensure every future horse and every gameplay boundary uses the 28-real-day horse year.
create or replace function public.generate_store_horse(p_rotation timestamptz,p_preferred_breed text default null) returns uuid language plpgsql security definer set search_path=public as $$
declare h_id uuid;breed_name text;g jsonb;m jsonb;visual jsonb;horse_sex_value horse_sex;attempt integer:=0;begin
 select coalesce(p_preferred_breed,(select name from foundation_breeds where active order by random() limit 1)) into breed_name;
 loop attempt:=attempt+1;g:=random_foundation_genetics(breed_name);exit when not is_lethal_genotype(g);if attempt>=100 then raise exception 'Unable to generate a viable Foundation genotype';end if;end loop;
 m:=random_horse_markings(g,breed_name);horse_sex_value:=(case when random()<.5 then 'Mare' else 'Stallion' end)::horse_sex;visual:=build_visual_phenotype(breed_name,horse_sex_value,2,g,m);
 insert into horses(owner_id,name,breed,sex,color,origin,birth_date,birth_stats,stats,image_url,genetics,breed_composition,markings,visual_phenotype,image_generation_status,image_prompt_version)
 values(null,'Unnamed Foundation Horse',breed_name,horse_sex_value,genetic_color(g),'Foundation',now()-interval '56 days',random_foundation_stats(),null,'/foundation-horse.png',g,jsonb_build_object(breed_name,1),m,visual,'complete','breed-population-v1') returning id into h_id;
 update horses set stats=birth_stats where id=h_id;perform assign_horse_visual(h_id);return h_id;
end$$;

create or replace function public.breed_horses(stallion_id uuid,mare_id uuid) returns public.horses language plpgsql security definer set search_path=public as $$
declare sire horses;dam horses;foal horses;s stables;child_stats jsonb='{}';child_genetics jsonb;child_markings jsonb;child_visual jsonb;d record;baseline bigint;variance int;variance_min int;variance_max int;fee int;child_breed text;child_sex horse_sex;sire_age numeric;dam_age numeric;begin
 if stallion_id=mare_id then raise exception 'Choose two different horses';end if;select * into sire from horses where id=stallion_id for update;select * into dam from horses where id=mare_id for update;
 if sire.id is null or dam.id is null or sire.owner_id<>auth.uid() or dam.owner_id<>auth.uid() then raise exception 'Both horses must be owned by you';end if;if sire.sanctuary_retired_at is not null or dam.sanctuary_retired_at is not null then raise exception 'Sanctuary horses are permanently retired';end if;if sire.sex<>'Stallion' or dam.sex<>'Mare' then raise exception 'Breeding requires a stallion and mare';end if;
 sire_age:=horse_game_age(sire.birth_date);dam_age:=horse_game_age(dam.birth_date);if sire_age<3 then raise exception 'The stallion is too young to breed. Eligible at age 3.';end if;if dam_age<3 then raise exception 'The mare is too young to breed. Eligible at age 3.';end if;if sire_age>=26 or sire.retired then raise exception 'The stallion is retired from breeding.';end if;if dam_age>=26 or dam.retired then raise exception 'The mare is retired from breeding.';end if;if dam.last_bred_at is not null and dam.last_bred_at>now()-interval '10 days' then raise exception 'Mare cooldown active';end if;
 select * into s from stables where id=auth.uid() for update;perform require_available_stall(s.id);child_genetics:=inherit_genetics(sire.genetics,dam.genetics);if is_lethal_genotype(child_genetics) then raise exception 'This breeding produced a non-viable lethal genotype. No foal was created and no fee was charged.';end if;fee:=sire.stud_fee;if s.balance<fee then raise exception 'Insufficient funds';end if;
 select inheritance_variance_min,inheritance_variance_max into variance_min,variance_max from stat_system_config where id=true;for d in select key from stat_definitions where active order by sort_order loop baseline:=round(((sire.stats->>d.key)::numeric+(dam.stats->>d.key)::numeric)/2)::bigint;variance:=variance_min+floor(random()*(variance_max-variance_min+1))::int;child_stats:=child_stats||jsonb_build_object(d.key,greatest(1,baseline+variance));end loop;
 child_breed:=resolve_crossbreed(sire.breed,dam.breed);child_sex:=(case when random()<.5 then 'Mare' else 'Stallion' end)::horse_sex;child_markings:=random_horse_markings(child_genetics,child_breed);child_visual:=build_visual_phenotype(child_breed,child_sex,0,child_genetics,child_markings);
 insert into horses(owner_id,name,breed,sex,color,origin,birth_date,sire_id,dam_id,generation,birth_stats,stats,genetics,breed_composition,image_url,markings,visual_phenotype,image_generation_status,image_prompt_version)values(s.id,'Unnamed Foal',child_breed,child_sex,genetic_color(child_genetics),'Bred',now(),sire.id,dam.id,greatest(sire.generation,dam.generation)+1,child_stats,child_stats,child_genetics,combine_breed_composition(sire.breed_composition,dam.breed_composition),'/foundation-horse.png',child_markings,child_visual,'pending','horse-v22')returning * into foal;
 insert into horse_ownership_history(horse_id,owner_id,acquired_at,acquisition_method)values(foal.id,s.id,now(),'Bred by Player');insert into store_horse_image_jobs(horse_id)values(foal.id);update horses set last_bred_at=now()where id=dam.id;update stables set balance=balance-fee where id=s.id;if fee>0 then insert into currency_ledger(stable_id,amount,reason,horse_id)values(s.id,-fee,'Stud fee',foal.id);end if;insert into breeding_records(owner_id,sire_id,dam_id,foal_id,stud_fee)values(s.id,sire.id,dam.id,foal.id,fee);return foal;
end$$;

create or replace function public.owner_set_horse_age(p_horse uuid,p_age_years numeric,p_reason text default 'Owner age correction') returns timestamptz language plpgsql security definer set search_path=public as $$declare dob timestamptz;before_age numeric;horse_name text;actor_no bigint;begin perform require_super_admin();if p_age_years<0 or p_age_years>100 then raise exception 'Age must be between 0 and 100';end if;select horse_game_age(birth_date),name into before_age,horse_name from horses where id=p_horse for update;if not found then raise exception 'Horse not found';end if;select account_number into actor_no from stables where id=auth.uid();dob:=now()-make_interval(secs=>(p_age_years*28*86400)::double precision);perform set_config('app.horse_editor','on',true);update horses set birth_date=dob where id=p_horse;insert into horse_edit_audit(horse_id,horse_name,actor_id,actor_account,action,changed_fields,old_values,new_values,reason)values(p_horse,horse_name,auth.uid(),actor_no,'age_change',array['birth_date','age'],jsonb_build_object('age',before_age),jsonb_build_object('age',p_age_years,'birth_date',dob),left(p_reason,500));return dob;end$$;
revoke all on function public.owner_set_horse_age(uuid,numeric,text) from public;grant execute on function public.owner_set_horse_age(uuid,numeric,text) to authenticated;
