-- Central trust/safety moderation. Rules and evidence are intentionally private.
create table public.content_moderation_rules(
 id uuid primary key default gen_random_uuid(),label text not null,pattern text not null,
 category text not null check(category in('sexual_explicit','sexual_solicitation','harassment','threats_violence','self_harm','hate','predatory','personal_information','spam_scam')),
 severity text not null check(severity in('low','medium','high','urgent')),
 action text not null check(action in('warn','block','review','urgent_review')),
 active boolean not null default true,version integer not null default 1,created_by uuid references public.stables(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.content_moderation_events(
 id uuid primary key default gen_random_uuid(),author_id uuid references public.stables(id)on delete set null,
 content_type text not null,content_id text,context jsonb not null default'{}',category text not null,severity text not null,action text not null,
 rule_id uuid references public.content_moderation_rules(id)on delete set null,rule_version integer,content_evidence text not null,
 status text not null default'pending'check(status in('pending','reviewed','dismissed','actioned')),reviewed_by uuid references public.stables(id),review_note text,created_at timestamptz not null default now(),reviewed_at timestamptz
);
alter table public.content_moderation_rules enable row level security;alter table public.content_moderation_rules force row level security;
alter table public.content_moderation_events enable row level security;alter table public.content_moderation_events force row level security;
create index content_moderation_queue_idx on public.content_moderation_events(status,created_at desc);

insert into public.content_moderation_rules(label,pattern,category,severity,action)values
('Explicit sexual solicitation','(send|show|trade).*(nude|nudes|explicit photo)|sexual meetup','sexual_solicitation','high','review'),
('Explicit sexual content','(explicit sex|pornographic|sexual roleplay)','sexual_explicit','high','block'),
('Targeted degrading abuse','you (are|re).*(worthless|disgusting|subhuman)','harassment','high','review'),
('Targeted violence threat','(i will|im going to|we will).*(kill|murder|hurt|attack).*you','threats_violence','urgent','urgent_review'),
('Self-harm encouragement','(you should|go|just).*(kill yourself|end your life|hurt yourself)','self_harm','urgent','urgent_review'),
('Dehumanizing hate','(all|those).*(are vermin|are animals|should be exterminated)','hate','urgent','urgent_review'),
('Secret-contact solicitation','(keep this secret|dont tell anyone).*(meet|photo|picture|contact)','predatory','urgent','urgent_review'),
('Credential disclosure','(password|authentication code|login code|recovery code) (is|:)','personal_information','high','review'),
('Government identifier','[0-9]{3}[- ][0-9]{2}[- ][0-9]{4}','personal_information','high','review'),
('Private contact disclosure','(home address|phone number|email address) (is|:)','personal_information','high','review'),
('Scam solicitation','(guaranteed|free).*(money|led|prize).*(click|link|send)','spam_scam','medium','block');

create or replace function public.normalize_moderation_text(p_text text)returns text language sql immutable as $$
 select trim(regexp_replace(translate(lower(coalesce(p_text,'')),'01345@$!','oieasssi'),'[^a-z0-9@.]+',' ','g'))
$$;
create or replace function public.content_moderation_result(p_text text)returns jsonb language plpgsql stable security definer set search_path=public as $$
declare normalized text:=normalize_moderation_text(p_text);matched content_moderation_rules;begin
 if trim(coalesce(p_text,''))=''then return jsonb_build_object('action','allow');end if;
 select*into matched from content_moderation_rules where active and normalized~pattern order by case severity when'urgent'then 4 when'high'then 3 when'medium'then 2 else 1 end desc,created_at limit 1;
 if not found then return jsonb_build_object('action','allow');end if;
 return jsonb_build_object('action',matched.action,'category',matched.category,'severity',matched.severity,'rule_id',matched.id,'rule_version',matched.version);
end$$;
create or replace function public.moderate_player_content(p_text text,p_content_type text,p_author uuid default auth.uid(),p_content_id text default null,p_context jsonb default'{}')returns jsonb language plpgsql security definer set search_path=public as $$
declare result jsonb:=content_moderation_result(p_text);begin
 if result->>'action'<>'allow'then insert into content_moderation_events(author_id,content_type,content_id,context,category,severity,action,rule_id,rule_version,content_evidence)
 values(p_author,left(p_content_type,80),left(p_content_id,200),coalesce(p_context,'{}'),result->>'category',result->>'severity',result->>'action',(result->>'rule_id')::uuid,(result->>'rule_version')::integer,left(p_text,5000));end if;
 return result-'rule_id'-'rule_version';
exception when others then return jsonb_build_object('action','unavailable');end$$;
create or replace function public.require_safe_player_content(p_text text)returns void language plpgsql stable security definer set search_path=public as $$declare result jsonb;begin
 result:=content_moderation_result(p_text);if result->>'action'<>'allow'then raise exception'This content can’t be published because it may violate Legacy Equine’s Community Standards. Please revise it and try again.';end if;
exception when raise_exception then raise;when others then raise exception'Unable to publish right now. Please try again shortly.';end$$;

-- Mailbox: moderate before delivery; blocked text is retained only in the private review queue.
create or replace function public.send_mailbox_message(p_recipient uuid,p_body text,p_thread uuid default null)returns jsonb language plpgsql security definer set search_path=public as $$declare decision jsonb;thread mailbox_threads;message mailbox_messages;one_id uuid;two_id uuid;last_time timestamptz;begin
 perform require_social_eligibility();if p_recipient=auth.uid()or not account_social_eligible(p_recipient)then raise exception'Recipient is unavailable';end if;if exists(select 1 from player_blocks where(blocker_id=auth.uid()and blocked_id=p_recipient)or(blocker_id=p_recipient and blocked_id=auth.uid()))then raise exception'Messaging is unavailable for this player';end if;
 if length(trim(coalesce(p_body,'')))not between 1 and 3000 then raise exception'Message must be 1–3,000 characters';end if;select max(created_at)into last_time from mailbox_messages where sender_id=auth.uid();if last_time>now()-interval'3 seconds'then raise exception'Please wait before sending another message';end if;
 decision:=moderate_player_content(p_body,'mailbox_message',auth.uid(),null,jsonb_build_object('recipient_id',p_recipient));if decision->>'action'='unavailable'then return jsonb_build_object('delivered',false,'message','Unable to send right now. Please try again shortly.');elsif decision->>'action'<>'allow'then return jsonb_build_object('delivered',false,'category',decision->>'category','message','This message can’t be sent because it may violate Legacy Equine’s Community Standards. Please revise it and try again.');end if;
 one_id:=least(auth.uid()::text,p_recipient::text)::uuid;two_id:=greatest(auth.uid()::text,p_recipient::text)::uuid;if p_thread is not null then select*into thread from mailbox_threads where id=p_thread and auth.uid()in(participant_one,participant_two)and p_recipient in(participant_one,participant_two)for update;end if;
 if thread.id is null then insert into mailbox_threads(participant_one,participant_two)values(one_id,two_id)on conflict(participant_one,participant_two)do update set updated_at=now()returning*into thread;end if;insert into mailbox_messages(thread_id,sender_id,body)values(thread.id,auth.uid(),left(trim(regexp_replace(p_body,'<[^>]*>','','g')),3000))returning*into message;update mailbox_threads set updated_at=now()where id=thread.id;
 return jsonb_build_object('delivered',true,'thread_id',thread.id,'message_id',message.id,'created_at',message.created_at);end$$;

-- Chat: return NULL on a blocked decision so nothing is published.
create or replace function public.send_chat_message(target_room uuid,message_content text,refs jsonb default'[]')returns chat_messages language plpgsql security definer set search_path=public as $$declare decision jsonb;r chat_rooms;s stables;result chat_messages;last_message chat_messages;begin perform require_social_eligibility();select*into s from stables where id=auth.uid();if s.username is null then raise exception'Create a username in Settings before chatting';end if;select*into r from chat_rooms where id=target_room for update;if not found or not r.active or r.archived_at is not null then raise exception'Chat room is unavailable';end if;if r.locked or r.read_only then raise exception'This room is currently read-only';end if;if r.post_permission='staff'and not community_staff()then raise exception'Only Community staff may post here';end if;if exists(select 1 from chat_mutes m where m.stable_id=s.id and(m.room_id is null or m.room_id=r.id)and m.expires_at>now())then raise exception'You are temporarily muted from this chat';end if;if length(trim(message_content))not between 1 and 1000 then raise exception'Messages must be 1–1,000 characters';end if;select*into last_message from chat_messages where author_id=s.id order by created_at desc limit 1;if last_message.created_at>now()-interval'3 seconds'then raise exception'Please wait a moment before sending another message';end if;if last_message.created_at>now()-interval'2 minutes'and lower(last_message.content)=lower(trim(message_content))then raise exception'Please do not repeat the same message';end if;
 decision:=moderate_player_content(message_content,'community_chat',auth.uid(),null,jsonb_build_object('room_id',target_room));if decision->>'action'<>'allow'then return null;end if;
 insert into chat_messages(room_id,author_id,content,entity_refs)values(r.id,s.id,left(trim(regexp_replace(message_content,'<[^>]*>','','g')),1000),coalesce(refs,'[]'))returning*into result;return result;end$$;

create or replace function public.update_stable_profile(new_name text,new_username text,new_bio text)returns public.stables language plpgsql security definer set search_path=public as $$declare result stables;normalized_username text:=nullif(trim(coalesce(new_username,'')),'');begin
 if auth.uid()is null then raise exception'Authentication required';end if;if length(trim(new_name))not between 2 and 60 then raise exception'Stable name must be 2–60 characters';end if;if normalized_username is not null and normalized_username!~'^[A-Za-z0-9_]{3,24}$'then raise exception'Username must be 3–24 letters, numbers, or underscores';end if;perform require_safe_player_content(concat_ws(' ',new_name,normalized_username,new_bio));update stables set name=trim(new_name),username=normalized_username,bio=left(trim(coalesce(new_bio,'')),500)where id=auth.uid()returning*into result;if not found then raise exception'Stable not found';end if;return result;exception when unique_violation then raise exception'That username is already taken';end$$;
create or replace function public.save_public_stable_content(p_news text,p_about text,p_featured uuid[])returns void language plpgsql security definer set search_path=public as $$declare clean_featured uuid[];begin perform require_safe_player_content(concat_ws(' ',p_news,p_about));select coalesce(array_agg(id order by id),'{}')into clean_featured from(select distinct h.id from unnest(coalesce(p_featured,'{}'))wanted(id)join horses h on h.id=wanted.id and h.owner_id=auth.uid()and not h.retired limit 12)x;insert into stable_public_profiles(stable_id,stable_news,about_text,featured_horses)values(auth.uid(),stable_safe_rich_text(p_news),stable_safe_rich_text(p_about),clean_featured)on conflict(stable_id)do update set stable_news=excluded.stable_news,about_text=excluded.about_text,featured_horses=excluded.featured_horses,updated_at=now();end$$;
create or replace function public.save_profession_business_profile(p_profession text,p_display_name text,p_banner_url text,p_about text,p_announcement text,p_featured_service text default null)returns void language plpgsql security definer set search_path=public as $$declare lvl integer;clean_name text;begin select max(level)into lvl from player_profession_certifications where stable_id=auth.uid()and profession_id=p_profession;if lvl is null then raise exception'Earn the Basic certification to unlock this business';end if;perform require_safe_player_content(concat_ws(' ',p_display_name,p_about,p_announcement));clean_name:=business_safe_text(p_display_name,80);if length(trim(clean_name))<2 then raise exception'Business name is required';end if;if p_banner_url is not null and p_banner_url<>''and p_banner_url!~'^https://[^[:space:]]+$'then raise exception'Invalid business banner URL';end if;if p_featured_service is not null and not exists(select 1 from service_catalog where id=p_featured_service and profession_id=p_profession and active and minimum_level<=lvl)then raise exception'Featured service is not authorized';end if;insert into profession_business_profiles(stable_id,profession_id,display_name,banner_url,about_text,announcement,featured_service_id)values(auth.uid(),p_profession,clean_name,nullif(p_banner_url,''),business_safe_text(p_about,2000),business_safe_text(p_announcement,1000),p_featured_service)on conflict(stable_id,profession_id)do update set display_name=excluded.display_name,banner_url=excluded.banner_url,about_text=excluded.about_text,announcement=excluded.announcement,featured_service_id=excluded.featured_service_id,updated_at=now();end$$;
create or replace function public.save_public_stable_customization(p_mode text,p_layout_image_url text,p_blocks jsonb)returns void language plpgsql security definer set search_path=public as $$declare allowed text[]:=array['banner','news','about','featured','stallions','broodmares','winners','services','roster','custom'];hotspot_types text[]:=array['news','featured','about','services','roster'];clean jsonb;clean_url text:=left(trim(coalesce(p_layout_image_url,'')),2048);begin if p_mode not in('standard','custom')then raise exception'Choose Standard or Custom Layout';end if;if p_mode='custom'and not has_custom_stable_layout(auth.uid())then raise exception'Custom Stable Layouts unlock at Account Level 20';end if;if p_mode='custom'and clean_url=''then raise exception'Upload a Stable Layout image before using Custom Layout';end if;if clean_url<>''and clean_url not like'%/storage/v1/object/public/legacy-equine-media/'||auth.uid()::text||'/artwork-album/%'then raise exception'Choose an image from your Legacy Equine uploads';end if;if jsonb_typeof(p_blocks)<>'array'or jsonb_array_length(p_blocks)>20 then raise exception'Invalid Stable layout';end if;if exists(select 1 from jsonb_array_elements(p_blocks)x where not(x->>'type'=any(allowed))or coalesce(x->>'id','')!~'^[a-z0-9_-]{1,40}$')then raise exception'Unsupported Stable layout block';end if;if(select count(*)from jsonb_array_elements(p_blocks))<>(select count(distinct x->>'id')from jsonb_array_elements(p_blocks)x)then raise exception'Stable layout block IDs must be unique';end if;perform require_safe_player_content(coalesce((select string_agg(x->>'content',' ')from jsonb_array_elements(p_blocks)x where x->>'type'='custom'),'') );select jsonb_agg(jsonb_build_object('id',x->>'id','type',x->>'type','visible',coalesce((x->>'visible')::boolean,true))||case when x->>'type'='custom'then jsonb_build_object('content',stable_safe_rich_text(x->>'content'))else'{}'::jsonb end||case when x->>'type'=any(hotspot_types)then jsonb_build_object('hotspot',jsonb_build_object('x',least(95,greatest(0,coalesce((x->'hotspot'->>'x')::numeric,0))),'y',least(95,greatest(0,coalesce((x->'hotspot'->>'y')::numeric,0))),'width',least(50,greatest(1,coalesce((x->'hotspot'->>'width')::numeric,20))),'height',least(50,greatest(1,coalesce((x->'hotspot'->>'height')::numeric,10)))))else'{}'::jsonb end)into clean from jsonb_array_elements(p_blocks)x;insert into stable_public_profiles(stable_id,blocks,layout_mode,layout_image_url)values(auth.uid(),clean,p_mode,clean_url)on conflict(stable_id)do update set blocks=excluded.blocks,layout_mode=excluded.layout_mode,layout_image_url=excluded.layout_image_url,updated_at=now();end$$;

create or replace function public.can_manage_safety(p_user uuid default auth.uid())returns boolean language sql stable security definer set search_path=public as $$select is_owner_account(p_user)or has_admin_permission('safety.moderation.manage',p_user)$$;
create or replace function public.admin_moderation_workspace()returns jsonb language plpgsql security definer set search_path=public as $$begin if not can_manage_safety()then raise exception'Safety moderation permission required';end if;return jsonb_build_object('queue',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'content_type',e.content_type,'content_id',e.content_id,'context',e.context,'account_number',s.account_number,'author',coalesce(s.username,s.name),'category',e.category,'severity',e.severity,'action',e.action,'status',e.status,'content_evidence',e.content_evidence,'created_at',e.created_at,'review_note',e.review_note)order by e.created_at desc)from(select*from content_moderation_events order by created_at desc limit 300)e left join stables s on s.id=e.author_id),'[]'::jsonb),'rules',coalesce((select jsonb_agg(to_jsonb(r)order by r.category,r.label)from content_moderation_rules r),'[]'::jsonb),'reports',coalesce((select jsonb_agg(jsonb_build_object('id',t.id,'ticket_number',support_ticket_code(t.ticket_number),'title',t.title,'status',t.status,'account_number',s.account_number,'author',coalesce(s.username,s.name),'created_at',t.created_at)order by t.created_at desc)from support_tickets t join stables s on s.id=t.stable_id where t.category='Report Player/Content'limit 200),'[]'::jsonb));end$$;
create or replace function public.admin_test_moderation(p_text text)returns jsonb language plpgsql stable security definer set search_path=public as $$declare result jsonb;begin if not can_manage_safety()then raise exception'Safety moderation permission required';end if;result:=content_moderation_result(p_text);return case when result->>'action'='allow'then result else result||jsonb_build_object('rule_reference',result->>'rule_id')end;end$$;
create or replace function public.admin_save_moderation_rule(p_id uuid,p_label text,p_pattern text,p_category text,p_severity text,p_action text,p_active boolean)returns uuid language plpgsql security definer set search_path=public as $$declare result uuid:=coalesce(p_id,gen_random_uuid());begin if not can_manage_safety()then raise exception'Safety moderation permission required';end if;if length(trim(p_label))not between 2 and 100 or length(p_pattern)not between 2 and 500 then raise exception'Rule label and pattern are required';end if;perform regexp_match('',p_pattern);insert into content_moderation_rules(id,label,pattern,category,severity,action,active,created_by)values(result,trim(p_label),p_pattern,p_category,p_severity,p_action,p_active,auth.uid())on conflict(id)do update set label=excluded.label,pattern=excluded.pattern,category=excluded.category,severity=excluded.severity,action=excluded.action,active=excluded.active,version=content_moderation_rules.version+1,updated_at=now();insert into admin_audit_log(actor_id,action_type,system,target_type,target_id,details)values(auth.uid(),'moderation.rule_saved','safety','moderation_rule',result::text,jsonb_build_object('category',p_category,'severity',p_severity,'action',p_action,'active',p_active));return result;end$$;
create or replace function public.admin_delete_moderation_rule(p_id uuid)returns void language plpgsql security definer set search_path=public as $$declare old content_moderation_rules;begin if not can_manage_safety()then raise exception'Safety moderation permission required';end if;delete from content_moderation_rules where id=p_id returning*into old;if not found then raise exception'Moderation rule not found';end if;insert into admin_audit_log(actor_id,action_type,system,target_type,target_id,details)values(auth.uid(),'moderation.rule_removed','safety','moderation_rule',p_id::text,jsonb_build_object('category',old.category,'label',old.label));end$$;
create or replace function public.admin_resolve_moderation_event(p_event uuid,p_status text,p_note text)returns void language plpgsql security definer set search_path=public as $$begin if not can_manage_safety()then raise exception'Safety moderation permission required';end if;if p_status not in('reviewed','dismissed','actioned')or length(trim(coalesce(p_note,'')))<3 then raise exception'Review outcome and note are required';end if;update content_moderation_events set status=p_status,reviewed_by=auth.uid(),review_note=left(trim(p_note),1000),reviewed_at=now()where id=p_event;if not found then raise exception'Moderation event not found';end if;insert into admin_audit_log(actor_id,action_type,system,target_type,target_id,details)values(auth.uid(),'moderation.event_'||p_status,'safety','moderation_event',p_event::text,jsonb_build_object('note',left(trim(p_note),1000)));end$$;

-- Non-destructive initial audit: serious matches are queued; existing content is not changed.
do $$declare row record;begin for row in select id,bio from stables where trim(coalesce(bio,''))<>''loop perform moderate_player_content(row.bio,'existing_player_bio_audit',row.id,row.id::text,'{}');end loop;for row in select stable_id,stable_news||' '||about_text body from stable_public_profiles where trim(stable_news||about_text)<>''loop perform moderate_player_content(row.body,'existing_public_stable_audit',row.stable_id,row.stable_id::text,'{}');end loop;for row in select stable_id,profession_id,display_name||' '||about_text||' '||announcement body from profession_business_profiles loop perform moderate_player_content(row.body,'existing_profession_business_audit',row.stable_id,row.profession_id,'{}');end loop;end$$;

revoke all on table public.content_moderation_rules,public.content_moderation_events from anon,authenticated;
revoke all on function public.normalize_moderation_text(text),public.content_moderation_result(text),public.moderate_player_content(text,text,uuid,text,jsonb),public.require_safe_player_content(text),public.can_manage_safety(uuid),public.admin_moderation_workspace(),public.admin_test_moderation(text),public.admin_save_moderation_rule(uuid,text,text,text,text,text,boolean),public.admin_delete_moderation_rule(uuid),public.admin_resolve_moderation_event(uuid,text,text)from public;
grant execute on function public.admin_moderation_workspace(),public.admin_test_moderation(text),public.admin_save_moderation_rule(uuid,text,text,text,text,text,boolean),public.admin_delete_moderation_rule(uuid),public.admin_resolve_moderation_event(uuid,text,text)to authenticated;
