-- Phase 2: activate permanent-stat Show Levels prospectively.
revoke execute on function public.preview_show_tier_v2_migration()from anon;

create table public.show_entry_eligibility_removals(
 id uuid primary key default gen_random_uuid(),entry_id uuid not null,show_id uuid not null references public.player_shows(id),horse_id uuid not null references public.horses(id),owner_id uuid not null references public.stables(id),entry_fee_refunded bigint not null default 0,reason text not null,details jsonb not null default'{}',removed_at timestamptz not null default now(),unique(entry_id)
);
alter table public.show_entry_eligibility_removals enable row level security;
create policy "owners read own Show eligibility removals"on public.show_entry_eligibility_removals for select using(owner_id=auth.uid()or has_show_capability('shows.admin.audit'));

create or replace function public.remove_invalid_show_entry(p_entry uuid,p_reason text)returns boolean language plpgsql security definer set search_path=public as $$declare e player_show_entries;sh player_shows;avg numeric;level text;begin
 select * into e from player_show_entries where id=p_entry for update;if not found or exists(select 1 from player_show_results where entry_id=e.id)then return false;end if;select * into sh from player_shows where id=e.show_id for update;if sh.status not in('open','processing')then return false;end if;
 avg:=horse_permanent_stat_average(e.horse_id);level:=get_horse_show_level(e.horse_id);
 insert into show_entry_eligibility_removals(entry_id,show_id,horse_id,owner_id,entry_fee_refunded,reason,details)values(e.id,e.show_id,e.horse_id,e.owner_id,sh.entry_fee,p_reason,jsonb_build_object('permanent_average',avg,'resolved_level',level,'required_level',sh.tier_id))on conflict(entry_id)do nothing;if not found then return false;end if;
 if sh.entry_fee>0 then update stables set balance=balance+sh.entry_fee where id=e.owner_id;update player_shows set entry_fee_purse=greatest(0,entry_fee_purse-sh.entry_fee)where id=sh.id;insert into currency_ledger(stable_id,amount,reason,horse_id)values(e.owner_id,sh.entry_fee,'Show eligibility refund: '||sh.name,e.horse_id);end if;delete from player_show_entries where id=e.id;return true;end$$;
create or replace function public.revalidate_show_entries(p_show uuid)returns jsonb language plpgsql security definer set search_path=public as $$declare row record;removed integer:=0;refunded bigint:=0;begin
 for row in select e.id,sh.entry_fee from player_show_entries e join player_shows sh on sh.id=e.show_id where e.show_id=p_show and sh.status in('open','processing')and get_horse_show_level(e.horse_id)<>sh.tier_id order by e.id loop if remove_invalid_show_entry(row.id,'Horse advanced beyond Show Level eligibility.')then removed:=removed+1;refunded:=refunded+row.entry_fee;end if;end loop;return jsonb_build_object('removed',removed,'refunded',refunded);end$$;
create or replace function public.apply_show_tier_v2_future_entry_migration()returns jsonb language plpgsql security definer set search_path=public as $$declare row record;removed integer:=0;refunded bigint:=0;begin
 for row in select e.id,sh.entry_fee from player_show_entries e join player_shows sh on sh.id=e.show_id where sh.status in('open','processing')and sh.run_at>now()and get_horse_show_level(e.horse_id)<>sh.tier_id order by e.id loop if remove_invalid_show_entry(row.id,'Show Tier V2 migration: horse is outside this Show Level.')then removed:=removed+1;refunded:=refunded+row.entry_fee;end if;end loop;
 insert into show_admin_audit(actor_id,action,details)select id,'show_tier_v2_activated',jsonb_build_object('removed',removed,'refunded',refunded,'preview',preview_show_tier_v2_migration())from stables where account_number=1 limit 1;return jsonb_build_object('removed',removed,'refunded',refunded);end$$;

create or replace function public.preview_show_entries(p_pairs jsonb)returns jsonb language plpgsql stable security definer set search_path=public as $$declare v_progress jsonb;v_item jsonb;v_show player_shows;v_horse horses;v_eligible jsonb:='[]';v_skipped jsonb:='[]';v_fee bigint:=0;v_count integer;v_seen text[]:='{}';v_key text;v_selected jsonb:='{}';v_selected_for_show integer;v_avg numeric;v_level text;begin
 v_progress:=get_account_progression();if(select count(distinct x->>'show_id')from jsonb_array_elements(coalesce(p_pairs,'[]'))x)>1 and not((v_progress->>'advanced_bulk_entry')::boolean or has_show_capability('shows.bulk_enter_all'))then raise exception'Multiple-Show entry is not available for this account';end if;
 for v_item in select*from jsonb_array_elements(coalesce(p_pairs,'[]'))loop v_key:=(v_item->>'show_id')||':'||(v_item->>'horse_id');if v_key=any(v_seen)then continue;end if;v_seen:=array_append(v_seen,v_key);select*into v_show from player_shows where id=(v_item->>'show_id')::uuid;select*into v_horse from horses where id=(v_item->>'horse_id')::uuid and owner_id=auth.uid();v_avg:=horse_permanent_stat_average(v_horse.id);v_level:=get_horse_show_level(v_horse.id);
  if v_show.id is null or v_horse.id is null then v_skipped:=v_skipped||jsonb_build_array(v_item||jsonb_build_object('reason','Horse or Show unavailable'));elsif v_show.status<>'open'or v_show.run_at<=now()then v_skipped:=v_skipped||jsonb_build_array(v_item||jsonb_build_object('horse_name',v_horse.name,'show_name',v_show.name,'reason','Show is closed'));elsif v_show.locked_at is not null then v_skipped:=v_skipped||jsonb_build_array(v_item||jsonb_build_object('horse_name',v_horse.name,'show_name',v_show.name,'reason','Entries are locked'));elsif v_show.is_private and not(has_show_capability('shows.admin.qa')or exists(select 1 from show_qa_allowlist q where q.stable_id=auth.uid()and q.active))then v_skipped:=v_skipped||jsonb_build_array(v_item||jsonb_build_object('horse_name',v_horse.name,'show_name',v_show.name,'reason','Private test Show'));elsif exists(select 1 from player_show_entries e where e.show_id=v_show.id and e.horse_id=v_horse.id)then v_skipped:=v_skipped||jsonb_build_array(v_item||jsonb_build_object('horse_name',v_horse.name,'show_name',v_show.name,'reason','Already entered'));elsif v_horse.sanctuary_retired_at is not null then v_skipped:=v_skipped||jsonb_build_array(v_item||jsonb_build_object('horse_name',v_horse.name,'show_name',v_show.name,'reason','Horse is retired to Sanctuary'));elsif v_level<>v_show.tier_id then v_skipped:=v_skipped||jsonb_build_array(v_item||jsonb_build_object('horse_name',v_horse.name,'show_name',v_show.name,'permanent_average',v_avg,'show_level',v_level,'reason','Permanent Stat Average Show Level'));else select count(*)into v_count from player_show_entries where show_id=v_show.id;v_selected_for_show:=coalesce((v_selected->>v_show.id::text)::integer,0);if v_show.max_entries is not null and v_count+v_selected_for_show>=v_show.max_entries then v_skipped:=v_skipped||jsonb_build_array(v_item||jsonb_build_object('horse_name',v_horse.name,'show_name',v_show.name,'reason','Show is full'));else v_eligible:=v_eligible||jsonb_build_array(v_item||jsonb_build_object('horse_name',v_horse.name,'show_name',v_show.name,'fee',v_show.entry_fee,'permanent_average',v_avg,'show_level',v_level));v_fee:=v_fee+v_show.entry_fee;v_selected:=jsonb_set(v_selected,array[v_show.id::text],to_jsonb(v_selected_for_show+1),true);end if;end if;
 end loop;return jsonb_build_object('eligible',v_eligible,'skipped',v_skipped,'total_fee',v_fee,'balance',(select balance from stables where id=auth.uid()),'previewed_at',now());end$$;

create or replace function public.get_show_entry_options(p_show_id uuid)returns table(horse_id uuid,name text,breed text,career_points integer,current_tier_id text,current_tier text,entry_status text,ineligibility_reason text)language sql security definer set search_path=public stable as $$
 select h.id,h.name,h.breed,h.career_points,get_horse_show_level(h.id),ct.name,case when e.id is not null then'entered'when get_horse_show_level(h.id)=sh.tier_id and h.sanctuary_retired_at is null then'eligible'else'ineligible'end,case when e.id is not null then'Already entered'when h.sanctuary_retired_at is not null then'Permanently retired to the LE Equine Sanctuary'when get_horse_show_level(h.id)<>sh.tier_id then ct.name||' · Avg '||horse_permanent_stat_average(h.id)||' — Show requires '||required.name else''end from horses h cross join player_shows sh join show_tiers required on required.id=sh.tier_id left join show_tiers ct on ct.id=get_horse_show_level(h.id)left join player_show_entries e on e.show_id=sh.id and e.horse_id=h.id where sh.id=p_show_id and h.owner_id=auth.uid()order by case when e.id is not null then 2 when get_horse_show_level(h.id)=sh.tier_id then 1 else 3 end,h.name
$$;

create or replace function public.confirm_show_entries(p_pairs jsonb,p_request_id uuid default gen_random_uuid())returns jsonb language plpgsql security definer set search_path=public as $$declare v_preview jsonb;v_item jsonb;v_stable stables;v_show player_shows;v_horse horses;v_entry uuid;v_ids uuid[]:='{}';v_total bigint;v_result jsonb;v_batch uuid:=gen_random_uuid();begin
 if auth.uid()is null then raise exception'Authentication required';end if;select result into v_result from show_action_requests where id=p_request_id and stable_id=auth.uid()and action_type='enter_shows';if found then return v_result;end if;select*into v_stable from stables where id=auth.uid()for update;perform 1 from player_shows ps where ps.id in(select(x->>'show_id')::uuid from jsonb_array_elements(coalesce(p_pairs,'[]'))x)order by ps.id for update;perform 1 from horses h where h.id in(select(x->>'horse_id')::uuid from jsonb_array_elements(coalesce(p_pairs,'[]'))x)order by h.id for update;v_preview:=preview_show_entries(p_pairs);if jsonb_array_length(v_preview->'skipped')>0 then return v_preview||jsonb_build_object('changed',true,'entries_created',0);end if;if jsonb_array_length(v_preview->'eligible')=0 then raise exception'No eligible entries selected';end if;v_total:=(v_preview->>'total_fee')::bigint;if v_stable.balance<v_total then raise exception'You do not have enough LE Dollars for these entries';end if;
 for v_item in select*from jsonb_array_elements(v_preview->'eligible')loop select*into v_show from player_shows where id=(v_item->>'show_id')::uuid for update;select*into v_horse from horses where id=(v_item->>'horse_id')::uuid for update;if get_horse_show_level(v_horse.id)<>v_show.tier_id then return preview_show_entries(p_pairs)||jsonb_build_object('changed',true,'entries_created',0);end if;insert into player_show_entries(show_id,horse_id,owner_id,tier_id,career_points_snapshot,horse_name_snapshot,owner_name_snapshot,owner_account_snapshot,eligibility_snapshot)values(v_show.id,v_horse.id,v_stable.id,v_show.tier_id,v_horse.career_points,v_horse.name,v_stable.name,v_stable.account_number,jsonb_build_object('permanent_average_at_entry',horse_permanent_stat_average(v_horse.id),'show_level_at_entry',get_horse_show_level(v_horse.id),'career_points_at_entry',v_horse.career_points))returning id into v_entry;v_ids:=array_append(v_ids,v_entry);if v_show.entry_fee>0 then update player_shows set entry_fee_purse=entry_fee_purse+v_show.entry_fee where id=v_show.id;insert into currency_ledger(stable_id,amount,reason,horse_id)values(v_stable.id,-v_show.entry_fee,'Show entry: '||v_show.name,v_horse.id);insert into system_fund_ledger(fund_id,amount,transaction_type,source,destination,initiated_by,reason,related_id,batch_id)values('show_fund',v_show.entry_fee,'show_entry_fee',v_stable.name,v_show.name||' purse',v_stable.id,'Show entry fee: '||v_horse.name,v_show.id,v_batch);insert into system_fund_ledger(fund_id,amount,transaction_type,source,destination,initiated_by,reason,related_id,batch_id)values('show_fund',-v_show.entry_fee,'show_purse_allocation','LE Show Fund',v_show.name||' purse',v_stable.id,'Entry fee allocated to Show purse',v_show.id,v_batch);update system_funds set lifetime_inflow=lifetime_inflow+v_show.entry_fee,lifetime_outflow=lifetime_outflow+v_show.entry_fee where id='show_fund';end if;end loop;if v_total>0 then update stables set balance=balance-v_total where id=v_stable.id;end if;v_result:=v_preview||jsonb_build_object('changed',false,'entries_created',cardinality(v_ids),'entry_ids',v_ids,'batch_id',v_batch,'balance_after',v_stable.balance-v_total);insert into show_action_requests(id,stable_id,action_type,result)values(p_request_id,v_stable.id,'enter_shows',v_result);return v_result;exception when unique_violation then raise exception'One of these horses was just entered. Review your entries again';end$$;

create or replace function public.process_due_player_shows()returns integer language plpgsql security definer set search_path=public as $$declare sh player_shows;ent record;weights jsonb;purse bigint;rule show_placement_rules;rank_no int;processed int:=0;breakdown jsonb;score numeric;base_score numeric;inserted uuid;begin
 for sh in select*from player_shows where status in('open','processing')and run_at<=now()order by run_at for update skip locked loop update player_shows set status='processing'where id=sh.id;perform revalidate_show_entries(sh.id);rank_no:=0;purse:=sh.entry_fee_purse+sh.show_fund_allocation+sh.treasury_allocation;select stat_weights into weights from show_disciplines where id=sh.discipline_id;for ent in select e.*,h.stats,h.tack_bonuses from player_show_entries e join horses h on h.id=e.horse_id where e.show_id=sh.id order by e.id loop breakdown:=show_score_breakdown(ent.horse_id,weights,sh.run_at);score:=(select sum((breakdown->key->>'effective')::numeric*(value::text)::numeric)/nullif(sum((value::text)::numeric),0)from jsonb_each(weights));base_score:=(select sum(((breakdown->key->>'base')::numeric+(breakdown->key->>'training')::numeric)*(value::text)::numeric)/nullif(sum((value::text)::numeric),0)from jsonb_each(weights));update player_show_entries set eligibility_snapshot=coalesce(eligibility_snapshot,'{}')||jsonb_build_object('competition_score',score,'base_score',base_score,'score_breakdown',breakdown,'permanent_average_at_run',horse_permanent_stat_average(ent.horse_id),'show_level_at_run',get_horse_show_level(ent.horse_id))where id=ent.id;end loop;
  for ent in select e.*,(e.eligibility_snapshot->>'competition_score')::numeric score,(e.eligibility_snapshot->>'base_score')::numeric base_score,e.eligibility_snapshot->'score_breakdown'breakdown from player_show_entries e where e.show_id=sh.id order by score desc,base_score desc,e.career_points_snapshot desc,e.entered_at,e.horse_id loop rank_no:=rank_no+1;select*into rule from show_placement_rules where placement=rank_no;inserted:=null;insert into player_show_results(show_id,entry_id,horse_id,owner_id,placement,competition_score,base_contribution,tack_contribution,service_contribution,career_points_awarded,led_winnings,horse_name_snapshot,owner_name_snapshot,owner_account_snapshot,score_breakdown)values(sh.id,ent.id,ent.horse_id,ent.owner_id,rank_no,ent.score,ent.base_score,coalesce((select avg((value->>'tack')::numeric)from jsonb_each(ent.breakdown)),0),coalesce((select avg((value->>'service')::numeric)from jsonb_each(ent.breakdown)),0),coalesce(rule.career_points,0),floor(purse*coalesce(rule.prize_percent,0)/100),ent.horse_name_snapshot,ent.owner_name_snapshot,ent.owner_account_snapshot,ent.breakdown)on conflict(entry_id)do nothing returning id into inserted;if inserted is not null then update horses set career_points=career_points+coalesce(rule.career_points,0)where id=ent.horse_id;if coalesce(rule.prize_percent,0)>0 then update stables set balance=balance+floor(purse*rule.prize_percent/100)where id=ent.owner_id;insert into currency_ledger(stable_id,amount,reason,horse_id)values(ent.owner_id,floor(purse*rule.prize_percent/100),'Show winnings: '||sh.name,ent.horse_id);end if;end if;end loop;update player_shows set status='complete',processed_at=coalesce(processed_at,now())where id=sh.id;processed:=processed+1;end loop;return processed;end$$;

create or replace function public.admin_save_show_level_thresholds(p_novice numeric,p_intermediate numeric,p_advanced numeric,p_elite numeric)returns jsonb language plpgsql security definer set search_path=public as $$declare before jsonb;after jsonb;counts jsonb;begin if not has_show_capability('shows.admin.edit')then raise exception'Show administration permission required';end if;if p_novice<>0 or p_intermediate<=p_novice or p_advanced<=p_intermediate or p_elite<=p_advanced then raise exception'Show Level minimums must be ascending and Novice must begin at 0';end if;before:=get_show_level_config();counts:=admin_preview_show_level_counts(p_novice,p_intermediate,p_advanced,p_elite);update show_tiers set minimum_average=case id when'novice'then p_novice when'intermediate'then p_intermediate when'advanced'then p_advanced when'elite'then p_elite else minimum_average end;after:=get_show_level_config();insert into show_admin_audit(actor_id,action,details)values(auth.uid(),'show_level_thresholds_updated',jsonb_build_object('before',before,'after',after,'horse_counts',counts));return jsonb_build_object('tiers',after,'horse_counts',counts);end$$;
create or replace function public.handbook_game_config(p_key text)returns jsonb language plpgsql stable security definer set search_path=public as $$declare result jsonb:='{}';begin if p_key='showing'then select jsonb_build_object('basis','average_permanent_stats','tiers',coalesce(jsonb_agg(jsonb_build_object('name',x->>'name','minimum',(x->>'minimum_average')::numeric,'maximum',(x->>'maximum_average')::numeric)order by(x->>'sort_order')::integer),'[]'))into result from jsonb_array_elements(get_show_level_config())x;elsif p_key='ap'then select jsonb_build_object('first',first_place,'second',second_place,'third',third_place)into result from show_ap_config where id=true;elsif p_key='feeding'then select jsonb_build_object('hay_per_horse_per_day',1,'grain_per_horse_per_day',1,'base_storage',base_storage,'storage_per_five_levels',storage_per_five_levels,'subscriber_bonus',subscriber_storage_bonus)into result from feed_system_config where id=true;end if;return coalesce(result,'{}');end$$;

create or replace function public.get_horse_show_level_summary(p_horse uuid)returns jsonb language sql stable security definer set search_path=public as $$select jsonb_build_object('horse_id',h.id,'permanent_average',horse_permanent_stat_average(h.id),'show_level',get_horse_show_level(h.id),'show_level_name',t.name,'next_level',n.name,'next_minimum',n.minimum_average)from horses h join show_tiers t on t.id=get_horse_show_level(h.id)left join lateral(select name,minimum_average from show_tiers where active and minimum_average>t.minimum_average order by minimum_average limit 1)n on true where h.id=p_horse$$;
create or replace function public.get_owned_horse_show_levels()returns jsonb language sql stable security definer set search_path=public as $$select coalesce(jsonb_agg(jsonb_build_object('horse_id',h.id,'permanent_average',horse_permanent_stat_average(h.id),'show_level',get_horse_show_level(h.id))),'[]'::jsonb)from horses h where h.owner_id=auth.uid()and h.sanctuary_retired_at is null$$;
select public.apply_show_tier_v2_future_entry_migration();
revoke all on function public.remove_invalid_show_entry(uuid,text),public.revalidate_show_entries(uuid),public.apply_show_tier_v2_future_entry_migration(),public.admin_save_show_level_thresholds(numeric,numeric,numeric,numeric),public.get_horse_show_level_summary(uuid),public.get_owned_horse_show_levels()from public;
grant execute on function public.admin_save_show_level_thresholds(numeric,numeric,numeric,numeric)to authenticated;
grant execute on function public.revalidate_show_entries(uuid)to service_role;
grant execute on function public.preview_show_entries(jsonb),public.confirm_show_entries(jsonb,uuid),public.get_show_entry_options(uuid)to authenticated;
grant execute on function public.process_due_player_shows()to service_role;
grant execute on function public.get_horse_show_level_summary(uuid),public.get_owned_horse_show_levels()to authenticated;
