create or replace function public.build_visual_phenotype(b text,s horse_sex,age_years numeric,g jsonb,m jsonb)
returns jsonb language plpgsql stable as $$
declare color_name text:=genetic_color(g);a breed_visual_archetypes;pattern text:='solid';mane text:='coat-appropriate dark mane and tail';begin
 select * into a from breed_visual_archetypes where breed=b;
 if color_name ilike '%Palomino%' or color_name ilike '%Cremello%' or color_name ilike '%Perlino%' then mane:='light cream to flaxen mane and tail';elsif color_name ilike '%Silver%' then mane:='genetically silver-diluted mane and tail';elsif color_name ilike '%Chestnut%' or color_name ilike '%Red Dun%' or color_name ilike '%Red Roan%' then mane:='red or flaxen coat-appropriate mane and tail';end if;
 if gene_count(g,'Tobiano','TO')>0 then pattern:='tobiano white spotting';elsif gene_count(g,'Frame','O')=1 then pattern:='frame overo white spotting';elsif gene_count(g,'Sabino1','SB1')>0 then pattern:='sabino white pattern';elsif gene_count(g,'Splash1','SW1')>0 then pattern:='splashed white pattern';elsif gene_count(g,'Leopard','LP')>0 then pattern:='leopard complex Appaloosa pattern with mottled skin and breed-appropriate secondary characteristics';end if;
 return jsonb_build_object('breed',b,'sex',s,'age_years',age_years,'color',color_name,'body',coalesce(a.body_description,'realistic balanced conformation appropriate to the named breed'),'height_range',coalesce(a.height_range,'height proportionate to breed'),'movement',coalesce(a.movement_description,'balanced natural movement'),'temperament',coalesce(a.temperament_description,'alert, natural equine expression'),'breed_constraints',coalesce(a.breed_constraints,'avoid caricature'),'coat',color_name,'mane_tail',mane,'pattern',pattern,'face_marking',m->>'face','left_front',m->>'left_front','right_front',m->>'right_front','left_hind',m->>'left_hind','right_hind',m->>'right_hind','pose','standing square','view','side or subtle three-quarter profile','background','pure neutral white RGB 255 255 255 seamless background, edge-to-edge and shadow-free except for a faint natural hoof contact shadow','lighting','bright neutral daylight, crisp coat detail, clean highlights, accurate coat color, strong natural contrast and no color cast');end $$;

with prepared as materialized (select h.id,case when h.visual_phenotype='{}'::jsonb then random_horse_markings(h.genetics,h.breed) else h.markings end markings from public.horses h where h.owner_id is not null and coalesce(h.image_url,'') in ('','/foundation-horse.png'))
update public.horses h set markings=p.markings,visual_phenotype=jsonb_set(jsonb_set(build_visual_phenotype(h.breed,h.sex,greatest(0,extract(epoch from (now()-h.birth_date))/31557600),h.genetics,p.markings),'{background}','"pure neutral white RGB 255 255 255 seamless background, edge-to-edge and shadow-free except for a faint natural hoof contact shadow"'::jsonb,true),'{lighting}','"bright neutral daylight, crisp coat detail, clean highlights, accurate coat color, strong natural contrast and no color cast"'::jsonb,true),image_generation_status='pending',image_prompt_version='horse-v4' from prepared p where p.id=h.id;
insert into public.store_horse_image_jobs(horse_id,status,attempts,next_attempt_at,last_error,completed_at) select h.id,'pending',0,now(),null,null from public.horses h where h.owner_id is not null and coalesce(h.image_url,'') in ('','/foundation-horse.png') on conflict(horse_id) do update set status='pending',attempts=0,next_attempt_at=now(),last_error=null,completed_at=null;

create or replace function public.claim_store_horse_image_job()
returns table(job_id uuid,horse_id uuid,visual_phenotype jsonb,markings jsonb) language plpgsql security definer set search_path=public as $$
declare chosen uuid;begin if auth.role()<>'service_role' then raise exception 'Service role required';end if;
 select j.id into chosen from store_horse_image_jobs j join horses h on h.id=j.horse_id left join store_inventory si on si.horse_id=j.horse_id and si.status='active' where j.status='pending' and j.next_attempt_at<=now() and (h.owner_id is not null or si.id is not null) order by case when h.owner_id is not null then 0 else 1 end,j.created_at for update of j skip locked limit 1;
 if chosen is null then return;end if;update store_horse_image_jobs set status='processing',attempts=attempts+1 where id=chosen;update horses set image_generation_status='processing' where id=(select j.horse_id from store_horse_image_jobs j where j.id=chosen);return query select j.id,h.id,h.visual_phenotype,h.markings from store_horse_image_jobs j join horses h on h.id=j.horse_id where j.id=chosen;end $$;

create or replace function public.breed_horses(stallion_id uuid,mare_id uuid)
returns public.horses language plpgsql security definer set search_path=public as $$
declare sire horses;dam horses;foal horses;s stables;child_stats jsonb='{}';child_genetics jsonb;child_markings jsonb;child_visual jsonb;d record;baseline int;variance int;fee int;child_breed text;child_sex horse_sex;begin
 if stallion_id=mare_id then raise exception 'Choose two different horses';end if;select * into sire from horses where id=stallion_id for update;select * into dam from horses where id=mare_id for update;if sire.owner_id<>auth.uid() or dam.owner_id<>auth.uid() then raise exception 'Both horses must be owned by you';end if;if sire.sex<>'Stallion' or dam.sex<>'Mare' then raise exception 'Breeding requires a stallion and mare';end if;if dam.last_bred_at is not null and dam.last_bred_at>now()-interval '10 days' then raise exception 'Mare cooldown active';end if;
 child_genetics:=inherit_genetics(sire.genetics,dam.genetics);if is_lethal_genotype(child_genetics) then raise exception 'This breeding produced a non-viable lethal genotype. No foal was created and no fee was charged.';end if;fee:=sire.stud_fee;select * into s from stables where id=auth.uid() for update;if s.balance<fee then raise exception 'Insufficient funds';end if;
 for d in select key from stat_definitions where active order by sort_order loop baseline:=round(((sire.stats->>d.key)::numeric+(dam.stats->>d.key)::numeric)/2)::int;variance:=floor(random()*13)::int-6;if random()<.25 then variance:=variance-1;end if;child_stats:=child_stats||jsonb_build_object(d.key,greatest(1,baseline+variance));end loop;
 child_breed:=resolve_crossbreed(sire.breed,dam.breed);child_sex:=(case when random()<.5 then 'Mare' else 'Stallion' end)::horse_sex;child_markings:=random_horse_markings(child_genetics,child_breed);child_visual:=jsonb_set(jsonb_set(build_visual_phenotype(child_breed,child_sex,0,child_genetics,child_markings),'{background}','"pure neutral white RGB 255 255 255 seamless background, edge-to-edge and shadow-free except for a faint natural hoof contact shadow"'::jsonb,true),'{lighting}','"bright neutral daylight, crisp coat detail, clean highlights, accurate coat color, strong natural contrast and no color cast"'::jsonb,true);
 insert into horses(owner_id,name,breed,sex,color,origin,birth_date,sire_id,dam_id,generation,stats,genetics,breed_composition,image_url,markings,visual_phenotype,image_generation_status,image_prompt_version) values(auth.uid(),'Unnamed Foal',child_breed,child_sex,genetic_color(child_genetics),'Bred',now(),sire.id,dam.id,greatest(sire.generation,dam.generation)+1,child_stats,child_genetics,combine_breed_composition(sire.breed_composition,dam.breed_composition),'/foundation-horse.png',child_markings,child_visual,'pending','horse-v4') returning * into foal;
 insert into store_horse_image_jobs(horse_id) values(foal.id);update horses set last_bred_at=now() where id=dam.id;update stables set balance=balance-fee where id=auth.uid();if fee>0 then insert into currency_ledger(stable_id,amount,reason,horse_id) values(auth.uid(),-fee,'Stud fee',foal.id);end if;insert into breeding_records(owner_id,sire_id,dam_id,foal_id,stud_fee) values(auth.uid(),sire.id,dam.id,foal.id,fee);return foal;end $$;

revoke all on function public.claim_store_horse_image_job() from public;
grant execute on function public.claim_store_horse_image_job() to service_role;
